<?php 
$config = array(
	'colleges' => array(
		'DU' => array(
			'inputType' => 'Score',
			'examName' => 'DU',
			'totalRound' => 11,
			'rankType'=>'Other',
			'categoryData' => array('general' => 'General','obc' => 'OBC','sc' => 'SC','st' => 'ST','pwd' => 'PWD','km' => 'KM','minority' => 'Minority'),
			'defaultCategory' => 'General',
			'defaultRankType' => 'Other',
			'invertLogic' => 1,
			'maxValue' => 100,
			'listingId' => 24642,
			'previewText' => array(
				"The University of Delhi (popularly known as DU) is among India’s top universities to study Arts, Commerce and Science at the undergraduate level. <strong>DU cut-offs</strong> are based on the Class 12th exams result, and students who have cleared 12th board from <a href='https://www.shiksha.com/boards/cbse'>CBSE</a>, ISC, and HSC exams in various states are eligible for <a href='<admissionsUrl>'>DU admission</a>. Here you can find <a href='https://www.shiksha.com/science/articles/du-cutoff-2019-blogId-21487' target='_blank'>Delhi University ".(date('Y'))." cut-offs</a>, from 1st cut-off to 11th cut-off for all colleges and courses. Use the search boxes to find <a href='https://www.shiksha.com/courses-after-12th'>courses after 12th</a> within your reach, find detailed course and college information, and prepare yourself for the ".(date('Y'))." DU admissions process.",
				"Use the filters to find specific matches like girls colleges in DU, category cut-offs, or <a href='<allCoursesUrl>'>DU courses</a> you are interested in like BCom honours, English honours, BSc and more."
			),
			'childCollegesPreviewText' => array(
				"<shortName> is one of the constituent colleges of the <a href='<parentListingUrl>'>University of Delhi</a>. <shortName> admissions are conducted along with the <a href='<admissionsUrl>'>Delhi University admission</a> cycle, and students who have passed the class 12th board exams from <a href='https://www.shiksha.com/boards/cbse'>CBSE</a>, ISC, and HSC exams in various states are eligible to apply. Here you can find <shortName> ".(date('Y'))." cut-offs, for <courseCount> courses offered at the college. Based on your Class 12th marks and category, you can apply to <shortName> if you clear the cut-off for a course in any round.",
				"<a href='<allCoursesUrl>'><shortName> offers courses</a> in <bips>"
			)
		),
		'MU' => array(
			'inputType' => 'Score',
			'examName' => 'MU',
			'totalRound' => 7,
			'rankType'=>'Other',
			'categoryData' => array('open' => 'OPEN',
									'sc' => 'Scheduled Caste',
									'st' => 'Scheduled Tribes',
									'vjdt' => 'Vimukta Jati / Denotified Tribes (A)',
									'quota' => '3% Quota',
									'ntb' => 'Nomadic Tribes (B)',
									'ntc' => 'Nomadic Tribes (C)',
									'obc' => 'Other Backward Class',
									'glm' => 'Gujarati Linguistic Minority',
									'ntd' => 'Nomadic Tribes (D)',
									'sbc' => 'Special Backward Class',
									'opc' => 'Open,Physically Challenged',
									'sindhi' => 'Sindhi',
									'jk' => 'Jammu and Kashmir',
									'defence' => 'Defence',
									'minority' => 'Minority',
									'christains' => 'Christains',
									'special' => 'Special',
									'of' => 'OPEN_Female',
									'dtnt' => 'DT/NT',
									'scf' => 'SC_Female',
									'stf' => 'ST_Female',
									'ntbf' => 'NT-B_Female',
									'ntcf' => 'NT-C_Female',
									'obcf' => 'OBC_Female',
									'sbcf' => 'SBC_Female',
									'tm' => 'Tamil Minority',
									'osim' => 'Other South Indian Linguistic Minority',
									'sports' => 'Sports',
									'km' => 'Kashmiri Migrants',
									'es' => 'EX Serviceman',
									'cultural' => 'Cultural',
									'gt' => 'GOVT. TRANSFER',
									'dtaf' => 'DT-A_Female',
									'other' => 'Other',
									'go' => 'Govt. Other',
									'vja' => 'VJA',
									'apm' => 'APM',
									'nta' => 'NT_A',
									'lm' => 'Linguistic Minority',
									'others' => 'Others',
									'otf' => 'OTF',
									'ff' => 'Freedom Fighter',
									'handicapped' => 'Handicapped',
									'special' => 'category 	Special Category ',
									),
			'defaultCategory' => 'OPEN',
			'defaultRankType' => 'Other',
			'invertLogic' => 1,
			'maxValue' => 100,
			'listingId' => 856,
			'previewText' => array(
				"Mumbai University announce its cut off & merit list for commerce, science, arts & other various courses to get admission in UG programs every year. For this year <a href='https://www.shiksha.com/university/university-of-mumbai-856'>Mumbai University</a> Cut Off & Merit List is going to be declared in mid of June ".(date('Y')).". There are around 750 colleges affiliated to Mumbai University and Mumbai University Cut Off ".(date('Y'))." will be determined based on the reservation categories and the seats available in each of these affiliated colleges. Around 5.5 Lakhs students have applied this year to various <a href='<allCoursesUrl>'>courses in Mumbai University</a> and the admission of these students is dependent on the Cut Off & Merit list released by Mumbai University for year ".(date('Y')).". <br>At Shiksha we follow each merit & cut off list of Mumbai University deeply and provide you the authentic data based on various sources. Here you will get Mumbai University ".(date('Y'))." cut-offs, from 1st cut off to last cut off for all 750 colleges and 1000+ courses.",
				"Use the search boxes to find <a href='https://www.shiksha.com/courses-after-12th'>courses after 12th</a> within your reach, detailed course and college information, and prepare yourself for the ".(date('Y'))." <a href='<admissionsUrl>'>Mumbai University admission</a> process. Use the filters to find specific matches like girls colleges in Mumbai University, category cut-offs, or Mumbai University courses you are interested in such as BA, BSc, BCom honours, English honours, Bfa and more."
			),
			'childCollegesPreviewText' => array(
				"<shortName> is one of the constituent/affiliated colleges of <a href='<parentListingUrl>'>Mumbai University</a>. <shortName> admissions are conducted along with the <a href='https://www.shiksha.com/university/university-of-mumbai-856/admission'>Mumbai University admission</a> cycle, and students who have passed the class 12th board exams from <a href='https://www.shiksha.com/boards/cbse'>CBSE</a>, ISC, and HSC exams in various states are eligible to apply. Here you can find <shortName> ".(date('Y'))." cut-offs, for <courseCount> courses offered at the college. Based on your Class 12th marks and category, you can apply for <a href='<admissionsUrl>'><shortName> ".(date('Y'))." admissions</a> if you clear the cut-off for a course in any round.",
				"<a href='<allCoursesUrl>'><shortName> offers courses</a> in <bips>"
			),
			'metaTitle' => '<shortName> Cut off <currentYear> - College and Course wise Cut Off & Merit List of <shortName>',
			'metaDescription' => '<shortName> <currentYear> Cut Off & Merit list for arts, science & commerce will be released in June <currentYear> for all 700+ affiliated colleges. Get <shortName> Cut Offs <currentYear>, admission intake details, college and course wise Cut Off for UG & PG admissions at Shiksha.com'
		),
	),

	'parentListingIds' => array(24642 => 24642, 856 => 856),
	'idToCollegeMapping' => array(24642 => 'DU', 856 => 'MU'),
	'metaTitle' => array('withAbbreviation' => '<abbr> Cut off '.date('Y').' - Arts, Science & Commerce Cut off list '.date('Y').' by <fullName>',
						'noAbbreviation' => '<fullName> Cut off '.date('Y').' - Arts, Science & Commerce Cut off list '.date('Y').' by <fullName>'),
    'metaDescription'=> array('withAbbreviation' => '<fullName> '.date('Y').' Cut Off for arts, science & commerce will be declared in mid of June '.date('Y').'. Get <abbr> Cut offs '.date('Y').', admission intake details, '.date('Y').' results, Colleges & course Wise Cut Off for UG & PG admissions @ Shiksha.com',
		'noAbbreviation' => '<fullName> '.date('Y').' Cut Off for arts, science & commerce will be declared in mid of June '.date('Y').'. Get <fullName> Cut offs '.date('Y').', admission intake details, '.date('Y').' results, Colleges & course Wise Cut Off for UG & PG admissions @ Shiksha.com',
		'withAbbreviationOneCourse' => '<fullName> '.date('Y').' Cut Off for arts, science & commerce will be declared in mid of June '.date('Y').'. Get <abbr> Cut offs '.date('Y').', admission intake details, '.date('Y').' results, Colleges & course Wise Cut Off for UG & PG admissions @ Shiksha.com',
		'noAbbreviationOneCourse' => '<fullName> '.date('Y').' Cut Off for arts, science & commerce will be declared in mid of June '.date('Y').'. Get <fullName> Cut offs '.date('Y').', admission intake details, '.date('Y').' results, Colleges & course Wise Cut Off for UG & PG admissions @ Shiksha.com'
	),
);
?>