<?php 
$config['SA_SEARCH_PARAMS_FIELDS_ALIAS'] = array(
		"keyword"            => "q",
		"pageNumber"         => "pn",
		"categoryIds"         => "c",
		"subCategoryIds"      => "sc",
		"city"               => "ct",
		"state"              => "st",
		"country"            => "co",
        "continent"          => "cn",
		"specialization"     => "sp",
		"specializationIds"  => "si",
		"fees"               => "fe",
		"exams"              => "ex",
		"examScore"          => "es",
		"courseFee"          => "cf",
		"universities"       => "u",
        "institute"          => "i",
		"level"              => "cl",
		"qerResults"         => "qer",
		"requestFrom"		 => "rf",
        "sort"               => "sr",
		"selectedLdbId"		 => "ldb",
        "workex"             =>"we",
        "ugMarks"            =>"ug",
        "class12"            =>"c12",
        "apdeadline"         =>"adl",
        "intseason"          =>"ise",
        "scholarship"        =>"scp",
        "sop"                =>"sop",
        "lor"                =>"lor",
        "courseDuration"     =>"crdr",
        "desiredCourse"      => "ds",   
		"selectedLdbId"		 => "ldb",
        "trackingId"         => "tid",
        "textSearchFlag"     => "ts",
        "remainingKeyword"   => "rk",
        "filterSpecializationId" => "f"

        );

$config['SA_SEARCH_FILTER_FACETS'] = array(
                                'course'=> array(
                                                'fees',
                                                'location',
                                                'exams',
                                                'specialization',
                                                'courselevel',
                                                'category',
                                                'duration',
                                                'deadline',
                                                'intakeseason',
                                                'shikshapply',
                                                'scholarship'
                                            ),
                                'university'=> array(
                                                'type',  
                                                'livingexpense',
                                                'location',
                                                'desiredcourse',
                                                'category',
                                                'accomodation',
                                                'scholarship'
                                            )
                            );

$config['SolrDataFieldAliases'] = array(
        'saCourseId'=>'a',
        'saCourseSeoUrl'=>'b',
        'saUnivSeoUrl'=>'c',
        'saUnivName'=>'d',
        'saUnivCountryName'=>'e',
        'saUnivStateName'=>'f',
        'saUnivCityName'=>'g',
        'saUnivType'=>'h',
        'saCourseName'=>'i',
        'saCourseDurationValue'=>'j',
        'saCourseDurationUnit'=>'k',
        'saCourseRank'=>'l',
        'saCourseRankName'=>'m',
        'saCourseRankURL'=>'n',
        'saCourseTotal1stYearFees'=>'o',
        'saCourseEligibilityExams'=>'p',
        'saCourse12thCutoff'=>'q',
        'saCourseUgCutoff'=>'r',
        'saCourseWorkXP'=>'s',
        'saCourseLevel1'=>'t',
        'saTOEFLExamScore'=>'u',
        'saIELTSExamScore'=>'v',
        'saGMATExamScore'=>'w',
        'saGREExamScore'=>'x',
        'saSATExamScore'=>'y',
        'saPTEExamScore'=>'z',
        'saCAELExamScore'=>'aa',
        'saMELABExamScore'=>'ab',
        'saCAEExamScore'=>'ac',
        'saUnivLogoLink' => 'ad',
        'saCourseDesiredCourseId'=>'ae',
        'saCourseWorkXPRequired'=>'af',
        'saCourseUgCutoffUnit'=>'ag',
        'saCourseParentCategoryId'=>'ah',
        'saUnivId' => 'ai',
        'saUnivEstablishyear'=>'aj',
        'saUnivLivingExpense'=>'ak',
        'saUnivRanking' =>'al',
        'saUnivRankingName' =>'am',
        'saUnivRankingURL' =>'an',
        'saCourseApplicationSubmissionDeadline'=>'ao',
        'saCourseApplicationSubmissionIntake'=>'ap',
        'saCourseShikshaApply'=>'aq',
        'saCourseSOPRequired'=>'ar',
        'saCourseLORRequired'=>'as',
        'saCourseUgCutoffConverted'=>'at',
        'saCoursePgCutoff'=>'au',
        'saCourseScholarship'=>'av',
        'saUnivType2'=>'aw',
        'saUnivAccommodationAvailable'=>'ax',
        'saCourseSpecializationName'=>'ay',
        'saCourseInventoryType'=>'az',
        'saCourseSubcategoryId'=>'ba'
    );
$config['SA_SEARCH_FEES_UPPER_VALUE']=50;
$config['SA_SEARCH_WORK_EXPERIENCE_UPPER_VALUE']=10;
$config['COUNTRY_WITH_STATE']=array(3,4,5,8,17,30,36,45,47,51);
$config['SA_SEARCH_FILTER_NAMES'] = array(
        'workExp',
        'bachelorMarks',
        '12thMarks',
        'courseFees',
        'eligibilityExams',
        'eligibilityExamScore',
        'specializations',
        'locationCity',
        'locationCountry',
        'scholarships',
        'courseLevels',
        'courseDuration',
        'applicationProcess',
    );