<?php
$headerComponents = array (
  'css' =>  array('headerCms','raised_all','mainStyle','footer'),
  'js'  =>  array('user','common','prototype','CalendarPopup','sums_mis_common'),
  'title' =>  'SUMS - Client selection for creating quotation page',
  'tabName' =>        'Register',
  'taburl'   =>  SITE_URL_HTTPS.'enterprise/Enterprise/register',
  'metaKeywords'  =>'Some Meta Keywords',
  'product' => '',
  'search'  =>  false,
  'displayname' =>  (isset($sumsUserInfo['validity'][0]['displayname'])?$sumsUserInfo['validity'][0]['displayname']:""),
  'callShiksha' =>  1
);

$this->load->view('enterprise/headerCMS', $headerComponents);
$this->load->view('enterprise/cmsTabs',$sumsUserInfo);
$this->load->view('common/calendardiv');

$startOffsetForMis = $this->input->post('startOffsetForMis');
?>
<script>
   var cal = new CalendarPopup("calendardiv");
   cal.offsetX = -150;
   cal.offsetY = 20;
</script>
<form id="reportForm" method="post">
	<input type="hidden" name="startOffsetForMis" id="startOffsetForMis" value="<?php echo isset($startOffsetForMis) ? $startOffsetForMis : 0; ?>"/>
	<input type="hidden" name="countOffsetForMis" id="countOffsetForMis" value="<?php echo $updateoffsetvalue; ?>"/>
	<input type="hidden" name="methodNameForMis" id="methodNameForMis" value="postReportForm"/>
	<textarea style="display:none" name="postData" id="postData" ><?php echo $requestArray; ?></textarea>
</form>
<div id="dataLoaderPanel" style="position:absolute;display:none">
    <img src="/public/images/loader.gif"/>
</div>
<div class="mar_full_10p">
    <div style="width:223px; float:left">
        <?php 
		$leftPanelViewValue = 'leftPanelFor' . $prodId;
                // Load another view to display MIS collection form side bar
		$this->load->view('sums/'. $leftPanelViewValue, array('prodId'=>$prodId,'mis_reprot_type'=>$mis_reprot_type));
	?>
    </div>
    <div style="margin-left:233px">
        <div class="lineSpace_10p">&nbsp;</div>
        <div class="fontSize_14p OrgangeFont brd" style="padding:10px;">
        	<div class="txt_align_c bld">
        	<?php
			echo ucfirst($mis_reprot_type).' MIS';
			if (!empty($shikshainventory)) 
			{
				if ($shikshainventory == 'csm') {
					echo ':- Client Subscription MIS';
				}else if ($shikshainventory == 'bcpm') {
					echo ':- Clients Product MIS';
				}else if ($shikshainventory == 'scpim') {
					echo ':- Shiksha Category Product Inventory MIS';
				}else if ($shikshainventory == 'sspm') {
					echo ':- Shiksha Search Product MIS';
				} 
			
			}
        	?>
        	</div>
        	<div class="row">
			<div class="blackFont float_R">Report Generated On :- <?php echo date('l jS \of F Y h:i:s A',time());?> </div>
			<div class="blackFont">Report Generated By :- <?php echo (isset($sumsUserInfo['validity'][0]['displayname'])?$sumsUserInfo['validity'][0]['displayname']:"");?></div>			
		</div>		
        </div>
        <?php if ( $ReportResult[0]['totalCount'] > 0 ) { ?>
        <div class="lineSpace_5">&nbsp;</div>
		<div>
			<div class="float_L" style="width:200px">	
				<div>
					<?php if ( $ReportResult[0]['totalCount'] > 0) { ?>
					Total <?php
						$text = ( $ReportResult[0]['totalCount'] == 1 ) ? "Record" : "Records"; 
						echo $ReportResult[0]['totalCount'] . '&nbsp;' . $text; ?> Found.
					<?php } ?>
				</div>
			</div>
			<div style="margin-left:200px" class="txt_align_r">
				<div class="pagingID txt_align_r"   style="line-height:23px"   id ="paginataionPlaceForMis">
				</div>
			</div>
			<div class="clear_L"></div>
		</div>
        <div >
        <?php } ?>
	<?php
		if (count($ReportResult[0]['results']) > 0 ) { 
			echo "<table border=1 rules='cols' cellpadding=0 cellspacing=0>";
			foreach ($ReportResult[0]['results'] as $Report) {
				echo "<tr>";
				foreach ($Report as $key=>$value) {
					echo "<td valign='middle' class='tableHeaderSums' bgcolor='#E2E2E2' height='30'>".ucfirst($key)."</td>";
					
				}
				echo "</tr>";
				break;
			}
			$color1 = 'tRow2Sums';
			$color2 = 'tRow1Sums';
			$row_count = 0;
			foreach ($ReportResult[0]['results'] as $Report) {
				$row_color = ($row_count % 2) ? $color1 : $color2;
				echo "<tr class='".$row_color."' >";
				foreach ($Report as $key=>$value) {
					echo "<td align='center' style='padding:0 5px'>$value</td>";
				}
				echo "</tr>";
				$row_count++; 

			}
			echo "</table>";
		} else {
			echo "No Record Found";
		}
	?>
	</div>
     </div>
    <div class="lineSpace_35">&nbsp;</div>
</div>
</body>
</html>
<script>
doPagination('<?php echo $ReportResult[0]['totalCount']; ?>','startOffsetForMis','countOffsetForMis','paginataionPlaceForMis',null,'methodNameForMis',10); 
function postReportForm(){
document.getElementById('reportForm').submit();
}

</script>
