<?php
$headerComponents = array (
  'css' =>  array('headerCms','raised_all','mainStyle','footer'),
  'js'  =>  array('user','common','prototype','CalendarPopup','sums_mis_common','sums_target'),
  'title' =>  'SUMS - Client selection for creating quotation page',
  'tabName' =>        'Register',
  'taburl'   =>  SITE_URL_HTTPS.'enterprise/Enterprise/register',
  'metaKeywords'  =>'Some Meta Keywords',
  'product' => '',
  'search'  =>  false,
  'displayname' =>  (isset($sumsUserInfo['validity'][0]['displayname'])?$sumsUserInfo['validity'][0]['displayname']:""),
  'callShiksha' =>  1
);

$this->load->view('enterprise/headerCMS', $headerComponents);
$this->load->view('enterprise/cmsTabs',$sumsUserInfo);
$this->load->view('common/calendardiv');
?>
<script>
   var cal = new CalendarPopup("calendardiv");
   cal.offsetX = -150;
   cal.offsetY = 20;
</script>
<div id="dataLoaderPanel" style="position:absolute;display:none">
    <img src="/public/images/loader.gif"/>
</div>
<div class="mar_full_10p">
    <div style="width:223px; float:left">
        <?php 
		$leftPanelViewValue = 'leftPanelFor' . $prodId;
        // Load another view to display MIS collection form side bar
		$this->load->view('sums/'. $leftPanelViewValue, array('prodId'=>$prodId,'type'=>$type,'sumsUserInfo'=>$sumsUserInfo));
	?>
    </div>
    <div style="margin-left:233px">
        <div class="lineSpace_10p">&nbsp;</div>
        <div class="bld fontSize_14p OrgangeFont" style="padding-left:10px;">Sales MIS Report</div>
        <div class="grayLine"></div>
        <div class="lineSpace_10">&nbsp;</div>
        <div style="display:inline;float:left;width:100%">
    </div>
    <div class="lineSpace_10p">&nbsp;</div>
        <div class="fontSize_14p OrgangeFont brd" style="padding:10px;">
			<div class="txt_align_c bld">
				<?php
						echo "&nbsp;";
						if ($search_array['report_type'] =='Quarter_till_date_sales_Report') {
							$type = "Quarter till date sales Report";
						} elseif ($search_array['report_type'] =='Month_till_date_sales_Report') {
							$type = "Month till date sales Report";
						} elseif ($search_array['report_type'] =='Product_MIX_Report') {
							$type = "Product MIX Report";
						}
						echo  "\" $type \"" ;
						echo "<br>";
						if (!empty($search_array['year'])) {
							echo "Year:-&nbsp;". $search_array['year'] ;
							echo "<br>";
						}
						if (!empty($search_array['month'])) {
							$monthArray = array("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December");
							echo "Month:-&nbsp;". $monthArray[($search_array['month'] -1)] ;
							echo "<br>";
						}
						if (!empty($search_array['Output_Value'])) {
							echo "Output Value:-&nbsp;". $search_array['Output_Value'] ;
							echo "<br>";
						}
						if (!empty($search_array['trans_start_date'])) {
							echo "Start Date:-&nbsp;". $search_array['trans_start_date'] ;
							echo "<br>";
						}
						if (!empty($search_array['trans_end_date'])) {
							echo "End Date:-&nbsp;". $search_array['trans_end_date'] ;
							echo "<br>";
						}
						if (!empty($search_array['Quarters'])) {
							if ($search_array['Quarters'] == '4,5,6') {
								$Quarters = 'First Quarter';
							}elseif ($search_array['Quarters'] == '7,8,9') {
								$Quarters = 'Second Quarter';
							}elseif ($search_array['Quarters'] == '10,11,12') {
								$Quarters = 'Third Quarter';
							}elseif ($search_array['Quarters'] == '1,2,3') {
								$Quarters = 'Fourth Quarter';
							}
							echo "Quarter:-&nbsp;". $Quarters ;
						}
						echo "<br>";
						
				?>
				</div>
				<div class="row">
				<div class="blackFont float_R">Report Generated On :- <?php echo date('l jS \of F Y h:i:s A',time());?> </div>
				<div class="blackFont">Report Generated By :- <?php echo (isset($sumsUserInfo['validity'][0]['displayname'])?$sumsUserInfo['validity'][0]['displayname']:"");?></div>			
			</div>		
        </div>
        <div class="lineSpace_5">&nbsp;</div>
    <div >
	<div style="margin-left:0px">
		<?php
		if (count($ReportResult[0]['results']) > 0 ) { 
			echo "<table border=1 rules='cols' cellpadding=0 cellspacing=0>";
			foreach ($ReportResult[0]['results'] as $Report) {
				echo "<tr>";
				foreach ($Report as $key=>$value) {
					echo "<td valign='middle' class='tableHeaderSums' bgcolor='#E2E2E2' height='30'>".ucfirst($key)."</td>";
					
				}
				echo "</tr>";
				break;
			}
			$color1 = 'tRow2Sums';
			$color2 = 'tRow1Sums';
			$row_count = 0;
			foreach ($ReportResult[0]['results'] as $Report) {
				$row_color = ($row_count % 2) ? $color1 : $color2;
				echo "<tr class='".$row_color."' >";
				foreach ($Report as $key=>$value) {
					echo "<td align='center' style='padding:0 5px'>$value</td>";
				}
				echo "</tr>";
				$row_count++; 

			}
			echo "</table>";
		} else {
			echo "No Record Found";
		}
		?>
	</div>
    <div class="lineSpace_35">&nbsp;</div>
</div>
</body>
</html>
