<?php
$config['subCatStrings'] = array(
    '2'  => array('B.E. / B.Tech','B.Sc','M.E. / M.Tech','M.Sc'),
    '3'  => array('BBA','Distance MBA','MBA / PGDM','Online MBA'),
    '4'  => array('Accounting','Banking', 'CA', 'Commerce'),
    '5'  => array('Clinical Research','MBBS','Nursing','Pharmacy'),
    '6'  => array('Aviation','Hotel Management','Tourism Management'),
    '7'  => array('Mass Communication','Journalism','Acting','Media'),
    '9'  => array('Arts &amp; Humanities','Law','Creative Arts'),
    '10' => array('BCA','DOEACC','MCA','Programming Languages'),
    '11' => array('Front Office','Inventory','Shop Floor'),
    '12' => array('Animation','Graphic Designing','Web Designing'),
    '13' => array('Fashion Design','Industrial Design','Interior Design'),
    '14' => array('Engineering Entrance','Management Entrance'),
);
$config['studyAbroadMap'] = array(
    'australia'  => array('url' => SHIKSHA_STUDYABROAD_HOME.'/australia/universities',
                   'label' => 'Australia',
                   'flagClass' => 'australia',
                   'lastRow'=>false),
    'canada'     => array('url' => SHIKSHA_STUDYABROAD_HOME.'/canada/universities',
                   'label' => 'Canada',
                   'flagClass' => 'canada',
                   'lastRow'=>false),
    'france'     => array('url' => SHIKSHA_STUDYABROAD_HOME.'/france/universities',
                   'label' => 'France',
                   'flagClass' => 'france',
                   'lastRow'=>false),
    'germany'    => array('url' => SHIKSHA_STUDYABROAD_HOME.'/germany/universities',
                   'label' => 'Germany',
                   'flagClass' => 'germany',
                   'lastRow'=>false),
    'malaysia'   => array('url' => SHIKSHA_STUDYABROAD_HOME.'/malaysia/universities',
                   'label' => 'Malaysia',
                   'flagClass' => 'malaysia',
                   'lastRow'=>false),
    'newzealand' => array('url' => SHIKSHA_STUDYABROAD_HOME.'/new-zealand/universities',
                   'label' => 'New Zealand',
                   'flagClass' => 'newzealand',
                   'lastRow'=>false),
    'singapore'  => array('url' => SHIKSHA_STUDYABROAD_HOME.'/singapore/universities',
                   'label' => 'Singapore',
                   'flagClass' => 'singapore',
                   'lastRow'=>true),
    'uk'         => array('url' => SHIKSHA_STUDYABROAD_HOME.'/uk/universities',
                   'label' => 'U.K.',
                   'flagClass' => 'uk',
                   'lastRow'=>true),
    'usa'        => array('url' => SHIKSHA_STUDYABROAD_HOME.'/usa/universities',
                   'label' => 'U.S.',
                   'flagClass' => 'usa',
                   'lastRow'=>true)
);
