<?php
/**
 * This class stores config variable in static member
 *
 * @author     Ankur
 * @version
 */
class StructuredConfig {
	// associative array stores static details for the colleges
	public static $religion_array = array(
                                        'SELECT',
                                        'HINDU',
                                        'MUSLIM',
                                        'CHRISTIAN',
                                        'SIKH',
                                        'PARSI',
                                        'JEWISH',
                                        'BUDDHIST',
                                        'JAIN',
                                        'BAHAI',
                                        'OTHER'
                                        );
        public static $graduation_exam_array = array(
                                        'SELECT',
                                        'BA',
                                        'B.Sc',
                                        'B.E./B.Tech',
                                        'B.Des',
                                        'B.Com',
                                        'BBA/BBM/BBS',
					'B.Ed',
                                        'BCA/BCM',
                                        'BVSc',
                                        'BHM',
                                        'BJMC',
                                        'BDS',
                                        'B.Pharma',
                                        'B.Arch',
                                        'MBBS',
                                        'LLB',
                                        'Diploma',
                                        'OTHER'
                                        );
	public static $board_array = array(
                                        'SELECT',
                                        'Andhra pradesh board of secondary education',
                                        'Andhra Pradesh Board of Intermediate Education',
                                        'Assam Higher Secondary Education Council',
                                        'Assam Board of Secondary Education',
                                        'Board of Intermediate Education Telangana',
                                        'Board of Secondary Education, Madhya Pradesh',
                                        'Board of Secondary Education, Telangana',
                                        'Bihar School Examination Board',
                                        'Bihar Intermediate Education Council',
                                        'Central Board of Secondary Education',
                                        'Central Board of Secondary Education International',
                                        'Indian School Certificate Examination (ISC)',
                                        'Chhattisgarh Board of Secondary Education',
                                        'Chhattisgarh Madhyamik Shiksha Mandal',
                                        'Goa Board of Secondary & Higher Secondary Education',
                                        'Gujarat Secondary Education Board',
                                        'Gurukul visvidhalya vrindavan',
                                        'Haryana Board of Education',
                                        'Himachal Pradesh Board of School Education',
                                        'Indian Certificate of Secondary Education (ICSE)',
                                        'Jharkhand Academic Council',
                                        'J&K State Board of School Education',
                                        'Karnataka Secondary Education Examination Board',
                                        'Karnataka Board of the Pre-University Education',
                                        'Kerala Board of Public Examinations',
                                        'Maharashtra State Board of Secondary and Higher Secondary Education',
                                        'Manipur Board of Secondary Education',
                                        'Manipur Council of Higher Secondary Education',
                                        'Meghalaya Board of School Education',
                                        'Mizoram Board of School Education',
                                        'Nagaland Board of School Education',
                                        'National Institute of Open Schooling',
                                        'Board of Secondary Education, Odisha',
                                        'Council of Higher Secondary Education, Odisha',
                                        'Punjab School Education Board',
                                        'Board of Secondary Education, Rajasthan',
                                        'Tamil Nadu Board of Secondary Education',
                                        'Tamil Nadu Board of Higher Secondary Education',
                                        'Tripura Board of Secondary Education',
                                        'Uttar Pradesh Board of High School and Intermediate Education (UPB)',
                                        'Uttaranchal Shiksha Evam Pariksha Parishad',
                                        'West Bengal Board of Secondary Education',
                                        'OTHER'            
                                        );
	public static $univerisities_array = array(
                                        'SELECT',
                                        'Agra University',
                                        'Air Hostess Academy (AHA)',
                                        'Alagappa University',
                                        'Aligarh Muslim University (AMU)',
                                        'All India Institute of Management Studies',
                                        'All India Institute of Medical Sciences (AIIMS), Delhi',
                                        'All India Management Association (AIMA)',
                                        'Allahabad University',
                                        'Alliance Business Academy (ABA)',
                                        'Amity Business School (ABS)',
                                        'Amity University',
                                        'Amravati University',
                                        'Andhra University',
                                        'Anna University',
                                        'Annamalai University',
                                        'Apeejay School Of Marketing (ASM)',
                                        'Aptech',
                                        'Arena Multimedia',
                                        'Armed Forces Medical College (AFMC), Pune',
                                        'Asansol Engineering College (AEC)',
                                        'Asia Pacific Institute of Management (APIM)',
                                        'Assam Engineering College (AEC)',
                                        'Assam University',
                                        'Avadh University',
                                        'B N Mandal University (BNMU)',
                                        'Babasaheb Ambedkar Marathwada University (BAMU), Aurangabad',
                                        'Babasaheb Bhimrao Ambedkar University (BBAU), Lucknow',
                                        'Banaras Hindu University (BHU), Varanasi',
                                        'Banasthali University',
                                        'Bangalore Institute Of Technology (BIT)',
                                        'Bangalore Medical College (BMC)',
                                        'Bangalore University',
                                        'Barkatullah University',
                                        'Bengal Engineering College (BEC)',
                                        'Berhampur University',
                                        'Bhagalpur University',
                                        'Bharathidasan University, Trichy',
                                        'Bharatiya Vidya Bhavan (BVB)',
                                        'Bhartiyar University, Coimbatore',
                                        'Bhavnagar University',
                                        'Bhopal University',
                                        'Bihar University',
                                        'Biju Patnaik University of Technology (BPUT)',
                                        'Bikaner University',
                                        'Birla Institute of Management Technology (BIMT)',
                                        'Birla Institute of Technology (BIT), Ranchi',
                                        'Birla Institute of Technology and Science (BITS), Pilani',
                                        'Board of Technical Education (BTE)',
                                        'Bundelkhand University',
                                        'Burdwan University',
                                        'Calcutta Medical College (CMC)',
                                        'Calcutta University',
                                        'Calicut University',
                                        'Centre for Development of Advanced Computing (CDAC)',
                                        'Ch Charan Singh University (CCSU), Meerut',
                                        'Chennai University',
                                        'Chhatrapati Shahu Ji Maharaj University (CSJMU)',
                                        'Christian College, Lucknow',
                                        'Christian Medical College (CMC), Vellore',
                                        'CIPET',
                                        'Cochin University of Science & Technology (CUST)',
                                        'College of Engineering and Technology (CET), Bhubaneshwar',
                                        'DAV Institute of Management (DAVIM), Faridabad',
                                        'Deen Dayal Upadhyay Gorakhpur University (DDUGU)',
                                        'Delhi College of Engineering (DCE), Delhi',
                                        'Delhi University - College of Art',
                                        'Delhi University - Daulat Ram College ',
                                        'Delhi University - Hansraj College',
                                        'Delhi University - Hindu College ',
                                        'Delhi University - Lady Shree Ram College (LSR)',
                                        'Delhi University - Miranda House',
                                        'Delhi University - Other',
                                        'Delhi University - Shri Ram College of Commerce  (SRCC)',
                                        'Delhi University - St Stephens College',
                                        'Devi Ahilya Vishwa Vidhyalaya (DAVV), Indore',
                                        'Dibrugarh University',
                                        'DOEACC',
                                        'Dr. B.R. Ambedkar National Institute of Technology (NIT), Jalandhar',
                                        'Dr. Bhim Rao Ambedkar University (BRAU), Bihar',
                                        'Dr. Harisingh Gour University (HGU), Sagar',
                                        'Dr. MGR Medical University (MGRMU), Chennai',
                                        'EMPI Business School',
                                        'Faculty Of Management Studies (FMS), Delhi',
                                        'Faculty Of Management Studies',
                                        'Fergusson College, Pune',
                                        'Film & Television Institute of India (FTII), Pune',
                                        'Fore School of Management (FSM), Delhi',
                                        'Fortune Institute of International Business (FIIB)',
                                        'Goa Institute of Management (GIM)',
                                        'Goa University',
                                        'Goenka College of Commerce & Business Administration (GCCBA)',
                                        'Government College of Engineering (GCE), Pune',
                                        'Government College of Science (GCS), Raipur',
                                        'Government Medical College and Hospital (GMCH), Chandigarh',
                                        'Gujarat Agricultural University (GAU)',
                                        'Gujarat University',
                                        'Gulbarga University',
                                        'Guru Ghasidas University (GGU)',
                                        'Guru Gobind Singh Indraprastha University (GGSIU)',
                                        'Guru Jambheshwar University of Science & Technology (GJUST), Hisar',
                                        'Guru Nanak Dev University (GNDU)',
                                        'Gurukula Kangri University (GKU)',
                                        'Guwahati Medical College and Hospital (GMCH)',
                                        'Guwahati University',
                                        'Haldia Institute of Technology (HIT)',
                                        'Hidayatullah National Law University (HNLU)',
                                        'Himachal Pradesh University (HPU)',
                                        'HNB Garhwal University (HNBGU)',
                                        'Hyderabad University',
                                        'Indian Business Academy (IBA)',
                                        'Indian Institute of Bankers (IIB)',
                                        'Indian Institute of Finance (IIF)',
                                        'Indian Institute of Foreign Trade (IIFT)',
                                        'Indian Institute Of Hardware Technology (IIHT)',
                                        'Indian Institute of Hotel Management (IIHM), Aurangabad',
                                        'Indian Institute of Management (IIM), Ahmedabad',
                                        'Indian Institute of Management (IIM), Bangalore',
                                        'Indian Institute of Management (IIM), Indore',
                                        'Indian Institute of Management (IIM), Kolkatta',
                                        'Indian Institute of Management (IIM), Kozhikode',
                                        'Indian Institute of Management (IIM), Lucknow',
                                        'Indian Institute of Mass Communication (IIMC), Delhi',
                                        'Indian Institute of Materials Management (IIMM)',
                                        'Indian Institute of Modern Management (IIMM), Pune',
                                        'Indian Institute Of Packaging (IIP)',
                                        'Indian Institute of Planning And Management (IIPM)',
                                        'Indian Institute of Science (IIS), Bangalore',
                                        'Indian Institute of Social Welfare and Business Management (IISWBM)',
                                        'Indian Institute of Technology (IIT), Chennai',
                                        'Indian Institute of Technology (IIT), Delhi',
                                        'Indian Institute of Technology (IIT), Guwahati',
                                        'Indian Institute of Technology (IIT), Kanpur',
                                        'Indian Institute of Technology (IIT), Kharagpur',
                                        'Indian Institute of Technology (IIT), Mumbai',
                                        'Indian Institute of Technology (IIT), Roorkee',
                                        'Indian Law Society Law College (ILSLC), Pune',
                                        'Indian School of Business (ISB), Hyderabad',
                                        'Indian School of Mines (ISM), Dhanbad',
                                        'Indian Statistical Institute (ISI), Bangalore',
                                        'Indian Statistical Institute (ISI), Delhi',
                                        'Indian Statistical Institute (ISI), Kolkatta',
                                        'Indira Gandhi National Open University (IGNOU)',
                                        'Industrial Training Institute (ITI)',
                                        'Institute for Technology & Management (ITM)',
                                        'Institute of Business Management & Research (IBMR)',
                                        'Institute of Chartered Accountant of India  (ICAI)',
                                        'Institute of Chartered Financial Analysts of India (ICFAI)',
                                        'Institute of Company Secretaries of India  (ICSI)',
                                        'Institute of Cost & Works Accountants of India (ICWAI)',
                                        'Institute of Hotel Management (IHM)',
                                        'Institute of Management Education (IME)',
                                        'Institute of Management Studies (IMS), Dehradun',
                                        'Institute of Management Studies (IMS), Ghaziabad',
                                        'institute of Management Technology (IMT), Ghaziabad',
                                        'Institute of Marketing & Management (IMM)',
                                        'Institute of Productivity & Management (IPM)',
                                        'Institute of Rural Management (IRMA), Anand',
                                        'Institute of Technology, Banaras Hindu University',
                                        'International Institute of Information Technology (IIIT), Allahabad',
                                        'International Institute of Information Technology (IIIT), Bangalore',
                                        'International Institute of Information Technology (IIIT), Hyderabad',
                                        'International Institute of Information Technology (IIIT), Kolkatta',
                                        'International Management Institute (IMI), Delhi',
                                        'International School of Business & Media (ISBM)',
                                        'Jabalpur University',
                                        'Jadavpur University',
                                        'Jagan Institute of Management Studies (JIMS)',
                                        'Jaipuria Institute of Management (JIMS)',
                                        'Jamia Hamdard',
                                        'Jamia Milia Islamia (JMI)',
                                        'Jammu University',
                                        'Jamnalal Bajaj Institute of Management Studies (JLBIM)',
                                        'Jawaharlal Nehru Technological University (JNTU)',
                                        'Jawaharlal Nehru University  (JNU)',
                                        'Jetking',
                                        'Jipmer, Pondicherry',
                                        'Jiwaji University',
                                        'JJ Institute of Applied Art (JJIAA), Mumbai',
                                        'K.J. Somaiya Institute of Management Studies & Research (KJSIMSR), Mumbai',
                                        'Kakatiya University',
                                        'Kalyani University',
                                        'Kannur University',
                                        'Kanpur University',
                                        'Karnataka State Open University (KSOU)',
                                        'Karnataka University',
                                        'Karunya University',
                                        'Kashmir University',
                                        'Kasturba Medical College (KMC), Manipal',
                                        'Kerala University',
                                        'King Edward Medical College (KEC), Mumbai',
                                        'Kota University',
                                        'Kumaun University',
                                        'Kurukshetra University',
                                        'Kuvempu University, Karnataka',
                                        'Lady Hardinge Medical College (LHMC), Delhi',
                                        'Lal Bahadur Shastri Institute of Management (LBSIM)',
                                        'Lovely Professional University (LPU)',
                                        'Loyola College, Chennai',
                                        'Loyola Institute of Business Administration (LIBM), Chennai',
                                        'Lucknow University',
                                        'Madan Mohan Malaviya Engineering College (MMMEC)',
                                        'Madras Christian College   (MCC)',
                                        'Madras Medical College  (MMC)',
                                        'Madras University',
                                        'Madurai Kamaraj University (MKU)',
                                        'Magadh University',
                                        'Maharaja Sayajirao University (MSU), Baroda',
                                        'Maharana Pratap University of Agriculture and Technology (MPUAT)',
                                        'Maharishi Dayanand Saraswati University (MDSU), Ajmer',
                                        'Maharishi Dayanand University (MDU), Rohtak',
                                        'Maharishi Institute of Management (MIM)',
                                        'Mahatma Gandhi University (MGU)',
                                        'Mahatma Jyotiba Phule Rohilkhand University (MJPRS)',
                                        'Malviya National Institute of Technology (NIT), Jaipur',
                                        'Management Development Institute (MDI), Gurgaon',
                                        'Mangalore University',
                                        'Manipal Academy of Higher Education (MAHE)',
                                        'Manipal Institute of Management (MIM)',
                                        'Manipal Institute of Technology (MIT)',
                                        'Manipal University',
                                        'Manipur University',
                                        'Manonmaniam Sundaranar University (MSU), Thirunelvelli',
                                        'Maulana Azad Medical College (MAMC), Delhi',
                                        'Maulana Azad National Institute of Technology (NIT), Bhopal',
                                        'Meerut University',
                                        'Motilal Nehru Institute National Institute of Technology  (NIT), Allahabad',
                                        'Mudra Institute of Communications (MICA), Ahmedabad',
                                        'Mumbai University',
                                        'Nagarjuna University',
                                        'Nagpur University',
                                        'Narsee Monjee Institute Of Management Studies (NMIMS)',
                                        'National Institute of Business Management (NIBM)',
                                        'National Institute of Construction Management and Research (NICMR)',
                                        'National Institute of Design (NID), Ahmedabad',
                                        'National Institute of Engineering (NIE)',
                                        'National Institute of Fashion Technology (NIFT)',
                                        'National Institute of Financial Management  (NIFM)',
                                        'National Institute of Management (NIM)',
                                        'National Institute of Sales (NIS)',
                                        'National Institute of Technology (NIT), Bharatidasan',
                                        'National Institute of Technology (NIT), Calicut',
                                        'National Institute of Technology (NIT), Durgapur',
                                        'National Institute of Technology (NIT), Karnataka',
                                        'National Institute of Technology (NIT), Kurukshetra',
                                        'National Institute of Technology (NIT), Other',
                                        'National Institute of Technology (NIT), Rourkela',
                                        'National Institute of Technology (NIT), Silchar',
                                        'National Institute of Technology (NIT), Srinagar',
                                        'National Institute of Technology (NIT), Tiruchirappalli',
                                        'National Institute of Technology (NIT), Warangal',
                                        'National Institute of Technology (NIT), Suratkal',
                                        'National Law Institute University (NLIU), Bhopal',
                                        'National Law School (NLS), Bangalore',
                                        'National Law School of India University (NLSIU), Bangalore',
                                        'National Law University (NLU), Jodhpur',
                                        'National Power Training Institute (NPTI)',
                                        'Netaji Subhas Institute of Technology (NSIT)',
                                        'Nettur Technical Training Foundation (NTTF)',
                                        'New Delhi Institute of Management (NDIM)',
                                        'NIILM School of Business (NIILSB)',
                                        'NIIT',
                                        'Nirma Institute of Management (NIM), Ahmedabad',
                                        'North Bengal University (NBU)',
                                        'North Eastern Hill University (NEHU)',
                                        'North Gujarat University (NGU)',
                                        'North Maharashtra University (NMU)',
                                        'North Odisha University (NOU)',
                                        'Oberoi Centre for Learning & Development (OCLD)',
                                        'Osmania University',
                                        'Panjab University',
                                        'Patna University',
                                        'Periyar University',
                                        'Pondicherry University',
                                        'Pragathi Mahavidyalaya, Hyderabad',
                                        'Presidency College, Chennai',
                                        'Presidency College, Kolkatta',
                                        'PSG, Coimbatore',
                                        'Pune University',
                                        'Punjab Technical University (PTU)',
                                        'Punjabi University, Patiala',
                                        'Rai Business School (RBS)',
                                        'Rai University',
                                        'Rajasthan University',
                                        'Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV), Bhopal',
                                        'Ranchi University',
                                        'Rani Durgavati Vishwavidyalaya (RDVV), Jabalpur',
                                        'RV College Of Engineering (RVCE)',
                                        'Sambalpur University',
                                        'Sardar Patel University (SPU)',
                                        'Sardar Vallabhbhai National Institute of Technology  (NIT), Surat',
                                        'Sastra University',
                                        'Sathyabama University',
                                        'Saurashtra University',
                                        'School Of Planning & Architecture (SPA)',
                                        'Shivaji University, Maharasthra',
                                        'Shreemati Nathibai Damodar Thackersey Women\'s University (SNDTWU)',
                                        'Siddaganga Institute of Technology (SIT)',
                                        'SIES College of Management Studies (SIESCMS)',
                                        'Sikkim Manipal University (SMU)',
                                        'Siliguri Institute Of Technology (SIT)',
                                        'SP Jain Institute of Management Research (SPJIMR), Mumbai',
                                        'Sri Jayachamarajendran College of Engineering (SJCE)',
                                        'Sri Krishnadevaraya University (SKU)',
                                        'Sri Venkateshwara University (SVU), Tirupati',
                                        'SRM university (SRMU)',
                                        'St.Xaviers College, Kolkatta',
                                        'St.Xaviers College, Mumbai',
                                        'State Institute of Education Technology (SIET), Lucknow',
                                        'State Institute of Education Technology (SIET), Patna',
                                        'State Institute of Education Technology (SIET), Pune',
                                        'State Institute of Education Technology (SIET), Thiruvananthapuram',
                                        'Stella Maris College (SMC), Chennai',
                                        'Swami Ramanand Teerth Marathawada University  (SRTMU)',
                                        'Symbiosis, Pune',
                                        'Symbiosis Centre for Distance Learning (SCDL)',
                                        'Symbiosis Centre For Management & HRD (SCMHRD)',
                                        'Symbiosis Institute of Business Management (SIBM), Pune',
                                        'Symbiosis Institute of Management Studies (SIMS)',
                                        'Symbiosis Society Law College (SSLC), Pune',
                                        'Ta Pai Management Institute (TAPMI)',
                                        'Tamil Nadu Open University (TNOU)',
                                        'TASMAC',
                                        'Tata Institute of Social Sciences  (TISS)',
                                        'Tezpur University',
                                        'Thapar Institute of Engineering & Technology (TIET)',
                                        'Thiruvalluvar University',
                                        'Tripura University',
                                        'University Business School (UBS), Chandigarh',
                                        'University College of Law (UCL), Bangalore',
                                        'University of Mysore',
                                        'University of North Bengal  (UNB)',
                                        'University Vishveshvaraya College of Engineering (UVCE)',
                                        'Utkal University',
                                        'Uttar Pradesh Technical University (UPTU)',
                                        'Veer Bahadur Singh Purvanchal University (VBSPU)',
                                        'Veer Narmad South Gujarat University (VNSGU)',
                                        'Vellore Engineering College (VEC)',
                                        'Vellore Institute of Technology (VIT)',
                                        'Vidyasagar University',
                                        'Vikram University, Ujjain',
                                        'Vinayaka Mission University (VMU)',
                                        'Vinoba Bhave University (VBU)',
                                        'Visvesvaraya National Institute of Technology (NIT), Nagpur',
                                        'Visveswaraiah Technological University  (VTU)',
                                        'Welcomgroup Graduate School of Hotel Administration (WGSHA), Manipal',
                                        'Welingkar Institute of Management Development and Research  (WIMDR)',
                                        'West Bengal University of Technology (WBUT)',
                                        'Wigan & Leigh College (WLC)',
                                        'Wildlife Institute of India (WII)',
                                        'Xavier Institute of Social Service (XOSS), Ranchi',
                                        'Xavier Labour Relations Institute (XLRI), Jamshedpur',
                                        'Xavier\'s Institute of Management (XIMS), Bhuvaneshwar',
                                        'Yashwantrao Chavan Maharashtra Open University (YCMOU)',
                                        'Young Men Christian Association  (YMCA)',
                                        'Young Womens Christian Association (YWCA)',                                       
                                        'OTHER'
                                        );
}
