module.exports = Object.freeze({
  COLLEGE_PREDICTOR_BASE_URL   : '/b-tech/resources',
  collegePredictorUrl_JEEMains: '/jee-mains-college-predictor',
  cutOffPredictorUrl_JEEMains: '/jee-mains-cut-off-predictor',
  branchPredictorUrl_JEEMains: '/jee-mains-branch-predictor',
  collegePredictorUrl_KCET : 	'/kcet-college-predictor',
  cutOffPredictorUrl_KCET: 		'/kcet-college-predictor',
  branchPredictorUrl_KCET: 		'/kcet-college-predictor',
  collegePredictorUrl_COMEDK :  '/comedk-college-predictor',
  cutOffPredictorUrl_COMEDK :   '/comedk-cut-off-predictor',
  branchPredictorUrl_COMEDK :   '/comedk-branch-predictor',
  collegePredictorUrl_KEAM :    '/keam-college-predictor',
  cutOffPredictorUrl_KEAM	:   '/keam-cut-off-predictor',
  branchPredictorUrl_KEAM	:   '/keam-branch-predictor',
  rankPredictorUrl_JEEMains : 	'/jee-mains-rank-predictor',
  rankPredictorUrl_COMEDK :     '/comedk-rank-predictor',
  collegePredictorUrl_WBJEE:    '/wbjee-college-predictor',
  cutOffPredictorUrl_WBJEE :    '/wbjee-cut-off-predictor',
  branchPredictorUrl_WBJEE :    '/wbjee-branch-predictor',
  collegePredictorUrl_MPPET :   '/mppet-college-predictor',
  cutOffPredictorUrl_MPPET :    '/mppet-cut-off-predictor',
  branchPredictorUrl_MPPET :    '/mppet-branch-predictor',
  collegePredictorUrl_CGPET : 	'/cgpet-college-predictor',
  cutOffPredictorUrl_CGPET : 	'/cgpet-cut-off-predictor',
  branchPredictorUrl_CGPET : 	'/cgpet-branch-predictor',
  collegePredictorUrl_TNEA : 	'/tnea-college-predictor',
  cutOffPredictorUrl_TNEA : 	'/tnea-cut-off-predictor',
  branchPredictorUrl_TNEA : 	'/tnea-branch-predictor',
  collegePredictorUrl_PTU : 	'/ptu-college-predictor',
  cutOffPredictorUrl_PTU : 		'/ptu-cut-off-predictor',
  branchPredictorUrl_PTU : 		'/ptu-branch-predictor',
 collegePredictorUrl_UPSEE : 	'/upsee-college-predictor',
  cutOffPredictorUrl_UPSEE : 	'/upsee-cut-off-predictor',
  branchPredictorUrl_UPSEE : 	'/upsee-branch-predictor',
  collegePredictorUrl_MHCET : 	'/mhcet-college-predictor',
  cutOffPredictorUrl_MHCET : 	'/mhcet-cut-off-predictor',
  branchPredictorUrl_MHCET : 	'/mhcet-branch-predictor',
  collegePredictorUrl_HSTES : 	'/hstes-college-predictor',
  cutOffPredictorUrl_HSTES : 	'/hstes-cut-off-predictor',
  branchPredictorUrl_HSTES : 	'/hstes-branch-predictor',
  collegePredictorUrl_APEAMCET : '/ap-eamcet-college-predictor',
  cutOffPredictorUrl_APEAMCET : '/ap-eamcet-cut-off-predictor',
  branchPredictorUrl_APEAMCET : '/ap-eamcet-branch-predictor',
  collegePredictorUrl_TSEAMCET : '/ts-eamcet-college-predictor',
  cutOffPredictorUrl_TSEAMCET : '/ts-eamcet-cut-off-predictor',
  branchPredictorUrl_TSEAMCET : '/ts-eamcet-branch-predictor',
  collegePredictorUrl_OJEE : 	'/ojee-college-predictor',
  cutOffPredictorUrl_OJEE : 	'/ojee-cut-off-predictor',
  branchPredictorUrl_OJEE : 	'/ojee-branch-predictor',
  collegePredictorUrl_GGSIPU : '/ggsipu-college-predictor',
  cutOffPredictorUrl_GGSIPU : '/ggsipu-cut-off-predictor',
  branchPredictorUrl_GGSIPU : '/ggsipu-branch-predictor',
  collegePredictorUrl_BITSAT : '/bitsat-college-predictor',
  cutOffPredictorUrl_BITSAT : '/bitsat-cut-off-predictor',
  branchPredictorUrl_BITSAT : '/bitsat-branch-predictor',
  collegePredictorUrl_GUJCET : '/gujcet-college-predictor',
  cutOffPredictorUrl_GUJCET : '/gujcet-cut-off-predictor',
  branchPredictorUrl_GUJCET : '/gujcet-branch-predictor',

  collegePredictorUrl_NIFT : '/design/resources/nift-college-predictor',
  collegePredictorUrl_NCHMCT : '/hospitality-travel/resources/nchmct-college-predictor',
  collegePredictorUrl_MAHCET : '/mba/resources/mahcet-college-predictor',
  collegePredictorUrl_CLAT : '/law/resources/clat-college-predictor',


  contactusUrl : '/mcommon5/MobileSiteStatic/contactUs',
  aboutusUrl : '/mcommon5/MobileSiteStatic/aboutus',
  helplineUrl : '/mcommon5/MobileSiteStatic/studentHelpLine',
  termUrl    : '/mcommon5/MobileSiteStatic/terms',
  policyUrl  : '/mcommon5/MobileSiteStatic/privacy'
});


