<?php

$config = array();

$config['SHIKSHA_URLS'] = array(
                            array('pageName'=>'Home Page', 'teamName'=>'UGC','URL'=>'https://www.shiksha.com'),
                            array('pageName'=>'Category Page', 'teamName'=>'Listings','URL'=>'https://www.shiksha.com/mba/colleges/mba-colleges-in-india'),
                            array('pageName'=>'Course Homepage', 'teamName'=>'Listings','URL'=>'https://www.shiksha.com/mba/mba-home'),
                            array('pageName'=>'Ranking Page', 'teamName'=>'Listings','URL'=>'https://www.shiksha.com/mba/ranking/top-mba-colleges-india/2-2-0-0-0'),
                            array('pageName'=>'ANA Homepage', 'teamName'=>'Mobile_app','URL'=>'https://ask.shiksha.com'),                            
                            array('pageName'=>'All Questions Page', 'teamName'=>'Mobile_app','URL'=>'https://ask.shiksha.com/questions'),
                            array('pageName'=>'Question detail page', 'teamName'=>'Mobile_app','URL'=>'https://ask.shiksha.com/i-am-30-years-old-and-i-just-completed-my-12th-with-commerce-in-2nd-attempt-am-i-eligible-for-bca-or-suggest-some-qna-3487647'),
			    array('pageName'=>'ANA Expert Panel Page', 'teamName'=>'Mobile_app','URL'=>'https://ask.shiksha.com/experts'),
			    array('pageName'=>'All Tags Page', 'teamName'=>'Mobile_app','URL'=>'https://www.shiksha.com/tags'),
			    array('pageName'=>'Tag Detail Page', 'teamName'=>'Mobile_app','URL'=>'https://www.shiksha.com/tags/bca-tdp-429'),
                            array('pageName'=>'All Exam Page', 'teamName'=>'UGC','URL'=>'https://www.shiksha.com/mba/exam'),
                            array('pageName'=>'Exam Detail Page', 'teamName'=>'UGC','URL'=>'https://www.shiksha.com/mba/exam/cat'),
                            array('pageName'=>'Institute Detail Page', 'teamName'=>'Listings','URL'=>'https://www.shiksha.com/getListingDetail/28361/institute/college-Faculty-Of-Management-Studies-University-Of-Delhi-Fms-Delhi-India'),
                            array('pageName'=>'Course Detail Page', 'teamName'=>'Listings','URL'=>'https://www.shiksha.com/mba/course/master-business-administration-faculty-management-studies-fms/111548'),
                            array('pageName'=>'Compare Page', 'teamName'=>'UGC','URL'=>'https://www.shiksha.com/comparison-of-iim-ahemdabad-vs-iim-bangalore-1653-1688'),
                            array('pageName'=>'College Review Homepage', 'teamName'=>'LDB','URL'=>'https://www.shiksha.com/mba/resources/college-reviews'),
                            array('pageName'=>'College Review Filter', 'teamName'=>'LDB','URL'=>'https://www.shiksha.com/mba/resources/reviews/top-mba-colleges-in-bangalore'),
                            array('pageName'=>'User Profile Page', 'teamName'=>'LDB','URL'=>'https://www.shiksha.com/userprofile/2579211'),
                            array('pageName'=>'IIM Call Predictor', 'teamName'=>'Listings','URL'=>'https://www.shiksha.com/mba/resources/iim-call-predictor'),
                            array('pageName'=>'Campus Connect Homepage', 'teamName'=>'UGC','URL'=>'https://www.shiksha.com/mba/resources/ask-current-mba-students'),
                            array('pageName'=>'Naukri Tool', 'teamName'=>'UGC','URL'=>'https://www.shiksha.com/mba/resources/mba-alumni-data'),
                            array('pageName'=>'Shortlist Homepage', 'teamName'=>'Listings','URL'=>'https://www.shiksha.com/my-shortlist-home'),
                            array('pageName'=>'Online Form Homepage', 'teamName'=>'UGC','URL'=>'https://www.shiksha.com/mba/resources/application-forms'),
                            array('pageName'=>'Article List Page', 'teamName'=>'UGC','URL'=>'https://www.shiksha.com/mba/resources/mba-news-articles'),
                            array('pageName'=>'Article Detail Page', 'teamName'=>'UGC','URL'=>'https://www.shiksha.com/iim-ahmedabad-invites-application-for-pgpx-2017-2018-last-date-sept-12-article-12987-1'),
                            array('pageName'=>'Event Calendar Page', 'teamName'=>'UGC','URL'=>'https://www.shiksha.com/mba/resources/exam-calendar'),
                            array('pageName'=>'Career Detail Page', 'teamName'=>'UGC','URL'=>'https://www.shiksha.com/careers/aeronautical-engineer-4'),
                            array('pageName'=>'Career Central Homepage', 'teamName'=>'UGC','URL'=>'https://www.shiksha.com/careers'),
                            array('pageName'=>'College Predictor', 'teamName'=>'UGC','URL'=>'https://www.shiksha.com/jee-mains-college-predictor'),
                            array('pageName'=>'Rank Predictor', 'teamName'=>'Listings','URL'=>'https://www.shiksha.com/jee-main-rank-predictor'),
                            array('pageName'=>'Search Page', 'teamName'=>'Listings','URL'=>'https://www.shiksha.com/search/?q=mba+in+india&qer=0%7C0%7C0%7C0%7C0%7C734%2C25%2C1375%2C1308%2C5%2C31%2C765%2C1307%2C768%2C743%2C17%2C782%2C699%2C12%2C746%2C1410%2C33%2C722%2C1310%2C442%2C1314%2C729%2C757%2C1306%2C737%2C762%2C34%2C14%2C4%2C26%2C24%2C13%2C747%2C741%2C730%2C8%2C716%2C761%2C535%2C726%2C758%2C745%2C753%2C19%2C744%2C756%2C763%2C11%2C723%2C731%2C738%2C15%2C1312%2C759%2C740%2C736%2C20%2C10%2C710%2C760%2C18%2C27%2C719%2C742%2C7%2C739%2C767%2C9%2C735%2C721%2C713%2C3%2C732%2C281%2C1313%2C280%2C752%2C30%2C754%2C1311%2C450%2C6%2C764%2C755%2C783%2C720%2C733%2C279%2C29%2C23%2C750%2C718%2C711%2C21%2C1305%2C1309%2C22%2C714%2C699%2C725%2C16%2C751%2C715%2C727%2C2%2C748%2C728%2C32%7C0%7C0%7C0&sa=%5E%5E0%5E0%5E0%5E0%5E0&ts=1215389&rf=searchwidget'),
							array('pageName'=>'SA Home Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/'),
							array('pageName'=>'SA Category Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/mba-in-abroad-dc11508'),
    						array('pageName'=>'SA Search Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/search-abroad/?q=MBA+in+General+Management&co[]=3&ds[]=1508&c[]=239&sc[]=254&qer=yes&tid=3275&ref=searchPage#'),
    						array('pageName'=>'SA Country Home', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/usa'),
    						array('pageName'=>'SA Country Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/usa/universities'),
    						array('pageName'=>'SA University Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/usa/universities/harvard-university?refCourseId=196202'),
    						array('pageName'=>'SA Course Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/usa/universities/harvard-university/mba'),
							array('pageName'=>'SA Article Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/top-5-post-graduate-courses-in-canada-articlepage-142'),
    						array('pageName'=>'SA Exam Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/exams/ielts'),
    						array('pageName'=>'SA Guide Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/student-guide-to-the-united-states-of-america-usa-guidepage-15'),
							array('pageName'=>'SA Apply Content', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/sop-statement-of-purpose-applycontent1701'),
							array('pageName'=>'SA Apply Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/apply'),
							array('pageName'=>'SA Counsellor Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/apply/counselors/iqra-362'),
							array('pageName'=>'SA Shipment Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/apply/shipment'),
							array('pageName'=>'SA Scholarship Home Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/scholarships'),
							array('pageName'=>'SA Scholarship Category Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/scholarships/masters-courses'),
							array('pageName'=>'SA Scholarship Detail Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/scholarships/global-study-awards'),
							array('pageName'=>'SA User Profile Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/users/Ranjita10605'),
							array('pageName'=>'SA Univ Ranking Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/top-universities-in-abroad-abroadranking32'),
							array('pageName'=>'SA Course Ranking Page', 'teamName'=>'StudyAbroad','URL'=>'https://studyabroad.shiksha.com/top-mba-colleges-in-usa-abroadranking30')
                        );
?>
