<?php


$ISDCodesList = array(
		'India'=>array('shikhsaCountry'=>'India', 'ISD'=>'91', 'shikshaCountryId'=>'2'),
		'Afghanistan'=>array('shikhsaCountry'=>'Afghanistan', 'ISD'=>'93', 'shikshaCountryId'=>'63'),
		'Albania'=>array('shikhsaCountry'=>'Albania', 'ISD'=>'355', 'shikshaCountryId'=>'64'),
		'Algeria'=>array('shikhsaCountry'=>'Algeria', 'ISD'=>'213', 'shikshaCountryId'=>'65'),
		'American Samoa'=>array('shikhsaCountry'=>'American Samoa', 'ISD'=>'1', 'shikshaCountryId'=>'66'),
		'Andorra'=>array('shikhsaCountry'=>'Andorra', 'ISD'=>'376', 'shikshaCountryId'=>'67'),
		'Angola'=>array('shikhsaCountry'=>'Angola', 'ISD'=>'244', 'shikshaCountryId'=>'68'),
		'Anguilla'=>array('shikhsaCountry'=>'Anguilla', 'ISD'=>'1', 'shikshaCountryId'=>'69'),
		'Antarctica'=>array('shikhsaCountry'=>'Antarctica', 'ISD'=>'672', 'shikshaCountryId'=>'70'),
		'Antigua and Barbuda'=>array('shikhsaCountry'=>'Antigua and Barbuda', 'ISD'=>'1', 'shikshaCountryId'=>'71'),
		'Argentina'=>array('shikhsaCountry'=>'Argentina', 'ISD'=>'54', 'shikshaCountryId'=>'72'),
		'Armenia'=>array('shikhsaCountry'=>'Armenia', 'ISD'=>'374', 'shikshaCountryId'=>'33'),
		'Aruba'=>array('shikhsaCountry'=>'Aruba', 'ISD'=>'297', 'shikshaCountryId'=>'73'),
		'Australia'=>array('shikhsaCountry'=>'Australia', 'ISD'=>'61', 'shikshaCountryId'=>'5'),
		'Austria'=>array('shikhsaCountry'=>'Austria', 'ISD'=>'43', 'shikshaCountryId'=>'47'),
		'Azerbaijan'=>array('shikhsaCountry'=>'Azerbaijan', 'ISD'=>'994', 'shikshaCountryId'=>'74'),
		'Bahamas'=>array('shikhsaCountry'=>'Bahamas', 'ISD'=>'1', 'shikshaCountryId'=>'75'),
		'Bahrain'=>array('shikhsaCountry'=>'Bahrain', 'ISD'=>'973', 'shikshaCountryId'=>'60'),
		'Bangladesh'=>array('shikhsaCountry'=>'Bangladesh', 'ISD'=>'880', 'shikshaCountryId'=>'51'),
		'Barbados'=>array('shikhsaCountry'=>'Barbados', 'ISD'=>'1', 'shikshaCountryId'=>'61'),
		'Belarus'=>array('shikhsaCountry'=>'Belarus', 'ISD'=>'375', 'shikshaCountryId'=>'76'),
		'Belgium'=>array('shikhsaCountry'=>'Belgium', 'ISD'=>'32', 'shikshaCountryId'=>'32'),
		'Belize'=>array('shikhsaCountry'=>'Belize', 'ISD'=>'501', 'shikshaCountryId'=>'77'),
		'Benin'=>array('shikhsaCountry'=>'Benin', 'ISD'=>'229', 'shikshaCountryId'=>'78'),
		'Bermuda'=>array('shikhsaCountry'=>'Bermuda', 'ISD'=>'1', 'shikshaCountryId'=>'79'),
		'Bhutan'=>array('shikhsaCountry'=>'Bhutan', 'ISD'=>'975', 'shikshaCountryId'=>'80'),
		'Bolivia'=>array('shikhsaCountry'=>'Bolivia', 'ISD'=>'591', 'shikshaCountryId'=>'81'),
		'Bosnia and Herzegovina'=>array('shikhsaCountry'=>'Bosnia and Herzegovina', 'ISD'=>'387', 'shikshaCountryId'=>'82'),
		'Botswana'=>array('shikhsaCountry'=>'Botswana', 'ISD'=>'267', 'shikshaCountryId'=>'83'),
		'Brazil'=>array('shikhsaCountry'=>'Brazil', 'ISD'=>'55', 'shikshaCountryId'=>'84'),
		'British Indian Ocean Territory'=>array('shikhsaCountry'=>'British Indian Ocean Territory', 'ISD'=>'246', 'shikshaCountryId'=>'85'),
		'Brunei Darussalam'=>array('shikhsaCountry'=>'Brunei', 'ISD'=>'673', 'shikshaCountryId'=>'87'),
		'Bulgaria'=>array('shikhsaCountry'=>'Bulgaria', 'ISD'=>'359', 'shikshaCountryId'=>'88'),
		'Burkina Faso'=>array('shikhsaCountry'=>'Burkina Faso', 'ISD'=>'226', 'shikshaCountryId'=>'89'),
		'Burundi'=>array('shikhsaCountry'=>'Burundi', 'ISD'=>'257', 'shikshaCountryId'=>'90'),
		'Cambodia'=>array('shikhsaCountry'=>'Cambodia', 'ISD'=>'855', 'shikshaCountryId'=>'91'),
		'Cameroon'=>array('shikhsaCountry'=>'Cameroon', 'ISD'=>'237', 'shikshaCountryId'=>'92'),
		'Canada'=>array('shikhsaCountry'=>'Canada', 'ISD'=>'1', 'shikshaCountryId'=>'8'),
		'Cape Verde'=>array('shikhsaCountry'=>'Cape Verde', 'ISD'=>'238', 'shikshaCountryId'=>'93'),
		'Cayman Islands'=>array('shikhsaCountry'=>'Cayman Islands', 'ISD'=>'1', 'shikshaCountryId'=>'94'),
		'Central African Republic'=>array('shikhsaCountry'=>'Central African Republic', 'ISD'=>'236', 'shikshaCountryId'=>'95'),
		'Chad'=>array('shikhsaCountry'=>'Chad', 'ISD'=>'235', 'shikshaCountryId'=>'96'),
		'Chile'=>array('shikhsaCountry'=>'Chile', 'ISD'=>'56', 'shikshaCountryId'=>'97'),
		'China'=>array('shikhsaCountry'=>'China', 'ISD'=>'86', 'shikshaCountryId'=>'36'),
		'Christmas Island'=>array('shikhsaCountry'=>'Christmas Island', 'ISD'=>'61', 'shikshaCountryId'=>'98'),
		'Cocos (Keeling) Islands'=>array('shikhsaCountry'=>'Cocos Islands', 'ISD'=>'891', 'shikshaCountryId'=>'99'),
		'Colombia'=>array('shikhsaCountry'=>'Colombia', 'ISD'=>'57', 'shikshaCountryId'=>'100'),
		'Comoros'=>array('shikhsaCountry'=>'Comoros', 'ISD'=>'269', 'shikshaCountryId'=>'101'),
		'Congo'=>array('shikhsaCountry'=>'Democratic Republic of the Congo', 'ISD'=>'242', 'shikshaCountryId'=>'108'),
		'Cook Islands'=>array('shikhsaCountry'=>'Cook Islands', 'ISD'=>'682', 'shikshaCountryId'=>'102'),
		'Costa Rica'=>array('shikhsaCountry'=>'Costa Rica', 'ISD'=>'506', 'shikshaCountryId'=>'103'),
		'Croatia'=>array('shikhsaCountry'=>'Croatia', 'ISD'=>'385', 'shikshaCountryId'=>'104'),
		'Cuba'=>array('shikhsaCountry'=>'Cuba', 'ISD'=>'53', 'shikshaCountryId'=>'105'),
		'Curacao'=>array('shikhsaCountry'=>'Curacao', 'ISD'=>'599', 'shikshaCountryId'=>'106'),
		'Cyprus'=>array('shikhsaCountry'=>'Cyprus', 'ISD'=>'357', 'shikshaCountryId'=>'50'),
		'Czech Republic'=>array('shikhsaCountry'=>'Czech Republic', 'ISD'=>'420', 'shikshaCountryId'=>'107'),
		'Denmark'=>array('shikhsaCountry'=>'Denmark', 'ISD'=>'45', 'shikshaCountryId'=>'15'),
		'Djibouti'=>array('shikhsaCountry'=>'Djibouti', 'ISD'=>'253', 'shikshaCountryId'=>'109'),
		'Dominica'=>array('shikhsaCountry'=>'Dominica', 'ISD'=>'1', 'shikshaCountryId'=>'110'),
		'Dominican Republic'=>array('shikhsaCountry'=>'Dominican Republic', 'ISD'=>'1', 'shikshaCountryId'=>'111'),
		'Ecuador'=>array('shikhsaCountry'=>'Ecuador', 'ISD'=>'593', 'shikshaCountryId'=>'113'),
		'Egypt'=>array('shikhsaCountry'=>'Egypt', 'ISD'=>'20', 'shikshaCountryId'=>'114'),
		'El Salvador'=>array('shikhsaCountry'=>'El Salvador', 'ISD'=>'503', 'shikshaCountryId'=>'115'),
		'Equatorial Guinea'=>array('shikhsaCountry'=>'Equatorial Guinea', 'ISD'=>'240', 'shikshaCountryId'=>'116'),
		'Eritrea'=>array('shikhsaCountry'=>'Eritrea', 'ISD'=>'291', 'shikshaCountryId'=>'117'),
		'Estonia'=>array('shikhsaCountry'=>'Estonia', 'ISD'=>'372', 'shikshaCountryId'=>'42'),
		'Ethiopia'=>array('shikhsaCountry'=>'Ethiopia', 'ISD'=>'251', 'shikshaCountryId'=>'118'),
		'Falkland Islands (Malvinas)'=>array('shikhsaCountry'=>'Falkland Islands', 'ISD'=>'500', 'shikshaCountryId'=>'119'),
		'Faroe Islands'=>array('shikhsaCountry'=>'Faroe Islands', 'ISD'=>'298', 'shikshaCountryId'=>'120'),
		'Fiji'=>array('shikhsaCountry'=>'Fiji', 'ISD'=>'679', 'shikshaCountryId'=>'35'),
		'Finland'=>array('shikhsaCountry'=>'Finland', 'ISD'=>'358', 'shikshaCountryId'=>'121'),
		'France'=>array('shikhsaCountry'=>'France', 'ISD'=>'33', 'shikshaCountryId'=>'12'),
		'French Polynesia'=>array('shikhsaCountry'=>'French Polynesia', 'ISD'=>'689', 'shikshaCountryId'=>'122'),
		'Gabon'=>array('shikhsaCountry'=>'Gabon', 'ISD'=>'241', 'shikshaCountryId'=>'123'),
		'Gambia'=>array('shikhsaCountry'=>'Gambia', 'ISD'=>'220', 'shikshaCountryId'=>'124'),
		'Georgia'=>array('shikhsaCountry'=>'Georgia', 'ISD'=>'995', 'shikshaCountryId'=>'56'),
		'Germany'=>array('shikhsaCountry'=>'Germany', 'ISD'=>'49', 'shikshaCountryId'=>'9'),
		'Ghana'=>array('shikhsaCountry'=>'Ghana', 'ISD'=>'233', 'shikshaCountryId'=>'125'),
		'Gibraltar'=>array('shikhsaCountry'=>'Gibraltar', 'ISD'=>'350', 'shikshaCountryId'=>'126'),
		'Greece'=>array('shikhsaCountry'=>'Greece', 'ISD'=>'30', 'shikshaCountryId'=>'40'),
		'Greenland'=>array('shikhsaCountry'=>'Greenland', 'ISD'=>'299', 'shikshaCountryId'=>'127'),
		'Grenada'=>array('shikhsaCountry'=>'Grenada', 'ISD'=>'1', 'shikshaCountryId'=>'128'),
		'Guam'=>array('shikhsaCountry'=>'Guam', 'ISD'=>'1', 'shikshaCountryId'=>'129'),
		'Guatemala'=>array('shikhsaCountry'=>'Guatemala', 'ISD'=>'502', 'shikshaCountryId'=>'130'),
		'Guernsey'=>array('shikhsaCountry'=>'Guernsey', 'ISD'=>'44', 'shikshaCountryId'=>'131'),
		'Guinea'=>array('shikhsaCountry'=>'Guinea', 'ISD'=>'224', 'shikshaCountryId'=>'132'),
		'Guinea-Bissau'=>array('shikhsaCountry'=>'Guinea-Bissau', 'ISD'=>'245', 'shikshaCountryId'=>'133'),
		'Guyana'=>array('shikhsaCountry'=>'Guyana', 'ISD'=>'592', 'shikshaCountryId'=>'62'),
		'Haiti'=>array('shikhsaCountry'=>'Haiti', 'ISD'=>'509', 'shikshaCountryId'=>'134'),
		'Honduras'=>array('shikhsaCountry'=>'Honduras', 'ISD'=>'504', 'shikshaCountryId'=>'135'),
		'Hong Kong'=>array('shikhsaCountry'=>'Hong Kong', 'ISD'=>'852', 'shikshaCountryId'=>'57'),
		'Hungary'=>array('shikhsaCountry'=>'Hungary', 'ISD'=>'36', 'shikshaCountryId'=>'46'),
		'Iceland'=>array('shikhsaCountry'=>'Iceland', 'ISD'=>'354', 'shikshaCountryId'=>'136'),
		'Indonesia'=>array('shikhsaCountry'=>'Indonesia', 'ISD'=>'62', 'shikshaCountryId'=>'137'),
		'Iran, Islamic Republic of'=>array('shikhsaCountry'=>'Iran', 'ISD'=>'98', 'shikshaCountryId'=>'138'),
		'Iraq'=>array('shikhsaCountry'=>'Iraq', 'ISD'=>'964', 'shikshaCountryId'=>'139'),
		'Ireland'=>array('shikhsaCountry'=>'Ireland', 'ISD'=>'353', 'shikshaCountryId'=>'21'),
		'Isle of Man'=>array('shikhsaCountry'=>'Isle of Man', 'ISD'=>'44', 'shikshaCountryId'=>'140'),
		'Israel'=>array('shikhsaCountry'=>'Israel', 'ISD'=>'972', 'shikshaCountryId'=>'141'),
		'Italy'=>array('shikhsaCountry'=>'Italy', 'ISD'=>'39', 'shikshaCountryId'=>'22'),
		'Jamaica'=>array('shikhsaCountry'=>'Jamaica', 'ISD'=>'1', 'shikshaCountryId'=>'143'),
		'Japan'=>array('shikhsaCountry'=>'Japan', 'ISD'=>'81', 'shikshaCountryId'=>'30'),
		'Jersey'=>array('shikhsaCountry'=>'Jersey', 'ISD'=>'44', 'shikshaCountryId'=>'144'),
		'Jordan'=>array('shikhsaCountry'=>'Jordan', 'ISD'=>'962', 'shikshaCountryId'=>'145'),
		'Kazakhstan'=>array('shikhsaCountry'=>'Kazakhstan', 'ISD'=>'7', 'shikshaCountryId'=>'146'),
		'Kenya'=>array('shikhsaCountry'=>'Kenya', 'ISD'=>'254', 'shikshaCountryId'=>'147'),
		'Kiribati'=>array('shikhsaCountry'=>'Kiribati', 'ISD'=>'686', 'shikshaCountryId'=>'148'),
		'Kuwait'=>array('shikhsaCountry'=>'Kuwait', 'ISD'=>'965', 'shikshaCountryId'=>'150'),
		'Kyrgyzstan'=>array('shikhsaCountry'=>'Kyrgyzstan', 'ISD'=>'996', 'shikshaCountryId'=>'151'),
		'Latvia'=>array('shikhsaCountry'=>'Latvia', 'ISD'=>'371', 'shikshaCountryId'=>'153'),
		'Lebanon'=>array('shikhsaCountry'=>'Lebanon', 'ISD'=>'961', 'shikshaCountryId'=>'154'),
		'Lesotho'=>array('shikhsaCountry'=>'Lesotho', 'ISD'=>'266', 'shikshaCountryId'=>'155'),
		'Liberia'=>array('shikhsaCountry'=>'Liberia', 'ISD'=>'231', 'shikshaCountryId'=>'156'),
		'Libyan Arab Jamahiriya'=>array('shikhsaCountry'=>'Libya', 'ISD'=>'218', 'shikshaCountryId'=>'157'),
		'Liechtenstein'=>array('shikhsaCountry'=>'Liechtenstein', 'ISD'=>'423', 'shikshaCountryId'=>'158'),
		'Lithuania'=>array('shikhsaCountry'=>'Lithuania', 'ISD'=>'370', 'shikshaCountryId'=>'53'),
		'Luxembourg'=>array('shikhsaCountry'=>'Luxembourg', 'ISD'=>'352', 'shikshaCountryId'=>'43'),
		'Macao'=>array('shikhsaCountry'=>'Macao', 'ISD'=>'853', 'shikshaCountryId'=>'159'),
		'Macedonia'=>array('shikhsaCountry'=>'Macedonia', 'ISD'=>'389', 'shikshaCountryId'=>'160'),
		'Madagascar'=>array('shikhsaCountry'=>'Madagascar', 'ISD'=>'261', 'shikshaCountryId'=>'161'),
		'Malawi'=>array('shikhsaCountry'=>'Malawi', 'ISD'=>'265', 'shikshaCountryId'=>'162'),
		'Malaysia'=>array('shikhsaCountry'=>'Malaysia', 'ISD'=>'60', 'shikshaCountryId'=>'10'),
		'Maldives'=>array('shikhsaCountry'=>'Maldives', 'ISD'=>'960', 'shikshaCountryId'=>'163'),
		'Mali'=>array('shikhsaCountry'=>'Mali', 'ISD'=>'223', 'shikshaCountryId'=>'164'),
		'Malta'=>array('shikhsaCountry'=>'Malta', 'ISD'=>'356', 'shikshaCountryId'=>'59'),
		'Marshall Islands'=>array('shikhsaCountry'=>'Marshall Islands', 'ISD'=>'692', 'shikshaCountryId'=>'165'),
		'Mauritania'=>array('shikhsaCountry'=>'Mauritania', 'ISD'=>'222', 'shikshaCountryId'=>'166'),
		'Mauritius'=>array('shikhsaCountry'=>'Mauritius', 'ISD'=>'230', 'shikshaCountryId'=>'41'),
		'Mayotte'=>array('shikhsaCountry'=>'Mayotte', 'ISD'=>'262', 'shikshaCountryId'=>'167'),
		'Mexico'=>array('shikhsaCountry'=>'Mexico', 'ISD'=>'52', 'shikshaCountryId'=>'168'),
		'Micronesia, Federated States of'=>array('shikhsaCountry'=>'Micronesia', 'ISD'=>'691', 'shikshaCountryId'=>'169'),
		'Moldova, Republic of'=>array('shikhsaCountry'=>'Moldova', 'ISD'=>'373', 'shikshaCountryId'=>'170'),
		'Monaco'=>array('shikhsaCountry'=>'Monaco', 'ISD'=>'377', 'shikshaCountryId'=>'54'),
		'Mongolia'=>array('shikhsaCountry'=>'Mongolia', 'ISD'=>'976', 'shikshaCountryId'=>'171'),
		'Montenegro'=>array('shikhsaCountry'=>'Montenegro', 'ISD'=>'382', 'shikshaCountryId'=>'172'),
		'Montserrat'=>array('shikhsaCountry'=>'Montserrat', 'ISD'=>'1', 'shikshaCountryId'=>'173'),
		'Morocco'=>array('shikhsaCountry'=>'Morocco', 'ISD'=>'212', 'shikshaCountryId'=>'174'),
		'Mozambique'=>array('shikhsaCountry'=>'Mozambique', 'ISD'=>'258', 'shikshaCountryId'=>'175'),
		'Myanmar'=>array('shikhsaCountry'=>'Myanmar', 'ISD'=>'95', 'shikshaCountryId'=>'176'),
		'Namibia'=>array('shikhsaCountry'=>'Namibia', 'ISD'=>'264', 'shikshaCountryId'=>'177'),
		'Nauru'=>array('shikhsaCountry'=>'Nauru', 'ISD'=>'674', 'shikshaCountryId'=>'178'),
		'Nepal'=>array('shikhsaCountry'=>'Nepal', 'ISD'=>'977', 'shikshaCountryId'=>'55'),
		'Netherlands'=>array('shikhsaCountry'=>'Netherlands', 'ISD'=>'31', 'shikshaCountryId'=>'14'),
		'New Caledonia'=>array('shikhsaCountry'=>'New Caledonia', 'ISD'=>'687', 'shikshaCountryId'=>'180'),
		'New Zealand'=>array('shikhsaCountry'=>'New Zealand', 'ISD'=>'64', 'shikshaCountryId'=>'7'),
		'Nicaragua'=>array('shikhsaCountry'=>'Nicaragua', 'ISD'=>'505', 'shikshaCountryId'=>'181'),
		'Niger'=>array('shikhsaCountry'=>'Niger', 'ISD'=>'227', 'shikshaCountryId'=>'182'),
		'Nigeria'=>array('shikhsaCountry'=>'Nigeria', 'ISD'=>'234', 'shikshaCountryId'=>'183'),
		'Niue'=>array('shikhsaCountry'=>'Niue', 'ISD'=>'683', 'shikshaCountryId'=>'184'),
		'North Korea'=>array('shikhsaCountry'=>'North Korea', 'ISD'=>'850', 'shikshaCountryId'=>'185'),
		'Northern Mariana Islands'=>array('shikhsaCountry'=>'Northern Mariana Islands', 'ISD'=>'1', 'shikshaCountryId'=>'186'),
		'Norway'=>array('shikhsaCountry'=>'Norway', 'ISD'=>'47', 'shikshaCountryId'=>'27'),
		'Oman'=>array('shikhsaCountry'=>'Oman', 'ISD'=>'968', 'shikshaCountryId'=>'187'),
		'Pakistan'=>array('shikhsaCountry'=>'Pakistan', 'ISD'=>'92', 'shikshaCountryId'=>'188'),
		'Palau'=>array('shikhsaCountry'=>'Palau', 'ISD'=>'680', 'shikshaCountryId'=>'189'),
		'Palestinian Territory'=>array('shikhsaCountry'=>'Palestine', 'ISD'=>'970', 'shikshaCountryId'=>'190'),
		'Panama'=>array('shikhsaCountry'=>'Panama', 'ISD'=>'507', 'shikshaCountryId'=>'191'),
		'Papua New Guinea'=>array('shikhsaCountry'=>'Papua New Guinea', 'ISD'=>'675', 'shikshaCountryId'=>'192'),
		'Paraguay'=>array('shikhsaCountry'=>'Paraguay', 'ISD'=>'595', 'shikshaCountryId'=>'193'),
		'Peru'=>array('shikhsaCountry'=>'Peru', 'ISD'=>'51', 'shikshaCountryId'=>'194'),
		'Philippines'=>array('shikhsaCountry'=>'Philippines', 'ISD'=>'63', 'shikshaCountryId'=>'49'),
		'Pitcairn'=>array('shikhsaCountry'=>'Pitcairn', 'ISD'=>'64', 'shikshaCountryId'=>'195'),
		'Poland'=>array('shikhsaCountry'=>'Poland', 'ISD'=>'48', 'shikshaCountryId'=>'25'),
		'Portugal'=>array('shikhsaCountry'=>'Portugal', 'ISD'=>'351', 'shikshaCountryId'=>'26'),
		'Puerto Rico'=>array('shikhsaCountry'=>'Puerto Rico', 'ISD'=>'1', 'shikshaCountryId'=>'196'),
		'Qatar'=>array('shikhsaCountry'=>'Qatar', 'ISD'=>'974', 'shikshaCountryId'=>'197'),
		'Republic of Korea'=>array('shikhsaCountry'=>'South Korea', 'ISD'=>'82', 'shikshaCountryId'=>'38'),
		'Republic of the Congo'=>array('shikhsaCountry'=>'Democratic Republic of the Congo', 'ISD'=>'242', 'shikshaCountryId'=>'108'),
		'Reunion'=>array('shikhsaCountry'=>'Reunion', 'ISD'=>'262', 'shikshaCountryId'=>'199'),
		'Romania'=>array('shikhsaCountry'=>'Romania', 'ISD'=>'40', 'shikshaCountryId'=>'200'),
		'Russian Federation'=>array('shikhsaCountry'=>'Russia', 'ISD'=>'7', 'shikshaCountryId'=>'17'),
		'Rwanda'=>array('shikhsaCountry'=>'Rwanda', 'ISD'=>'250', 'shikshaCountryId'=>'201'),
		'Saint Bartelemey'=>array('shikhsaCountry'=>'Saint Barthelemy', 'ISD'=>'590', 'shikshaCountryId'=>'202'),
		'Saint Helena'=>array('shikhsaCountry'=>'Saint Helena', 'ISD'=>'290', 'shikshaCountryId'=>'203'),
		'Saint Kitts and Nevis'=>array('shikhsaCountry'=>'Saint Kitts and Nevis', 'ISD'=>'1', 'shikshaCountryId'=>'204'),
		'Saint Lucia'=>array('shikhsaCountry'=>'Saint Lucia', 'ISD'=>'1', 'shikshaCountryId'=>'205'),
		'Saint Martin'=>array('shikhsaCountry'=>'Saint Martin', 'ISD'=>'590', 'shikshaCountryId'=>'206'),
		'Saint Pierre and Miquelon'=>array('shikhsaCountry'=>'Saint Pierre and Miquelon', 'ISD'=>'508', 'shikshaCountryId'=>'207'),
		'Saint Vincent and the Grenadines'=>array('shikhsaCountry'=>'Saint Vincent and the Grenadines', 'ISD'=>'1', 'shikshaCountryId'=>'208'),
		'Samoa'=>array('shikhsaCountry'=>'Samoa', 'ISD'=>'685', 'shikshaCountryId'=>'209'),
		'San Marino'=>array('shikhsaCountry'=>'San Marino', 'ISD'=>'378', 'shikshaCountryId'=>'210'),
		'Sao Tome and Principe'=>array('shikhsaCountry'=>'Sao Tome and Principe', 'ISD'=>'239', 'shikshaCountryId'=>'211'),
		'Saudi Arabia'=>array('shikhsaCountry'=>'Saudi Arabia', 'ISD'=>'966', 'shikshaCountryId'=>'212'),
		'Senegal'=>array('shikhsaCountry'=>'Senegal', 'ISD'=>'221', 'shikshaCountryId'=>'213'),
		'Serbia'=>array('shikhsaCountry'=>'Serbia', 'ISD'=>'381', 'shikshaCountryId'=>'214'),
		'Seychelles'=>array('shikhsaCountry'=>'Seychelles', 'ISD'=>'248', 'shikshaCountryId'=>'215'),
		'Sierra Leone'=>array('shikhsaCountry'=>'Sierra Leone', 'ISD'=>'232', 'shikshaCountryId'=>'216'),
		'Singapore'=>array('shikhsaCountry'=>'Singapore', 'ISD'=>'65', 'shikshaCountryId'=>'6'),
		'Sint Maarten'=>array('shikhsaCountry'=>'Sint Maarten', 'ISD'=>'1', 'shikshaCountryId'=>'217'),
		'Slovakia'=>array('shikhsaCountry'=>'Slovakia', 'ISD'=>'421', 'shikshaCountryId'=>'218'),
		'Slovenia'=>array('shikhsaCountry'=>'Slovenia', 'ISD'=>'386', 'shikshaCountryId'=>'48'),
		'Solomon Islands'=>array('shikhsaCountry'=>'Solomon Islands', 'ISD'=>'677', 'shikshaCountryId'=>'219'),
		'Somalia'=>array('shikhsaCountry'=>'Somalia', 'ISD'=>'252', 'shikshaCountryId'=>'220'),
		'South Africa'=>array('shikhsaCountry'=>'South Africa', 'ISD'=>'27', 'shikshaCountryId'=>'45'),
		'South Sudan'=>array('shikhsaCountry'=>'South Sudan', 'ISD'=>'211', 'shikshaCountryId'=>'221'),
		'Spain'=>array('shikhsaCountry'=>'Spain', 'ISD'=>'34', 'shikshaCountryId'=>'16'),
		'Sri Lanka'=>array('shikhsaCountry'=>'Sri Lanka', 'ISD'=>'94', 'shikshaCountryId'=>'222'),
		'Sudan'=>array('shikhsaCountry'=>'Sudan', 'ISD'=>'249', 'shikshaCountryId'=>'223'),
		'Suriname'=>array('shikhsaCountry'=>'Suriname', 'ISD'=>'597', 'shikshaCountryId'=>'224'),
		'Svalbard and Jan Mayen'=>array('shikhsaCountry'=>'Svalbard and Jan Mayen', 'ISD'=>'47', 'shikshaCountryId'=>'225'),
		'Swaziland'=>array('shikhsaCountry'=>'Swaziland', 'ISD'=>'268', 'shikshaCountryId'=>'226'),
		'Sweden'=>array('shikhsaCountry'=>'Sweden', 'ISD'=>'46', 'shikshaCountryId'=>'11'),
		'Switzerland'=>array('shikhsaCountry'=>'Switzerland', 'ISD'=>'41', 'shikshaCountryId'=>'13'),
		'Syrian Arab Republic'=>array('shikhsaCountry'=>'Syria', 'ISD'=>'963', 'shikshaCountryId'=>'227'),
		'Taiwan'=>array('shikhsaCountry'=>'Taiwan', 'ISD'=>'886', 'shikshaCountryId'=>'228'),
		'Tajikistan'=>array('shikhsaCountry'=>'Tajikistan', 'ISD'=>'992', 'shikshaCountryId'=>'229'),
		'Tanzania'=>array('shikhsaCountry'=>'Tanzania', 'ISD'=>'255', 'shikshaCountryId'=>'230'),
		'Thailand'=>array('shikhsaCountry'=>'Thailand', 'ISD'=>'66', 'shikshaCountryId'=>'31'),
		'Timor-Leste'=>array('shikhsaCountry'=>'East Timor', 'ISD'=>'670', 'shikshaCountryId'=>'112'),
		'Togo'=>array('shikhsaCountry'=>'Togo', 'ISD'=>'228', 'shikshaCountryId'=>'230'),
		'Tokelau'=>array('shikhsaCountry'=>'Tokelau', 'ISD'=>'690', 'shikshaCountryId'=>'232'),
		'Tonga'=>array('shikhsaCountry'=>'Tonga', 'ISD'=>'676', 'shikshaCountryId'=>'233'),
		'Trinidad and Tobago'=>array('shikhsaCountry'=>'Trinidad and Tobago', 'ISD'=>'1', 'shikshaCountryId'=>'234'),
		'Tunisia'=>array('shikhsaCountry'=>'Tunisia', 'ISD'=>'216', 'shikshaCountryId'=>'235'),
		'Turkey'=>array('shikhsaCountry'=>'Turkey', 'ISD'=>'90', 'shikshaCountryId'=>'58'),
		'Turkmenistan'=>array('shikhsaCountry'=>'Turkmenistan', 'ISD'=>'993', 'shikshaCountryId'=>'236'),
		'Turks and Caicos Islands'=>array('shikhsaCountry'=>'Turks and Caicos Islands', 'ISD'=>'1', 'shikshaCountryId'=>'237'),
		'Tuvalu'=>array('shikhsaCountry'=>'Tuvalu', 'ISD'=>'688', 'shikshaCountryId'=>'238'),
		'Uganda'=>array('shikhsaCountry'=>'Uganda', 'ISD'=>'256', 'shikshaCountryId'=>'240'),
		'Ukraine'=>array('shikhsaCountry'=>'Ukraine', 'ISD'=>'380', 'shikshaCountryId'=>'44'),
		'United Arab Emirates'=>array('shikhsaCountry'=>'UAE', 'ISD'=>'971', 'shikshaCountryId'=>'18'),
		'United Kingdom'=>array('shikhsaCountry'=>'UK', 'ISD'=>'44', 'shikshaCountryId'=>'4'),
		'United States'=>array('shikhsaCountry'=>'USA', 'ISD'=>'1', 'shikshaCountryId'=>'3'),
		'Uruguay'=>array('shikhsaCountry'=>'Uruguay', 'ISD'=>'598', 'shikshaCountryId'=>'241'),
		'Uzbekistan'=>array('shikhsaCountry'=>'Uzbekistan', 'ISD'=>'998', 'shikshaCountryId'=>'242'),
		'Vanuatu'=>array('shikhsaCountry'=>'Vanuatu', 'ISD'=>'678', 'shikshaCountryId'=>'243'),
		'Venezuela'=>array('shikhsaCountry'=>'Venezuela', 'ISD'=>'58', 'shikshaCountryId'=>'245'),
		'Vietnam'=>array('shikhsaCountry'=>'Vietnam', 'ISD'=>'84', 'shikshaCountryId'=>'246'),
		'Wallis and Futuna'=>array('shikhsaCountry'=>'Wallis and Futuna', 'ISD'=>'681', 'shikshaCountryId'=>'247'),
		'Western Sahara'=>array('shikhsaCountry'=>'Western Sahara', 'ISD'=>'212', 'shikshaCountryId'=>'248'),
		'Yemen'=>array('shikhsaCountry'=>'Yemen', 'ISD'=>'967', 'shikshaCountryId'=>'249'),
		'Zambia'=>array('shikhsaCountry'=>'Zambia', 'ISD'=>'260', 'shikshaCountryId'=>'250'),
		'Zimbabwe'=>array('shikhsaCountry'=>'Zimbabwe', 'ISD'=>'263', 'shikshaCountryId'=>'251')
	);

$shikshaCountryToISDCodeMapping = array(
		'63'=>array('shikshaCountry'=>'Afghanistan', 'ISD'=>'93'),
		'64'=>array('shikshaCountry'=>'Albania', 'ISD'=>'355'),
		'65'=>array('shikshaCountry'=>'Algeria', 'ISD'=>'213'),
		'66'=>array('shikshaCountry'=>'American Samoa', 'ISD'=>'1'),
		'67'=>array('shikshaCountry'=>'Andorra', 'ISD'=>'376'),
		'68'=>array('shikshaCountry'=>'Angola', 'ISD'=>'244'),
		'69'=>array('shikshaCountry'=>'Anguilla', 'ISD'=>'1'),
		'70'=>array('shikshaCountry'=>'Antarctica', 'ISD'=>'672'),
		'71'=>array('shikshaCountry'=>'Antigua and Barbuda', 'ISD'=>'1'),
		'72'=>array('shikshaCountry'=>'Argentina', 'ISD'=>'54'),
		'33'=>array('shikshaCountry'=>'Armenia', 'ISD'=>'374'),
		'73'=>array('shikshaCountry'=>'Aruba', 'ISD'=>'297'),
		'5'=>array('shikshaCountry'=>'Australia', 'ISD'=>'61'),
		'47'=>array('shikshaCountry'=>'Austria', 'ISD'=>'43'),
		'74'=>array('shikshaCountry'=>'Azerbaijan', 'ISD'=>'994'),
		'75'=>array('shikshaCountry'=>'Bahamas', 'ISD'=>'1'),
		'60'=>array('shikshaCountry'=>'Bahrain', 'ISD'=>'973'),
		'51'=>array('shikshaCountry'=>'Bangladesh', 'ISD'=>'880'),
		'61'=>array('shikshaCountry'=>'Barbados', 'ISD'=>'1'),
		'76'=>array('shikshaCountry'=>'Belarus', 'ISD'=>'375'),
		'32'=>array('shikshaCountry'=>'Belgium', 'ISD'=>'32'),
		'77'=>array('shikshaCountry'=>'Belize', 'ISD'=>'501'),
		'78'=>array('shikshaCountry'=>'Benin', 'ISD'=>'229'),
		'79'=>array('shikshaCountry'=>'Bermuda', 'ISD'=>'1'),
		'80'=>array('shikshaCountry'=>'Bhutan', 'ISD'=>'975'),
		'81'=>array('shikshaCountry'=>'Bolivia', 'ISD'=>'591'),
		'82'=>array('shikshaCountry'=>'Bosnia and Herzegovina', 'ISD'=>'387'),
		'83'=>array('shikshaCountry'=>'Botswana', 'ISD'=>'267'),
		'84'=>array('shikshaCountry'=>'Brazil', 'ISD'=>'55'),
		'85'=>array('shikshaCountry'=>'British Indian Ocean Territory', 'ISD'=>'246'),
		'87'=>array('shikshaCountry'=>'Brunei', 'ISD'=>'673'),
		'88'=>array('shikshaCountry'=>'Bulgaria', 'ISD'=>'359'),
		'89'=>array('shikshaCountry'=>'Burkina Faso', 'ISD'=>'226'),
		'90'=>array('shikshaCountry'=>'Burundi', 'ISD'=>'257'),
		'91'=>array('shikshaCountry'=>'Cambodia', 'ISD'=>'855'),
		'92'=>array('shikshaCountry'=>'Cameroon', 'ISD'=>'237'),
		'8'=>array('shikshaCountry'=>'Canada', 'ISD'=>'1'),
		'93'=>array('shikshaCountry'=>'Cape Verde', 'ISD'=>'238'),
		'94'=>array('shikshaCountry'=>'Cayman Islands', 'ISD'=>'1'),
		'95'=>array('shikshaCountry'=>'Central African Republic', 'ISD'=>'236'),
		'96'=>array('shikshaCountry'=>'Chad', 'ISD'=>'235'),
		'97'=>array('shikshaCountry'=>'Chile', 'ISD'=>'56'),
		'36'=>array('shikshaCountry'=>'China', 'ISD'=>'86'),
		'98'=>array('shikshaCountry'=>'Christmas Island', 'ISD'=>'61'),
		'99'=>array('shikshaCountry'=>'Cocos Islands', 'ISD'=>'891'),
		'100'=>array('shikshaCountry'=>'Colombia', 'ISD'=>'57'),
		'101'=>array('shikshaCountry'=>'Comoros', 'ISD'=>'269'),
		'108'=>array('shikshaCountry'=>'Democratic Republic of the Congo', 'ISD'=>'242'),
		'102'=>array('shikshaCountry'=>'Cook Islands', 'ISD'=>'682'),
		'103'=>array('shikshaCountry'=>'Costa Rica', 'ISD'=>'506'),
		'104'=>array('shikshaCountry'=>'Croatia', 'ISD'=>'385'),
		'105'=>array('shikshaCountry'=>'Cuba', 'ISD'=>'53'),
		'106'=>array('shikshaCountry'=>'Curacao', 'ISD'=>'599'),
		'50'=>array('shikshaCountry'=>'Cyprus', 'ISD'=>'357'),
		'107'=>array('shikshaCountry'=>'Czech Republic', 'ISD'=>'420'),
		'15'=>array('shikshaCountry'=>'Denmark', 'ISD'=>'45'),
		'109'=>array('shikshaCountry'=>'Djibouti', 'ISD'=>'253'),
		'110'=>array('shikshaCountry'=>'Dominica', 'ISD'=>'1'),
		'111'=>array('shikshaCountry'=>'Dominican Republic', 'ISD'=>'1'),
		'113'=>array('shikshaCountry'=>'Ecuador', 'ISD'=>'593'),
		'114'=>array('shikshaCountry'=>'Egypt', 'ISD'=>'20'),
		'115'=>array('shikshaCountry'=>'El Salvador', 'ISD'=>'503'),
		'116'=>array('shikshaCountry'=>'Equatorial Guinea', 'ISD'=>'240'),
		'117'=>array('shikshaCountry'=>'Eritrea', 'ISD'=>'291'),
		'42'=>array('shikshaCountry'=>'Estonia', 'ISD'=>'372'),
		'118'=>array('shikshaCountry'=>'Ethiopia', 'ISD'=>'251'),
		'119'=>array('shikshaCountry'=>'Falkland Islands', 'ISD'=>'500'),
		'120'=>array('shikshaCountry'=>'Faroe Islands', 'ISD'=>'298'),
		'35'=>array('shikshaCountry'=>'Fiji', 'ISD'=>'679'),
		'121'=>array('shikshaCountry'=>'Finland', 'ISD'=>'358'),
		'12'=>array('shikshaCountry'=>'France', 'ISD'=>'33'),
		'122'=>array('shikshaCountry'=>'French Polynesia', 'ISD'=>'689'),
		'123'=>array('shikshaCountry'=>'Gabon', 'ISD'=>'241'),
		'124'=>array('shikshaCountry'=>'Gambia', 'ISD'=>'220'),
		'56'=>array('shikshaCountry'=>'Georgia', 'ISD'=>'995'),
		'9'=>array('shikshaCountry'=>'Germany', 'ISD'=>'49'),
		'125'=>array('shikshaCountry'=>'Ghana', 'ISD'=>'233'),
		'126'=>array('shikshaCountry'=>'Gibraltar', 'ISD'=>'350'),
		'40'=>array('shikshaCountry'=>'Greece', 'ISD'=>'30'),
		'127'=>array('shikshaCountry'=>'Greenland', 'ISD'=>'299'),
		'128'=>array('shikshaCountry'=>'Grenada', 'ISD'=>'1'),
		'129'=>array('shikshaCountry'=>'Guam', 'ISD'=>'1'),
		'130'=>array('shikshaCountry'=>'Guatemala', 'ISD'=>'502'),
		'131'=>array('shikshaCountry'=>'Guernsey', 'ISD'=>'44'),
		'132'=>array('shikshaCountry'=>'Guinea', 'ISD'=>'224'),
		'133'=>array('shikshaCountry'=>'Guinea-Bissau', 'ISD'=>'245'),
		'62'=>array('shikshaCountry'=>'Guyana', 'ISD'=>'592'),
		'134'=>array('shikshaCountry'=>'Haiti', 'ISD'=>'509'),
		'243'=>array('shikshaCountry'=>'Vatican', 'ISD'=>'379'),
		'135'=>array('shikshaCountry'=>'Honduras', 'ISD'=>'504'),
		'57'=>array('shikshaCountry'=>'Hong Kong', 'ISD'=>'852'),
		'46'=>array('shikshaCountry'=>'Hungary', 'ISD'=>'36'),
		'136'=>array('shikshaCountry'=>'Iceland', 'ISD'=>'354'),
		'137'=>array('shikshaCountry'=>'Indonesia', 'ISD'=>'62'),
		'138'=>array('shikshaCountry'=>'Iran', 'ISD'=>'98'),
		'139'=>array('shikshaCountry'=>'Iraq', 'ISD'=>'964'),
		'21'=>array('shikshaCountry'=>'Ireland', 'ISD'=>'353'),
		'140'=>array('shikshaCountry'=>'Isle of Man', 'ISD'=>'44'),
		'141'=>array('shikshaCountry'=>'Israel', 'ISD'=>'972'),
		'22'=>array('shikshaCountry'=>'Italy', 'ISD'=>'39'),
		'143'=>array('shikshaCountry'=>'Jamaica', 'ISD'=>'1'),
		'30'=>array('shikshaCountry'=>'Japan', 'ISD'=>'81'),
		'144'=>array('shikshaCountry'=>'Jersey', 'ISD'=>'44'),
		'145'=>array('shikshaCountry'=>'Jordan', 'ISD'=>'962'),
		'146'=>array('shikshaCountry'=>'Kazakhstan', 'ISD'=>'7'),
		'147'=>array('shikshaCountry'=>'Kenya', 'ISD'=>'254'),
		'148'=>array('shikshaCountry'=>'Kiribati', 'ISD'=>'686'),
		'150'=>array('shikshaCountry'=>'Kuwait', 'ISD'=>'965'),
		'151'=>array('shikshaCountry'=>'Kyrgyzstan', 'ISD'=>'996'),
		'153'=>array('shikshaCountry'=>'Latvia', 'ISD'=>'371'),
		'154'=>array('shikshaCountry'=>'Lebanon', 'ISD'=>'961'),
		'155'=>array('shikshaCountry'=>'Lesotho', 'ISD'=>'266'),
		'156'=>array('shikshaCountry'=>'Liberia', 'ISD'=>'231'),
		'157'=>array('shikshaCountry'=>'Libya', 'ISD'=>'218'),
		'158'=>array('shikshaCountry'=>'Liechtenstein', 'ISD'=>'423'),
		'53'=>array('shikshaCountry'=>'Lithuania', 'ISD'=>'370'),
		'43'=>array('shikshaCountry'=>'Luxembourg', 'ISD'=>'352'),
		'159'=>array('shikshaCountry'=>'Macao', 'ISD'=>'853'),
		'160'=>array('shikshaCountry'=>'Macedonia', 'ISD'=>'389'),
		'161'=>array('shikshaCountry'=>'Madagascar', 'ISD'=>'261'),
		'162'=>array('shikshaCountry'=>'Malawi', 'ISD'=>'265'),
		'10'=>array('shikshaCountry'=>'Malaysia', 'ISD'=>'60'),
		'163'=>array('shikshaCountry'=>'Maldives', 'ISD'=>'960'),
		'164'=>array('shikshaCountry'=>'Mali', 'ISD'=>'223'),
		'59'=>array('shikshaCountry'=>'Malta', 'ISD'=>'356'),
		'165'=>array('shikshaCountry'=>'Marshall Islands', 'ISD'=>'692'),
		'166'=>array('shikshaCountry'=>'Mauritania', 'ISD'=>'222'),
		'41'=>array('shikshaCountry'=>'Mauritius', 'ISD'=>'230'),
		'167'=>array('shikshaCountry'=>'Mayotte', 'ISD'=>'262'),
		'168'=>array('shikshaCountry'=>'Mexico', 'ISD'=>'52'),
		'169'=>array('shikshaCountry'=>'Micronesia', 'ISD'=>'691'),
		'170'=>array('shikshaCountry'=>'Moldova', 'ISD'=>'373'),
		'54'=>array('shikshaCountry'=>'Monaco', 'ISD'=>'377'),
		'171'=>array('shikshaCountry'=>'Mongolia', 'ISD'=>'976'),
		'172'=>array('shikshaCountry'=>'Montenegro', 'ISD'=>'382'),
		'173'=>array('shikshaCountry'=>'Montserrat', 'ISD'=>'1'),
		'174'=>array('shikshaCountry'=>'Morocco', 'ISD'=>'212'),
		'175'=>array('shikshaCountry'=>'Mozambique', 'ISD'=>'258'),
		'176'=>array('shikshaCountry'=>'Myanmar', 'ISD'=>'95'),
		'177'=>array('shikshaCountry'=>'Namibia', 'ISD'=>'264'),
		'178'=>array('shikshaCountry'=>'Nauru', 'ISD'=>'674'),
		'55'=>array('shikshaCountry'=>'Nepal', 'ISD'=>'977'),
		'14'=>array('shikshaCountry'=>'Netherlands', 'ISD'=>'31'),
		'180'=>array('shikshaCountry'=>'New Caledonia', 'ISD'=>'687'),
		'7'=>array('shikshaCountry'=>'New Zealand', 'ISD'=>'64'),
		'181'=>array('shikshaCountry'=>'Nicaragua', 'ISD'=>'505'),
		'182'=>array('shikshaCountry'=>'Niger', 'ISD'=>'227'),
		'183'=>array('shikshaCountry'=>'Nigeria', 'ISD'=>'234'),
		'184'=>array('shikshaCountry'=>'Niue', 'ISD'=>'683'),
		'185'=>array('shikshaCountry'=>'North Korea', 'ISD'=>'850'),
		'186'=>array('shikshaCountry'=>'Northern Mariana Islands', 'ISD'=>'1'),
		'27'=>array('shikshaCountry'=>'Norway', 'ISD'=>'47'),
		'187'=>array('shikshaCountry'=>'Oman', 'ISD'=>'968'),
		'188'=>array('shikshaCountry'=>'Pakistan', 'ISD'=>'92'),
		'189'=>array('shikshaCountry'=>'Palau', 'ISD'=>'680'),
		'190'=>array('shikshaCountry'=>'Palestine', 'ISD'=>'970'),
		'191'=>array('shikshaCountry'=>'Panama', 'ISD'=>'507'),
		'192'=>array('shikshaCountry'=>'Papua New Guinea', 'ISD'=>'675'),
		'193'=>array('shikshaCountry'=>'Paraguay', 'ISD'=>'595'),
		'194'=>array('shikshaCountry'=>'Peru', 'ISD'=>'51'),
		'49'=>array('shikshaCountry'=>'Philippines', 'ISD'=>'63'),
		'195'=>array('shikshaCountry'=>'Pitcairn', 'ISD'=>'64'),
		'25'=>array('shikshaCountry'=>'Poland', 'ISD'=>'48'),
		'26'=>array('shikshaCountry'=>'Portugal', 'ISD'=>'351'),
		'196'=>array('shikshaCountry'=>'Puerto Rico', 'ISD'=>'1'),
		'197'=>array('shikshaCountry'=>'Qatar', 'ISD'=>'974'),
		'38'=>array('shikshaCountry'=>'South Korea', 'ISD'=>'82'),
		'108'=>array('shikshaCountry'=>'Democratic Republic of the Congo', 'ISD'=>'242'),
		'199'=>array('shikshaCountry'=>'Reunion', 'ISD'=>'262'),
		'200'=>array('shikshaCountry'=>'Romania', 'ISD'=>'40'),
		'17'=>array('shikshaCountry'=>'Russia', 'ISD'=>'7'),
		'201'=>array('shikshaCountry'=>'Rwanda', 'ISD'=>'250'),
		'202'=>array('shikshaCountry'=>'Saint Barthelemy', 'ISD'=>'590'),
		'203'=>array('shikshaCountry'=>'Saint Helena', 'ISD'=>'290'),
		'204'=>array('shikshaCountry'=>'Saint Kitts and Nevis', 'ISD'=>'1'),
		'205'=>array('shikshaCountry'=>'Saint Lucia', 'ISD'=>'1'),
		'206'=>array('shikshaCountry'=>'Saint Martin', 'ISD'=>'590'),
		'207'=>array('shikshaCountry'=>'Saint Pierre and Miquelon', 'ISD'=>'508'),
		'208'=>array('shikshaCountry'=>'Saint Vincent and the Grenadines', 'ISD'=>'1'),
		'209'=>array('shikshaCountry'=>'Samoa', 'ISD'=>'685'),
		'210'=>array('shikshaCountry'=>'San Marino', 'ISD'=>'378'),
		'211'=>array('shikshaCountry'=>'Sao Tome and Principe', 'ISD'=>'239'),
		'212'=>array('shikshaCountry'=>'Saudi Arabia', 'ISD'=>'966'),
		'213'=>array('shikshaCountry'=>'Senegal', 'ISD'=>'221'),
		'214'=>array('shikshaCountry'=>'Serbia', 'ISD'=>'381'),
		'215'=>array('shikshaCountry'=>'Seychelles', 'ISD'=>'248'),
		'216'=>array('shikshaCountry'=>'Sierra Leone', 'ISD'=>'232'),
		'6'=>array('shikshaCountry'=>'Singapore', 'ISD'=>'65'),
		'217'=>array('shikshaCountry'=>'Sint Maarten', 'ISD'=>'1'),
		'218'=>array('shikshaCountry'=>'Slovakia', 'ISD'=>'421'),
		'48'=>array('shikshaCountry'=>'Slovenia', 'ISD'=>'386'),
		'219'=>array('shikshaCountry'=>'Solomon Islands', 'ISD'=>'677'),
		'220'=>array('shikshaCountry'=>'Somalia', 'ISD'=>'252'),
		'45'=>array('shikshaCountry'=>'South Africa', 'ISD'=>'27'),
		'221'=>array('shikshaCountry'=>'South Sudan', 'ISD'=>'211'),
		'16'=>array('shikshaCountry'=>'Spain', 'ISD'=>'34'),
		'222'=>array('shikshaCountry'=>'Sri Lanka', 'ISD'=>'94'),
		'223'=>array('shikshaCountry'=>'Sudan', 'ISD'=>'249'),
		'224'=>array('shikshaCountry'=>'Suriname', 'ISD'=>'597'),
		'225'=>array('shikshaCountry'=>'Svalbard and Jan Mayen', 'ISD'=>'47'),
		'226'=>array('shikshaCountry'=>'Swaziland', 'ISD'=>'268'),
		'11'=>array('shikshaCountry'=>'Sweden', 'ISD'=>'46'),
		'13'=>array('shikshaCountry'=>'Switzerland', 'ISD'=>'41'),
		'227'=>array('shikshaCountry'=>'Syria', 'ISD'=>'963'),
		'228'=>array('shikshaCountry'=>'Taiwan', 'ISD'=>'886'),
		'229'=>array('shikshaCountry'=>'Tajikistan', 'ISD'=>'992'),
		'230'=>array('shikshaCountry'=>'Tanzania', 'ISD'=>'255'),
		'31'=>array('shikshaCountry'=>'Thailand', 'ISD'=>'66'),
		'112'=>array('shikshaCountry'=>'East Timor', 'ISD'=>'670'),
		'230'=>array('shikshaCountry'=>'Togo', 'ISD'=>'228'),
		'232'=>array('shikshaCountry'=>'Tokelau', 'ISD'=>'690'),
		'233'=>array('shikshaCountry'=>'Tonga', 'ISD'=>'676'),
		'234'=>array('shikshaCountry'=>'Trinidad and Tobago', 'ISD'=>'1'),
		'235'=>array('shikshaCountry'=>'Tunisia', 'ISD'=>'216'),
		'58'=>array('shikshaCountry'=>'Turkey', 'ISD'=>'90'),
		'236'=>array('shikshaCountry'=>'Turkmenistan', 'ISD'=>'993'),
		'237'=>array('shikshaCountry'=>'Turks and Caicos Islands', 'ISD'=>'1'),
		'238'=>array('shikshaCountry'=>'Tuvalu', 'ISD'=>'688'),
		'240'=>array('shikshaCountry'=>'Uganda', 'ISD'=>'256'),
		'44'=>array('shikshaCountry'=>'Ukraine', 'ISD'=>'380'),
		'18'=>array('shikshaCountry'=>'UAE', 'ISD'=>'971'),
		'4'=>array('shikshaCountry'=>'UK', 'ISD'=>'44'),
		'3'=>array('shikshaCountry'=>'USA', 'ISD'=>'1'),
		'241'=>array('shikshaCountry'=>'Uruguay', 'ISD'=>'598'),
		'242'=>array('shikshaCountry'=>'Uzbekistan', 'ISD'=>'998'),
		'243'=>array('shikshaCountry'=>'Vanuatu', 'ISD'=>'678'),
		'245'=>array('shikshaCountry'=>'Venezuela', 'ISD'=>'58'),
		'246'=>array('shikshaCountry'=>'Vietnam', 'ISD'=>'84'),
		'247'=>array('shikshaCountry'=>'Wallis and Futuna', 'ISD'=>'681'),
		'248'=>array('shikshaCountry'=>'Western Sahara', 'ISD'=>'212'),
		'249'=>array('shikshaCountry'=>'Yemen', 'ISD'=>'967'),
		'250'=>array('shikshaCountry'=>'Zambia', 'ISD'=>'260'),
		'251'=>array('shikshaCountry'=>'Zimbabwe', 'ISD'=>'263'),
		'2'=>array('shikshaCountry'=>'India', 'ISD'=>'91')
	);