<?php
$config['depttToStreamMap'] = array(
	'1'  => array('depttName' => 'Management',    'streamId' => 1),
	'2'  => array('depttName' => 'Engineering',   'streamId' => 2), 
	'4'  => array('depttName' => 'Design',        'streamId' => 3), 
	'10' => array('depttName' => 'Hospitality',   'streamId' => 4), 
	'3'  => array('depttName' => 'Law',           'streamId' => 5), 
	'9'  => array('depttName' => 'Animation',     'streamId' => 6), 
	'7'  => array('depttName' => 'MassComm',      'streamId' => 7), 
	'11' => array('depttName' => 'IT',            'streamId' => 8), 
	'19' => array('depttName' => 'Humanities',    'streamId' => 9), 
	'8'  => array('depttName' => 'Arts',          'streamId' => 10), 
	'5'  => array('depttName' => 'Science',       'streamId' => 11), 
	'16' => array('depttName' => 'Architecture',  'streamId' => 12), 
	'15' => array('depttName' => 'Accounting',    'streamId' => 13), 
	'14' => array('depttName' => 'BFSI',          'streamId' => 14), 
	'17' => array('depttName' => 'Aviation',      'streamId' => 15), 
	'21' => array('depttName' => 'Teaching',      'streamId' => 16), 
	'20' => array('depttName' => 'Nursing',       'streamId' => 17), 
	'12' => array('depttName' => 'Medicine',      'streamId' => 18), 
	'18' => array('depttName' => 'BeautyFitness', 'streamId' => 19), 
);
$config['streamToDepttInUrl'] = array(
	'1'  => 'mba',
	'2'  => 'engineering',
	'3'  => 'design',
	'4'  => 'hospitality',
	'5'  => 'law',
	'6'  => 'animation',
	'7'  => 'mass-communication',
	'8'  => 'it',
	'9'  => 'humanities',
	'10' => 'arts',
	'11' => 'science',
	'12' => 'architecture',
	'13' => 'accounting',
	'14' => 'bfsi',
	'15' => 'aviation',
	'16' => 'teaching',
	'17' => 'nursing',
	'18' => 'medicine',
	'19' => 'beautyfitness',
);
//6 - MCA, 13 - Media, these two dept removed after recat
