<?php

$config['tableMetaData'] = array(
    
    /**
     * Location Tables
     */ 
    'countryTable' => array(
                                'desc' => 'Master list of countries',
                                'fieldDesc' => array(
                                                'countryId' => 'Country ID',
                                                'name' => 'Country name',
                                                'tier' => 'Country\'s tier. Tier 1 are the main countries then 2, 3 etc.'
                                            )
                        ),
    
    'stateTable'   => array(
                                'desc' => 'Master list of states',
                                'fkeys' => array(
                                                    'countryId' => 'countryTable'
                                                ),
                                'fieldDesc' => array(
                                                
                                            )
                        ),
    
    'countryCityTable'   => array(
                                    'desc' => 'Master list of cities',
                                    'fkeys' => array(
                                                        'countryId' => 'countryTable',
                                                        'state_id' => 'stateTable'
                                                    ),
                                    'fieldDesc' => array(
                                                    
                                                )
                                ),
    
    'virtualCityMapping'   => array(
                                    'desc' => 'Mapping of virtual city to cities',
                                    'fkeys' => array(
                                                        'city_id' => 'countryCityTable'
                                                    ),
                                    'fieldDesc' => array(
                                                    
                                                )
                                ),
    
    'localityCityMapping'   => array(
                                        'desc' => 'Master list of localities',
                                        'fkeys' => array(
                                                            'cityId' => 'countryCityTable',
                                                            'zoneId' => 'tZoneMapping'
                                                        )
                                    ),

    'tZoneMapping'   => array(
                                'desc' => 'Master list of zones'
                            ),

    'tregion'   => array(
                            'desc' => 'Master list of regions'
                        ),

    'tregionmapping'   => array(
                                    'desc' => 'Mapping between countires and regions',
                                    'fkeys' => array(
                                                        'regionid' => 'tregion',
                                                        'id' => 'countryTable'
                                                    )
                            ),
    
    'tuser' => array(
                        'desc' => 'Master table for user data',
                        'fkeys' => array(
                                            'city' => 'countryCityTable',
                                            'country' => 'countryTable'
                                        ),
                        'fieldDesc' => array(
                                                'userid' => 'ID of the user',
                                                'displayname' => 'Unique name for the user. Generated by appending a random number to first name',
                                                'city' => 'User\'s residence city',
                                                'randomkey' => 'Used for email verification',
                                                'usergroup' => 'Group/access level of the user.<br />user: Normal registered user<br />enterprise: Clients<br />cms: Admin access',
                                                'textpassword' => 'Password in plain text format',
                                                'country' => 'User\'s residence country',
                                            )
                        ),
    
    'tUserPref'   => array(
                            'desc' => 'User study preferences',
                            'fkeys' => array(
                                                'UserId' => 'tuser',
                                                'DesiredCourse' => 'tCourseSpecializationMapping'
                                            ),
                            'fieldDesc' => array(
                                                'TimeOfStart' => 'When is user planning to start the course',
                                                'UserDetail' => 'More info user wants to convey to institutes',
                                                'DesiredCourse' => 'ID of the course user wants to study',
                                                'ExtraFlag' => 'Whether the course is testprep or study abroad',
                                                'is_processed' => 'Whether the lead has been consumed by genie system',
                                            ),
                        ),
    
    'tUserLocationPref'   => array(
                            'desc' => 'User study location preferences',
                            'fkeys' => array(
                                                'UserId' => 'tuser',
                                                'PrefId' => 'tUserPref'
                                            ),
                            'fieldDesc' => array(
                                                'TimeOfStart' => 'When is user planning to start the course',
                                                'UserDetail' => 'More info user wants to convey to institutes',
                                                'DesiredCourse' => 'ID of the course user wants to study',
                                                'ExtraFlag' => 'Whether the course is testprep or study abroad',
                                                'is_processed' => 'Whether the lead has been consumed by genie system',
                                            ),
                        ),
    
    'tUserEducation'   => array(
                            'desc' => 'User\'s educational background info',
                            'fkeys' => array(
                                                'UserId' => 'tuser',
                                                'PrefId' => 'tUserPref'
                                            ),
                            'fieldDesc' => array(
                                                'Name' => 'Name of the degree/course/exam user undertook',
                                                'OngoingCompletedFlag' => 'Whether the degree/course is completed or ongoing'
                                            ),
                        ),
    
    'tUserSpecializationPref'   => array(
                            'desc' => 'User course specialization preferences',
                            'fkeys' => array(
                                                'UserId' => 'tuser',
                                                'PrefId' => 'tUserPref',
                                                'SpecializationId' => 'tCourseSpecializationMapping'
                                            ),
                            'fieldDesc' => array(
                                                'SpecializationId' => 'Specialization of the course that user wants to study e.g. user want to persue Full Time MBA, the specialization can be Marketing, HR, Finance etc.'
                                            ),
                        ),
    
    'tUserPref_testprep_mapping'   => array(
                            'desc' => 'User course preferences for test prep',
                            'fkeys' => array(
                                                'blogid' => 'blogTable',
                                                'prefid' => 'tUserPref'
                                            ),
                            'fieldDesc' => array(
                                                'blogid' => 'ID of the exam/test for which user wants to prepare for e.g. CAT, MAT, UPSE, AIPMT etc. '
                                            ),
                        ),
    
    'tuserflag'   => array(
                            'desc' => 'User flags',
                            'fkeys' => array(
                                                'userId' => 'tuser',
                                                'DesiredCourse' => 'tCourseSpecializationMapping'
                                            ),
                            'fieldDesc' => array(
                                                'hardbounce' => 'Is email address of user hard bouncing',
                                                'unsubscribe' => 'Unsubscribe from all mailers',
                                                'ownershipchallenged' => 'Has user used someone else\'s email address',
                                                'softbounce' => 'Is email address of user soft bouncing',
                                                'abused' => 'Is there is report abuse against user',
                                                'mobileverified' => 'Is mobile number verified',
                                                'emailverified' => 'Is email address verified',
                                                'isNDNC' => 'Is user\'s mobile number registered in National Do Not Call registry. If yes, we do not send promotional SMSs to this user',
                                                'isLDBUser' => 'Is user a lead',
                                                'isTestUser' => 'Is user a test user i.e. registered with mobile no. like 9999999999',
                                            )
                        ),
    'tusersourceInfo'   => array(
                            'desc' => 'Info about user\'s registration source',
                            'fkeys' => array(
                                                'userid' => 'tuser',
                                                'DesiredCourse' => 'tCourseSpecializationMapping'
                                            ),
                            'fieldDesc' => array(
                                                'coordinates' => 'Screen coordinates of registration widget',
                                                'referer' => 'URL of page from where registration happened',
                                                'resolution' => 'Resolution of screen from where registration happened',
                                                'landingpage' => 'URL of the page user redirected to port registration',
                                                'browser' => 'Info of browser from where registration happened',
                                                'keyid' => 'ID of the key to identify registration point',
                                                'keyquery' => 'SQL query to retrieve keyid',
                                                'time' => 'Time of registration'
                                            )
                        ),
    'tuserLoginTracking'   => array(
                            'desc' => 'User\'s login/logout tracking',
                            'fkeys' => array(
                                                'userId' => 'tuser',
                                                'DesiredCourse' => 'tCourseSpecializationMapping'
                                            ),
                            'fieldDesc' => array(
                                                'activityTime' => 'Time of activity',
                                                'activity' => 'Login/Logout',
                                                'ipAddress' => 'IP adress from where activity happened'
                                            )
                        ),
    
    'LDBSearchTracking'   => array(
                            'desc' => 'Stores the criteria used for student searches',
                            'fkeys' => array(
                                                'ClientId' => 'tuser'
                                            ),
                            'fieldDesc' => array(
                                                'Specialization' => 'List of specialization ids (from tCourseSpecializationMapping) joined by #!#'
                                            )
                        ),
    
    'LDBLeadContactedTracking'   => array(
                            'desc' => 'Stores the actions (view details/sms/email) taken by clients on users appearing in student search results along with number of credits deducted for that action and subscription from which credits were deducted.',
                            'fkeys' => array(
                                                'ClientId' => 'tuser',
                                                'UserId' => 'tuser'
                                            ),
                            'fieldDesc' => array(
                                                'UserId' => 'ID of the lead',
                                                'activity_flag' => 'Flag to check whether the activity was done manually from student search (LDB) or automatically via lead genie (SA)'
                                            )
                        ),
    
    'LDBLeadViewCount'   => array(
                            'desc' => 'Stores the number of times a lead is viewed by various clients',
                            'fkeys' => array(
                                                'UserId' => 'tuser'
                                            ),
                            'fieldDesc' => array(
                                                'UserId' => 'ID of the lead',
                                                'ViewCount' => 'No. of times the lead\'s details are viewed',
                                                'EmailCount' => 'No. of times the lead is emailed',
                                                'SmsCount' => 'No. of times the lead is sms\'ed',
                                                'UpdateTime' => 'Time of the last activity'
                                            )
                        ),
    
    'tGroupCreditDeductionPolicy'   => array(
                            'desc' => 'Policy of credit deducation for credit groups',
                            'fkeys' => array(
                                                
                                            ),
                            'fieldDesc' => array(
                                                
                                            )
                        ),
    
    'tCourseGrouping'   => array(
                            'desc' => 'Mapping of desired courses with credit groups',
                            'fkeys' => array(
                                                'groupId' => 'tGroupCreditDeductionPolicy',
                                                'courseId' => 'tCourseSpecializationMapping',
                                            ),
                            'fieldDesc' => array(
                                                
                                            )
                        ),
    
    'cmp_formcustomization' => array(
                                'desc' => '',
                                'fkeys' => array(
                                                    
                                                ),
                                'fieldDesc' => array(
                                                    
                                                )
                            ),
    
    'marketing_pageid_courses_mapping' => array(
                                'desc' => '',
                                'fkeys' => array(
                                                    
                                                ),
                                'fieldDesc' => array(
                                                    
                                                )
                            ),
    
    'marketing_page_master' => array(
                                'desc' => '',
                                'fkeys' => array(
                                                    
                                                ),
                                'fieldDesc' => array(
                                                    
                                                )
                            ),
    
    'mmp_pageid_formid_mapping' => array(
                                'desc' => '',
                                'fkeys' => array(
                                                    
                                                ),
                                'fieldDesc' => array(
                                                    
                                                )
                            ),
    
    'mmp_forms' => array(
                                'desc' => '',
                                'fkeys' => array(
                                                    
                                                ),
                                'fieldDesc' => array(
                                                    
                                                )
                            ),
);