<?php
/**
 * File for Value source for gender field
 */
namespace registration\libraries\FieldValueSources;

/**
 * Value source for gender field
 */ 
class CurrentSchool extends AbstractValueSource
{
    /**
	 * Get values
	 *
	 * @param array $params Additional parameters
	 * @return array
	 */ 
    public function getValues($params = array())
    {
		$vals = array(
				"Abhyasa Residential Public School",
				"Academic Heights Public School (AHPS)",
				"Academy for Professional Excellence",
				"Adamas International School",
				"Aditya Birla World Academy",
				"AECS Magnolia Maaruti International School",
				"Aga Khan Academy",
				"Ahmedabad International School",
				"Ajmera Global School",
				"Akal Academy",
				"Akash International School",
				"Akshar Arbol International School",
				"Akshayah Global School",
				"Alliance World School",
				"Alpha-Cambridge International School",
				"Ambitus World School",
				"American Embassy School",
				"American International School",
				"American School of Bombay",
				"Ameya World School",
				"Amity Global School",
				"Amulakh Amichand International School",
				"Anand Niketan International",
				"Anisha Global School",
				"Apeejay School",
				"APL Global School",
				"Apollo International School",
				"Apple Perks International School, Metturdam",
				"Arsha Vidya Mandir Senior Secondary School",
				"Asia Pacific World School",
				"Aspire International School, Nagpur",
				"Avalon Heights International School",
				"Avasara Leadership Institute",
				"B D Somani International School",
				"Bangalore International School",
				"Belvedere Spring School",
				"Bilasrai Kashinath Gadia (A Level) Junior College",
				"Billabong High International College Boarding House",
				"Billabong High International School",
				"Bodhi International School",
				"Bombay Cambridge School",
				"Bombay International School",
				"Bridge International School",
				"Bright Start Fellowship International School",
				"British Council, Kolkata",
				"Budding Minds International School",
				"Bunts Sangha\'s S M Shetty International School & Junior College",
				"Calcutta International School",
				"Calcutta New School Society, The Cambridge School",
				"Calorx Olive International School",
				"Cambridge International School",
				"Campion International School",
				"Campion School",
				"Canadian International School",
				"Candor International School",
				"Carmel Convent School",
				"Cathedral and John Connon School",
				"CET International School",
				"CfBT Education Resource Management Pvt Ltd",
				"Chinmaya International Residential School",
				"Chirec International School",
				"Chitkara International School",
				"Choice Academy for Teacher Development",
				"Choithram International",
				"Christ Church School",
				"Christ Junior College - Residential",
				"Christ Nagar International School",
				"City Montessori School, Lucknow",
				"CP Goenka International School, Juhu",
				"CPS Global School",
				"Crescent School",
				"CS Academy",
				"D Y Patil International College",
				"D Y Patil International School",
				"D Y Patil Pranjali International School",
				"D.R.S. International School",
				"Daffodil International School",
				"Dayawati Modi Academy",
				"Deccan International School",
				"Delhi Public School",
				"Dexter Kids",
				"Dhirubhai Ambani International School",
				"Divine Child International School, Adalaj",
				"Don Bosco International School",
				"DPS  International School",
				"Dr. Pillai Global Academy",
				"Dr. S Radhakrishnan Vidyalaya, Malad West",
				"Dr. Sarvepalli Radhakrishnan Vidyalaya, Borivli (West)",
				"DRS International School",
				"DSB International School",
				"Dwarkibai Gangadhar Khetan International School",
				"Eastern Public School",
				"Ebenezer International School",
				"Ecole Globale International Girls School",
				"École Mondiale World School",
				"Edubridge International School",
				"Euro International School",
				"European School of Goa",
				"Excel Global School",
				"Excelsior American School",
				"Fazlani L\'Académie Globale",
				"Firststeps School",
				"Foundation World School",
				"Fountainhead School",
				"Fravashi International Academy",
				"G D Goenka World School",
				"G.L Kakadia International School",
				"Gandhinagar International Public School",
				"Garden High International School",
				"Garodia International Centre for Learning",
				"Gateway - The Complete School",
				"GD Goenka World School",
				"Geethaanjali The Global School",
				"GEM International School",
				"GEMS Akademia Global School",
				"GEMS Cambridge International School",
				"GEMS Education Services India Private Ltd",
				"Genesis Global School",
				"Gitanjali International School Bangalore",
				"Gitanjali School",
				"Glendale Academy",
				"Global City International School",
				"Global English School",
				"Global Indian International School",
				"Goldcrest International School",
				"Good Shepherd International School",
				"GPS International",
				"Greenwood High School",
				"Gundecha Education Academy",
				"Guru Harkrishan Public School",
				"Gurukul",
				"Harmony International School",
				"Harvest International School",
				"Head Start Educational Academy",
				"Hebron School",
				"Heritage Girls School",
				"HFS International",
				"Himalayan International Residential School",
				"Himali Boarding School",
				"Hindustan International School",
				"Hiranandani Foundation School International",
				"HLC International",
				"Holy Sai International School",
				"HUS School",
				"HVB Global Academy",
				"HVPS International School",
				"I Can The Learning Centre School",
				"India International School",
				"Indirapuram Public School",
				"Indus International School",
				"Indus Valley Public School",
				"Innisfree House School",
				"International Centre for Excellence",
				"International Fateh Academy",
				"International School",
				"International School Aamby",
				"International School of Hyderabad",
				"Inventure Academy",
				"IRA Global School",
				"ITM Global School Gwalior",
				"Jain Heritage - A Cambridge School",
				"Jain Heritage School",
				"Jain International Residential School",
				"Jamnabai Narsee International School",
				"Jamnabai Narsee School",
				"Jankidevi Public School",
				"Jay Cambridge International School",
				"Jayshree Periwal International School",
				"JBCN International School",
				"Jeevana School",
				"JG International School",
				"Johnson Grammar School",
				"JSS International School",
				"Jyotirmay International School",
				"K.K. Cambridge International School",
				"Kasiga School",
				"Kaumaram Sushila International Residential School",
				"KC High",
				"Kennedy High The Global School",
				"KES International School",
				"Keshar Academy of Learning",
				"KiiT International School",
				"Kimberley The Boarding School",
				"Kodaikanal International School",
				"Kothari International School",
				"Kunwar\'s Global School",
				"Lalaji Memorial Omega International School",
				"Lancers International School",
				"Laxmi Global School",
				"Learning Panorama School",
				"L\'ecole Chempaka",
				"Legacy School",
				"Litera Valley School Patna",
				"Lotus Valley International School",
				"Lucky International School",
				"Luxor World School",
				"M.C.T.M. Chidambaram Chettyar International School",
				"M.M. International School",
				"Mahatma Gandhi International School",
				"Mahindra United World College of India",
				"Mainadevi Bajaj International School",
				"Mallya Aditi International School",
				"Manchester International School",
				"Maneckji Cooper Education Trust School",
				"Manthan School",
				"Mar Athanasius International School, Kothamangalam",
				"Mayo College",
				"Mayoor School, Ajmer",
				"MDK International School",
				"Meenakshi World School",
				"Mercedes-Benz International School",
				"Meridian School for Boys and Girls",
				"MET Rishikul Vidyalaya",
				"Methodist High School",
				"Miri Piri Academy",
				"MITCON International School",
				"Modern Vidya Niketan",
				"Mody School",
				"Mussoorie International School",
				"N.H. Goel World School",
				"Nahar International School",
				"Nandi Academy",
				"National Public School",
				"Navrachana International School",
				"Neerja Modi school",
				"Nelson\'s International School",
				"NES International School Mumbai",
				"New Baldwin International Residential School",
				"New Era High School",
				"NSS Hill Spring International School",
				"Oakridge International School",
				"Oasis International School",
				"Oasis Public High School",
				"Oberoi International School",
				"Omkar Cambridge International School",
				"Oyster International School And Junior College",
				"P P Savani Cambridge International School",
				"Panbai International School",
				"Pathways School",
				"Phoenix Public School",
				"Pinnacle High International School",
				"Podar International School",
				"Prakriya Green Wisdom School",
				"Primrose Schools",
				"Primus Public School",
				"Prudence International School, Panvel",
				"Pushpalata British International School",
				"R.B.K International School",
				"Raffles International School",
				"RAM RATNA INTERNATIONAL SCHOOL",
				"Rasbihari International School",
				"Raunaq Public School",
				"RBK International Academy",
				"Redbridge International Academy",
				"Reqelford International School",
				"Richmondd Global School",
				"RIMS International School & Junior College",
				"RiverDale International Residential School",
				"Rockwell International School",
				"Rockwoods High School",
				"Rustomjee Cambridge International School",
				"Ryan Global School",
				"Ryan International School",
				"SAAMAR International Islamic School",
				"Sadhbhavana World School",
				"Saffron Public School",
				"Saint Msg Glorious International School",
				"Sancta Maria International School",
				"Sangam School of Excellence",
				"Sanjay Ghodawat International School",
				"Sanjeewan Vidyalaya",
				"Sanskar School",
				"Sanskriti School",
				"SANT NISCHAL SINGH PUBLIC SCHOOL",
				"Sarala Birla Academy",
				"Savitridevi Hariram Agarwal International School",
				"SCAD World School",
				"Scottish High International",
				"Seedling International Academy",
				"Seedling Modern Public School",
				"Shalom Hills International School",
				"Shalom Presidency School",
				"Sherwood College",
				"Shivalik Public School",
				"Sholai School, Centre For Learning, Organic Agriculture And Appropriate Technology",
				"Shrine Vailankanni International School",
				"Singapore International School",
				"SMT PS Shivashankarappa English Residential School",
				"Smt. Sulochanadevi Singhania School",
				"South City International School",
				"Sparkrill International School",
				"Springdales School",
				"Sreenidhi International School",
				"Sri Chandra Gupta Maurya International School",
				"Sri Mayapur International School",
				"Sri Vani International School",
				"Srikriti - The Teacher Education Centre",
				"St Peters Matriculation Higher Secondary School",
				"St. Anne International School",
				"St. Columba\'s School",
				"St. Joan of Arc International School",
				"St. Joseph\'s Convent International School",
				"St. Stanislaus International School",
				"Step by Step School",
				"Stonehill International School",
				"Suguna International School",
				"Sun City World School",
				"SVKM International School",
				"Swayam Cambridge International School",
				"Symbiosis International School",
				"Tagore International School",
				"Taktse International School",
				"Thakur International School",
				"The Ardee World School",
				"The Blue Mountains School",
				"The British School",
				"The Cambridge school",
				"The Cathedral and John Connon School",
				"The Cathedral Vidya School, Lonavala",
				"The Daly College",
				"The Doon School",
				"The Emerald Heights International School",
				"The Galaxy School",
				"THE GATEWAY SCHOOL OF MUMBAI",
				"The Gaudium School",
				"The Geekay World School",
				"The Heritage School",
				"The Indian Public School",
				"The International School Bangalore",
				"The King\'s School",
				"The Lawrence School",
				"The Levelfield School",
				"The Lords\' International School",
				"The New Tulip International School",
				"The Rajas International School",
				"The Riverside School",
				"The Sanskaar Valley School",
				"The Schram Academy",
				"The Scottish High International School",
				"The Shri Ram School",
				"The Universal School",
				"The Valley School",
				"The Vikasa International School",
				"Treamis International School",
				"Tree House High School",
				"Tridha School",
				"Trileaves International School",
				"Trinity International School",
				"Trio World Academy",
				"Tripada International School",
				"Trivandrum International School",
				"Unison World School",
				"Utpal Shanghvi Global School",
				"UWC Mahindra College",
				"Vaels International School",
				"Vasant Valley School",
				"Veer Bhagat Singh Vidyalaya",
				"Velammal Global School",
				"Vibgyor High",
				"Victoria International School",
				"Victorious Kidss Educares",
				"Vidya Global School",
				"Vidya Sanskar International School",
				"Vidyanjali International School",
				"Vikaasa World School",
				"Vip\'s International School",
				"Vishwashanti Gurukul",
				"Vision Vidyashram World School",
				"Vivekalaya\'s Prakriya International School",
				"Vruksha Montessori School",
				"Welham Boys\' School",
				"Welham Girls\' School",
				"Wisdom High International School",
				"Witty International School",
				"Woodland Overseas School",
				"Woodstock School",
				"Yagappa International School"  
			);
        return $vals;
    }
}