<?php
        define('HOME_PAGE_RIGHT_BANNER_ZONE',651); 
	define('HOME_PAGE_RIGHT_BANNER_WIDTH',159);
	define('HOME_PAGE_RIGHT_BANNER_HEIGHT',1764);
	define('HOME_PAGE_TOP_BANNER_WIDTH',728);
	define('HOME_PAGE_TOP_BANNER_HEIGHT',90);
	define('HOME_PAGE_TOP_BANNER_ZONE',511);
	define('ONLINE_TEST_PAGE_TOP_BANNER_WIDTH',728);
	define('ONLINE_TEST_PAGE_TOP_BANNER_HEIGHT',90);
	define('ONLINE_TEST_PAGE_TOP_BANNER_ZONE',580);

	define('HOME_PAGE_SIDEBANNER_BANNER_WIDTH',300);
	define('HOME_PAGE_SIDEBANNER_BANNER_HEIGHT',250);
	define('HOME_PAGE_SIDEBANNER_BANNER_ZONE',352);

    define('HOME_PAGE_FOOTER_BANNER_WIDTH',728);
    define('HOME_PAGE_FOOTER_BANNER_HEIGHT',90);
    define('HOME_PAGE_FOOTER_BANNER_ZONE',531);

    define('HOME_PAGE_LEFTSIDE_BANNER_WIDTH',356);
    define('HOME_PAGE_LEFTSIDE_BANNER_HEIGHT',286);
    define('HOME_PAGE_LEFTSIDE_BANNER_ZONE',552);
    /* Split 1 banner into 3 slots */
    define('HOME_PAGE_LEFTSIDE1_BANNER_WIDTH',356);
    define('HOME_PAGE_LEFTSIDE1_BANNER_HEIGHT',125);
    define('HOME_PAGE_LEFTSIDE1_BANNER_ZONE',581);

    define('HOME_PAGE_LEFTSIDE2_BANNER_WIDTH',336);
    define('HOME_PAGE_LEFTSIDE2_BANNER_HEIGHT',40);
    define('HOME_PAGE_LEFTSIDE2_BANNER_ZONE',582);

    define('HOME_PAGE_LEFTSIDE3_BANNER_WIDTH',336);
    define('HOME_PAGE_LEFTSIDE3_BANNER_HEIGHT',40);
    define('HOME_PAGE_LEFTSIDE3_BANNER_ZONE',583);


	define('CATEGORY_PAGE_HEADER_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_HEADER_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_HEADER_BANNER_ZONE',802);
	
	define('CATEGORY_PAGE_FOREIGN_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_FOREIGN_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_FOREIGN_PAGE_TOP_BANNER_ZONE',491);
	
    define('CATEGORY_PAGE_FOREIGN_DETAIL_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_FOREIGN_DETAIL_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_FOREIGN_DETAIL_PAGE_TOP_BANNER_ZONE',557);
	
    define('CATEGORY_PAGE_FOREIGN_PAGE_RIGHT_BANNER_WIDTH',200);
	define('CATEGORY_PAGE_FOREIGN_PAGE_RIGHT_BANNER_HEIGHT',1000);
	define('CATEGORY_PAGE_FOREIGN_PAGE_RIGHT_BANNER_ZONE',561);
	    
    define('CATEGORY_PAGE_FOREIGN_PAGE_RIGHT1_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_FOREIGN_PAGE_RIGHT1_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_FOREIGN_PAGE_RIGHT1_BANNER_ZONE',558);
    
    define('CATEGORY_PAGE_FOREIGN_PAGE_RIGHT2_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_FOREIGN_PAGE_RIGHT2_BANNER_HEIGHT',550);
	define('CATEGORY_PAGE_FOREIGN_PAGE_RIGHT2_BANNER_ZONE',559);
    
    define('CATEGORY_PAGE_FOREIGN_PAGE_SKYSCRAPPER_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_FOREIGN_PAGE_SKYSCRAPPER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_FOREIGN_PAGE_SKYSCRAPPER_BANNER_ZONE',560);
    
    define('CATEGORY_PAGE_ANIMATION_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_ANIMATION_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_ANIMATION_PAGE_TOP_BANNER_ZONE',478);
	
	define('CATEGORY_PAGE_LANGUAGES_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_LANGUAGES_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_LANGUAGES_PAGE_TOP_BANNER_ZONE',478);
	
	define('CATEGORY_PAGE_IT_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_IT_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_IT_PAGE_TOP_BANNER_ZONE',478);
	
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_TOP_BANNER_ZONE',478);
	
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_TOP_BANNER_ZONE',478);
	
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_TOP_BANNER_ZONE',478);
	
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_TOP_BANNER_ZONE',478);
	
	define('CATEGORY_PAGE_RETAIL_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_RETAIL_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_RETAIL_PAGE_TOP_BANNER_ZONE',478);
	
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_TOP_BANNER_ZONE',478);
	
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_TOP_BANNER_ZONE',478);

        define('TESTPREP_CATEGORY_PAGE_GOVT_EXAMS_PAGE_TOP_BANNER_WIDTH',728);
	define('TESTPREP_CATEGORY_PAGE_GOVT_EXAMS_PAGE_TOP_BANNER_HEIGHT',90);
	define('TESTPREP_CATEGORY_PAGE_GOVT_EXAMS_PAGE_TOP_BANNER_ZONE',478);
	
        define('TESTPREP_CATEGORY_PAGE_MBA_EXAMS_PAGE_TOP_BANNER_WIDTH',728);
	define('TESTPREP_CATEGORY_PAGE_MBA_EXAMS_PAGE_TOP_BANNER_HEIGHT',90);
	define('TESTPREP_CATEGORY_PAGE_MBA_EXAMS_PAGE_TOP_BANNER_ZONE',478);

        define('TESTPREP_CATEGORY_PAGE_MEDICAL_EXAMS_PAGE_TOP_BANNER_WIDTH',728);
	define('TESTPREP_CATEGORY_PAGE_MEDICAL_EXAMS_PAGE_TOP_BANNER_HEIGHT',90);
	define('TESTPREP_CATEGORY_PAGE_MEDICAL_EXAMS_PAGE_TOP_BANNER_ZONE',478);

        define('TESTPREP_CATEGORY_PAGE_FOREIGN_EXAMS_PAGE_TOP_BANNER_WIDTH',728);
	define('TESTPREP_CATEGORY_PAGE_FOREIGN_EXAMS_PAGE_TOP_BANNER_HEIGHT',90);
	define('TESTPREP_CATEGORY_PAGE_FOREIGN_EXAMS_PAGE_TOP_BANNER_ZONE',478);

        define('TESTPREP_CATEGORY_PAGE_ENGINEERING_EXAMS_PAGE_TOP_BANNER_WIDTH',728);
	define('TESTPREP_CATEGORY_PAGE_ENGINEERING_EXAMS_PAGE_TOP_BANNER_HEIGHT',90);
	define('TESTPREP_CATEGORY_PAGE_ENGINEERING_EXAMS_PAGE_TOP_BANNER_ZONE',478);

	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_TOP_BANNER_ZONE',478);
	
	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_TOP_BANNER_ZONE',488);

	define('CATEGORY_PAGE_MIDDLE_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_MIDDLE_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_MIDDLE_BANNER_ZONE',354);
	
	define('CATEGORY_PAGE_FOREIGN_PAGE_MIDDLE_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_FOREIGN_PAGE_MIDDLE_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_FOREIGN_PAGE_MIDDLE_BANNER_ZONE',492);
	
	define('CATEGORY_PAGE_ANIMATION_PAGE_MIDDLE_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_ANIMATION_PAGE_MIDDLE_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_ANIMATION_PAGE_MIDDLE_BANNER_ZONE',479);
	
	define('CATEGORY_PAGE_LANGUAGES_PAGE_MIDDLE_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_LANGUAGES_PAGE_MIDDLE_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_LANGUAGES_PAGE_MIDDLE_BANNER_ZONE',479);
	
	define('CATEGORY_PAGE_IT_PAGE_MIDDLE_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_IT_PAGE_MIDDLE_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_IT_PAGE_MIDDLE_BANNER_ZONE',479);
	
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_MIDDLE_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_MIDDLE_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_MIDDLE_BANNER_ZONE',479);
	
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_MIDDLE_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_MIDDLE_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_MIDDLE_BANNER_ZONE',479);
	
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_MIDDLE_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_MIDDLE_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_MIDDLE_BANNER_ZONE',479);
	
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_MIDDLE_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_MIDDLE_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_MIDDLE_BANNER_ZONE',479);
	
	define('CATEGORY_PAGE_RETAIL_PAGE_MIDDLE_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_RETAIL_PAGE_MIDDLE_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_RETAIL_PAGE_MIDDLE_BANNER_ZONE',479);
	
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_MIDDLE_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_MIDDLE_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_MIDDLE_BANNER_ZONE',479);
	
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_MIDDLE_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_MIDDLE_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_MIDDLE_BANNER_ZONE',479);
	
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_MIDDLE_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_MIDDLE_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_MIDDLE_BANNER_ZONE',479);
	
	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_MIDDLE_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_MIDDLE_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_MIDDLE_BANNER_ZONE',489);

	define('CATEGORY_PAGE_EXAM_DETAIL_PAGE_SIDE1_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_EXAM_DETAIL_PAGE_SIDE1_BANNER_HEIGHT',85);
	define('CATEGORY_PAGE_EXAM_DETAIL_PAGE_SIDE1_BANNER_ZONE',484);

	define('CATEGORY_PAGE_EXAM_DETAIL_PAGE_SIDE2_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_EXAM_DETAIL_PAGE_SIDE2_BANNER_HEIGHT',85);
	define('CATEGORY_PAGE_EXAM_DETAIL_PAGE_SIDE2_BANNER_ZONE',485);

	define('CATEGORY_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',40);
	define('CATEGORY_PAGE_SMALLSCRAPPER_BANNER_ZONE',355);
	
	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_FOREIGN_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_ANIMATION_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_LANGUAGES_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_IT_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_RETAIL_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120
	);	
	
	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
	define('CATEGORY_PAGE_FOREIGN_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
	define('CATEGORY_PAGE_ANIMATION_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
	define('CATEGORY_PAGE_LANGUAGES_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
	define('CATEGORY_PAGE_IT_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
	define('CATEGORY_PAGE_RETAIL_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);

        define('TESTPREP_CATEGORY_PAGE_GOVT_EXAMS_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
        define('TESTPREP_CATEGORY_PAGE_MBA_EXAMS_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
        define('TESTPREP_CATEGORY_PAGE_MEDICAL_EXAMS_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
        define('TESTPREP_CATEGORY_PAGE_ENGINEERING_EXAMS_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);
        define('TESTPREP_CATEGORY_PAGE_FOREIGN_EXAMS_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',3175);

        define('TESTPREP_CATEGORY_PAGE_GOVT_EXAMS_PAGE_SMALLSCRAPPER_BANNER_WIDTH',207);
        define('TESTPREP_CATEGORY_PAGE_MBA_EXAMS_PAGE_SMALLSCRAPPER_BANNER_WIDTH',207);
        define('TESTPREP_CATEGORY_PAGE_MEDICAL_EXAMS_PAGE_SMALLSCRAPPER_BANNER_WIDTH',207);
        define('TESTPREP_CATEGORY_PAGE_ENGINEERING_EXAMS_PAGE_SMALLSCRAPPER_BANNER_WIDTH',207);
        define('TESTPREP_CATEGORY_PAGE_FOREIGN_EXAMS_PAGE_SMALLSCRAPPER_BANNER_WIDTH',207);
	
	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_SMALLSCRAPPER_BANNER_ZONE',487);
	define('CATEGORY_PAGE_FOREIGN_PAGE_SMALLSCRAPPER_BANNER_ZONE',490);
	define('CATEGORY_PAGE_ANIMATION_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);
	define('CATEGORY_PAGE_LANGUAGES_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);
	define('CATEGORY_PAGE_IT_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);
	define('CATEGORY_PAGE_RETAIL_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);

        define('TESTPREP_CATEGORY_PAGE_GOVT_EXAMS_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);
        define('TESTPREP_CATEGORY_PAGE_MBA_EXAMS_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);
        define('TESTPREP_CATEGORY_PAGE_ENGINEERING_EXAMS_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);
        define('TESTPREP_CATEGORY_PAGE_FOREIGN_EXAMS_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);
        define('TESTPREP_CATEGORY_PAGE_MEDICAL_EXAMS_PAGE_SMALLSCRAPPER_BANNER_ZONE',482);

	define('CATEGORY_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_BIGSCRAPPER_BANNER_ZONE',356);
	

	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_FOREIGN_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_ANIMATION_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_LANGUAGES_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_IT_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_RETAIL_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);

	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_FOREIGN_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_ANIMATION_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_LANGUAGES_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_IT_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_RETAIL_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);

	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_BIGSCRAPPER_BANNER_ZONE',481);
	define('CATEGORY_PAGE_FOREIGN_PAGE_BIGSCRAPPER_BANNER_ZONE',481);
	define('CATEGORY_PAGE_ANIMATION_PAGE_BIGSCRAPPER_BANNER_ZONE',481);
	define('CATEGORY_PAGE_LANGUAGES_PAGE_BIGSCRAPPER_BANNER_ZONE', 481);
	define('CATEGORY_PAGE_IT_PAGE_BIGSCRAPPER_BANNER_ZONE',481);
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_BIGSCRAPPER_BANNER_ZONE',481);
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_BIGSCRAPPER_BANNER_ZONE',481);
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_BIGSCRAPPER_BANNER_ZONE',481);
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_BIGSCRAPPER_BANNER_ZONE',481);
	define('CATEGORY_PAGE_RETAIL_PAGE_BIGSCRAPPER_BANNER_ZONE',481);
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_BIGSCRAPPER_BANNER_ZONE',481);
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_BIGSCRAPPER_BANNER_ZONE',481);
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_BIGSCRAPPER_BANNER_ZONE',481);

	define('CATEGORY_PAGE_FOOTER_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_FOOTER_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_FOOTER_BANNER_ZONE',357);
	

	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_BOTTOM_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_FOREIGN_PAGE_BOTTOM_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_ANIMATION_PAGE_BOTTOM_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_LANGUAGES_PAGE_BOTTOM_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_IT_PAGE_BOTTOM_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_BOTTOM_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_BOTTOM_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_BOTTOM_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_BOTTOM_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_RETAIL_PAGE_BOTTOM_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_BOTTOM_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_BOTTOM_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_BOTTOM_BANNER_WIDTH',728);


	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_BOTTOM_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_FOREIGN_PAGE_BOTTOM_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_ANIMATION_PAGE_BOTTOM_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_LANGUAGES_PAGE_BOTTOM_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_IT_PAGE_BOTTOM_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_BOTTOM_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_BOTTOM_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_BOTTOM_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_BOTTOM_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_RETAIL_PAGE_BOTTOM_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_BOTTOM_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_BOTTOM_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_BOTTOM_BANNER_HEIGHT',90);	
		
	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_BOTTOM_BANNER_ZONE',447);
	define('CATEGORY_PAGE_FOREIGN_PAGE_BOTTOM_BANNER_ZONE',447);
	define('CATEGORY_PAGE_ANIMATION_PAGE_BOTTOM_BANNER_ZONE',392);
	define('CATEGORY_PAGE_LANGUAGES_PAGE_BOTTOM_BANNER_ZONE',397);
	define('CATEGORY_PAGE_IT_PAGE_BOTTOM_BANNER_ZONE',402);
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_BOTTOM_BANNER_ZONE',407);
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_BOTTOM_BANNER_ZONE',412);
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_BOTTOM_BANNER_ZONE',417);
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_BOTTOM_BANNER_ZONE',422);
	define('CATEGORY_PAGE_RETAIL_PAGE_BOTTOM_BANNER_ZONE',427);
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_BOTTOM_BANNER_ZONE',437);
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_BOTTOM_BANNER_ZONE',442);
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_BOTTOM_BANNER_ZONE',432);

	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_BOTTOM_BANNER_TYPE','google');
	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_BOTTOM_BANNER_NUM_ADS','5');
	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_BOTTOM_BANNER_ADS_CHANNEL','home_page');
	define('CATEGORY_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('CATEGORY_PAGE_FOREIGN_PAGE_BOTTOM_BANNER_TYPE','google');
	define('CATEGORY_PAGE_FOREIGN_PAGE_BOTTOM_BANNER_NUM_ADS','5');
	define('CATEGORY_PAGE_FOREIGN_PAGE_BOTTOM_BANNER_ADS_CHANNEL','home_page');
	define('CATEGORY_PAGE_FOREIGN_PAGE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('CATEGORY_PAGE_ANIMATION_PAGE_BOTTOM_BANNER_TYPE','google');
	define('CATEGORY_PAGE_ANIMATION_PAGE_BOTTOM_BANNER_NUM_ADS','3');
	define('CATEGORY_PAGE_ANIMATION_PAGE_BOTTOM_BANNER_ADS_CHANNEL','animation_multimedia');
	define('CATEGORY_PAGE_ANIMATION_PAGE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('CATEGORY_PAGE_LANGUAGES_PAGE_BOTTOM_BANNER_TYPE','google');
	define('CATEGORY_PAGE_LANGUAGES_PAGE_BOTTOM_BANNER_NUM_ADS','3');
	define('CATEGORY_PAGE_LANGUAGES_PAGE_BOTTOM_BANNER_ADS_CHANNEL','arts_law_languages');
	define('CATEGORY_PAGE_LANGUAGES_PAGE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('CATEGORY_PAGE_IT_PAGE_BOTTOM_BANNER_TYPE','google');
	define('CATEGORY_PAGE_IT_PAGE_BOTTOM_BANNER_NUM_ADS','3');
	define('CATEGORY_PAGE_IT_PAGE_BOTTOM_BANNER_ADS_CHANNEL','information_technology');
	define('CATEGORY_PAGE_IT_PAGE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('CATEGORY_PAGE_MANAGEMENT_PAGE_BOTTOM_BANNER_TYPE','google');
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_BOTTOM_BANNER_NUM_ADS','3');
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_BOTTOM_BANNER_ADS_CHANNEL','management_business');
	define('CATEGORY_PAGE_MANAGEMENT_PAGE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_BOTTOM_BANNER_TYPE','google');
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_BOTTOM_BANNER_NUM_ADS','3');
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_BOTTOM_BANNER_ADS_CHANNEL','media_films_masscom');
	define('CATEGORY_PAGE_MEDIA_MASS_COMM_PAGE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_BOTTOM_BANNER_TYPE','google');
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_BOTTOM_BANNER_NUM_ADS','3');
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_BOTTOM_BANNER_ADS_CHANNEL','medicine_healthcare');
	define('CATEGORY_PAGE_HEALTH_MEDICINE_PAGE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_BOTTOM_BANNER_TYPE','google');
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_BOTTOM_BANNER_NUM_ADS','3');
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_BOTTOM_BANNER_ADS_CHANNEL','professional_courses');
	define('CATEGORY_PAGE_PROFESSIONAL_PAGE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('CATEGORY_PAGE_RETAIL_PAGE_BOTTOM_BANNER_TYPE','google');
	define('CATEGORY_PAGE_RETAIL_PAGE_BOTTOM_BANNER_NUM_ADS','3');
	define('CATEGORY_PAGE_RETAIL_PAGE_BOTTOM_BANNER_ADS_CHANNEL','retail');
	define('CATEGORY_PAGE_RETAIL_PAGE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_BOTTOM_BANNER_TYPE','google');
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_BOTTOM_BANNER_NUM_ADS','3');
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_BOTTOM_BANNER_ADS_CHANNEL','banking_finance_accounting');
	define('CATEGORY_PAGE_BANKING_FINANCE_PAGE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('CATEGORY_PAGE_HOSPITALITY_PAGE_BOTTOM_BANNER_TYPE','google');
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_BOTTOM_BANNER_NUM_ADS','3');
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_BOTTOM_BANNER_ADS_CHANNEL','hospitality_tourism');
	define('CATEGORY_PAGE_HOSPITALITY_PAGE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_BOTTOM_BANNER_TYPE','google');
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_BOTTOM_BANNER_NUM_ADS','3');
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_BOTTOM_BANNER_ADS_CHANNEL','science_engineering');
	define('CATEGORY_PAGE_SCIENCE_ENGINEERING_PAGE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('CATEGORY_PAGE_INDIA_PAGE_BOTTOM_BANNER_TYPE','google');
	define('CATEGORY_PAGE_INDIA_PAGE_BOTTOM_BANNER_NUM_ADS','5');
	define('CATEGORY_PAGE_INDIA_PAGE_BOTTOM_BANNER_ADS_CHANNEL','india');
	define('CATEGORY_PAGE_INDIA_PAGE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('SEARCH_PAGE_HEADER_BANNER_WIDTH',728);
	define('SEARCH_PAGE_HEADER_BANNER_HEIGHT',90);
	define('SEARCH_PAGE_HEADER_BANNER_ZONE',358);

	define('SEARCH_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('SEARCH_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',40);
	define('SEARCH_PAGE_SMALLSCRAPPER_BANNER_ZONE',359);

	define('SEARCH_PAGE_BIGSCRAPPER_BANNER_WIDTH',120);
	define('SEARCH_PAGE_BIGSCRAPPER_BANNER_HEIGHT',600);
	define('SEARCH_PAGE_BIGSCRAPPER_BANNER_ZONE',360);

	define('SEARCH_PAGE_MEDIUMSCRAPPER_BANNER_WIDTH',120);
	define('SEARCH_PAGE_MEDIUMSCRAPPER_BANNER_HEIGHT',240);
	define('SEARCH_PAGE_MEDIUMSCRAPPER_BANNER_ZONE',361);

	define('SEARCH_PAGE_FOOTER_BANNER_WIDTH',450);
	define('SEARCH_PAGE_FOOTER_BANNER_HEIGHT',300);
	define('SEARCH_PAGE_FOOTER_BANNER_ZONE',362);

	define('LISTINGS_PAGE_HEADER_BANNER_WIDTH',728);
	define('LISTINGS_PAGE_HEADER_BANNER_HEIGHT',90);
	define('LISTINGS_PAGE_HEADER_BANNER_ZONE',363);
	
	/* Need to change zone,width and height */	
    define('SEARCH_PAGE_FEATURED1_BANNER_WIDTH', 208);
	define('SEARCH_PAGE_FEATURED1_BANNER_HEIGHT', 400);
	define('SEARCH_PAGE_FEATURED1_BANNER_ZONE', 360);
	
	define('SEARCH_PAGE_FEATURED2_BANNER_WIDTH', 208);
	define('SEARCH_PAGE_FEATURED2_BANNER_HEIGHT', 400);
	define('SEARCH_PAGE_FEATURED2_BANNER_ZONE', 360);
	
	define('SEARCH_PAGE_FEATURED3_BANNER_WIDTH', 208);
	define('SEARCH_PAGE_FEATURED3_BANNER_HEIGHT', 400);
	define('SEARCH_PAGE_FEATURED3_BANNER_ZONE', 360);

    define('SEARCH_PAGE_FEATURED4_BANNER_WIDTH', 208);
	define('SEARCH_PAGE_FEATURED4_BANNER_HEIGHT', 400);
	define('SEARCH_PAGE_FEATURED4_BANNER_ZONE', 360);
	
	define('SEARCH_PAGE_FEATURED5_BANNER_WIDTH', 208);
	define('SEARCH_PAGE_FEATURED5_BANNER_HEIGHT', 400);
	define('SEARCH_PAGE_FEATURED5_BANNER_ZONE', 360);

	define('LISTINGS_PAGE_SIDE_BANNER_WIDTH',120);
	define('LISTINGS_PAGE_SIDE_BANNER_HEIGHT',600);
	define('LISTINGS_PAGE_SIDE_BANNER_ZONE',364);
	define('LISTINGS_PAGE_SIDE_BANNER_TYPE','google');
	define('LISTINGS_PAGE_SIDE_BANNER_NUM_ADS','5');
	define('LISTINGS_PAGE_SIDE_BANNER_ADS_CHANNEL','details_right');
	define('LISTINGS_PAGE_SIDE_BANNER_AD_LAYOUT','Vertical');

	define('LISTINGS_PAGE_FOOTER_BANNER_WIDTH',450);
	define('LISTINGS_PAGE_FOOTER_BANNER_HEIGHT',300);
	define('LISTINGS_PAGE_FOOTER_BANNER_ZONE',365);
	define('LISTINGS_PAGE_FOOTER_BANNER_TYPE','google');
	define('LISTINGS_PAGE_FOOTER_BANNER_NUM_ADS','5');
	define('LISTINGS_PAGE_FOOTER_BANNER_ADS_CHANNEL','details_bottom');
	define('LISTINGS_PAGE_FOOTER_BANNER_AD_LAYOUT','Vertical');

	define('ACCOUNT_SETTING_PAGE_HEADER_BANNER_WIDTH',728);
	define('ACCOUNT_SETTING_PAGE_HEADER_BANNER_HEIGHT',90);
	define('ACCOUNT_SETTING_PAGE_HEADER_BANNER_ZONE',386);
	
	define('ACCOUNT_SETTING_PAGE_SIDE_BANNER_WIDTH',120);
	define('ACCOUNT_SETTING_PAGE_SIDE_BANNER_HEIGHT',550);
	define('ACCOUNT_SETTING_PAGE_SIDE_BANNER_ZONE',377);
	define('ACCOUNT_SETTING_PAGE_SIDE_BANNER_TYPE','google');
	define('ACCOUNT_SETTING_PAGE_SIDE_BANNER_NUM_ADS','5');
	define('ACCOUNT_SETTING_PAGE_SIDE_BANNER_ADS_CHANNEL','discussion_bottom');
	define('ACCOUNT_SETTING_PAGE_SIDE_BANNER_AD_LAYOUT','Vertical');

	define('ACCOUNT_SETTING_PAGE_FOOTER_BANNER_WIDTH',728);
	define('ACCOUNT_SETTING_PAGE_FOOTER_BANNER_HEIGHT',90);
	define('ACCOUNT_SETTING_PAGE_FOOTER_BANNER_ZONE',387);
	define('ACCOUNT_SETTING_PAGE_FOOTER_BANNER_TYPE','google');
	define('ACCOUNT_SETTING_PAGE_FOOTER_BANNER_NUM_ADS','5');
	define('ACCOUNT_SETTING_PAGE_FOOTER_BANNER_ADS_CHANNEL','discussion_bottom');
	define('ACCOUNT_SETTING_PAGE_FOOTER_BANNER_AD_LAYOUT','Vertical');

	define('EVENTS_HOME_PAGE_HEADER_BANNER_WIDTH',728);
	define('EVENTS_HOME_PAGE_HEADER_BANNER_HEIGHT',90);
	define('EVENTS_HOME_PAGE_HEADER_BANNER_ZONE',384);

	define('EVENTS_HOME_PAGE_RIGHT_BANNER_WIDTH',250);
        define('EVENTS_HOME_PAGE_RIGHT_BANNER_HEIGHT',250);
        define('EVENTS_HOME_PAGE_RIGHT_BANNER_ZONE',565);
	
	define('EVENTS_VIEWALL_PAGE_HEADER_BANNER_WIDTH',728);
        define('EVENTS_VIEWALL_PAGE_HEADER_BANNER_HEIGHT',90);
        define('EVENTS_VIEWALL_PAGE_HEADER_BANNER_ZONE',566);

        define('EVENTS_VIEWALL_PAGE_RIGHT_BANNER_WIDTH',250);
        define('EVENTS_VIEWALL_PAGE_RIGHT_BANNER_HEIGHT',250);
        define('EVENTS_VIEWALL_PAGE_RIGHT_BANNER_ZONE',565);

	define('EVENTS_HOME_PAGE_FOOTER_BANNER_WIDTH',450);
	define('EVENTS_HOME_PAGE_FOOTER_BANNER_HEIGHT',300);
	define('EVENTS_HOME_PAGE_FOOTER_BANNER_ZONE',385);
	define('EVENTS_HOME_PAGE_FOOTER_BANNER_TYPE','google');
	define('EVENTS_HOME_PAGE_FOOTER_BANNER_NUM_ADS','5');
	define('EVENTS_HOME_PAGE_FOOTER_BANNER_ADS_CHANNEL','event_calendar_bottom');
	define('EVENTS_HOME_PAGE_FOOTER_BANNER_AD_LAYOUT','Vertical');

	define('EVENTS_DETAILS_PAGE_HEADER_BANNER_WIDTH',728);
	define('EVENTS_DETAILS_PAGE_HEADER_BANNER_HEIGHT',90);
	define('EVENTS_DETAILS_PAGE_HEADER_BANNER_ZONE',381);

	define('EVENTS_DETAILS_PAGE_SIDE_BANNER_WIDTH',120);
	define('EVENTS_DETAILS_PAGE_SIDE_BANNER_HEIGHT',600);
	define('EVENTS_DETAILS_PAGE_SIDE_BANNER_ZONE',382);

	define('EVENTS_DETAILS_PAGE_FOOTER_BANNER_WIDTH',450);
	define('EVENTS_DETAILS_PAGE_FOOTER_BANNER_HEIGHT',300);
	define('EVENTS_DETAILS_PAGE_FOOTER_BANNER_ZONE',383);
	define('EVENTS_DETAILS_PAGE_FOOTER_BANNER_TYPE','google');
	define('EVENTS_DETAILS_PAGE_FOOTER_BANNER_NUM_ADS','5');
	define('EVENTS_DETAILS_PAGE_FOOTER_BANNER_ADS_CHANNEL','event_calendar_details_bottom');
	//define('EVENTS_DETAILS_PAGE_FOOTER_BANNER_AD_LAYOUT','Horizontal');
	define('EVENTS_DETAILS_PAGE_FOOTER_BANNER_AD_LAYOUT','Vertical');

	define('ASK_DISCUSS_PAGE_HEADER_BANNER_WIDTH',728);
	define('ASK_DISCUSS_PAGE_HEADER_BANNER_HEIGHT',90);
	define('ASK_DISCUSS_PAGE_HEADER_BANNER_ZONE',379);

	define('ASK_DISCUSS_PAGE_FOOTER_BANNER_WIDTH',450);
	define('ASK_DISCUSS_PAGE_FOOTER_BANNER_HEIGHT',300);
	define('ASK_DISCUSS_PAGE_FOOTER_BANNER_ZONE',380);
	define('ASK_DISCUSS_PAGE_FOOTER_BANNER_TYPE','google');
	define('ASK_DISCUSS_PAGE_FOOTER_BANNER_NUM_ADS','5');
	define('ASK_DISCUSS_PAGE_FOOTER_BANNER_ADS_CHANNEL','discussion_bottom');
	define('ASK_DISCUSS_PAGE_FOOTER_BANNER_AD_LAYOUT','Vertical');

	define('DISCUSSION_DETAIL_PAGE_HEADER_BANNER_WIDTH',728);
	define('DISCUSSION_DETAIL_PAGE_HEADER_BANNER_HEIGHT',90);
	define('DISCUSSION_DETAIL_PAGE_HEADER_BANNER_ZONE',376);

	define('DISCUSSION_DETAIL_PAGE_SIDE_BANNER_WIDTH',120);
	define('DISCUSSION_DETAIL_PAGE_SIDE_BANNER_HEIGHT',240);
	define('DISCUSSION_DETAIL_PAGE_SIDE_BANNER_ZONE',377);
	define('DISCUSSION_DETAIL_PAGE_SIDE_BANNER_TYPE','google');
	define('DISCUSSION_DETAIL_PAGE_SIDE_BANNER_NUM_ADS','5');
	define('DISCUSSION_DETAIL_PAGE_SIDE_BANNER_ADS_CHANNEL','discussion_details_bottom_right');
	define('DISCUSSION_DETAIL_PAGE_SIDE_BANNER_AD_LAYOUT','Vertical');

	define('DISCUSSION_DETAIL_PAGE_SIDETOP_BANNER_WIDTH',250);
	define('DISCUSSION_DETAIL_PAGE_SIDETOP_BANNER_HEIGHT',250);
	define('DISCUSSION_DETAIL_PAGE_SIDETOP_BANNER_ZONE',514);

	define('DISCUSSION_DETAIL_PAGE_FOOTER_BANNER_WIDTH',450);
	define('DISCUSSION_DETAIL_PAGE_FOOTER_BANNER_HEIGHT',300);
	define('DISCUSSION_DETAIL_PAGE_FOOTER_BANNER_ZONE',378);
	define('DISCUSSION_DETAIL_PAGE_FOOTER_BANNER_TYPE','google');
	define('DISCUSSION_DETAIL_PAGE_FOOTER_BANNER_NUM_ADS','5');
	define('DISCUSSION_DETAIL_PAGE_FOOTER_BANNER_ADS_CHANNEL','discussion_details_bottom');
	define('DISCUSSION_DETAIL_PAGE_FOOTER_BANNER_AD_LAYOUT','Vertical');

	define('ALERT_HOME_PAGE_HEADER_BANNER_WIDTH',728);
	define('ALERT_HOME_PAGE_HEADER_BANNER_HEIGHT',90);
	define('ALERT_HOME_PAGE_HEADER_BANNER_ZONE',372);

	define('ALERT_HOME_PAGE_GOOGLESIDEBANNER_BANNER_WIDTH',120);
	define('ALERT_HOME_PAGE_GOOGLESIDEBANNER_BANNER_HEIGHT',240);
	define('ALERT_HOME_PAGE_GOOGLESIDEBANNER_BANNER_ZONE',373);

	define('ALERT_HOME_PAGE_SKYSCRAPPER_BANNER_WIDTH',120);
	define('ALERT_HOME_PAGE_SKYSCRAPPER_BANNER_HEIGHT',240);
	define('ALERT_HOME_PAGE_SKYSCRAPPER_BANNER_ZONE',374);

	define('ALERT_HOME_PAGE_FOOTER_BANNER_WIDTH',728);
	define('ALERT_HOME_PAGE_FOOTER_BANNER_HEIGHT',90);
	define('ALERT_HOME_PAGE_FOOTER_BANNER_ZONE',375);
	define('ALERT_HOME_PAGE_FOOTER_BANNER_TYPE','google');
	define('ALERT_HOME_PAGE_FOOTER_BANNER_NUM_ADS','5');
	define('ALERT_PAGE_FOOTER_BANNER_ADS_CHANNEL','discussion_details_bottom');
	define('ALERT_HOME_PAGE_FOOTER_BANNER_AD_LAYOUT','Vertical');

	define('GROUP_PAGE_HEADER_BANNER_WIDTH',728);
	define('GROUP_PAGE_HEADER_BANNER_HEIGHT',90);
	define('GROUP_PAGE_HEADER_BANNER_ZONE',370);
	
    define('REGISTER_PAGE_FOOTER_BANNER_WIDTH',450);
	define('REGISTER_PAGE_FOOTER_BANNER_HEIGHT',300);
	define('REGISTER_PAGE_FOOTER_BANNER_ZONE',371);

	define('GROUP_PAGE_FOOTER_BANNER_WIDTH',450);
	define('GROUP_PAGE_FOOTER_BANNER_HEIGHT',300);
	define('GROUP_PAGE_FOOTER_BANNER_ZONE',371);
	define('GROUP_PAGE_FOOTER_BANNER_TYPE','google');
	define('GROUP_PAGE_FOOTER_BANNER_NUM_ADS','5');	
	define('GROUP_PAGE_FOOTER_BANNER_ADS_CHANNEL','college_netowrks');
	define('GROUP_PAGE_FOOTER_BANNER_AD_LAYOUT','Vertical');

	define('COLLEGE_DETAIL_PAGE_HEADER_BANNER_WIDTH',728);
	define('COLLEGE_DETAIL_PAGE_HEADER_BANNER_HEIGHT',90);
	define('COLLEGE_DETAIL_PAGE_HEADER_BANNER_ZONE',368);
	
	define('COLLEGE_DETAIL_PAGE_FOOTER_BANNER_WIDTH',728);
	define('COLLEGE_DETAIL_PAGE_FOOTER_BANNER_HEIGHT',90);
	define('COLLEGE_DETAIL_PAGE_FOOTER_BANNER_ZONE',369);
	define('COLLEGE_DETAIL_PAGE_FOOTER_BANNER_TYPE','google');
	define('COLLEGE_DETAIL_PAGE_FOOTER_BANNER_NUM_ADS','5');
	define('COLLEGE_DETAIL_PAGE_FOOTER_BANNER_AD_LAYOUT','Vertical');
	define('COLLEGE_DETAILS_PAGE_FOOTER_BANNER_ADS_CHANNEL','college_netowrks');

	define('MESSAGE_DETAIL_PAGE_HEADER_BANNER_WIDTH',728);
	define('MESSAGE_DETAIL_PAGE_HEADER_BANNER_HEIGHT',90);
	define('MESSAGE_DETAIL_PAGE_HEADER_BANNER_ZONE',366);

	define('MESSAGE_DETAIL_PAGE_FOOTER_BANNER_WIDTH',728);
	define('MESSAGE_DETAIL_PAGE_FOOTER_BANNER_HEIGHT',90);
	define('MESSAGE_DETAIL_PAGE_FOOTER_BANNER_ZONE',367);
	define('MESSAGE_DETAIL_PAGE_FOOTER_BANNER_TYPE','google');
	define('MESSAGE_DETAIL_PAGE_FOOTER_BANNER_NUM_ADS','5');
	define('MESSAGE_DETAILS_PAGE_FOOTER_BANNER_ADS_CHANNEL','college_netowrks');
	define('MESSAGE_DETAIL_PAGE_FOOTER_BANNER_AD_LAYOUT','Vertical');
	
	define('ARTICLES_DETAILS_PAGE_HEADER_BANNER_WIDTH',728);
	define('ARTICLES_DETAILS_PAGE_HEADER_BANNER_HEIGHT',90);
	define('ARTICLES_DETAILS_PAGE_HEADER_BANNER_ZONE',571);
	
	define('ARTICLES_DETAILS_PAGE_SIDE_BANNER_WIDTH',310);
	define('ARTICLES_DETAILS_PAGE_SIDE_BANNER_HEIGHT',250);
	define('ARTICLES_DETAILS_PAGE_SIDE_BANNER_ZONE',572);

	define('ARTICLES_LIST_PAGE_HEADER_BANNER_WIDTH',728);
	define('ARTICLES_LIST_PAGE_HEADER_BANNER_HEIGHT',90);
	define('ARTICLES_LIST_PAGE_HEADER_BANNER_ZONE',573);

	define('ARTICLES_LIST_PAGE_SIDE_BANNER_WIDTH',250);
	define('ARTICLES_LIST_PAGE_SIDE_BANNER_HEIGHT',250);
	define('ARTICLES_LIST_PAGE_SIDE_BANNER_ZONE',574);

	define('ARTICLE_DETAILS_PAGE_SIDEBANNER_BANNER_WIDTH',728);
	define('ARTICLE_DETAILS_PAGE_SIDEBANNER_BANNER_HEIGHT',90);
	define('ARTICLE_DETAILS_PAGE_SIDEBANNER_BANNER_ZONE',367);
	define('ARTICLE_DETAILS_PAGE_SIDEBANNER_BANNER_TYPE','google');
	define('ARTICLE_DETAILS_PAGE_SIDEBANNER_BANNER_NUM_ADS','10');
	define('ARTICLE_DETAILS_PAGE_SIDEBANNER_BANNER_ADS_CHANNEL','event_calendar_details_bottom');
	define('ARTICLE_DETAILS_PAGE_SIDEBANNER_BANNER_AD_LAYOUT','Vertical');
        
        define('ENTERPRISE_HOME_PAGE_TOP_BANNER_WIDTH',728);
	define('ENTERPRISE_HOME_PAGE_TOP_BANNER_HEIGHT',90);
        define('ENTERPRISE_HOME_PAGE_TOP_BANNER_ZONE',512);

	define('HOME_PAGE_POPUP_BANNER_WIDTH',250);
	define('HOME_PAGE_POPUP_BANNER_HEIGHT',250);
	define('HOME_PAGE_POPUP_BANNER_ZONE',513);

    define('NAUKRISHIKSHA_PAGE_SIDE_BANNER_TYPE','google');
	define('NAUKRISHIKSHA_PAGE_SIDE_BANNER_NUM_ADS','5');
	define('NAUKRISHIKSHA_PAGE_SIDE_BANNER_ADS_CHANNEL','naukshik_right');
	define('NAUKRISHIKSHA_PAGE_SIDE_BANNER_AD_LAYOUT','Vertical');
    
    define('NAUKRISHIKSHA_PAGE_TOP_BANNER_WIDTH',120);
    define('NAUKRISHIKSHA_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('NAUKRISHIKSHA_PAGE_FOREIGN_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('NAUKRISHIKSHA_PAGE_ANIMATION_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('NAUKRISHIKSHA_PAGE_LANGUAGES_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('NAUKRISHIKSHA_PAGE_IT_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('NAUKRISHIKSHA_PAGE_MANAGEMENT_PAGE_SMALLSCRAPPER_BANNER_WIDTH',175);
	define('NAUKRISHIKSHA_PAGE_MEDIA_MASS_COMM_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('NAUKRISHIKSHA_PAGE_HEALTH_MEDICINE_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('NAUKRISHIKSHA_PAGE_PROFESSIONAL_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('NAUKRISHIKSHA_PAGE_RETAIL_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('NAUKRISHIKSHA_PAGE_BANKING_FINANCE_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('NAUKRISHIKSHA_PAGE_HOSPITALITY_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120);
	define('NAUKRISHIKSHA_PAGE_SCIENCE_ENGINEERING_PAGE_SMALLSCRAPPER_BANNER_WIDTH',120
	);	
	
    define('NAUKRISHIKSHA_PAGE_TOP_BANNER_HEIGHT',230);
	define('NAUKRISHIKSHA_PAGE_ENTRANCE_EXAM_PREPARATION_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',230);
	define('NAUKRISHIKSHA_PAGE_FOREIGN_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',230);
	define('NAUKRISHIKSHA_PAGE_ANIMATION_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',230);
	define('NAUKRISHIKSHA_PAGE_LANGUAGES_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',230);
	define('NAUKRISHIKSHA_PAGE_IT_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',230);
	define('NAUKRISHIKSHA_PAGE_MANAGEMENT_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',230);
	define('NAUKRISHIKSHA_PAGE_MEDIA_MASS_COMM_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',230);
	define('NAUKRISHIKSHA_PAGE_HEALTH_MEDICINE_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',230);
	define('NAUKRISHIKSHA_PAGE_PROFESSIONAL_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',230);
	define('NAUKRISHIKSHA_PAGE_RETAIL_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',230);
	define('NAUKRISHIKSHA_PAGE_BANKING_FINANCE_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',230);
	define('NAUKRISHIKSHA_PAGE_HOSPITALITY_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',230);
	define('NAUKRISHIKSHA_PAGE_SCIENCE_ENGINEERING_PAGE_SMALLSCRAPPER_BANNER_HEIGHT',230);
	
    define('NAUKRISHIKSHA_PAGE_TOP_BANNER_ZONE',516);
	define('NAUKRISHIKSHA_PAGE_ANIMATION_PAGE_SMALLSCRAPPER_BANNER_ZONE',517);
	define('NAUKRISHIKSHA_PAGE_LANGUAGES_PAGE_SMALLSCRAPPER_BANNER_ZONE',517);
	define('NAUKRISHIKSHA_PAGE_IT_PAGE_SMALLSCRAPPER_BANNER_ZONE',517);
	define('NAUKRISHIKSHA_PAGE_MANAGEMENT_PAGE_SMALLSCRAPPER_BANNER_ZONE',517);
	define('NAUKRISHIKSHA_PAGE_MEDIA_MASS_COMM_PAGE_SMALLSCRAPPER_BANNER_ZONE',517);
	define('NAUKRISHIKSHA_PAGE_HEALTH_MEDICINE_PAGE_SMALLSCRAPPER_BANNER_ZONE',517);
	define('NAUKRISHIKSHA_PAGE_PROFESSIONAL_PAGE_SMALLSCRAPPER_BANNER_ZONE',517);
	define('NAUKRISHIKSHA_PAGE_RETAIL_PAGE_SMALLSCRAPPER_BANNER_ZONE',517);
	define('NAUKRISHIKSHA_PAGE_BANKING_FINANCE_PAGE_SMALLSCRAPPER_BANNER_ZONE',517);
	define('NAUKRISHIKSHA_PAGE_HOSPITALITY_PAGE_SMALLSCRAPPER_BANNER_ZONE',517);
	define('NAUKRISHIKSHA_PAGE_SCIENCE_ENGINEERING_PAGE_SMALLSCRAPPER_BANNER_ZONE',517);
	
    define('NAUKRISHIKSHA_PAGE_TOPINSTITUTES_BANNER_ZONE',516);
	define('NAUKRISHIKSHA_PAGE_TOPINSTITUTES_BANNER_HEIGHT',1703);
	define('NAUKRISHIKSHA_PAGE_TOPINSTITUTES_BANNER_WIDTH',120);

	define('QUESTION_POST_SUCCESS_PAGE_FOOTER_BANNER_WIDTH',450);
	define('QUESTION_POST_SUCCESS_PAGE_FOOTER_BANNER_HEIGHT',300);
	define('QUESTION_POST_SUCCESS_PAGE_FOOTER_BANNER_ZONE',378);
	define('QUESTION_POST_SUCCESS_PAGE_FOOTER_BANNER_TYPE','google');
	define('QUESTION_POST_SUCCESS_PAGE_FOOTER_BANNER_NUM_ADS','5');
	define('QUESTION_POST_SUCCESS_PAGE_FOOTER_BANNER_ADS_CHANNEL','activity_landing_quesposting_pgbot');
	define('QUESTION_POST_SUCCESS_PAGE_FOOTER_BANNER_AD_LAYOUT','Vertical');

	define('QUESTION_POST_SUCCESS_PAGE_SIDE_BOTTOM_BANNER_WIDTH',120);
	define('QUESTION_POST_SUCCESS_PAGE_SIDE_BOTTOM_BANNER_HEIGHT',240);
	define('QUESTION_POST_SUCCESS_PAGE_SIDE_BOTTOM_BANNER_ZONE',377);
	define('QUESTION_POST_SUCCESS_PAGE_SIDE_BOTTOM_BANNER_TYPE','google');
	define('QUESTION_POST_SUCCESS_PAGE_SIDE_BOTTOM_BANNER_NUM_ADS','5');
	define('QUESTION_POST_SUCCESS_PAGE_SIDE_BOTTOM_BANNER_ADS_CHANNEL','activity_landing_quesposting_rghtbot');
	define('QUESTION_POST_SUCCESS_PAGE_SIDE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('ANSWER_POST_SUCCESS_PAGE_FOOTER_BANNER_WIDTH',450);
	define('ANSWER_POST_SUCCESS_PAGE_FOOTER_BANNER_HEIGHT',300);
	define('ANSWER_POST_SUCCESS_PAGE_FOOTER_BANNER_ZONE',378);
	define('ANSWER_POST_SUCCESS_PAGE_FOOTER_BANNER_TYPE','google');
	define('ANSWER_POST_SUCCESS_PAGE_FOOTER_BANNER_NUM_ADS','5');
	define('ANSWER_POST_SUCCESS_PAGE_FOOTER_BANNER_ADS_CHANNEL','activity_landing_ansposting_pgbot');
	define('ANSWER_POST_SUCCESS_PAGE_FOOTER_BANNER_AD_LAYOUT','Vertical');

	define('ANSWER_POST_SUCCESS_PAGE_SIDE_BOTTOM_BANNER_WIDTH',120);
	define('ANSWER_POST_SUCCESS_PAGE_SIDE_BOTTOM_BANNER_HEIGHT',240);
	define('ANSWER_POST_SUCCESS_PAGE_SIDE_BOTTOM_BANNER_ZONE',377);
	define('ANSWER_POST_SUCCESS_PAGE_SIDE_BOTTOM_BANNER_TYPE','google');
	define('ANSWER_POST_SUCCESS_PAGE_SIDE_BOTTOM_BANNER_NUM_ADS','5');
	define('ANSWER_POST_SUCCESS_PAGE_SIDE_BOTTOM_BANNER_ADS_CHANNEL','activity_landing_ansposting_rghtbot');
	define('ANSWER_POST_SUCCESS_PAGE_SIDE_BOTTOM_BANNER_AD_LAYOUT','Vertical');

	define('CUSTOMIZED1_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
	define('CUSTOMIZED1_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
	define('CUSTOMIZED1_MARKETING_PAGE_LEFT_BANNER_ZONE',547);
	
	define('CUSTOMIZED2_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
	define('CUSTOMIZED2_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
	define('CUSTOMIZED2_MARKETING_PAGE_LEFT_BANNER_ZONE',546);

	define('CUSTOMIZED3_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
        define('CUSTOMIZED3_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
        define('CUSTOMIZED3_MARKETING_PAGE_LEFT_BANNER_ZONE',585);

        define('CUSTOMIZED4_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
        define('CUSTOMIZED4_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
        define('CUSTOMIZED4_MARKETING_PAGE_LEFT_BANNER_ZONE',586);

	define('CUSTOMIZED5_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
        define('CUSTOMIZED5_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
        define('CUSTOMIZED5_MARKETING_PAGE_LEFT_BANNER_ZONE',587);

        define('CUSTOMIZED6_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
        define('CUSTOMIZED6_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
        define('CUSTOMIZED6_MARKETING_PAGE_LEFT_BANNER_ZONE',588);

	define('CUSTOMIZED7_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
        define('CUSTOMIZED7_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
        define('CUSTOMIZED7_MARKETING_PAGE_LEFT_BANNER_ZONE',589);

        define('CUSTOMIZED8_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
        define('CUSTOMIZED8_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
        define('CUSTOMIZED8_MARKETING_PAGE_LEFT_BANNER_ZONE',590);

	define('CUSTOMIZED9_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
        define('CUSTOMIZED9_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
        define('CUSTOMIZED9_MARKETING_PAGE_LEFT_BANNER_ZONE',591);
	
	define('HOSPITALITY_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
	define('HOSPITALITY_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
	define('HOSPITALITY_MARKETING_PAGE_LEFT_BANNER_ZONE',553);

	define('SCIENCE_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
	define('SCIENCE_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
	define('SCIENCE_MARKETING_PAGE_LEFT_BANNER_ZONE',554);

	define('ANIMATION_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
	define('ANIMATION_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
	define('ANIMATION_MARKETING_PAGE_LEFT_BANNER_ZONE',555);

	define('IT_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
 	define('IT_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
 	define('IT_MARKETING_PAGE_LEFT_BANNER_ZONE',548);
	
	define('BBA_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
 	define('BBA_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
 	define('BBA_MARKETING_PAGE_LEFT_BANNER_ZONE',556);

	define('CLINICALRESEARCH_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
 	define('CLINICALRESEARCH_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
 	define('CLINICALRESEARCH_MARKETING_PAGE_LEFT_BANNER_ZONE',564);

	define('FASHIONDESIGN_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
 	define('FASHIONDESIGN_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
 	define('FASHIONDESIGN_MARKETING_PAGE_LEFT_BANNER_ZONE',563);

	define('MASSCOMM_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
 	define('MASSCOMM_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
 	define('MASSCOMM_MARKETING_PAGE_LEFT_BANNER_ZONE',562);
	define('TESTPREP_MARKETING_PAGE_LEFT_BANNER_WIDTH',410);
	define('TESTPREP_MARKETING_PAGE_LEFT_BANNER_HEIGHT',250);
	define('TESTPREP_MARKETING_PAGE_LEFT_BANNER_ZONE',578);
	define('HOME_PAGE_SPOTLIGHTBANNER_BANNER_WIDTH',485);
    define('HOME_PAGE_SPOTLIGHTBANNER_BANNER_HEIGHT',110);
    define('HOME_PAGE_SPOTLIGHTBANNER_BANNER_ZONE',592);
	
	//Amit Singhal: Naukri Shiksha Banners
	define('NAUKRI_PAGE_FULL_TIME_MBA/PGDM_TOP_BANNER_WIDTH',470);
	define('NAUKRI_PAGE_FULL_TIME_MBA/PGDM_TOP_BANNER_HEIGHT',60);
	define('NAUKRI_PAGE_FULL_TIME_MBA/PGDM_TOP_BANNER_ZONE',597);
	
	define('NAUKRI_PAGE_FULL_TIME_MBA/PGDM_SCRAPPER_BANNER_WIDTH',973);
	define('NAUKRI_PAGE_FULL_TIME_MBA/PGDM_SCRAPPER_BANNER_HEIGHT',200);
	define('NAUKRI_PAGE_FULL_TIME_MBA/PGDM_SCRAPPER_BANNER_ZONE',598);
	
	define('NAUKRI_PAGE_DISTANCE/CORRESPONDENCE_MBA_TOP_BANNER_WIDTH',470);
	define('NAUKRI_PAGE_DISTANCE/CORRESPONDENCE_MBA_TOP_BANNER_HEIGHT',60);
	define('NAUKRI_PAGE_DISTANCE/CORRESPONDENCE_MBA_TOP_BANNER_ZONE',605);
	
	define('NAUKRI_PAGE_DISTANCE/CORRESPONDENCE_MBA_SCRAPPER_BANNER_WIDTH',973);
	define('NAUKRI_PAGE_DISTANCE/CORRESPONDENCE_MBA_SCRAPPER_BANNER_HEIGHT',200);
	define('NAUKRI_PAGE_DISTANCE/CORRESPONDENCE_MBA_SCRAPPER_BANNER_ZONE',612);
	
	define('NAUKRI_PAGE_PART_TIME_MBA_TOP_BANNER_WIDTH',470);
	define('NAUKRI_PAGE_PART_TIME_MBA_TOP_BANNER_HEIGHT',60);
	define('NAUKRI_PAGE_PART_TIME_MBA_TOP_BANNER_ZONE',610);
	
	define('NAUKRI_PAGE_PART-TIME_MBA_SCRAPPER_BANNER_WIDTH',973);
	define('NAUKRI_PAGE_PART-TIME_MBA_SCRAPPER_BANNER_HEIGHT',200);
	define('NAUKRI_PAGE_PART-TIME_MBA_SCRAPPER_BANNER_ZONE',618);
	
	define('NAUKRI_PAGE_MCA,_PGDCA,_M.SC_CS/IT_TOP_BANNER_WIDTH',470);
	define('NAUKRI_PAGE_MCA,_PGDCA,_M.SC_CS/IT_TOP_BANNER_HEIGHT',60);
	define('NAUKRI_PAGE_MCA,_PGDCA,_M.SC_CS/IT_TOP_BANNER_ZONE',606);
	
	define('NAUKRI_PAGE_MCA,_PGDCA,_M.SC_CS/IT_SCRAPPER_BANNER_WIDTH',973);
	define('NAUKRI_PAGE_MCA,_PGDCA,_M.SC_CS/IT_SCRAPPER_BANNER_HEIGHT',200);
	define('NAUKRI_PAGE_MCA,_PGDCA,_M.SC_CS/IT_SCRAPPER_BANNER_ZONE',614);
	
	define('NAUKRI_PAGE_DISTANCE_MCA_TOP_BANNER_WIDTH',470);
	define('NAUKRI_PAGE_DISTANCE_MCA_TOP_BANNER_HEIGHT',60);
	define('NAUKRI_PAGE_DISTANCE_MCA_TOP_BANNER_ZONE',607);
	
	define('NAUKRI_PAGE_DISTANCE_MCA_SCRAPPER_BANNER_WIDTH',973);
	define('NAUKRI_PAGE_DISTANCE_MCA_SCRAPPER_BANNER_HEIGHT',200);
	define('NAUKRI_PAGE_DISTANCE_MCA_SCRAPPER_BANNER_ZONE',615);
	
	define('NAUKRI_PAGE_PROGRAMMING_LANGUAGES_TOP_BANNER_WIDTH',470);
	define('NAUKRI_PAGE_PROGRAMMING_LANGUAGES_TOP_BANNER_HEIGHT',60);
	define('NAUKRI_PAGE_PROGRAMMING_LANGUAGES_TOP_BANNER_ZONE',608);
	
	define('NAUKRI_PAGE_PROGRAMMING_LANGUAGES_SCRAPPER_BANNER_WIDTH',973);
	define('NAUKRI_PAGE_PROGRAMMING_LANGUAGES_SCRAPPER_BANNER_HEIGHT',200);
	define('NAUKRI_PAGE_PROGRAMMING_LANGUAGES_SCRAPPER_BANNER_ZONE',616);
	
	define('NAUKRI_PAGE_CISCO_CERTIFICATIONS_TOP_BANNER_WIDTH',470);
	define('NAUKRI_PAGE_CISCO_CERTIFICATIONS_TOP_BANNER_HEIGHT',60);
	define('NAUKRI_PAGE_CISCO_CERTIFICATIONS_TOP_BANNER_ZONE',609);
	
	define('NAUKRI_PAGE_CISCO_CERTIFICATIONS_SCRAPPER_BANNER_WIDTH',973);
	define('NAUKRI_PAGE_CISCO_CERTIFICATIONS_SCRAPPER_BANNER_HEIGHT',200);
	define('NAUKRI_PAGE_CISCO_CERTIFICATIONS_SCRAPPER_BANNER_ZONE',617);
	
	define('NAUKRI_PAGE_ANIMATION_TOP_BANNER_WIDTH',470);
	define('NAUKRI_PAGE_ANIMATION_TOP_BANNER_HEIGHT',60);
	define('NAUKRI_PAGE_ANIMATION_TOP_BANNER_ZONE',601);
	
	define('NAUKRI_PAGE_ANIMATION_SCRAPPER_BANNER_WIDTH',973);
	define('NAUKRI_PAGE_ANIMATION_SCRAPPER_BANNER_HEIGHT',200);
	define('NAUKRI_PAGE_ANIMATION_SCRAPPER_BANNER_ZONE',603);
	
	define('NAUKRI_PAGE_GRAPHIC_DESIGNING_TOP_BANNER_WIDTH',470);
	define('NAUKRI_PAGE_GRAPHIC_DESIGNING_TOP_BANNER_HEIGHT',60);
	define('NAUKRI_PAGE_GRAPHIC_DESIGNING_TOP_BANNER_ZONE',602);
	
	define('NAUKRI_PAGE_GRAPHIC_DESIGNING_SCRAPPER_BANNER_WIDTH',973);
	define('NAUKRI_PAGE_GRAPHIC_DESIGNING_SCRAPPER_BANNER_HEIGHT',200);
	define('NAUKRI_PAGE_GRAPHIC_DESIGNING_SCRAPPER_BANNER_ZONE',611);
	
	define('NAUKRI_PAGE_WEB_DESIGNING_TOP_BANNER_WIDTH',470);
	define('NAUKRI_PAGE_WEB_DESIGNING_TOP_BANNER_HEIGHT',60);
	define('NAUKRI_PAGE_WEB_DESIGNING_TOP_BANNER_ZONE',604);
	
	define('NAUKRI_PAGE_WEB_DESIGNING_SCRAPPER_BANNER_WIDTH',973);
	define('NAUKRI_PAGE_WEB_DESIGNING_SCRAPPER_BANNER_HEIGHT',200);
	define('NAUKRI_PAGE_WEB_DESIGNING_SCRAPPER_BANNER_ZONE',613);
	//Amit Singhal : Naukri Shiksha Banners
	
	//Amit Singhal : Category Page Revamp 2
	define('CATEGORY_PAGE_RIGHT_BANNER_WIDTH',250);
	define('CATEGORY_PAGE_RIGHT_BANNER_HEIGHT',740);
	define('CATEGORY_PAGE_RIGHT_BANNER_ZONE',482);

	define('CATEGORY_PAGE_RIGHT2_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_RIGHT2_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_RIGHT2_BANNER_ZONE',619);
	
	define('CATEGORY_PAGE_RIGHT3_BANNER_WIDTH',250);
	define('CATEGORY_PAGE_RIGHT3_BANNER_HEIGHT',370);
	define('CATEGORY_PAGE_RIGHT3_BANNER_ZONE',622);
	
	define('CATEGORY_PAGE_EIGTH_BANNER_WIDTH',468);
	define('CATEGORY_PAGE_EIGTH_BANNER_HEIGHT',60);
	define('CATEGORY_PAGE_EIGTH_BANNER_ZONE',621);
	//Amit Singhal : Category Page Revamp 2
	
	define('RECOMMENDATION_PAGE_RIGHT_BANNER_WIDTH',250);
	define('RECOMMENDATION_PAGE_RIGHT_BANNER_HEIGHT',330);
	define('RECOMMENDATION_PAGE_RIGHT_BANNER_ZONE',599);

	// Start: Added by Ankur Gupta on 10 Jan, 2012 for Homepage Gutter banners
	define('HOME_PAGE_LEFT_GUTTER_BANNER_WIDTH',100);
	define('HOME_PAGE_LEFT_GUTTER_BANNER_HEIGHT',180);
	define('HOME_PAGE_LEFT_GUTTER_BANNER_ZONE',649);

	define('HOME_PAGE_RIGHT_GUTTER_BANNER_WIDTH',120);
	define('HOME_PAGE_RIGHT_GUTTER_BANNER_HEIGHT',400);
	define('HOME_PAGE_RIGHT_GUTTER_BANNER_ZONE',649);
	// End: Added by Ankur Gupta on 10 Jan, 2012 for Homepage Gutter banners
	
	define('CATEGORY_PAGE_TOP_BANNER_WIDTH',728);
	define('CATEGORY_PAGE_TOP_BANNER_HEIGHT',90);
	define('CATEGORY_PAGE_TOP_BANNER_ZONE',478);
	
	define('CATEGORY_PAGE_FOURTH_BANNER_WIDTH',468);
	define('CATEGORY_PAGE_FOURTH_BANNER_HEIGHT',60);
	define('CATEGORY_PAGE_FOURTH_BANNER_ZONE',650);

    // Added by Amit K on 27th April 2012 for Cat pages Gutter banners, ticket #920
	define('CATEGORY_PAGE_RIGHT_GUTTER_BANNER_WIDTH',120);
	define('CATEGORY_PAGE_RIGHT_GUTTER_BANNER_HEIGHT',250);
	define('CATEGORY_PAGE_RIGHT_GUTTER_BANNER_ZONE',805);

    // Added by Amit K on 14th August 2013 for Abroad Cat pages Gutter banners, ticket #2442
	define('ABROAD_CATEGORY_PAGE_RIGHT_GUTTER_BANNER_WIDTH',120);
	define('ABROAD_CATEGORY_PAGE_RIGHT_GUTTER_BANNER_HEIGHT',600);
	define('ABROAD_CATEGORY_PAGE_RIGHT_GUTTER_BANNER_ZONE',715);
	
    define('ARTICLE_DETAILS_PAGE_BOTTOMBANNER_BANNER_WIDTH',728);
    define('ARTICLE_DETAILS_PAGE_BOTTOMBANNER_BANNER_HEIGHT',90);
    define('ARTICLE_DETAILS_PAGE_BOTTOMBANNER_BANNER_ZONE',367);
    define('ARTICLE_DETAILS_PAGE_BOTTOMBANNER_BANNER_TYPE','google');
    define('ARTICLE_DETAILS_PAGE_BOTTOMBANNER_BANNER_NUM_ADS','5');
    define('ARTICLE_DETAILS_PAGE_BOTTOMBANNER_BANNER_ADS_CHANNEL','event_calendar_details_bottom');
    define('ARTICLE_DETAILS_PAGE_BOTTOMBANNER_BANNER_AD_LAYOUT','Vertical');
	
	define('CATEGORY_PAGE_FOOTER_BANNER_WIDTH',300);
	define('CATEGORY_PAGE_FOOTER_BANNER_HEIGHT',600);
	define('CATEGORY_PAGE_FOOTER_BANNER_ZONE',365);
	define('CATEGORY_PAGE_FOOTER_BANNER_TYPE','google');
	define('CATEGORY_PAGE_FOOTER_BANNER_NUM_ADS','5');
	define('CATEGORY_PAGE_FOOTER_BANNER_ADS_CHANNEL','category_page');
	define('CATEGORY_PAGE_FOOTER_BANNER_AD_LAYOUT','Vertical');
	
	
	define('HOME_PAGE_EVENTS_BANNER_WIDTH',1360);
    define('HOME_PAGE_EVENTS_BANNER_HEIGHT',274);
    define('HOME_PAGE_EVENTS_BANNER_ZONE',679);

	define('CATEGORY_PAGE_RIGHTBOTTOM_BANNER_WIDTH',298);
	define('CATEGORY_PAGE_RIGHTBOTTOM_BANNER_HEIGHT',246);
	define('CATEGORY_PAGE_RIGHTBOTTOM_BANNER_ZONE',702);

    define('RANKING_PAGE_BOTTOM_RIGHT_BANNER_WIDTH',300);
	define('RANKING_PAGE_BOTTOM_RIGHT_BANNER_HEIGHT',600);
	define('RANKING_PAGE_BOTTOM_RIGHT_BANNER_ZONE',703);
	define('RANKING_PAGE_BOTTOM_RIGHT_BANNER_TYPE','google');
	define('RANKING_PAGE_BOTTOM_RIGHT_BANNER_NUM_ADS','2');
	define('RANKING_PAGE_BOTTOM_RIGHT_BANNER_ADS_CHANNEL','ranking_page');
	define('RANKING_PAGE_BOTTOM_RIGHT_BANNER_AD_LAYOUT','Vertical');	

    define('CAREER_PAGE_TOP_BANNER_WIDTH',940);
    define('CAREER_PAGE_TOP_BANNER_HEIGHT',300);
    define('CAREER_PAGE_TOP_BANNER_ZONE',700);

    define('CAREER_PAGE_RIGHT_BANNER_WIDTH',160);
    define('CAREER_PAGE_RIGHT_BANNER_HEIGHT',600);
    define('CAREER_PAGE_RIGHT_BANNER_ZONE',701);

    define('RANKING_PAGE_HEADER_BANNER_WIDTH',728);
	define('RANKING_PAGE_HEADER_BANNER_HEIGHT',90);
	define('RANKING_PAGE_HEADER_BANNER_ZONE', 718);
	
    // Added by Amit K on 24th March 2014 for Course pages Gutter banners, Story LF-873
	define('COURSE_PAGE_RIGHT_GUTTER_BANNER_WIDTH',120);
	define('COURSE_PAGE_RIGHT_GUTTER_BANNER_HEIGHT',400);
	define('COURSE_PAGE_RIGHT_GUTTER_BANNER_ZONE',719);

        define('CAREER_CENTRAL_HOME_PAGE_HEADER_BANNER_WIDTH',728);
        define('CAREER_CENTRAL_HOME_PAGE_HEADER_BANNER_HEIGHT',90);
        define('CAREER_CENTRAL_HOME_PAGE_HEADER_BANNER_ZONE',720);

        define('CAREER_CENTRAL_HOME_PAGE_RIGHT1_BANNER_WIDTH',243);
        define('CAREER_CENTRAL_HOME_PAGE_RIGHT1_BANNER_HEIGHT',126);
        define('CAREER_CENTRAL_HOME_PAGE_RIGHT1_BANNER_ZONE',745);

        define('CAREER_CENTRAL_INTEREST_PAGE_HEADER_BANNER_WIDTH',728);
        define('CAREER_CENTRAL_INTEREST_PAGE_HEADER_BANNER_HEIGHT',90);
        define('CAREER_CENTRAL_INTEREST_PAGE_HEADER_BANNER_ZONE',746);

        define('CAREER_CENTRAL_SUGGESTION_PAGE_HEADER_BANNER_WIDTH',728);
        define('CAREER_CENTRAL_SUGGESTION_PAGE_HEADER_BANNER_HEIGHT',90);
        define('CAREER_CENTRAL_SUGGESTION_PAGE_HEADER_BANNER_ZONE',747);

        define('CAREER_CENTRAL_DETAIL_PAGE_HEADER_BANNER_WIDTH',728);
        define('CAREER_CENTRAL_DETAIL_PAGE_HEADER_BANNER_HEIGHT',90);
        define('CAREER_CENTRAL_DETAIL_PAGE_HEADER_BANNER_ZONE',748);

        define('CAREER_CENTRAL_DETAIL_PAGE_BOTTOM_BANNER_WIDTH',720);
        define('CAREER_CENTRAL_DETAIL_PAGE_BOTTOM_BANNER_HEIGHT',150);
        define('CAREER_CENTRAL_DETAIL_PAGE_BOTTOM_BANNER_ZONE',749);

/*
 *	STUDY ABROAD BANNERS
 */
	define('SA_PAGE_TOP_BANNER_WIDTH',468);
	define('SA_PAGE_TOP_BANNER_HEIGHT',60);
	define('SA_PAGE_TOP_BANNER_ZONE',721);
	
	define('SA_CATEGORY_PAGE_MIDDLE_BANNER_WIDTH',728);
	define('SA_CATEGORY_PAGE_MIDDLE_BANNER_HEIGHT',90);
	define('SA_CATEGORY_PAGE_MIDDLE_BANNER_ZONE',722);
	
	define('SA_COUNTRY_PAGE_MIDDLE_BANNER_WIDTH',728);
	define('SA_COUNTRY_PAGE_MIDDLE_BANNER_HEIGHT',90);
	define('SA_COUNTRY_PAGE_MIDDLE_BANNER_ZONE',737);


	define('SA_CATEGORY_PAGE_BOTTOM_BANNER_WIDTH',966);
	define('SA_CATEGORY_PAGE_BOTTOM_BANNER_HEIGHT',250);
	define('SA_CATEGORY_PAGE_BOTTOM_BANNER_ZONE',723);
	
	// Revamped
	define('SA_GUTTER_PAGE_RIGHT_BANNER_WIDTH',120);
	define('SA_GUTTER_PAGE_RIGHT_BANNER_HEIGHT',600);
	define('SA_GUTTER_PAGE_RIGHT_BANNER_ZONE',715);	
/*
 *	STUDY ABROAD BANNERS
 */
	define('HOME_PAGE_SNIPER_BANNER_ZONE',730); 
	define('HOME_PAGE_SNIPER_BANNER_WIDTH',210);
	define('HOME_PAGE_SNIPER_BANNER_HEIGHT',70);

	//Add Banner Property on COllege predictor tool
	define('JEE_COLLEGE_PREDICTOR_PAGE_RIGHT_GUTTER_BANNER_WIDTH',120);
	define('JEE_COLLEGE_PREDICTOR_PAGE_RIGHT_GUTTER_BANNER_HEIGHT',400);
	define('JEE_COLLEGE_PREDICTOR_PAGE_RIGHT_GUTTER_BANNER_ZONE',731);
	
	define('KCET_COLLEGE_PREDICTOR_PAGE_RIGHT_GUTTER_BANNER_WIDTH',120);
	define('KCET_COLLEGE_PREDICTOR_PAGE_RIGHT_GUTTER_BANNER_HEIGHT',400);
	define('KCET_COLLEGE_PREDICTOR_PAGE_RIGHT_GUTTER_BANNER_ZONE',733);
	
	define('COMEDK_COLLEGE_PREDICTOR_PAGE_RIGHT_GUTTER_BANNER_WIDTH',120);
	define('COMEDK_COLLEGE_PREDICTOR_PAGE_RIGHT_GUTTER_BANNER_HEIGHT',400);
	define('COMEDK_COLLEGE_PREDICTOR_PAGE_RIGHT_GUTTER_BANNER_ZONE',732);

	//New category pages RNR
	define('RNR_CATEGORY_PAGE_SNIPPET_TOP_BANNER_WIDTH',700);
	define('RNR_CATEGORY_PAGE_SNIPPET_TOP_BANNER_HEIGHT',150);
	define('RNR_CATEGORY_PAGE_SNIPPET_TOP_BANNER_ZONE',803);
	
	define('RNR_CATEGORY_PAGE_SNIPPET_MIDDLE_BANNER_WIDTH',700);
	define('RNR_CATEGORY_PAGE_SNIPPET_MIDDLE_BANNER_HEIGHT',150);
	define('RNR_CATEGORY_PAGE_SNIPPET_MIDDLE_BANNER_ZONE',804);
	
	define('RNR_CATEGORY_PAGE_SNIPPET_BOTTOM_BANNER_WIDTH',700);
	define('RNR_CATEGORY_PAGE_SNIPPET_BOTTOM_BANNER_HEIGHT',150);
	define('RNR_CATEGORY_PAGE_SNIPPET_BOTTOM_BANNER_ZONE',736);
	
    //Exam pages banners

	define('EXAM_PAGE_TOP_BANNER_WIDTH',728);
	define('EXAM_PAGE_TOP_BANNER_HEIGHT',90);
	define('EXAM_PAGE_TOP_BANNER_ZONE',738);

        define('ALL_EXAM_PAGE_TOP_BANNER_WIDTH',728);
        define('ALL_EXAM_PAGE_TOP_BANNER_HEIGHT',90);
        define('ALL_EXAM_PAGE_TOP_BANNER_ZONE',843);
	
	define('EXAM_PAGE_RIGHT_BANNER_WIDTH',248);
	define('EXAM_PAGE_RIGHT_BANNER_HEIGHT',208);
	define('EXAM_PAGE_RIGHT_BANNER_ZONE',739);
	
	//Push Down Banner for ranking pages.
	
	define('RANKING_PAGE_PUSHDOWN_TOP_BANNER_WIDTH',940);
	define('RANKING_PAGE_PUSHDOWN_TOP_BANNER_HEIGHT',300);
	define('RANKING_PAGE_PUSHDOWN_TOP_BANNER_ZONE',740);
		
	//B.Tech college Reviews BAnners.
	define('COURSE_HOME_PAGE_RIGHT_BANNER_WIDTH',220);
	define('COURSE_HOME_PAGE_RIGHT_BANNER_HEIGHT',128);
	define('COURSE_HOME_PAGE_RIGHT_BANNER_ZONE',750);

	define('CATEGORY_BTECH_PAGE_MIDDLE_BANNER_WIDTH',220);
	define('CATEGORY_BTECH_PAGE_MIDDLE_BANNER_HEIGHT',128);
	define('CATEGORY_BTECH_PAGE_MIDDLE_BANNER_ZONE',751);

	define('RANKING_PAGE_MIDDLE_BANNER_WIDTH',220);
	define('RANKING_PAGE_MIDDLE_BANNER_HEIGHT',128);
	define('RANKING_PAGE_MIDDLE_BANNER_ZONE',752);


// B.Tech College Reviews Banners Mobile
	define('COURSE_HOME_PAGE_MOBILE_BANNER_WIDTH',300);
	define('COURSE_HOME_PAGE_MOBILE_BANNER_HEIGHT',120);
	define('COURSE_HOME_PAGE_MOBILE_BANNER_ZONE',753);
	
	define('CATEGORY_BTECH_PAGE_MOBILE_BANNER_WIDTH',300);
	define('CATEGORY_BTECH_PAGE_MOBILE_BANNER_HEIGHT',120);
	define('CATEGORY_BTECH_PAGE_MOBILE_BANNER_ZONE',754);
	
	define('RANKING_PAGE_MOBILE_BANNER_WIDTH',300);
	define('RANKING_PAGE_MOBILE_BANNER_HEIGHT',120);
	define('RANKING_PAGE_MOBILE_BANNER_ZONE',755);

        define('JEE_COLLEGE_PREDICTOR_PAGE_MOBILE_BANNER_WIDTH',272);
        define('JEE_COLLEGE_PREDICTOR_PAGE_MOBILE_BANNER_HEIGHT',65);
        define('JEE_COLLEGE_PREDICTOR_PAGE_MOBILE_BANNER_ZONE',806);

	//new home page banner for featured colleges
	define('NEW_HOME_PAGE_FC1_BANNER_WIDTH',886);
	define('NEW_HOME_PAGE_FC1_BANNER_HEIGHT',110);
	define('NEW_HOME_PAGE_FC1_BANNER_ZONE',756);
	
	define('NEW_HOME_PAGE_FC2_BANNER_WIDTH',886);
	define('NEW_HOME_PAGE_FC2_BANNER_HEIGHT',110);
	define('NEW_HOME_PAGE_FC2_BANNER_ZONE',757);
	
	define('NEW_HOME_PAGE_FC3_BANNER_WIDTH',886);
	define('NEW_HOME_PAGE_FC3_BANNER_HEIGHT',110);
	define('NEW_HOME_PAGE_FC3_BANNER_ZONE',758);
	
	define('NEW_HOME_PAGE_FC4_BANNER_WIDTH',886);
	define('NEW_HOME_PAGE_FC4_BANNER_HEIGHT',110);
	define('NEW_HOME_PAGE_FC4_BANNER_ZONE',759);
	
	//new home page banner for featured colleges
	define('NEW_HOME_PAGE_UE1_BANNER_WIDTH',290);
	define('NEW_HOME_PAGE_UE1_BANNER_HEIGHT',310);
	define('NEW_HOME_PAGE_UE1_BANNER_ZONE',760);

	// cat exam page gutter banner
	define('EXAM_PAGE_RIGHT_GUTTER_BANNER_WIDTH',120);
	define('EXAM_PAGE_RIGHT_GUTTER_BANNER_HEIGHT',250);
	define('EXAM_PAGE_RIGHT_GUTTER_BANNER_ZONE',761);

    //Add Banner Property on Rank Predictor tool
    define('JEE_RANK_PREDICTOR_PAGE_RIGHT_GUTTER_BANNER_WIDTH',120);
    define('JEE_RANK_PREDICTOR_PAGE_RIGHT_GUTTER_BANNER_HEIGHT',400);
    define('JEE_RANK_PREDICTOR_PAGE_RIGHT_GUTTER_BANNER_ZONE',794);

    // Desktop Question detail page banner
    define('QUESTION_DETAIL_PAGE_RIGHT_BANNER_WIDTH',300);
    define('QUESTION_DETAIL_PAGE_RIGHT_BANNER_HEIGHT',250);
    define('QUESTION_DETAIL_PAGE_RIGHT_BANNER_ZONE',795);

    //Desktop IIM Call Predictor page banners
	define('IIMCP_PAGE_TIER1_DESKTOP_RIGHT_BANNER_WIDTH', 200);
	define('IIMCP_PAGE_TIER1_DESKTOP_RIGHT_BANNER_HEIGHT', 300);
	define('IIMCP_PAGE_TIER1_DESKTOP_RIGHT_BANNER_ZONE', 796);

	define('IIMCP_PAGE_TIER2_DESKTOP_RIGHT_BANNER_WIDTH', 200);
	define('IIMCP_PAGE_TIER2_DESKTOP_RIGHT_BANNER_HEIGHT', 300);
	define('IIMCP_PAGE_TIER2_DESKTOP_RIGHT_BANNER_ZONE', 797);

	define('IIMCP_PAGE_TIER3_DESKTOP_RIGHT_BANNER_WIDTH', 200);
	define('IIMCP_PAGE_TIER3_DESKTOP_RIGHT_BANNER_HEIGHT', 300);
	define('IIMCP_PAGE_TIER3_DESKTOP_RIGHT_BANNER_ZONE', 798);

	define('IIMCP_PAGE_TIER1_MOBILE_BANNER_WIDTH', 272);
	define('IIMCP_PAGE_TIER1_MOBILE_BANNER_HEIGHT', 65);
	define('IIMCP_PAGE_TIER1_MOBILE_BANNER_ZONE', 799);

	define('IIMCP_PAGE_TIER2_MOBILE_BANNER_WIDTH', 272);
	define('IIMCP_PAGE_TIER2_MOBILE_BANNER_HEIGHT', 65);
	define('IIMCP_PAGE_TIER2_MOBILE_BANNER_ZONE', 800);

	define('IIMCP_PAGE_TIER3_MOBILE_BANNER_WIDTH', 272);
	define('IIMCP_PAGE_TIER3_MOBILE_BANNER_HEIGHT', 65);
	define('IIMCP_PAGE_TIER3_MOBILE_BANNER_ZONE', 801);
