<?php
    global $categoryMap;
    $categoryMap = array(
        'studyabroad' => array(
            'page' => 'FOREIGN_PAGE',
            'product'=>'catgeory_foreign',
            'displayName' => '<span style="line-height:28px">Study Abroad</span>',
            'rightImage' => '/public/images/fo_aeroplane.jpg',
            'leftImage' => '/public/images/fostudents_1.gif',
            'adImage' => '/public/images/300x250_bannerfoedu.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Important Dates',
            'eventsImage' => '/public/images/foreign-edu-calender.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/foreign-edu-scholarship.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/foreignedu-feautedcontent.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'1',
			'name'=>'Study Abroad',
			'headerName'=>'Study Abroad'
        ),
        'management' => array(
            'page' => 'MANAGEMENT_PAGE',
            'product'=>'catgeory_management',
            'displayName' => '<span style="line-height:28px">Management</span>',
            'rightImage' => '/public/images/topheader-management2.jpg',
            'leftImage' => '/public/images/topheader-management1.gif',
            'adImage' => '/public/images/management300x250.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/impdates-management.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/featured-schol-management.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/featured-contentmanag.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'3',
			'name'=>'Management and Business',
			'headerName'=>'Management'
        ),
		'design' => array(
            'page' => 'DESIGN_PAGE',
            'product'=>'catgeory_design',
            'displayName' => '<span style="line-height:28px">Design</span>',
            'rightImage' => '/public/images/topheader-management2.jpg',
            'leftImage' => '/public/images/topheader-management1.gif',
            'adImage' => '/public/images/management300x250.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/impdates-management.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/featured-schol-management.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/featured-contentmanag.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'3',
			'name'=>'Design',
			'headerName'=>'Design'
        ),
        'testprep' => array(
            'page' => 'ENTRANCE_EXAM_PREPARATION_PAGE',
            'product'=>'catgeory_enterance',
            'displayName' => '<span style="line-height:28px">Test Preparation</span>',
            'rightImage' => '/public/images/entrance-exam-header2.jpg',
            'leftImage' => '/public/images/entrance-exam-header1.gif',
            'adImage' => '/public/images/300x250_bannerext.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/impdates-entranceex.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/schol-entrancedate.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/featured-content-entranceex.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'14',
			'name'=>'Test Preparation',
			'headerName'=>'Test Preparation'
        ),
        'it' => array(                         
            'page' => 'IT_PAGE',
            'product'=>'catgeory_banking',
            'displayName' => '<span style="line-height:28px">Information Technology</span>',
            'rightImage' => '/public/images/top-headerit-2.jpg',
            'leftImage' => '/public/images/top-headerit-1.gif',
            'adImage' => '/public/images/banner-it300x250.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/imp-dates-it.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/featured-schol-it.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/featured-content-it.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'10',
			'name'=>'Information Technology',
			'headerName'=>'Information Technology'
        ),
        'banking' => array(           
            'page' => 'BANKING_FINANCE_PAGE',
            'product'=>'catgeory_banking',
            'displayName' => '<span style="line-height:28px">Banking &amp; Finance</span>',
            'rightImage' => '/public/images/banking-top-header2.jpg',
            'leftImage' => '/public/images/banking-top-header1.gif',
            'adImage' => '/public/images/300x250-bankingbanner.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/banking-imp-dates.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/banking-featured-scholal.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/baking-featured-content.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'4',
			'name'=>'Banking and Finance',
			'headerName'=>'Banking and Insurance'
        ),
        'arts' => array(
            'page' => 'LANGUAGES_PAGE',
            'product'=>'catgeory_language',
            'displayName' => '<span style="line-height:28px">Arts, Law, Languages &amp; Teaching</span>',
            'rightImage' => '/public/images/header-arts2.jpg',
            'leftImage' => '/public/images/header-arts.gif',
            'adImage' => '/public/images/300x250_bannerarts.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/impdates-arts.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/schol-arts.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/datesimp-arts.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'9',
			'name'=>'Arts, Law and Languages',
			'headerName'=>'Arts'
        ),
        'retail' => array(
            'page' => 'RETAIL_PAGE',
            'product'=>'catgeory_retail',
            'displayName' => '<span style="line-height:28px">Retail</span>',
            'rightImage' => '/public/images/retail-header-shop.jpg',
            'leftImage' => '/public/images/retail-header-man.gif',
            'adImage' => '/public/images/300x250_retailbanner.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/retail-featured-content.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/foreign-edu-scholarship.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/foreignedu-feautedcontent.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'11',
			'name'=>'Retail',
			'headerName'=>'Retail'
        ),
        'miscellaneous' => array(
            'page' => 'MISCELLANEOUS_PAGE',
            'product'=>'catgeory_miscellaneous',
            'displayName' => '<span style="line-height:28px">Miscellaneous</span>',
            'rightImage' => '/public/images/retail-header-shop.jpg',
            'leftImage' => '/public/images/retail-header-man.gif',
            'adImage' => '/public/images/300x250_retailbanner.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/retail-featured-content.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/foreign-edu-scholarship.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/foreignedu-feautedcontent.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'149',
			'name'=>'Miscellaneous',
			'headerName'=>'Miscellaneous'
        ),
        'india' => array(
            'page' => 'INDIA_PAGE',
            'product'=>'country_india',
            'displayName' => '<span style="line-height:28px"> &nbsp; INDIA</span>',
            'rightImage' => '/public/images/retail-header-shop.jpg',
            'leftImage' => '/public/images/indiaPageFlag.gif',
            'adImage' => '/public/images/300x250_retailbanner.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/retail-featured-content.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/foreign-edu-scholarship.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/foreignedu-feautedcontent.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
		    'messageBoardPosition' => 'right',
		    'id'=>'1',
		    'name'=>'India',
		    'headerName'=>'India'
        ),
        'hospitality' => array(           
            'page' => 'HOSPITALITY_PAGE',
            'product'=>'catgeory_hospitality',
            'displayName' => '<span style="line-height:28px">Hospitality <img src="/public/images/seprator.gif" align="absmiddle"/><span style="font-size:12px;"> Aviation &amp; Tourism</span></span>',
            'rightImage' => '/public/images/topheader-hospi2.jpg',
            'leftImage' => '/public/images/topheader-hospi.gif',
            'adImage' => '/public/images/300x250_hospi.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/impdates-hospi.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/featured-schol-hospi.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/featured-content-hospi.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'6',
			'name'=>'Hospitality, Tourism and Aviation',
			'headerName'=>'Hospitality'
        ),
        'media' => array(            
            'page' => 'MEDIA_MASS_COMM_PAGE',
            'product'=>'catgeory_media',
            'displayName' => '<span style="line-height:28px">Media<img src="/public/images/seprator.gif" align="absmiddle"/><span style="font-size:12px;">Films &amp; Mass Communication</span></span>',
            'rightImage' => '/public/images/header-top-media2.jpg',
            'leftImage' => '/public/images/header-top-media.gif',
            'adImage' => '/public/images/bannner300x250_media.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/impdates-media.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/schol-media.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/featured-content-media.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'7',
			'name'=>'Media, Films, Mass Communications',
			'headerName'=>'Media'
        ),
        'professionals' => array(
            'page' => 'PROFESSIONAL_PAGE',
            'product'=>'catgeory_professional',
            'displayName' => '<span style="line-height:28px">Professional Courses</span>',
            'rightImage' => '/public/images/courses-header2.jpg',
            'leftImage' => '/public/images/courses-header1.gif',
            'adImage' => '/public/images/350x250_bannercourses.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/impdates-pc.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/scol-pc.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/featured-contentpc.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'8',
			'name'=>'Professional Courses',
			'headerName'=>'Professional Courses'
        ),
        'distance' => array(
            'page' => 'ONLINE_PAGE',
            'product'=>'catgeory_online',
            'displayName' => '<span style="line-height:28px">Distance Learning and e-Learning</span>',
            'rightImage' => '/public/images/elarning-head2.jpg',
            'leftImage' => '/public/images/elarning-head1.gif',
            'adImage' => '/public/images/300x250_elarnbanner.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/impdates-elarn.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/featured-schol-elearn.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/feacontent-elearn.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'1',
			'name'=>'Distance Learning',
			'headerName'=>'Distance Learning'
        ),
        'health' => array(
            'page' => 'BEAUTY_PAGE',
            'product'=>'catgeory_beauty',
            'displayName' => '<span style="line-height:28px">Health and Beauty</span>',
            'rightImage' => '/public/images/health-tophead.jpg',
            'leftImage' => '/public/images/fruits-topheader.gif',
            'adImage' => '/public/images/300x250_healthbanner.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/impdates-healthb.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/schol-healthbeauty.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/feaut-content.jpg',
            'newsPosition' => 'left',
			'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'1',
			'name'=>'Health and Beauty',
			'headerName'=>'Health and Beauty'
        ),
        'animation' => array(
            'page' => 'ANIMATION_PAGE',
            'product'=>'catgeory_animation',
            'displayName' => '<span style="line-height:28px">Animation, Visual Effects, Gaming &amp; Comics (AVGC)</span>',
            'rightImage' => '/public/images/animation2.jpg',
            'leftImage' => '/public/images/animation1.gif',
            'adImage' => '/public/images/banner-it300x250.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/impdates.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/featured-schol-ani.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/featured-content-ani.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'12',
			'name'=>'Animation, Multimedia',
			'headerName' => 'Animation, Multimedia'
        ),
        'science' => array(
            'page' => 'SCIENCE_ENGINEERING_PAGE',
            'product'=>'catgeory_science',
            'displayName' => '<span style="line-height:28px">Science &amp; Engineering</span>',
            'rightImage' => '/public/images/topheader-sceng2.jpg',
            'leftImage' => '/public/images/topheader-sceng.gif',
            'adImage' => '/public/images/300x250-bannersceng.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Events',
            'eventsImage' => '/public/images/scie-impdates.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/schol-scieneng.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Contents',
            'newsImage' => '/public/images/featured-cotentsceng.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'2',
			'name'=>'Science and Engineering',
			'headerName' => 'Science and Engineering'
        ),
        'medicine' => array(              
            'page' => 'HEALTH_MEDICINE_PAGE',
            'product'=>'catgeory_medicine',
            'displayName' => '<span style="line-height:28px">Medicine <img src="/public/images/seprator.gif" align="absmiddle"/><span style="font-size:12px;"> Beauty &amp; Health Care</span></span>',
            'rightImage' => '/public/images/header-top-health2.jpg',
            'leftImage' => '/public/images/header-top-health.gif',
            'adImage' => '/public/images/300x250_heathbanner.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/impdates-health.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/featured-schol-health.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/featured-content-health.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'5',
			'name'=>'Medicine and Health Care',
			'headerName'=>'Medicine and Health Care'
        ),
        'legal' => array(
            'page' => 'LEGAL_PARALEGAL_PAGE',
            'product'=>'catgeory_legal',
            'displayName' => '<span style="line-height:28px">Legal and Paralegal</span>',
            'rightImage' => '/public/images/leagal-header2.jpg',
            'leftImage' => '/public/images/leagal-header1.gif',
            'adImage' => '/public/images/300x250_lega.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/dates-legal.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/featured-schol-legal.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/legal-content.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'1',
			'name'=>'Legal and Paralegal',
			'headerName'=>'Legal and Paralegal'
        ),
        'education' => array(
            'page' => 'EDUCATION_TEACHING_PAGE',
            'product'=>'catgeory_education',
            'displayName' => '<span style="line-height:28px">Education and Teaching</span>',
            'rightImage' => '/public/images/header-edcuation2.jpg',
            'leftImage' => '/public/images/header-edcuation1.gif',
            'adImage' => '/public/images/300x250_banner.jpg',
            'collegeCaption' => 'Featured Colleges',
            'eventsCaption' => 'Featured Content',
            'eventsImage' => '/public/images/impdates-edu.jpg',
            'eventsPosition' => 'left',
            'scholarshipCaption' => 'Featured Scholarships',
            'scholarshipImage' => '/public/images/featured-scholedu.jpg',
            'scholarshipPosition' => 'right',
            'newsCaption' => 'Featured Content',
            'newsImage' => '/public/images/featured-cont-edu.jpg',
            'newsPosition' => 'left',
            'messageBoardCaption' => 'Ask & Discuss',
			'messageBoardPosition' => 'right',
			'id'=>'1',
			'name'=>'Education',
			'headerName'=>'Education'
        ),
    );
    
    global $categoryParentMap;
    $categoryParentMap=array(	
    	'Animation, Visual Effects, Gaming & Comics (AVGC)' => array(
				'id'=> '12',
				'page' => 'ANIMATION_PAGE',
                'url'=> 'animation'
            ),
		'Arts, Law, Languages and Teaching' => array(
                'id'=> '9',
				'page' => 'LANGUAGES_PAGE',
                'url'=> 'arts'
            ),
		'Banking & Finance' => array(
                'id'=> '4',
				'page' => 'BANKING_FINANCE_PAGE',
                'url'=> 'banking'
            ),
		'Hospitality, Aviation & Tourism' => array(
                'id'=> '6',
				'page' => 'HOSPITALITY_PAGE',
                'url'=> 'hospitality'
            ),
		'Information Technology' => array(
                'id'=> '10',
				'page' => 'IT_PAGE',
                'url'=> 'it'
            ),
		'Management' => array(
                'id'=> '3',
                'page' => 'MANAGEMENT_PAGE',
                'url'=> 'management'
                ),
		'Media, Films & Mass Communication' => array(
                'id'=> '7',
				'page' => 'MEDIA_MASS_COMM_PAGE',
                'url'=> 'media'
            ),
    	'Medicine, Beauty & Health Care' => array(
                'id'=> '5',
				'page' => 'HEALTH_MEDICINE_PAGE',
                'url'=> 'medicine'
            ),
		'Retail' => array(
                'id'=> '11',
				'page' => 'RETAIL_PAGE',
                'url'=> 'retail'
            ),
		'Science & Engineering' => array(
                'id'=> '2',
				'page' => 'SCIENCE_ENGINEERING_PAGE',
                'url'=> 'science'
            ),
		'Design' => array(
                'id'=> '13',
		        'page' => 'DESIGN_PAGE',
                'url'=> 'design'
            ),
		'Test Preparation' => array(
                'id'=> '14',
		        'page' => 'TESTPREP_PAGE',
                'url'=> 'testprep'
            ),
        'Miscellaneous' => array(
            'id'=> '0',
            'page'=> 'MISCELLANEOUS_PAGE',
            'url'=> 'miscellaneous'
            ),
    );
	
	global $miscellaneousCatId;
	$miscellaneousCatId = 0;	
 
    global $parentCategoryMap;
    $parentCategoryMap = array( 
					'science'=> 2,
					'retail'=> 11,
					'medicine'=> 5,
					'masscom'=> 7,
					'management'=> 3,
					'it'=> 10,
					'hospitality'=> 6,
					'banking'=> 4,
					'arts'=> 9,
					'animation'=> 12,
					'design' => 13,
					'testprep' => 14
			);

    global $testprepMap;
 
    $testprepMap = array(
				'Govt' => 'Government Sector Examinations',
				'Medical' => 'Medical Exams',
				'Engineering' => 'Engineering Exams',
				'MBA' => 'MBA  Exams',
				'Foreign' => 'Foreign Education Exams',
			);