<?php

$shikshaCountryMap = array(
2 =>  array('name' => 'India', 'region' => 0),
3 =>  array('name' => 'USA', 'region' => 0),
4 =>  array('name' => 'UK', 'region' => 4),
5 =>  array('name' => 'Australia', 'region' => 0),
6 =>  array('name' => 'Singapore', 'region' => 1),
7 =>  array('name' => 'New Zealand', 'region' => 5),
8 =>  array('name' => 'Canada', 'region' => 0),
9 =>  array('name' => 'Germany', 'region' => 2),
10 =>  array('name' => 'Malaysia', 'region' => 1),
11 =>  array('name' => 'Sweden', 'region' => 2),
12 =>  array('name' => 'France', 'region' => 2),
13 =>  array('name' => 'Switzerland', 'region' => 2),
14 =>  array('name' => 'Holland', 'region' => 2),
15 =>  array('name' => 'Denmark', 'region' => 2),
16 =>  array('name' => 'Spain', 'region' => 2),
17 =>  array('name' => 'Russia', 'region' => 2),
18 =>  array('name' => 'UAE', 'region' => 3),
19 =>  array('name' => 'Qatar', 'region' => 3),
20 =>  array('name' => 'Saudi Arabia', 'region' => 3),
21 =>  array('name' => 'Ireland', 'region' => 4),
23 =>  array('name' => 'Finland', 'region' => 2),
22 =>  array('name' => 'Italy', 'region' => 2),
24 =>  array('name' => 'Slovakia', 'region' => 2),
25 =>  array('name' => 'Poland', 'region' => 2),
26 =>  array('name' => 'Portugal', 'region' => 2),
27 =>  array('name' => 'Norway', 'region' => 2),
28 =>  array('name' => 'Kuwait', 'region' => 3),
29 =>  array('name' => 'Oman', 'region' => 3),
30 =>  array('name' => 'Japan', 'region' => 6),
31 =>  array('name' => 'Thailand', 'region' => 1),
32 =>  array('name' => 'Belgium', 'region' => 2),
33 =>  array('name' => 'Armenia', 'region' => 2),
34 =>  array('name' => 'Iceland', 'region' => 2),
35 =>  array('name' => 'Fiji', 'region' => 5),
36 =>  array('name' => 'China', 'region' => 7),
37 =>  array('name' => 'North Korea', 'region' => 6),
38 =>  array('name' => 'South Korea', 'region' => 6),
39 => array('name' => 'Taiwan', 'region' => 7),
40 => array('name' => 'Greece', 'region' => 2),
41 => array('name' => 'Mauritius', 'region' => 8),
42 => array('name' => 'Estonia', 'region' => 2),
43 => array('name' => 'Luxembourg', 'region' => 2),
44 => array('name' => 'Ukraine', 'region' => 2),
45 => array('name' => 'South Africa', 'region' => 8),
46 => array('name' => 'Hungary', 'region' => 2),
47 => array('name' => 'Austria', 'region' => 2),
48 => array('name' => 'Slovenia', 'region' => 2),
49 => array('name' => 'Philippines', 'region' => 1),
50 => array('name' => 'Cyprus', 'region' => 2),
51 => array('name' => 'Bangladesh', 'region' => 1),
52 => array('name' => 'United Kingdom', 'region' => 2),
53 => array('name' => 'Lithuania', 'region' => 2),
54 => array('name' => 'Monaco', 'region' => 2),
55 => array('name' => 'Nepal', 'region' => 1),
56 => array('name' => 'Georgia', 'region' => 2)
);