<?php
/*
   Copyright 2014 Info Edge India Ltd

   $Author: Pranjul

   $Id: CollegePredictorConfig.php
*/

//class CollegePredictorConfig{
     // associative array stores static details for the exams
     //global $settings;
     $config =
 array('settings'=>array(
      'tabNames'=>array(
                'DESKTOP' =>array('JEE-MAINS'=>array('Find college and branch for your rank','Know cut-offs of a college','Want a branch? Know all the colleges')),
                'MOBILE5' =>array('JEE-MAINS'=>array('Find college and branch for your rank','Know cut-offs of a college','Want a branch? Know all the colleges'))
                ),
      'defaultTabInfo'=>array(
                'DESKTOP' =>array(
                          'JEE-MAINS'=>array('rankType'=>'Other','categoryName'=>'GEN','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'JEE-Mains','tabType'=>'rank'),
                          'KCET'=>array('rankType'=>'KCETGeneral','categoryName'=>'GM','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'KCET','tabType'=>'rank','stateName'=>'Karnataka'),
                          'COMEDK'=>array('rankType'=>'Home','categoryName'=>'GM','domicile'=>'NO','rank'=>1,'round'=>'2','examName'=>'COMEDK','tabType'=>'rank','stateName'=>'Karnataka'),
                          'KEAM'=>array('rankType'=>'Home','categoryName'=>'SM','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'KEAM','tabType'=>'rank','stateName'=>'Kerala'),
                          'WBJEE'=>array('rankType'=>'Other','categoryName'=>'OP','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'WBJEE','tabType'=>'rank','stateName'=>'West Bengal'),
                          'MPPET'=>array('rankType'=>'Other','categoryName'=>'UR','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'MPPET','tabType'=>'rank','stateName'=>'Madhya Pradesh'),
                          'CGPET'=>array('rankType'=>'Home','categoryName'=>'UR','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'CGPET','tabType'=>'rank','stateName'=>'Chhattisgarh'),
                          'TNEA'=>array('rankType'=>'Home','categoryName'=>'OC','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'TNEA','tabType'=>'rank','stateName'=>'Tamil Nadu'),
                          'PTU'=>array('rankType'=>'Other','categoryName'=>'GEN','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'PTU','tabType'=>'rank','stateName'=>'Punjab'),
                          'UPSEE'=>array('rankType'=>'Other','categoryName'=>'GNOP','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'UPSEE','tabType'=>'rank','stateName'=>'Uttar Pradesh'),
                           'MHCET'=>array('rankType'=>'Other','categoryName'=>'GOPEN','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'MHCET','tabType'=>'rank','stateName'=>'Maharashtra'),
                            'HSTES'=>array('rankType'=>'Home','categoryName'=>'AIC','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'HSTES','tabType'=>'rank','stateName'=>'Haryana'),
                            'AP-EAMCET'=>array('rankType'=>'Home','categoryName'=>'OC','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'AP-EAMCET','tabType'=>'rank','stateName'=>'Andhra Pradesh'),
                            'TS-EAMCET'=>array('rankType'=>'Home','categoryName'=>'OC','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'TS-EAMCET','tabType'=>'rank','stateName'=>'Telangana'),
                            'BITSAT'=>array('rankType'=>'Other','categoryName'=>'GEN','domicile'=>'NO','rank'=>400,'round'=>'1','examName'=>'BITSAT','tabType'=>'rank','invertLogic' => 1),
                            'GGSIPU'=>array('rankType'=>'Other','categoryName'=>'GNGNA','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'GGSIPU','tabType'=>'rank','stateName'=>'Delhi'),
                            'OJEE'=>array('rankType'=>'Home','categoryName'=>'JEE_M','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'OJEE','tabType'=>'rank','stateName'=>'Odisha'),
                            'GUJCET'=>array('rankType'=>'Home','categoryName'=>'GEN','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'GUJCET','tabType'=>'rank','stateName'=>'Gujarat'),
                            'NIFT'=>array('rankType'=>'Other','categoryName'=>'GEN','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'NIFT','tabType'=>'rank'),
                            'NCHMCT'=>array('rankType'=>'Other','categoryName'=>'GEN','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'NCHMCT','tabType'=>'rank'),
                            'MAHCET'=>array('rankType'=>'Home','categoryName'=>'GEN','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'MAHCET','tabType'=>'rank','stateName'=>'Maharashtra'),
                            'CLAT'=>array('rankType'=>'Other','categoryName'=>'OC','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'CLAT','tabType'=>'rank')
                          ),
                'MOBILE5' =>array(
                            'JEE-MAINS'=>array('rankType'=>'Other','categoryName'=>'GEN','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'JEE-Mains','tabType'=>'rank'),
                            'KCET'=>array('rankType'=>'KCETGeneral','categoryName'=>'GM','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'KCET','tabType'=>'rank','stateName'=>'Karnataka'),
                            'COMEDK'=>array('rankType'=>'Home','categoryName'=>'GM','domicile'=>'NO','rank'=>1,'round'=>'2','examName'=>'COMEDK','tabType'=>'rank','stateName'=>'Karnataka'),
                            'KEAM'=>array('rankType'=>'Home','categoryName'=>'SM','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'KEAM','tabType'=>'rank','stateName'=>'Kerala'),
                            'WBJEE'=>array('rankType'=>'Other','categoryName'=>'OP','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'WBJEE','tabType'=>'rank','stateName'=>'West Bengal'),
                            'MPPET'=>array('rankType'=>'Other','categoryName'=>'UR','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'MPPET','tabType'=>'rank','stateName'=>'Madhya Pradesh'),
                            'CGPET'=>array('rankType'=>'Home','categoryName'=>'UR','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'CGPET','tabType'=>'rank','stateName'=>'Chhattisgarh'),
                            'TNEA'=>array('rankType'=>'Home','categoryName'=>'OC','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'TNEA','tabType'=>'rank','stateName'=>'Tamil Nadu'),
                            'PTU'=>array('rankType'=>'Other','categoryName'=>'GEN','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'PTU','tabType'=>'rank','stateName'=>'Punjab'),
                            'UPSEE'=>array('rankType'=>'Other','categoryName'=>'GNOP','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'UPSEE','tabType'=>'rank','stateName'=>'Uttar Pradesh'),
                            'MHCET'=>array('rankType'=>'Other','categoryName'=>'GOPEN','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'MHCET','tabType'=>'rank','stateName'=>'Maharashtra'),
                            'HSTES'=>array('rankType'=>'Home','categoryName'=>'AIC','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'HSTES','tabType'=>'rank','stateName'=>'Haryana'),
                            'AP-EAMCET'=>array('rankType'=>'Home','categoryName'=>'OC','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'AP-EAMCET','tabType'=>'rank','stateName'=>'Andhra Pradesh'),
                            'TS-EAMCET'=>array('rankType'=>'Home','categoryName'=>'OC','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'TS-EAMCET','tabType'=>'rank','stateName'=>'Telangana'),
                            'OJEE'=>array('rankType'=>'Home','categoryName'=>'JEE_M','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'OJEE','tabType'=>'rank','stateName'=>'Odisha'),
                            'BITSAT'=>array('rankType'=>'Other','categoryName'=>'GEN','domicile'=>'NO','rank'=>400,'round'=>'1','examName'=>'BITSAT','tabType'=>'rank','invertLogic' => 1),
                            'GGSIPU'=>array('rankType'=>'Other','categoryName'=>'GNGNA','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'GGSIPU','tabType'=>'rank','stateName'=>'Delhi'),
                            'GUJCET'=>array('rankType'=>'Home','categoryName'=>'GEN','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'GUJCET','tabType'=>'rank','stateName'=>'Gujarat'),
                            'NIFT'=>array('rankType'=>'Other','categoryName'=>'GEN','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'NIFT','tabType'=>'rank'),
                            'NCHMCT'=>array('rankType'=>'Other','categoryName'=>'GEN','domicile'=>'NO','rank'=>1,'round'=>'1','examName'=>'NCHMCT','tabType'=>'rank'),
                            'MAHCET'=>array('rankType'=>'Other','categoryName'=>'GEN','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'MAHCET','tabType'=>'rank'),
                            'CLAT'=>array('rankType'=>'Other','categoryName'=>'OC','domicile'=>'NO','rank'=>1,'round'=>'all','examName'=>'CLAT','tabType'=>'rank')

                          ),
                ),
      'JEE-MAINS'=>array(
                    'tab'=>array(
		     'rank'=>array('heading'=>'JEE Main College Predictor '.date('Y').' - Updated with JoSAA '.date('Y').' closing ranks','imageTitle'=>'JEE MAINS college predictor'),	    
		    'college'=>array('heading'=>'College Cut-off JEE Main '.date('Y'),'imageTitle'=>'JEE MAINS cut off predictor'),
                    'branch'=>array('heading'=>'JEE Main '.date('Y').' Branch Predictor','imageTitle'=>'JEE MAINS branch predictor'),
                    ),
                'notice'=>'Prediction of colleges is based on JEE Main '.(date('Y') - 1).' closing ranks.',
                'mailerSubject'=>'JEE Main '.date('Y').' College Predictor',
                'showFilters'=>'YES',
                            'showFiltersOnMobile'=>'YES',
                'showSorting'=>'YES',
                'showInvite'=>'YES',
                'showEmail'=>'YES',
                'showPrint'=>'YES',
                'showFeeback'=>'YES',
                'showKnowYourRank' => 'YES',
                'examName' => 'JEE-Mains',
                'totalRound' =>7,
                'examYear'=>date('Y'),
                            'showRankType'=>'YES',
                            'rankType'=>'Other',
                            'stateName'=>'',
                            'inputType'=>'Rank',
                            'categoryData'=>array('GEN'=>'General','OBC'=>'OBC','SC'=>'SC','ST'=>'ST','PWD' => 'PWD'),
                            'roundData'=>array('1'=>'Round 1','2'=>'Round 2','3'=>'Round 3','4'=>'Round 4','5'=>'Round 5','6'=>'Round 6','7'=>'Round 7'),
                            'examNameForResultText'=>'JEE-Main',
                            'seo_title_exam_name'=>'JEE Main',
                            'seo_description_exam_name'=>'JEE Main',
                            'seo_description' => "Predict colleges you can admission in using your JEE Main ".date('Y')." rank.  Compare 800+ colleges (including IITs, NITs and IIITs)  and the Cut off, Fees and Placements of 3500+ courses using Shiksha JEE Main College Predictor ".date('Y'),

                            'overDetails'=>
                                        array(
                                            'markHeading'=>'Expected Marks in JEE Main 2017',
                                            'rankHeading'=>'Rank in JEE Main 2017*',
                                            'mapping'=>
                                                array(
                                                '&gt; 342'=>'In Top 10',
                                                '331 - 342'=>'11 - 20',
                                                '318 - 330'=>'21 - 50',
                                                '306 - 317'=>'51 - 100',
                                                '295 - 305'=>'101 - 200',
                                                '284 - 294'=>'201 - 500',
                                                '269 - 283'=>'501 - 1000',
                                                '243 - 268'=>'1001 - 2000',
                                                '226 - 242'=>'2001 - 5000',
                                                '201 - 225'=>'5001 - 10000',
                                                '181 - 200'=>'10001 - 20000',
                                                '157 - 180'=>'20001 - 35000',
                                                '134 - 156'=>'35001 - 50000',
                                                '118 - 133'=>'50001 - 75000',
                                                '&lt; 118'=>'&gt; 75000',
                                                ),
                                            'notice'=>'*If Ranks would have been given based on only JEE (Main) Marks.'
                                        ),
                'iitsCourseIds'=> array(110648 => 1,204533 => 1,110636 => 1,110653 => 1,110649 => 1,110652 => 1,110654 => 1,204537 => 1,110647 => 1,110643 => 1,110645 => 1,110639 => 1,110655 => 1,204550 => 1,234918 => 1,204536 => 1,204544 => 1,110641 => 1,204548 => 1,110642 => 1,110656 => 1,290278 => 1,290910 => 1,204541 => 1,172501 => 1,200649 => 1,200619 => 1,188738 => 1,172499 => 1,235408 => 1,235409 => 1,172502 => 1,188736 => 1,188737 => 1,16559 => 1,16562 => 1,251121 => 1,251118 => 1,172507 => 1,188739 => 1,188740 => 1,290230 => 1,290243 => 1,290257 => 1,234823 => 1,329015 => 1,253922 => 1,129934 => 1,329017 => 1,129937 => 1,253924 => 1,329019 => 1,253925 => 1,129932 => 1,253926 => 1,328987 => 1,253906 => 1,253927 => 1,329021 => 1,109575 => 1,109580 => 1,292450 => 1,292445 => 1,251681 => 1,109615 => 1,292468 => 1,109565 => 1,329023 => 1,109549 => 1,292444 => 1,109569 => 1,292465 => 1,109606 => 1,292470 => 1,292469 => 1,329025 => 1,292356 => 1,110582 => 1,204299 => 1,252103 => 1,236952 => 1,172244 => 1,189266 => 1,8300 => 1,8363 => 1,252102 => 1,204289 => 1,110580 => 1,172247 => 1,252101 => 1,204285 => 1,8368 => 1,290638 => 1,290640 => 1,290642 => 1,293993 => 1,129867 => 1,129872 => 1,129864 => 1,202891 => 1,202894 => 1,290152 => 1,290153 => 1,290150 => 1,8427 => 1,188685 => 1,8430 => 1,8501 => 1,172471 => 1,109687 => 1,252819 => 1,109684 => 1,109682 => 1,8423 => 1,130009 => 1,329027 => 1,130010 => 1,130011 => 1,186957 => 1,234882 => 1,186956 => 1,136148 => 1,234884 => 1,193085 => 1,193090 => 1,193094 => 1,291288 => 1,291291 => 1,290197 => 1,290199 => 1,290200 => 1,290198 => 1,329029 => 1,129913 => 1,129914 => 1,129912 => 1,329031 => 1,109925 => 1,292377 => 1,109932 => 1,176829 => 1,172233 => 1,109900 => 1,109917 => 1,73837 => 1,292381 => 1,172227 => 1,109916 => 1,292370 => 1,292390 => 1,7978 => 1,292822 => 1,10734 => 1,112406 => 1,297637 => 1,292900 => 1,292842 => 1,292382 => 1,112411 => 1,112409 => 1,292910 => 1,7977 => 1,7973 => 1,112410 => 1,297636 => 1,292904 => 1,7976 => 1,292828 => 1,7975 => 1,112412 => 1,112413 => 1,292913 => 1,292823 => 1,292915 => 1,292905 => 1,7974 => 1,297638 => 1,292829 => 1,112414 => 1,236761 => 1,297639 => 1,293012 => 1,292834 => 1,297643 => 1,172198 => 1,293009 => 1,297635 => 1,293006 => 1,90880 => 1,90886 => 1,199846 => 1,90899 => 1,235025 => 1,235150 => 1,8158 => 1,8270 => 1,329043 => 1,199872 => 1,199854 => 1,199817 => 1,8280 => 1,90893 => 1,199821 => 1,199811 => 1,199867 => 1,90894 => 1,199871 => 1,346229 => 1,134605 => 1,134606 => 1,134607 => 1,274330 => 1,290597 => 1,290599 => 1,290601 => 1,290594 => 1,129822 => 1,129817 => 1,129823 => 1,202852 => 1,202851 => 1,110247 => 1,110246 => 1,110242 => 1,185327 => 1,172258 => 1,110215 => 1,252581 => 1,110224 => 1,110210 => 1,172265 => 1,172260 => 1,273987 => 1,252585 => 1,273985 => 1,110223 => 1,273988 => 1,8343 => 1,129799 => 1,129800 => 1,129801 => 1,252686 => 1,293958 => 1,273688 => 1,329261 => 1,290827 => 1,290855 => 1,290883 => 1,290723 => 1,329271 => 1),
                'showHomeState' => 1,
            ),
          'KCET'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'KCET '.date('Y').' College Predictor','seoTitle'=>'KCET College Predictor '.date('Y').' – Which Colleges will you get Admission in using KCET Rank/Score?','imageTitle'=>'KCET college predictor'),
                                            'college'=>array('heading'=>'College Cut-off KCET '.date('Y'),'imageTitle'=>'KCET cut off predictor'),
                                            'branch'=>array('heading'=>'KCET '.date('Y').' Branch Predictor','imageTitle'=>'KCET branch predictor'),
                                ),
                                    'notice'=>'Prediction for KCET 2017 is based on KCET 2016 closing ranks.',
                                    'mailerSubject'=>'KCET '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'YES',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'HyderabadKarnatakaQuota',
                                    'stateName'=>'Karnataka',
                                    'examName'=>'KCET',
                                    'examYear'=>date('Y'),
                                    'totalRound' =>2,
                                    'roundData'=>array('1'=>'Round 1' ,'2' =>"Round 2"),
                                    'noStateDropDown'=>1,
                                    'categoryData'=>array('1G'=>'Category 1 General','1K'=>'Category 1 Kannada','1R'=>'Category 1 Rural','2AG'=>'Category 2 General','2AK'=>'Category 2 Kannada','2AR'=>'Category 2 Rural','2BG'=>'Category 2 General','2BK'=>'Category 2 Kannada','2BR'=>'Category 2 Rural','3AG'=>'Category 3 General','3AK'=>'Category 3 Kannada','3AR'=>'Category 3 Rural','3BG'=>'Category 3 General','3BK'=>'Category 3 Kannada','3BR'=>'Category 3 Rural','GM'=>'General Merit','GMK'=>'General Merit Kannada','GMR'=>'General Merit Rural','SCG'=>'SC General','SCK'=>'SC Kannada','SCR'=>'SC Rural','STG'=>'ST  General','STK'=>'ST  Kannada','STR'=>'ST  Rural','1H'=>'Category 1 General- HYD/KN','1KH'=>'Category 1 Kannada- HYD/KN','1RH'=>'Category 1 Rural- HYD/KN','2AH','Category 2 General- HYD/KN','2AKH'=>'Category 2 Kannada- HYD/KN','2ARH'=>'Category 2 Rural- HYD/KN','2BH'=>'Category 2 General- HYD/KN','2BKH'=>'Category 2 Kannada- HYD/KN','2BRH'=>'Category 2 Rural- HYD/KN','3AH'=>'Category 3 General- HYD/KN','3AKH'=>'Category 3 Kannada- HYD/KN','3ARH'=>'Category 3 Rural- HYD/KN','3BH'=>'Category 3 General- HYD/KN','3BKH'=>'Category 3 Kannada- HYD/KN','3BRH'=>'Category 3 Rural- HYD/KN','GMH'=>'General Merit - HYD/KN','GMKH'=>'General Merit Kannada- HYD/KN','GMRH'=>'General Merit Rural- HYD/KN','SCH'=>'SC General- HYD/KN','SCKH'=>'SC Kannada- HYD/KN','SCRH
'=>'SC Rural- HYD/KN','STH'=>'ST  General- HYD/KN','STKH'=>'ST  Kannada- HYD/KN','STRH'=>'ST  Rural- HYD/KN'),
                                    'examNameForResultText'=>'KCET',
                                    'seo_title_exam_name'=>'KCET',
                                    'seo_description_exam_name'=>'KCET',
                                    'seo_description' =>  'KCET College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your KCET '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via KCET '.date('Y').' exam.',
                                    'inputType'=>'Rank'

                    ),
                  'KEAM'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'KEAM '.date('Y').' College Predictor','seoTitle'=>'KEAM College Predictor '.date('Y').' – Which Colleges will you get Admission in using KEAM Rank/Score?','imageTitle'=>'KEAM college predictor'),
                                            'college'=>array('heading'=>'College Cut-off KEAM '.date('Y'),'imageTitle'=>'KEAM cut off predictor'),
                                            'branch'=>array('heading'=>'KEAM '.date('Y').' Branch Predictor','imageTitle'=>'KEAM branch predictor'),
                        ),
                                    'notice'=>'Prediction for KEAM 2018 is based on KEAM 2017 closing ranks.',
                                    'mailerSubject'=>'KEAM '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'NO',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'HOME',
                                    'stateName'=>'Kerala',
                                    'examName'=>'KEAM',
                                    'examYear'=>date('Y'),
                                    'noStateDropDown'=>1,
                                    'categoryData'=>array('SM'=>'SM - State Merit','EZ'=>'EZ - Ezhava Sub Category','MU'=>'MU - Muslim','BH'=>'BH - Other Backward Hindu','LA'=>'LA - Latin Catholic and Anglo Indian','DV'=>'DV - Dheevara and related communities','VK'=>'VK - Viswakarma and related communities','BX'=>'BX - Other Backward Christian','KU'=>'KU - Kudumbi','KN'=>'KN - Kusavan and related communities','SC'=>'SC - Scheduled Castes','ST'=>'ST - Scheduled Tribes','MG'=>'MG-Management Quota'),
                                    'roundData'=>array('1'=>'Round 1','2'=>'Round 2' ,'3'=>'Round 3'),
                                    'examNameForResultText'=>'KEAM',
                                    'seo_title_exam_name'=>'KEAM',
                                    'seo_description_exam_name'=>'KEAM',
                                    'seo_description' =>'KEAM College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your KEAM '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via KEAM '.date('Y').' exam.',
                                    'totalRound' => 3,
                                    'inputType'=>'Rank',

                    ),
                  
          'COMEDK'=>array(
                    'tab'=> array(
                                            'rank'=>array('heading'=>'COMEDK '.date('Y').' College Predictor','seoTitle'=>'COMEDK College Predictor '.date('Y').' – Which Colleges will you get Admission in using COMEDK Rank/Score?','imageTitle'=>'COMEDK college predictor'),
                                            'college'=>array('heading'=>'College Cut-off COMEDK '.date('Y'),'imageTitle'=>'COMEDK cut off predictor'),
                                            'branch'=>array('heading'=>'COMEDK '.date('Y').' Branch Predictor','imageTitle'=>'COMEDK branch predictor'),
                        ),
                                    'notice'=>'Prediction for COMEDK 2017 is based on COMEDK 2016 closing ranks.',
                                    'mailerSubject'=>'COMEDK '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'NO',
                                    'showKnowYourRank' => 'YES',
                                    'rankType'=>'HOME',
                                    'stateName'=>'Karnataka',
                                    'examName'=>'COMEDK',
                                    'noStateDropDown'=>1,
                                    'examYear'=>date('Y'),
                                    'categoryData'=>array('GM'=>'General Merit','HK'=>'Hyderabad Karnataka','CHR' =>"Christian Religion" ,"TLU" =>'Telugu'),
                                    'roundData'=>array('1'=>'Round 1' ,'2' =>"Round 2"),
                                    'examNameForResultText'=>'COMEDK',
                                    'seo_title_exam_name'=>'COMEDK',
                                    'seo_description_exam_name'=>'COMEDK',
                                    'seo_description' =>'COMEDK College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your COMEDK '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via COMEDK '.date('Y').' exam.',
                                    'inputType'=>'Rank',

                                    'overDetails'=>
                                        array(
                                        ),
                        'totalRound' =>2,
),
                  'WBJEE'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'WBJEE '.date('Y').' College Predictor','seoTitle'=>'WBJEE College Predictor '.date('Y').' – Which Colleges will you get Admission in using WBJEE Rank/Score?','imageTitle'=>'WBJEE college predictor'),
                                            'college'=>array('heading'=>'College Cut-off WBJEE '.date('Y'),'imageTitle'=>'WBJEE cut off predictor'),
                                            'branch'=>array('heading'=>'WBJEE '.date('Y').' Branch Predictor','imageTitle'=>'WBJEE branch predictor'),
                        ),
                                    'notice'=>'Prediction for WBJEE 2018 is based on WBJEE 2017 closing ranks.',
                                    'mailerSubject'=>'WBJEE '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'Yes',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'Home',
                                    'stateName'=>'West Bengal',
                                    'noStateDropDown'=>1,
                                    'examName'=>'WBJEE',
                                    'examYear'=>date('Y'),
                                    'categoryData'=>array('OP'=>'OP','PWD'=>'PWD','SC'=>'SC','ST'=>'ST','OBC'=>'OBC'),
                                    'roundData'=>array('1'=>'Round 1','2'=>'Round 2'),
                                    'examNameForResultText'=>'WBJEE',
                                    'seo_title_exam_name'=>'WBJEE',
                                    'seo_description_exam_name'=>'WBJEE',
                                    'seo_description' =>'WBJEE College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your WBJEE '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via WBJEE '.date('Y').' exam.',
                                    'totalRound' => 2,
                                    'inputType'=>'Rank'

                    ),
  'MPPET'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'MPPET '.date('Y').' College Predictor','seoTitle'=>'MPPET College Predictor '.date('Y').' – Which Colleges will you get Admission in using MPPET Rank/Score?','imageTitle'=>'MPPET college predictor'),
                                            'college'=>array('heading'=>'College Cut-off MPPET '.date('Y'),'imageTitle'=>'MPPET cut off predictor'),
                                            'branch'=>array('heading'=>'MPPET '.date('Y').' Branch Predictor','imageTitle'=>'MPPET branch predictor'),
                        ),
                                    'notice'=>'Prediction for MPPET 2018 is based on MPPET 2017 closing ranks.',
                                    'mailerSubject'=>'MPPET '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'YES',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'Other',
                                    'stateName'=>'Madhya Pradesh',
                                    'examName'=>'MPPET',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 2,
                                    'noStateDropDown'=>1,
                                    'categoryData'=>array('GN'=>'UR','OBC'=>'OBC','SC'=>'SC','ST'=>'ST'),
                                    'roundData'=>array('1'=>'Round 1' ,'2' => 'Round 2'),
                                    'examNameForResultText'=>'MPPET',
                                    'seo_title_exam_name'=>'MPPET',
                                    'seo_description_exam_name'=>'MPPET',
                                    'seo_description' =>'MPPET College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your MPPET '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via MPPET '.date('Y').' exam.',
                                    'inputType'=>'Rank'

                    ),
  'CGPET'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'CGPET '.date('Y').' College Predictor','seoTitle'=>'CGPET College Predictor '.date('Y').' – Which Colleges will you get Admission in using CGPET Rank/Score?','imageTitle'=>'CGPET college predictor'),
                                            'college'=>array('heading'=>'College Cut-off CGPET '.date('Y'),'imageTitle'=>'CGPET cut off predictor'),
                                            'branch'=>array('heading'=>'CGPET '.date('Y').' Branch Predictor','imageTitle'=>'CGPET branch predictor'),
                        ),
                                    'notice'=>'Prediction for CGPET '.date('Y').' is based on CGPET '.(date('Y')-1).' closing ranks.',
                                    'mailerSubject'=>'CGPET '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'NO',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'HOME',
                                    'stateName'=>'Chhattisgarh',
                                    'noStateDropDown'=>1,
                                    'examName'=>'CGPET',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 3,
                                    'categoryData'=>array('GN'=>'UR', 'SC' => 'SC', 'ST' => 'ST', 'OBC' => 'OBC'),
                                    'roundData'=>array('1'=>'Round 1','2'=>'Round 2', '3'=>'Round 3'),
                                    'examNameForResultText'=>'CGPET',
                                    'seo_title_exam_name'=>'CGPET',
                                    'seo_description_exam_name'=>'CGPET',
                                    'seo_description' =>'CGPET College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your CGPET '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via CGPET '.date('Y').' exam.',
                                    'inputType'=>'Rank'

                    ),
  'TNEA'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'TNEA '.date('Y').' College Predictor','seoTitle'=>'TNEA College Predictor '.date('Y').' – Which Colleges will you get Admission in using TNEA Rank/Score?','imageTitle'=>'TNEA college predictor'),
                                            'college'=>array('heading'=>'College Cut-off TNEA '.date('Y'),'imageTitle'=>'TNEA cut off predictor'),
                                            'branch'=>array('heading'=>'TNEA '.date('Y').' Branch Predictor','imageTitle'=>'TNEA branch predictor'),
                        ),
                                    'notice'=>'Prediction for TNEA '.date('Y').' is based on TNEA '.(date('Y')-1).' closing ranks.',
                                    'mailerSubject'=>'TNEA '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'NO',
                                    'noStateDropDown'=>1,
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'HOME',
                                    'stateName'=>'Tamil Nadu',
                                    'examName'=>'TNEA',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 1,
                                    'categoryData'=>array('OC'=>'OC-Open Category', 'BCM'=>'BCM-Backward class Muslim','BC'=>'BC-Backward class','MBC'=>'MBC-Most backward class','SCA'=>'SCA-Scheduled caste Arunthathiyars','SC'=>'SC-Scheduled caste','ST'=>'ST-Scheduled Tribes'),
                                    'roundData'=>array('1'=>'Round 1'),
                                    'examNameForResultText'=>'TNEA',
                                    'seo_title_exam_name'=>'TNEA',
                                    'seo_description_exam_name'=>'TNEA',
                                    'seo_description' =>'TNEA College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your TNEA '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via TNEA '.date('Y').' exam.',
                                    'inputType'=>'Score'

                    ),
        
  'PTU'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'PTU '.date('Y').' College Predictor','seoTitle'=>'PTU College Predictor '.date('Y').' – Which Colleges will you get Admission in using PTU Rank/Score?','imageTitle'=>'PTU college predictor'),
                                            'college'=>array('heading'=>'College Cut-off PTU '.date('Y'),'imageTitle'=>'PTU cut off predictor'),
                                            'branch'=>array('heading'=>'PTU '.date('Y').' Branch Predictor','imageTitle'=>'PTU branch predictor'),
                        ),
                                    'notice'=>'Prediction for PTU 2017 is based on PTU 2016 closing ranks.',
                                    'mailerSubject'=>'PTU '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'YES',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'',
                                    'stateName'=>'Punjab',
                                    'examName'=>'PTU',
                                    'examYear'=>date('Y'),
                                    'noStateDropDown'=>1,
                                    'totalRound' => 2,
                                    'categoryData'=>array('BC_AI'=>'Backward Caste - All India','GN_AI'=>'General - All India','GN_HS'=>'General - Home State','SC'=>'SC/ST','BC_HS'=>'Backward Caste - Home State'),
                                    'roundData'=>array('1'=>'Round 1', '2'=>'Round 2'),
                                    'examNameForResultText'=>'PTU',
                                    'seo_title_exam_name'=>'PTU',
                                    'seo_description_exam_name'=>'PTU',
                                    'seo_description' =>'PTU College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your PTU '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via PTU '.date('Y').' exam.',
                                    'inputType'=>'Rank'

                    ),
         

         'UPSEE'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'UPSEE '.date('Y').' College Predictor','seoTitle'=>'UPSEE College Predictor '.date('Y').' – Which Colleges will you get Admission in using UPSEE Rank/Score?','imageTitle'=>'UPSEE college predictor'),
                                            'college'=>array('heading'=>'College Cut-off UPSEE '.date('Y'),'imageTitle'=>'UPSEE cut off predictor'),
                                            'branch'=>array('heading'=>'UPSEE '.date('Y').' Branch Predictor','imageTitle'=>'UPSEE branch predictor'),
                        ),
                                    'notice'=>'Prediction for UPSEE 2017 is based on UPSEE 2016 closing ranks.',
                                    'mailerSubject'=>'UPSEE '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'YES',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'',
                                    'stateName'=>'Uttar Pradesh',
                                    'examName'=>'UPSEE',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 1,
                                    'categoryData'=>array('OPEN' => 'General Open','OPGL'=>'General Girl', 'BCNO' =>'OBC Open', 'BCGL' => 'OBC Girl', 'SCNO' => 'SC Open', 'SCGL' =>'SC Girl' , 'STNO' => 'ST Open', 'STGL' => 'ST Girl'),
                                    'roundData'=>array('1'=>'Round 1'),
                                    'examNameForResultText'=>'UPSEE',
                                    'seo_title_exam_name'=>'UPSEE',
                                    'seo_description_exam_name'=>'UPSEE',
                                    'seo_description' =>'UPSEE College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your UPSEE '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via UPSEE '.date('Y').' exam.',
                                    'inputType'=>'Rank'

                    ),
 'MHCET'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'MHT-CET '.date('Y').' College Predictor','seoTitle'=>'MHCET College Predictor '.date('Y').' – Which Colleges will you get Admission in using MHCET Rank/Score?','imageTitle'=>'MHCET college predictor'),
                                            'college'=>array('heading'=>'College Cut-off MHCET '.date('Y'),'imageTitle'=>'MHCET cut off predictor'),
                                            'branch'=>array('heading'=>'MHCET '.date('Y').' Branch Predictor','imageTitle'=>'MHCET branch predictor'),
                        ),
                                    'notice'=>'Prediction for MHCET 2017 is based on MHCET 2016 closing ranks.',
                                    'mailerSubject'=>'MHCET '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'YES',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'Other',
                                    'stateName'=>'Maharashtra',
                                    'examName'=>'MHCET',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 3,
                                    'noStateDropDown'=>1,
                                    'categoryData'=>array('OBC'=>'OBC','Open'=>'Open','OBCF'=>'OBC- Female','OpenF'=>'Open- Female','NT1'=>'NT1','NT2'=>'NT2','NT3'=>'NT3','NT1F'=>'NT1 - Female','NT2F'=>'NT2- Female','NT3F'=>'NT3- Female','SC'=>'SC','ST'=>'ST','SCF'=>'SC- Female','STF'=>'ST- Female','VJ'=>'VJ','VJF'=>'VJ- Female'),
                                    'roundData'=>array('1'=>'Round 1','2'=>'Round 2','3'=>'Round 3'),
                                    'examNameForResultText'=>'MHCET',
                                    'seo_title_exam_name'=>'MHCET',
                                    'seo_description_exam_name'=>'MHCET',
                                    'seo_description' =>'MHCET College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your MHCET '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via MHCET '.date('Y').' exam.',
                                    'inputType'=>'Rank'

                    ),
        'HSTES'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'HSTES '.date('Y').' College Predictor','seoTitle'=>'HSTES College Predictor '.date('Y').' – Which Colleges will you get Admission in using HSTES Rank/Score?','imageTitle'=>'HSTES college predictor'),
                                            'college'=>array('heading'=>'College Cut-off HSTES '.date('Y'),'imageTitle'=>'HSTES cut off predictor'),
                                            'branch'=>array('heading'=>'HSTES '.date('Y').' Branch Predictor','imageTitle'=>'HSTES branch predictor'),
                        ),
                                    'notice'=>'Prediction for HSTES 2018 is based on HSTES 2017 closing ranks.',
                                    'mailerSubject'=>'HSTES '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'NO',
                                    'rankType'=>'Home',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'Home',
                                    'stateName'=>'Haryana',
                                    'examName'=>'HSTES',
                                    'examYear'=>date('Y'),
                                    'noStateDropDown'=>1,
                                    'totalRound' => 2,
                                    'categoryData'=>array('AIC'=>'All India Category ','AICF'=>'All India Category Females','HOGC' => 'Haryana Open General Category', 'HOGCF'=>'Haryana Open General Category Females','SC' => 'Scheduled Caste of Haryana', 'SCF'=>'Scheduled Caste of Haryana Female','BC' =>'Backward Class of Haryana','BCF'=>'Backward Class of Haryana Females'),
                                    'roundData'=>array('1'=>'Round 1','2' =>'Round 2' ),
                                    'examNameForResultText'=>'HSTES',
                                    'seo_title_exam_name'=>'HSTES',
                                    'seo_description_exam_name'=>'HSTES',
                                    'seo_description' =>'HSTES College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your HSTES '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via HSTES '.date('Y').' exam.',
                                    'inputType'=>'Rank'

                    ),
        'AP-EAMCET'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'AP-EAMCET '.date('Y').' College Predictor','seoTitle'=>'AP-EAMCET College Predictor '.date('Y').' – Which Colleges will you get Admission in using AP-EAMCET Rank/Score?','imageTitle'=>'AP-EAMCET college predictor'),
                                            'college'=>array('heading'=>'College Cut-off AP-EAMCET '.date('Y'),'imageTitle'=>'AP-EAMCET cut off predictor'),
                                            'branch'=>array('heading'=>'AP-EAMCET '.date('Y').' Branch Predictor','imageTitle'=>'AP-EAMCET branch predictor'),
                        ),
                                    'notice'=>'Prediction for AP-EAMCET 2018 is based on AP-EAMCET 2017 closing ranks.',
                                    'mailerSubject'=>'AP-EAMCET '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'NO',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'Home',
                                    'stateName'=>'Andhra Pradesh',
                                    'examName'=>'AP-EAMCET',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 1,
                                    'categoryData'=>array("OC" => "OC","SC" => "SC","ST" => "ST","BC_A" => "BC_A","BC_B" => "BC_B","BC_C" => "BC_C","BC_D" => "BC_D","BC_E" => "BC_E"),
                                    'roundData'=>array('1'=>'Round 1'),
                                    'examNameForResultText'=>'AP-EAMCET',
                                    'seo_title_exam_name'=>'AP-EAMCET',
                                    'seo_description_exam_name'=>'AP-EAMCET',
                                    'seo_description' =>'AP-EAMCET College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your AP-EAMCET '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via AP-EAMCET '.date('Y').' exam.',
                                    'inputType'=>'Rank'

                    ),
        'TS-EAMCET'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'TS-EAMCET '.date('Y').' College Predictor','seoTitle'=>'TS-EAMCET College Predictor '.date('Y').' – Which Colleges will you get Admission in using TS-EAMCET Rank/Score?','imageTitle'=>'TS-EAMCET college predictor'),
                                            'college'=>array('heading'=>'College Cut-off TS-EAMCET '.date('Y'),'imageTitle'=>'TS-EAMCET cut off predictor'),
                                            'branch'=>array('heading'=>'TS-EAMCET '.date('Y').' Branch Predictor','imageTitle'=>'TS-EAMCET branch predictor'),
                        ),
                                    'notice'=>'Prediction for TS-EAMCET 2017 is based on TS-EAMCET 2016 closing ranks.',
                                    'mailerSubject'=>'TS-EAMCET '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'NO',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'HOME',
                                    'stateName'=>'Telangana',
                                    'examName'=>'TS-EAMCET',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 1,
                                    'categoryData'=>array('OC'=>'OC','SC'=>'SC','ST'=>'ST','BC_A'=>'BC_A','BC_B'=>'BC_B','BC_C'=>'BC_C','BC_D'=>'BC_D','BC_E'=>'BC_E'),
                                    'roundData'=>array('1'=>'Round 1'),
                                    'examNameForResultText'=>'TS-EAMCET',
                                    'seo_title_exam_name'=>'TS-EAMCET',
                                    'seo_description_exam_name'=>'TS-EAMCET',
                                    'seo_description' =>'TS-EAMCET College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your TS-EAMCET '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via TS-EAMCET '.date('Y').' exam.',
                                    'inputType'=>'Rank'

                    ),

            
            'BITSAT'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'BITSAT '.date('Y').' College Predictor','seoTitle'=>'BITSAT College Predictor '.date('Y').' – Which Colleges will you get Admission in using BITSAT Rank/Score?','imageTitle'=>'BITSAT college predictor'),
                                            'college'=>array('heading'=>'College Cut-off BITSAT '.date('Y'),'imageTitle'=>'BITSAT cut off predictor'),
                                            'branch'=>array('heading'=>'BITSAT '.date('Y').' Branch Predictor','imageTitle'=>'BITSAT branch predictor'),
                        ),
                                    'notice'=>'Prediction for BITSAT '.date('Y').' is based on BITSAT '.date('Y', strtotime('-1 year')).' closing ranks.',
                                    'mailerSubject'=>'BITSAT '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'NO',
                                    'invertLogic'=>1,
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'Other',
                                    'stateName'=>'',
                                    'examName'=>'BITSAT',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 1,
                                    'categoryData'=>array('GEN'=>'General'),
                                    'roundData'=>array('1'=>'Round 1'),
                                    'examNameForResultText'=>'BITSAT',
                                    'seo_title_exam_name'=>'BITSAT',
                                    'seo_description_exam_name'=>'BITSAT',
                                    'seo_description' =>'BITSAT College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your BITSAT '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via BITSAT '.date('Y').' exam.',
                                    'inputType'=>'Rank'
                    ),
            'OJEE'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'OJEE '.date('Y').' College Predictor','seoTitle'=>'OJEE College Predictor '.date('Y').' – Which Colleges will you get Admission in using OJEE Rank/Score?','imageTitle'=>'OJEE college predictor'),
                                            'college'=>array('heading'=>'College Cut-off OJEE '.date('Y'),'imageTitle'=>'OJEE cut off predictor'),
                                            'branch'=>array('heading'=>'OJEE '.date('Y').' Branch Predictor','imageTitle'=>'OJEE branch predictor'),
                        ),
                                    'notice'=>'Prediction for OJEE 2017 is based on OJEE 2016 closing ranks.',
                                    'mailerSubject'=>'OJEE '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'NO',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'HOME',
                                    'stateName'=>'Odisha',
                                    'examName'=>'OJEE',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 1,
                                    'categoryData'=>array('JEE_M' => 'JEE Mains Cut-Off','ES_C' => 'Ex-Servicemen','ES_W' => 'Ex-Servicemen- Women','GC_C' => 'Green Card Holder','GC_W' => 'Green Card Holder- Women','GE_C' => 'General','GE_W' =>  'General - Women','OL' => 'Outlying Odiya','PC_C' => 'Physically Challenged','PC_W' => 'Physically Challenged- Women','SC_C' => 'Scheduled Caste','SC_W' => 'Scheduled Caste- Women','ST_C' => 'Scheduled Tribe','ST_W' => 'Scheduled Tribe- Women','TFW' => 'Tuition Fee Waiver','ZZ' => 'Domicile Outside Odisha'),
                                    'roundData'=>array('1'=>'Round 1'),
                                    'examNameForResultText'=>'OJEE',
                                    'seo_title_exam_name'=>'OJEE',
                                    'seo_description_exam_name'=>'OJEE',
                                    'seo_description' =>'OJEE College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your OJEE '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via OJEE '.date('Y').' exam.',
                                    'inputType'=>'Rank'


                    ),


            'GGSIPU'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'GGSIPU '.date('Y').' College Predictor','seoTitle'=>'GGSIPU College Predictor '.date('Y').' – Which Colleges will you get Admission in using GGSIPU Rank/Score?','imageTitle'=>'GGSIPU college predictor'),
                                            'college'=>array('heading'=>'College Cut-off GGSIPU '.date('Y'),'imageTitle'=>'GGSIPU cut off predictor'),
                                            'branch'=>array('heading'=>'GGSIPU '.date('Y').' Branch Predictor','imageTitle'=>'GGSIPU branch predictor'),
                        ),
                                    'notice'=>'Prediction for GGSIPU 2017 is based on GGSIPU 2016 closing ranks.',
                                    'mailerSubject'=>'GGSIPU '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'NO',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'Other',
                                    'stateName'=>'',
                                    'examName'=>'GGSIPU',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 3,
                                    'categoryData'=>array('GNGNA' => 'General-All India','SCGNA' => 'SC-All India','STGNA'=>'ST-All India', 'GNGND'=>'General-Delhi', 'GNPHD'=>'General-Physically Handicapped-Delhi', 'OBGND'=>'OBC-Delhi','SCGND'=>'SC-Delhi','STGND'=>'ST-Delhi','GNGNO'=>'General-Outside Delhi','SCGNO'=>'SC-Outside Delhi','STGNO'=>'ST-Outside Delhi'),
                                    'roundData'=>array('1'=>'Round 1','2'=>'Round 2','3'=>'Round 3'),
                                    'examNameForResultText'=>'GGSIPU',
                                    'seo_title_exam_name'=>'GGSIPU',
                                    'seo_description_exam_name'=>'GGSIPU',
                                    'seo_description' =>'GGSIPU College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your GGSIPU '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via GGSIPU '.date('Y').' exam.',
                                    'inputType'=>'Rank'
                    ),
                'GUJCET'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'GUJCET '.date('Y').' College Predictor','seoTitle'=>'GUJCET College Predictor '.date('Y').' – Which Colleges will you get Admission in using GUJCET Rank/Score?','imageTitle'=>'GUJCET college predictor'),
                                            'college'=>array('heading'=>'College Cut-off GUJCET '.date('Y'),'imageTitle'=>'GUJCET cut off predictor'),
                                            'branch'=>array('heading'=>'GUJCET '.date('Y').' Branch Predictor','imageTitle'=>'GUJCET branch predictor'),
                        ),
                                    'notice'=>'Prediction for GUJCET 2017 is based on GUJCET 2016 closing ranks.',
                                    'mailerSubject'=>'GUJCET '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'NO',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'Home',
                                    'stateName'=>'Gujarat',
                                    'examName'=>'GUJCET',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 2,
                                    'categoryData'=>array('GEN'=>'General','SEBC'=>'SEBC','SC'=>'SC','ST'=>'ST'),
                                    'roundData'=>array('1'=>'Round 1' , '2' => 'Round 2'),
                                    'examNameForResultText'=>'GUJCET',
                                    'seo_title_exam_name'=>'GUJCET',
                                    'seo_description_exam_name'=>'GUJCET',
                                    'seo_description' =>'GUJCET College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your GUJCET '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via GUJCET '.date('Y').' exam.',
                                    'inputType'=>'Rank'
                    ),

            'NIFT'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'NIFT '.date('Y').' College Predictor','seoTitle'=>'NIFT College Predictor '.date('Y').' – Which Colleges will you get Admission in using NIFT Rank/Score?','imageTitle'=>'NIFT college predictor'),
                                            'college'=>array('heading'=>'College Cut-off NIFT '.date('Y'),'imageTitle'=>'NIFT cut off predictor'),
                                            'branch'=>array('heading'=>'NIFT '.date('Y').' Branch Predictor','imageTitle'=>'NIFT branch predictor'),    
                        ),
                                    'notice'=>'Prediction for NIFT 2018 is based on NIFT 2017 closing ranks.',
                                    'mailerSubject'=>'NIFT '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'stateName'=>'',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'NO',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'Other',
                                    'examName'=>'NIFT',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 1,
                                    'categoryData'=>array('GEN'=>'General','SC'=>'SC','ST'=>'ST','OBC_NC'=>'OBC Non Creamy','ST'=>'ST', 'GEN_D' => 'General Domicile', 'SC_D' => 'SC Domicile', 'ST_D' => 'ST Domicile', 'OBC_NC_D' => 'OBC Domicile Non Creamy'),
                                    'roundData'=>array('1'=>'Round 1'),
                                    'examNameForResultText'=>'NIFT',
                                    'seo_title_exam_name'=>'NIFT',
                                    'seo_description_exam_name'=>'NIFT',
                                    'seo_description' =>'NIFT College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your NIFT '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via NIFT '.date('Y').' exam.',
                                    'inputType'=>'Rank'
                    ),

            'NCHMCT'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'NCHMCT '.date('Y').' College Predictor','seoTitle'=>'NCHMCT College Predictor '.date('Y').' – Which Colleges will you get Admission in using NCHMCT Rank/Score?','imageTitle'=>'NCHMCT college predictor'),
                                            'college'=>array('heading'=>'College Cut-off NCHMCT '.date('Y'),'imageTitle'=>'NCHMCT cut off predictor'),
                                            'branch'=>array('heading'=>'NCHMCT '.date('Y').' Branch Predictor','imageTitle'=>'NCHMCT branch predictor'),    
                        ),
                                    'notice'=>'Prediction for NCHMCT 2018 is based on NCHMCT 2017 closing ranks.',
                                    'mailerSubject'=>'NCHMCT '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'stateName'=>'',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'NO',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'Other',
                                    'examName'=>'NCHMCT',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 2,
                                    'categoryData'=>array('GEN'=>'General', 'GEN_PWD' => 'General PwD', 'OBC_NCL' => 'OBC-NCL', 'OBC_NCL_PWD' => 'OBC-NCL (PwD)', 'SC'=>'SC', 'SC_PWD' => 'SC(PwD)', 'ST' => 'ST', 'ST_PWD' =>  'ST(PwD)', 'KM' => 'KM'),
                                    'roundData'=>array('1'=>'Round 1', '2' => 'Round 2'),
                                    'examNameForResultText'=>'NCHMCT',
                                    'seo_title_exam_name'=>'NCHMCT',
                                    'seo_description_exam_name'=>'NCHMCT',
                                    'seo_description' =>'NCHMCT College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your NCHMCT '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via NCHMCT '.date('Y').' exam.',
                                    'inputType'=>'Rank'
                    ),
            'MAHCET'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'MAHCET '.date('Y').' College Predictor','seoTitle'=>'MAHCET College Predictor '.date('Y').' – Which Colleges will you get Admission in using MAHCET Rank/Score?','imageTitle'=>'MAHCET college predictor'),
                                            'college'=>array('heading'=>'College Cut-off MAHCET '.date('Y'),'imageTitle'=>'MAHCET cut off predictor'),
                                            'branch'=>array('heading'=>'MAHCET '.date('Y').' Branch Predictor','imageTitle'=>'MAHCET branch predictor'),    
                        ),
                                    'notice'=>'Prediction for MAHCET 2018 is based on MAHCET 2017 closing ranks.',
                                    'mailerSubject'=>'MAHCET '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'stateName'=>'Maharashtra',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'YES',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'Other',
                                    'examName'=>'MAHCET',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 3,
                                    'categoryData'=>array('GEN'=>'General', 'SC'=>'SC', 'ST' =>  'ST', 'OBC' => 'OBC'),
                                    'roundData'=>array('1'=>'Round 1', '2' => 'Round 2', '3' => 'Round 3'),
                                    'examNameForResultText'=>'MAHCET',
                                    'seo_title_exam_name'=>'MAHCET',
                                    'seo_description_exam_name'=>'MAHCET',
                                    'seo_description' =>'MAHCET College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your MAHCET '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via MAHCET '.date('Y').' exam.',
                                    'inputType'=>'Rank'
                    ),

            'CLAT'=>array(
                    'tab'=>array(
                                            'rank'=>array('heading'=>'CLAT '.date('Y').' College Predictor','seoTitle'=>'CLAT College Predictor '.date('Y').' – Which Colleges will you get Admission in using CLAT Rank/Score?','imageTitle'=>'MAHCET college predictor'),
                                            'college'=>array('heading'=>'College Cut-off CLAT '.date('Y'),'imageTitle'=>'MAHCET cut off predictor'),
                                            'branch'=>array('heading'=>'CLAT '.date('Y').' Branch Predictor','imageTitle'=>'MAHCET branch predictor'),    
                        ),
                                    'notice'=>'Prediction for CLAT 2018 is based on CLAT 2017 closing ranks.',
                                    'mailerSubject'=>'CLAT '.date('Y').' College Predictor',
                                    'showFilters'=>'YES',
                                    'showFiltersOnMobile'=>'YES',
                                    'showSorting'=>'NO',
                                    'stateName'=>'',
                                    'showInvite'=>'NO',
                                    'showEmail'=>'NO',
                                    'showPrint'=>'NO',
                                    'showRankType'=>'NO',
                                    'showKnowYourRank' => 'NO',
                                    'rankType'=>'Other',
                                    'examName'=>'CLAT',
                                    'examYear'=>date('Y'),
                                    'totalRound' => 1,
                                    'categoryData'=>array('OC'=>'Open','BC'=>'Backward Classes', 'SC' =>  ' Scheduled Castes', 'ST' => 'Scheduled Tribes'),
                                    'roundData'=>array('1'=>'Round 1'),
                                    'examNameForResultText'=>'CLAT',
                                    'seo_title_exam_name'=>'CLAT',
                                    'seo_description_exam_name'=>'CLAT',
                                    'seo_description' =>'CLAT College Predictor '.date('Y').' enables you to predict colleges you can get admission in using your CLAT '.date('Y').' rank/score. Enter your rank/score, and Predict which institutes / colleges you might crack for admission via CLAT '.date('Y').' exam.',
                                    'inputType'=>'Rank'
                    ),

            'CPEXAMS' => array( 
                                'JEE-MAINS' => array('name' => 'JEE MAIN College Predictor', 'collegeUrl' => 'jee-mains-college-predictor',
                                                    'cutoffUrl' => 'jee-mains-cut-off-predictor' ,'branchUrl' => 'jee-mains-branch-predictor','shortName' => 'JEE Main '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
                                                ),
                                'KCET' => array('name' => 'KCET College Predictor' , 'collegeUrl' => 'kcet-college-predictor',
                                                    'cutoffUrl' => 'kcet-cut-off-predictor' ,'branchUrl' => 'kcet-branch-predictor','shortName' => 'KCET '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
                                                ),
                                
                                'COMEDK' => array('name' => 'COMEDK College Predictor' , 'collegeUrl' => 'comedk-college-predictor',
                                                    'cutoffUrl' => 'comedk-cut-off-predictor' ,'branchUrl' => 'comedk-branch-predictor','shortName' => 'COMEDK '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
                                                ),
                                'KEAM' => array('name' => 'KEAM College Predictor' , 'collegeUrl' => 'keam-college-predictor',
                                                    'cutoffUrl' => 'keam-cut-off-predictor' ,'branchUrl' => 'keam-branch-predictor','shortName' => 'KEAM '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
                                                ),
                                'WBJEE' => array('name' => 'WBJEE College Predictor' , 'collegeUrl' => 'wbjee-college-predictor',
                                                    'cutoffUrl' => 'wbjee-cut-off-predictor' ,'branchUrl' => 'wbjee-branch-predictor','shortName' => 'WBJEE '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
                                                ),
                                'MPPET' => array('name' => 'MPPET College Predictor' , 'collegeUrl' => 'mppet-college-predictor',
                                                    'cutoffUrl' => 'mppet-cut-off-predictor' ,'branchUrl' => 'mppet-branch-predictor','shortName' => 'MPPET '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
                                                ),
                                'CGPET' => array('name' => 'CGPET College Predictor' , 'collegeUrl' => 'cgpet-college-predictor',
                                                    'cutoffUrl' => 'cgpet-cut-off-predictor' ,'branchUrl' => 'cgpet-branch-predictor', 'shortName' => 'CGPET '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
   
                                                ),
                                'TNEA' => array('name' => 'TNEA College Predictor' , 'collegeUrl' => 'tnea-college-predictor',
                                                    'cutoffUrl' => 'tnea-cut-off-predictor' ,'branchUrl' => 'tnea-branch-predictor', 'shortName' => 'TNEA '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
   
                                                ),
                                'PTU' => array('name' => 'PTU College Predictor' , 'collegeUrl' => 'ptu-college-predictor',
                                                    'cutoffUrl' => 'ptu-cut-off-predictor' ,'branchUrl' => 'ptu-branch-predictor', 'shortName' => 'PTU '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
   
                                                ),
                                'UPSEE' => array('name' => 'UPSEE College Predictor' , 'collegeUrl' => 'upsee-college-predictor',
                                                    'cutoffUrl' => 'upsee-cut-off-predictor' ,'branchUrl' => 'upsee-branch-predictor', 'shortName' => 'UPSEE '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
                                                ),
                                 'MHCET' => array('name' => 'MHCET College Predictor' , 'collegeUrl' => 'mhcet-college-predictor',
                                                    'cutoffUrl' => 'mhcet-cut-off-predictor' ,'branchUrl' => 'mhcet-branch-predictor', 'shortName' => 'MHCET '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
                                                ),
                                 'HSTES' => array('name' => 'HSTES College Predictor' , 'collegeUrl' => 'hstes-college-predictor',
                                                    'cutoffUrl' => 'hstes-cut-off-predictor' ,'branchUrl' => 'hstes-branch-predictor', 'shortName' => 'HSTES '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
                                                ),
                                  'AP-EAMCET' => array('name' => 'AP-EAMCET College Predictor' , 'collegeUrl' => 'ap-eamcet-college-predictor',
                                                    'cutoffUrl' => 'ap-eamcet-cut-off-predictor' ,'branchUrl' => 'ap-eamcet-branch-predictor', 'shortName' => 'AP-EAMCET '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
    
                                                ),
                                  'TS-EAMCET' => array('name' => 'TS-EAMCET College Predictor' , 'collegeUrl' => 'ts-eamcet-college-predictor',
                                                    'cutoffUrl' => 'ts-eamcet-cut-off-predictor' ,'branchUrl' => 'ts-eamcet-branch-predictor', 'shortName' => 'TS-EAMCET '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
                                        ),                                    
                                'OJEE' => array('name' => 'OJEE College Predictor' , 'collegeUrl' => 'ojee-college-predictor',
                                                    'cutoffUrl' => 'ojee-cut-off-predictor' ,'branchUrl' => 'ojee-branch-predictor', 'shortName' => 'OJEE '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
                                    ),
                                                
                                  'BITSAT' => array('name' => 'BITSAT College Predictor' , 'collegeUrl' => 'bitsat-college-predictor',
                                                    'cutoffUrl' => 'bitsat-cut-off-predictor' ,'branchUrl' => 'bitsat-branch-predictor', 'shortName' => 'BITSAT '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
                                            ),
                                  'GGSIPU' => array('name' => 'GGSIPU College Predictor' , 'collegeUrl' => 'ggsipu-college-predictor',
                                                    'cutoffUrl' => 'ggsipu-cut-off-predictor' ,'branchUrl' => 'ggsipu-branch-predictor', 'shortName' => 'GGSIPU '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
                                            ),
                                    'GUJCET' => array('name' => 'GUJCET College Predictor' , 'collegeUrl' => 'gujcet-college-predictor',
                                                    'cutoffUrl' => 'gujcet-cut-off-predictor' ,'branchUrl' => 'gujcet-branch-predictor', 'shortName' => 'GUJCET '.date('Y'),
                                                    'directoryName' => '/b-tech/resources', 
                                            ),
                                    'NIFT' => array('name' => 'NIFT College Predictor' , 
                                                    'collegeUrl' => 'nift-college-predictor',
                                                    'cutoffUrl' => 'nift-cut-off-predictor' ,
                                                    'branchUrl' => 'nift-branch-predictor', 
                                                    'shortName' => 'NIFT '.date('Y'),
                                                    'directoryName' => '/design/resources',
                                                    'resultTitle' => 'Design'
                                            ),
                                    'NCHMCT' => array('name' => 'NCHMCT College Predictor' , 
                                                    'collegeUrl' => 'nchmct-college-predictor',
                                                    'cutoffUrl' => 'nchmct-cut-off-predictor' ,
                                                    'branchUrl' => 'nchmct-branch-predictor', 
                                                    'shortName' => 'NCHMCT '.date('Y'),
                                                    'directoryName' => '/hospitality-travel/resources',
                                                    'resultTitle' => 'Hospitality'
                                            ),
                                    'MAHCET' => array('name' => 'MAHCET College Predictor' , 
                                                    'collegeUrl' => 'mahcet-college-predictor',
                                                    'cutoffUrl' => 'mahcet-cut-off-predictor' ,
                                                    'branchUrl' => 'mahcet-branch-predictor', 
                                                    'shortName' => 'MAHCET '.date('Y'),
                                                    'directoryName' => '/mba/resources',
                                                    'resultTitle' => 'Business Management & Studies'
                                            ),
                                    'CLAT' => array('name' => 'CLAT College Predictor' , 
                                                    'collegeUrl' => 'clat-college-predictor',
                                                    'cutoffUrl' => 'clat-cut-off-predictor' ,
                                                    'branchUrl' => 'clat-branch-predictor', 
                                                    'shortName' => 'CLAT '.date('Y'),
                                                    'directoryName' => '/law/resources',
                                            )


                                  
                            ),
            'CPPOPULAR' => array('JEE-MAINS','UPSEE','MAHCET') // this is using in popular section in engineering rank predictor, url - engineering/rank-predictor
            ),  
        );
$config['nameToIdMappingForAllCollegePredictorPage'] = array(
    'BITSAT'        => 304,
    'WBJEE'         => 3044,
    'JEE-MAINS'     => 6244,
    'AP-EAMCET'     => 6490,
    'KCET'          => 6611,
    'UPSEE'         => 6612,
    'KEAM'          => 6616,
    'GUJCET'        => 9200,
    'MHCET'         => 9247,
    'TS-EAMCET'     => 10307,
    'TNEA'          => 6554,
    'JEE-ADVANCED'  => 6245,
    'GGSIPU'        => 13606,
    'PTU'           => 13665
);
$config['cpUrlMapping'] = array('b-tech' => 'Engineering', 'design' => 'Design', 'hospitality-travel' => 'Hospitality & Travel', 'mba' => 'Business & Management Studies','law' =>'Law');
//}

$config['CPExamNameToExamMainName'] = array('JEE-Mains'=>'JEE Mains','COMEDK'=>'COMEDK UGET', 'AP-EAMCET'=>'AP EAMCET','TS-EAMCET'=>'TS EAMCET');
$config['CPStateNameToStateTableName'] = array('Odisha'=>'Orissa');


$config['JEE-MAIN-InstituteData'] = array (
 'Indian Institute of Technology Bombay', 'Indian Institute of Technology Delhi', 'School of Planning & Architecture, New Delhi', 'Indian Institute of Technology Madras', 'National Institute of Technology, Tiruchirappalli', 'Indian Institute of Technology Kharagpur', 'Indian Institute of Technology Kanpur', 'School of Planning & Architecture, Bhopal', 'Indian Institute of Technology Roorkee', 'National Institute of Technology Calicut', 'School of Planning & Architecture, Vijayawada', 'Malaviya National Institute of Technology Jaipur', 'National Institute of Technology, Rourkela', 'Visvesvaraya National Institute of Technology, Nagpur', 'Netaji Subhas Institute of Technology', 'Birla Institute of Technology, Mesra, Ranchi', 'Maulana Azad National Institute of Technology Bhopal', 'Indian Institute of Technology Guwahati', 'National Institute of Technology Hamirpur', 'Indian Institute of Technology Hyderabad', 'Indian Institute of Engineering Science and Technology, Shibpur', 'National Institute of Technology Raipur', 'National Institute of Technology Patna', 'Mizoram University, Aizawl', 'Indian Institute of Technology (BHU) Varanasi', 'Delhi Technological University', 'Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir', 'Indian Institute of Technology Indore', 'Indraprastha Institute of Information Technology (IIT),Delhi', 'National Institute of Technology Karnataka, Surathkal', 'National Institute of Technology, Warangal', 'Sanaka Education Trusts Group Of Institutions', 'Indian Institute of Technology Gandhinagar', 'Indian Institute of Technology Bhubaneswar', 'Indian Institute of Technology Ropar', 'Bhartiya Vidya Bhavan\'s Sardar Patel Institute of Technology, Andheri, Mumbai', 'Motilal Nehru National Institute of Technology Allahabad', 'Indian Institute of Technology Mandi', 'Om Dayal Group Of Institutions', 'Indian Institute of Technology Tirupati', 'Indian Institute of Technology Patna', 'Indian Institute of Technology Jodhpur', 'Indian Institute of Technology (ISM) Dhanbad', 'Indian Institute of Technology Goa', 'Punjab Engineering College, Chandigarh', 'Institute of Chemical Technology, Matunga, Mumbai', 'Indian Institute of Technology Palakkad', 'Indian Institute of Information Technology, Allahabad', 'Indian Institute of Technology Dharwad', 'Indian Institute of Technology Bhilai'
);

?>
