export const MockPlacementData =  {
pageType: "Placement",
placementPageUrl: "/college/iim-bangalore-indian-institute-of-management-iimb-bannerghatta-road-318/placement",
hashUrl: "eyJpbnN0aXR1dGVJZCI6IjMxOCJ9",
selectedBaseCourseId: -1,
selectedBaseCourseName: null,
selectedYear: -1,
anaCountString: "280",
instituteTopCardData: {
instituteName: "IIM Bangalore - Indian Institute of Management (IIMB)",
instituteSpecificationType: "College",
inlineData: {
ownership: "Public/Government"
},
headerImageDesktop: "https://shikshatest02.infoedge.com/mediadata/images/1507192820phpXQxcnX_g.jpg",
headerImageMobile: "https://shikshatest02.infoedge.com/mediadata/images/1507192820phpXQxcnX_270x200.jpg",
logoImageUrl: "https://shikshatest02.infoedge.com/mediadata/images/1408538152phpa3KG8B.png",
affiliationData: null,
instituteImportantData: {
autonomous: true,
nationalImportance: true,
univeristyTypeWithSpecification: null,
ugcApproved: false,
naacAccreditation: null,
aiuMember: false,
},
parentUniversityData: null,
rankingData: [
{
sourceId: 21,
publisherId: 8,
publisherName: "NIRF",
rankingPageId: 2,
rank: 2,
rankingPageText: "MBA",
instituteId: 318,
courseId: 1688,
baseCourseId: 101,
displayableRank: "2",
year: 2018,
url: "https://shikshatest05.infoedge.com/mba/ranking/top-mba-colleges-in-india/2-2-0-0-0",
},
{
sourceId: 29,
publisherId: 2,
publisherName: "Business Today",
rankingPageId: 2,
rank: 3,
rankingPageText: "MBA",
instituteId: 318,
courseId: 1688,
baseCourseId: 101,
displayableRank: "3",
year: 2018,
url: "https://shikshatest05.infoedge.com/mba/ranking/top-mba-colleges-in-india/2-2-0-0-0",
},
{
sourceId: 17,
publisherId: 6,
publisherName: "The Week",
rankingPageId: 2,
rank: 2,
rankingPageText: "MBA",
instituteId: 318,
courseId: 1688,
baseCourseId: 101,
displayableRank: "2",
year: 2017,
url: "https://shikshatest05.infoedge.com/mba/ranking/top-mba-colleges-in-india/2-2-0-0-0",
},
{
sourceId: 5,
publisherId: 2,
publisherName: "Business Today",
rankingPageId: 18,
rank: 3,
rankingPageText: "Executive MBA",
instituteId: 318,
courseId: 115020,
baseCourseId: 75,
displayableRank: "3",
year: 2015,
url: "https://shikshatest05.infoedge.com/business-management-studies/ranking/top-executive-mba-colleges-in-india/18-2-0-0-0",
},
],
},
anaWidget: {
totalNumber: 280,
listingType: "institute",
questionsDetail: {
5223003: {
answerId: 5239451,
answerText: "Bangalore focuses heavily on class 10th and class 12th and graduation score, but you should try to get high score.",
activityTime: "3 months ago",
answerOwnerUserId: 10088181,
questionId: 5223003,
aboutMe: null,
commentCount: 1,
msgCount: 3,
viewCount: 151,
status: "LIVE",
userId: 6678351,
firstname: "shahid",
lastname: "Qureshi",
creationDate: "2019-01-26 03:29:07",
url: "https://ask.shikshatest03.infoedge.com/my-profile-10th-58-12th-60-and-bba-75-do-i-have-a-chance-to-get-admission-in-iim-bangalore-with-98-or-99-percentile-qna-5223003",
title: "My profile: 10th-58%, 12th-60% and BBA-75%. Do I have a chance to get admission in IIM, Bangalore with 98 or 99 percentile in CAT?",
answerOwnerName: "Naresh Jhawar",
answerOwnerLevel: "Contributor-Level 6",
answerOwnerImage: "",
likeCount: 0,
dislikeCount: 0,
threadStatus: null,
},
5235793: {
answerId: 5239435,
answerText: "There is no concept of stream in PGP course. ",
activityTime: "3 months ago",
answerOwnerUserId: 10088181,
questionId: 5235793,
aboutMe: null,
commentCount: 1,
msgCount: 2,
viewCount: 48,
status: "LIVE",
userId: 9104213,
firstname: "MARAPPAN",
lastname: "MARISH",
creationDate: "2019-02-02 16:10:21",
url: "https://ask.shikshatest03.infoedge.com/how-many-streams-are-available-in-mba-at-iim-bangalore-qna-5235793",
title: "How many streams are available in MBA at IIM, Bangalore?",
answerOwnerName: "Naresh Jhawar",
answerOwnerLevel: "Contributor-Level 6",
answerOwnerImage: "",
likeCount: 1,
dislikeCount: 0,
threadStatus: null,
},
},
allQuestionURL: "/college/iim-bangalore-indian-institute-of-management-iimb-bannerghatta-road-318/questions",
questionOrder: [
5235793,
5223003,
],
},
articleCount: 74,
alsoViewedInstitutes: [
{
instituteName: "SIBM - Symbiosis Institute Of Business Management Bengaluru",
instituteId: 36082,
instituteUrl: "/college/symbiosis-institute-of-business-management-bengaluru-hosur-road-bangalore-36082/placement",
imageUrl: "https://shikshatest05.infoedge.com/pwa/public/images/default-College.jpg",
cityName: "Bangalore",
establishYear: 2008,
courseName: null,
courseUrl: null,
courseId: 0,
listingType: "institute",
},
{
instituteName: "IIM Calcutta",
instituteId: 20190,
instituteUrl: "/college/iim-calcutta-joka-kolkata-20190/placement",
imageUrl: "https://shikshatest02.infoedge.com/mediadata/images/1488175508phpYJAn86_210x157.jpg",
cityName: "Kolkata",
establishYear: 1961,
courseName: null,
courseUrl: null,
courseId: 0,
listingType: "institute",
},
{
instituteName: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
instituteId: 307,
instituteUrl: "/college/iim-ahmedabad-indian-institute-of-management-iima-vastrapur-307/placement",
imageUrl: "https://shikshatest02.infoedge.com/mediadata/images/1554284228phpaM0XHz_210x157.png",
cityName: "Ahmedabad",
establishYear: 1961,
courseName: null,
courseUrl: null,
courseId: 0,
listingType: "institute",
},
{
instituteName: "IIM Indore - Indian Institute of Management",
instituteId: 29623,
instituteUrl: "/college/iim-indore-indian-institute-of-management-29623/placement",
imageUrl: "https://shikshatest02.infoedge.com/mediadata/images/1507532235php8lc7qJ_210x157.jpg",
cityName: "Indore",
establishYear: 1996,
courseName: null,
courseUrl: null,
courseId: 0,
listingType: "institute",
},
{
instituteName: "Indian School of Business",
instituteId: 28444,
instituteUrl: "/college/indian-school-of-business-gachibowli-hyderabad-28444/placement",
imageUrl: "https://shikshatest02.infoedge.com/mediadata/images/1488177209phpIlR6qx_210x157.jpg",
cityName: "Hyderabad",
establishYear: 2001,
courseName: null,
courseUrl: null,
courseId: 0,
listingType: "institute",
},
{
instituteName: "IIFT - Indian Institute Of Foreign Trade",
instituteId: 28559,
instituteUrl: "/university/indian-institute-of-foreign-trade-delhi-28559/placement",
imageUrl: "https://shikshatest05.infoedge.com/pwa/public/images/default-College.jpg",
cityName: "Delhi",
establishYear: 1963,
courseName: null,
courseUrl: null,
courseId: 0,
listingType: "university",
},
{
instituteName: "IMT - Institute Of Management Technology Ghaziabad",
instituteId: 255,
instituteUrl: "/college/imt-institute-of-management-technology-ghaziabad-255/placement",
imageUrl: "https://shikshatest02.infoedge.com/mediadata/images/1488176833php3V8jSZ_210x157.jpg",
cityName: "Ghaziabad",
establishYear: 1980,
courseName: null,
courseUrl: null,
courseId: 0,
listingType: "institute",
},
{
instituteName: "Rajiv Gandhi Indian Institute of Management",
instituteId: 23700,
instituteUrl: "/college/rajiv-gandhi-indian-institute-of-management-shillong-23700/placement",
imageUrl: "https://shikshatest05.infoedge.com/pwa/public/images/default-College.jpg",
cityName: "Shillong",
establishYear: 2008,
courseName: null,
courseUrl: null,
courseId: 0,
listingType: "institute",
},
{
instituteName: "SP Jain - Bharatiya Vidya Bhavan’s S.P. Jain Institute of Management and Research",
instituteId: 3489,
instituteUrl: "/college/sp-jain-bharatiya-vidya-bhavan-s-s-p-jain-institute-of-management-and-research-andheri-west-mumbai-3489/placement",
imageUrl: "https://shikshatest02.infoedge.com/mediadata/images/1497410025phpH7VjXr_210x157.jpg",
cityName: "Mumbai",
establishYear: 1981,
courseName: null,
courseUrl: null,
courseId: 0,
listingType: "institute",
},
{
instituteName: "XLRI - XLRI Xavier School Of Management",
instituteId: 28564,
instituteUrl: "/college/xlri-xavier-school-of-management-jamshedpur-28564/placement",
imageUrl: "https://shikshatest05.infoedge.com/pwa/public/images/default-College.jpg",
cityName: "Jamshedpur",
establishYear: 1949,
courseName: null,
courseUrl: null,
courseId: 0,
listingType: "institute",
},
],
flagshipCourseId: 1688,
scholarshipInfo: {
scholarShipDetails: [
{
listingId: 318,
description: "Indian Institute of Management, Bangalore offers/ participate in various scholarship to the PGP students: 1. Aditya Birla Scholarship - This merit-based scholarship of INR 1.75 lakh per student  is given to PGP students of both the first and the second years.  2. OPJEMS Scholarship - This merit-based scholarship of INR 1.50 lakh is given by the OP Jindal Group to one student of each academic year. 3. Societe Generale Global Solution Centre India Scholarship -  This is a means scholarship that covers tuition expenses in full. 4. IIMB PGP Alumni First Batch (1976) Scholarship -  This scholarship is for differently-abled women students. The scholarship aims to assist a differently-abled person (female) or a differently-abled person (male) if there is no female candidate. The scholarship carries a purse of INR 50,000, a medallion and a certificate.",
scholarship_type_id: 201,
scholarship_type_name: "Scholarship",
},
{
listingId: 318,
description: "Institute provides financial assistance to all PGP students with annual household income below INR 4,50,000. Other students with severe financial difficulties arising from sudden unforeseen circumstances are also considered.",
scholarship_type_id: 202,
scholarship_type_name: "Financial Assistance",
},
],
allScholarshipPageUrl: "/college/iim-bangalore-indian-institute-of-management-iimb-bannerghatta-road-318/scholarships",
},
recruitmentCompanies: [
{
companyName: "3M",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/3M.gif",
},
{
companyName: "A T Kearney",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/A_T_Kearney.jpg",
},
{
companyName: "Abbot",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/1411107551phpnYExWT.png",
},
{
companyName: "ACCENTURE",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/ACCENTURE.gif",
},
{
companyName: "Acura",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/1463980283phpYShDxR.png",
},
{
companyName: "Adani Group",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/1461041694php24uij1.jpeg",
},
{
companyName: "Aditya Birla Group",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/Aditya_Birla_Group.gif",
},
{
companyName: "Amazon",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/Amazon.gif",
},
{
companyName: "American Express",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/AmericanExpress.gif",
},
{
companyName: "Arthur D Little",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/Arthur_D_Little.gif",
},
{
companyName: "Arvind Brands",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/1450071942phpgT9mK6.jpeg",
},
{
companyName: "Asian Paints",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/AsianPaints.gif",
},
{
companyName: "Askmebazaar.com",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/1466486297phpvxjBc4.jpeg",
},
{
companyName: "AT Kearney",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/1457683984php6FDaSi.jpeg",
},
{
companyName: "AVIVA",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/AVIVA.gif",
},
{
companyName: "Axis Bank",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/AxisBank.gif",
},
{
companyName: "Barclays Capital",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/BarclaysCapital.gif",
},
{
companyName: "biocon",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/biocon.jpg",
},
{
companyName: "Capital One",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/Capital_One.gif",
},
{
companyName: "Citigroup",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/Citigroup.gif",
},
{
companyName: "Cognizant",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/CognizantTechnology.gif",
},
{
companyName: "DeloitteConsulting",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/DeloitteConsulting.gif",
},
{
companyName: "Deutsche Bank",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/DeutscheBank.gif",
},
{
companyName: "Google",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/1456721695phpyNVBaa.png",
},
{
companyName: "HDFC Bank",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/HDFC.gif",
},
{
companyName: "Heinz",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/Heinz.gif",
},
{
companyName: "Hindustan Unilever",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/HindustanUnilever.gif",
},
{
companyName: "HSBC",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/HSBC.gif",
},
{
companyName: "Hyundai",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/Hyundai.gif",
},
{
companyName: "IBM",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/IBM.gif",
},
{
companyName: "ICICI",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/ICICI.gif",
},
{
companyName: "ITC",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/ITC.gif",
},
{
companyName: "JP Morgan Chase",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/JPmorganChase.gif",
},
{
companyName: "McKinsey",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/McKinsey.gif",
},
{
companyName: "Morgan Stanley",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/morgan_stanley.jpg",
},
{
companyName: "Nerolac",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/Nerolac.gif",
},
{
companyName: "Nomura",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/Nomura.gif",
},
{
companyName: "Philips India",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/Philips_India.gif",
},
{
companyName: "Practo",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/1441955485phpZvXftq.png",
},
{
companyName: "Urban Clap",
logoUrl: "https://shikshatest02.infoedge.com/mediadata/images/1459143763phpE2k38V.png",
},
],
placements: {
type: "placements",
course: "1688",
course_type: "clientCourse",
avg_salary: 2142000,
batch_year: 2017,
max_salary: null,
median_salary: 2100000,
min_salary: null,
percentage_batch_placed: 100,
salary_unit: 1,
salary_unit_name: "INR",
total_international_offers: 13,
report_url: "https://shikshatest02.infoedge.com/mediadata/pdf/1507205159phpOdna35.pdf",
max_international_salary: null,
max_international_salary_unit: null,
max_international_salary_unit_name: null,
},
intership: {
type: "internship",
course: null,
course_type: null,
avg_salary: null,
batch_year: 2017,
max_salary: null,
median_salary: null,
min_salary: null,
percentage_batch_placed: null,
salary_unit: null,
salary_unit_name: null,
total_international_offers: null,
report_url: "https://shikshatest02.infoedge.com/mediadata/pdf/1507207099phpQk8bjB.pdf",
max_international_salary: null,
max_international_salary_unit: null,
max_international_salary_unit_name: null,
},
listingId: 318,
listingUrl: "/college/iim-bangalore-indian-institute-of-management-iimb-bannerghatta-road-318",
listingType: "institute",
allCourseUrl: "/college/iim-bangalore-indian-institute-of-management-iimb-bannerghatta-road-318/courses",
seoUrl: "/college/iim-bangalore-indian-institute-of-management-iimb-bannerghatta-road-318/placement",
seoData: {
instituteAdmissionUrl: null,
pageHeading: "IIM Bangalore - Indian Institute of Management (IIMB)",
headingName: "IIM Bangalore - Indian Institute of Management (IIMB)",
headingSuffix: " Placement - Highest & Average Salary Package",
scriptedText: null,
canonicalUrl: "/college/iim-bangalore-indian-institute-of-management-iimb-bannerghatta-road-318/placement",
metaTitle: "IIM Bangalore, Bannerghatta Road  Placement - Highest & Average Salary Package, Placement Companies & Internships Details",
metaDescription: "IIM Bangalore, Bannerghatta Road  placement details - 2142000 is average salary package in IIM Bangalore, Bannerghatta Road for  courses. Get full info on placement companies, internships & alumni employment details of  alumni at Shiksha.com.",
metaKeywords: null,
prevUrl: null,
nextUrl: null,
ampUrl: null,
},
anaCount: 280,
courseCount: 4,
listingName: "IIM Bangalore - Indian Institute of Management (IIMB)",
naukriData: {
completionYear: [
-1,
2016,
2017,
2018,
],
baseCourseIds: [
-1,
101,
0,
3,
137,
131,
50,
135,
86,
81,
102,
134,
84,
5,
1,
103,
33,
100,
6,
142,
132,
30,
26,
],
baseCourseObjects: {
1: {
baseCourseId: 1,
name: "B.A.",
alias: null,
url: "ba",
synonym: [
"Bachelor of Arts",
"bachelors",
],
level: 14,
credential: [
9
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
3: {
baseCourseId: 3,
name: "B.A. LL.B.",
alias: null,
url: "ba-llb",
synonym: [
"bachelors"
],
level: 14,
credential: [
9
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
5: {
baseCourseId: 5,
name: "B.Arch",
alias: null,
url: "barch",
synonym: [
"Bachelor of Architecture",
"Bachelors of Architecture",
],
level: 14,
credential: [
9
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
6: {
baseCourseId: 6,
name: "B.Com",
alias: null,
url: "bcom",
synonym: [
"Bachelor of Commerce",
"Bachelors of Commerce",
],
level: 14,
credential: [
9
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
26: {
baseCourseId: 26,
name: "B.Sc.",
alias: null,
url: "bsc",
synonym: [
"B-Sc",
"BS",
"B.S.",
"Bachelor in Science",
],
level: 14,
credential: [
9
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
30: {
baseCourseId: 30,
name: "BBA",
alias: null,
url: "bba",
synonym: [
"BBM",
"BMS",
"BBS. Bachelor of Business Administration",
],
level: 14,
credential: [
9
],
isDummy: 0,
isPopular: 1,
isHyperlocal: 0,
isExecutive: 0,
},
33: {
baseCourseId: 33,
name: "BCA",
alias: null,
url: "bca",
synonym: [
"Bachelor of Computer Application"
],
level: 14,
credential: [
9
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
50: {
baseCourseId: 50,
name: "CA",
alias: null,
url: "ca",
synonym: [
"Chartered Accountant",
"Chartered Accountancy",
],
level: 19,
credential: [
11
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 1,
isExecutive: 0,
},
81: {
baseCourseId: 81,
name: "LL.M.",
alias: null,
url: "llm",
synonym: [
"Master of Laws"
],
level: 15,
credential: [
9
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
84: {
baseCourseId: 84,
name: "M.Com",
alias: null,
url: "mcom",
synonym: [
"Master of Commerce"
],
level: 15,
credential: [
9
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
86: {
baseCourseId: 86,
name: "M.E./M.Tech",
alias: "M.Tech",
url: "me-mtech",
synonym: [
"M.E.",
"M.Tech",
"Master of Technology",
"Master of Engineering",
],
level: 15,
credential: [
9
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
100: {
baseCourseId: 100,
name: "M.Sc.",
alias: null,
url: "msc",
synonym: [
"MSc",
"M.Sc",
"M-Sc",
"MS",
"M.S.",
"Master of Science",
],
level: 15,
credential: [
9
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
101: {
baseCourseId: 101,
name: "MBA/PGDM",
alias: "MBA",
url: "mba-pgdm",
synonym: [
"MBA",
"PGDM",
"PGP",
"PGPM",
"PGPDM",
"PGPGM",
"Master in Business Administration",
],
level: 15,
credential: [
9,
10,
],
isDummy: 0,
isPopular: 1,
isHyperlocal: 0,
isExecutive: 0,
},
102: {
baseCourseId: 102,
name: "MBBS",
alias: null,
url: "mbbs",
synonym: [
"Bachelor of Medicine",
"Bachelor of Surgery",
],
level: 14,
credential: [
9
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
103: {
baseCourseId: 103,
name: "MCA",
alias: null,
url: "mca",
synonym: [
"Master of Computer Application"
],
level: 15,
credential: [
9
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
131: {
baseCourseId: 131,
name: "Other After 10th Degree",
alias: null,
url: "other-after-10th-degree",
synonym: [ ],
level: 13,
credential: [
9
],
isDummy: 1,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
132: {
baseCourseId: 132,
name: "Other UG Diploma",
alias: null,
url: "other-ug-diploma",
synonym: [ ],
level: 14,
credential: [
10
],
isDummy: 1,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
134: {
baseCourseId: 134,
name: "Other PG Diploma",
alias: null,
url: "other-pg-diploma",
synonym: [ ],
level: 15,
credential: [
10
],
isDummy: 1,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
135: {
baseCourseId: 135,
name: "Other PG Degree",
alias: null,
url: "other-pg-degree",
synonym: [ ],
level: 15,
credential: [
9
],
isDummy: 1,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
137: {
baseCourseId: 137,
name: "Other Advanced Masters Degree",
alias: null,
url: "other-advanced-masters-degree",
synonym: [ ],
level: 16,
credential: [
9
],
isDummy: 1,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
142: {
baseCourseId: 142,
name: "Other Certificate",
alias: null,
url: "other-certificate",
synonym: [ ],
level: 19,
credential: [
11
],
isDummy: 1,
isPopular: 0,
isHyperlocal: 1,
isExecutive: 0,
},
},
salaryData: {
minSalary: 8,
avgSalary: 14.35,
maxSalary: 37,
},
companyData: [
{
companyName: "Cognizant",
companyLogoFileName: "cognizant-technology-solutions.jpg",
numAlumni: 2,
avgSalary: 24.95,
},
{
companyName: "KPMG",
companyLogoFileName: "kpmg-global-services.jpg",
numAlumni: 3,
avgSalary: 15,
},
{
companyName: "Oracle",
companyLogoFileName: "NULL",
numAlumni: 2,
avgSalary: 14,
},
{
companyName: "Ericsson",
companyLogoFileName: "ericsson-india-global-services.jpg",
numAlumni: 2,
avgSalary: 10.4,
},
{
companyName: "KPMG Global Services",
companyLogoFileName: "NULL",
numAlumni: 2,
avgSalary: 9.8,
},
{
companyName: "Accenture",
companyLogoFileName: "accenture.jpg",
numAlumni: 2,
avgSalary: 7.85,
},
{
companyName: "Cognizant",
companyLogoFileName: "cognizant-technology-solutions.jpg",
numAlumni: 2,
avgSalary: 24.95,
},
{
companyName: "KPMG",
companyLogoFileName: "kpmg-global-services.jpg",
numAlumni: 3,
avgSalary: 15,
},
{
companyName: "Oracle",
companyLogoFileName: "NULL",
numAlumni: 2,
avgSalary: 14,
},
{
companyName: "Ericsson",
companyLogoFileName: "ericsson-india-global-services.jpg",
numAlumni: 2,
avgSalary: 10.4,
},
{
companyName: "KPMG Global Services",
companyLogoFileName: "NULL",
numAlumni: 2,
avgSalary: 9.8,
},
{
companyName: "Accenture",
companyLogoFileName: "accenture.jpg",
numAlumni: 2,
avgSalary: 7.85,
},
{
companyName: "Cognizant",
companyLogoFileName: "cognizant-technology-solutions.jpg",
numAlumni: 2,
avgSalary: 24.95,
},
{
companyName: "KPMG",
companyLogoFileName: "kpmg-global-services.jpg",
numAlumni: 3,
avgSalary: 15,
},
{
companyName: "Oracle",
companyLogoFileName: "NULL",
numAlumni: 2,
avgSalary: 14,
},
{
companyName: "Ericsson",
companyLogoFileName: "ericsson-india-global-services.jpg",
numAlumni: 2,
avgSalary: 10.4,
},
{
companyName: "KPMG Global Services",
companyLogoFileName: "NULL",
numAlumni: 2,
avgSalary: 9.8,
},
{
companyName: "Accenture",
companyLogoFileName: "accenture.jpg",
numAlumni: 2,
avgSalary: 7.85,
},
{
companyName: "Cognizant",
companyLogoFileName: "cognizant-technology-solutions.jpg",
numAlumni: 2,
avgSalary: 24.95,
},
{
companyName: "KPMG",
companyLogoFileName: "kpmg-global-services.jpg",
numAlumni: 3,
avgSalary: 15,
},
{
companyName: "Oracle",
companyLogoFileName: "NULL",
numAlumni: 2,
avgSalary: 14,
},
{
companyName: "Ericsson",
companyLogoFileName: "ericsson-india-global-services.jpg",
numAlumni: 2,
avgSalary: 10.4,
},
{
companyName: "KPMG Global Services",
companyLogoFileName: "NULL",
numAlumni: 2,
avgSalary: 9.8,
},
{
companyName: "Accenture",
companyLogoFileName: "accenture.jpg",
numAlumni: 2,
avgSalary: 7.85,
},
],
totalCompanies: 6,
},
currentLocation: {
listing_id: 318,
listing_location_id: 115642,
state_id: 106,
city_id: 278,
locality_id: 187,
state_name: "Karnataka",
city_name: "Bangalore",
locality_name: "Bannerghatta Road",
is_main: 1,
contact_details: {
listing_id: 318,
listing_location_id: 115642,
website_url: "http://www.iimb.ac.in/",
address: "Bannerghatta Road              ",
latitude: "12.8956",
longitude: "77.6025",
admission_contact_number: "08026582450",
admission_email: "info@iimb.ac.in",
generic_contact_number: "",
generic_email: "",
google_url: "https://shikshatest02.infoedge.com/mediadata/images/listingGoogle/listingLocationlive115642.jpg",
actual_listing_location_id: null,
},
},
aggregateReviewWidget: {
aggregateRatingDisplayOrder: {
avgSalaryPlacementRating: "Placements",
campusFacilitiesRating: "Infrastructure",
facultyRating: "Faculty & Course Curriculum",
crowdCampusRating: "Crowd & Campus Life",
moneyRating: "Worth the Money",
},
intervalsDisplayOrder: {
'4-5': ">4-5",
'3-4': ">3-4",
'2-3': ">2-3",
'1-2': "1-2",
},
ratingIdToDisplayNameMapping: {
1: "Worth the Money",
2: "Crowd & Campus Life",
3: "Placements",
4: "Infrastructure",
5: "Faculty & Course Curriculum",
6: "Infrastructure",
7: "Placements",
8: "Infrastructure",
9: "Infrastructure",
10: "Placements",
},
aggregateReviewData: {
totalCount: 9,
aggregateRating: {
averageRating: {
count: 9,
sum: 42.2,
mean: 4.7,
},
facultyRating: {
count: 9,
sum: 42,
mean: 4.7,
},
campusFacilitiesRating: {
count: 9,
sum: 41,
mean: 4.6,
},
avgSalaryPlacementRating: {
count: 9,
sum: 43,
mean: 4.8,
},
crowdCampusRating: {
count: 9,
sum: 42,
mean: 4.7,
},
moneyRating: {
count: 9,
sum: 43,
mean: 4.8,
},
},
intervalRatingCount: {
'1-2': 0,
'2-3': 0,
'3-4': 0,
'4-5': 9,
},
intervalRatingCountForPlacement: null,
},
},
admissionData: {
admissionDetails: null,
showAdmissionFlag: true,
url: "/college/iim-bangalore-indian-institute-of-management-iimb-bannerghatta-road-318/admission",
examList: [ ],
},
reviewWidget: {
pageType: "placement",
listingName: "IIM Bangalore - Indian Institute of Management (IIMB)",
listingUrl: "/college/iim-bangalore-indian-institute-of-management-iimb-bannerghatta-road-318",
instituteName: null,
instituteUrl: null,
reviewData: {
listingType: "institute",
reviewHeading: "Institute",
totalReviews: 14,
gaUserLevel: "Non-Logged In",
reviewsData: [
{
reviewId: 299353,
anonymousFlag: "NO",
averageRating: 4.6,
avgSalaryPlacementRating: 0,
campusFacilitiesRating: 0,
creationDate: "2018-07-26 15:26:36",
crowdCampusRating: 0,
facultyDescription: "Course curriculum in any MBA is almost the same where one has hectic schedule in the first term and which applies the same for IIM B too. We have quiz exams, mid terms and end terms along with projects and presentations in almost all the courses. Our batch strength is 430 and we have faculty of 109. ",
facultyRating: 0,
helpfulFlagCount: 17,
incentiveFlag: "0",
infraDescription: "Faculty in IIM B is around 109 and they are highly qualified with most of them holding one or two Ph.D. degrees. We have Wi-Fi access across the campus and classrooms are with CCTVs and projectors. We have one mess for the students which accommodate all of us with quality food and we have 4 different canteens in our campus.",
isShikshaInstitute: "YES",
postedDate: "2018-07-26 15:26:36",
moneyRating: 0,
notHelpfulFlagCount: 3,
placementDescription: "So I'm still in my first year but hearing from the seniors that placements are almost 100% for summers. There are diversified profiles here and people get placed into different sectors. All the top consult, finance and marketing (FMCG) firms visit our college.",
reason: 0,
recommendCollegeFlag: "YES",
reviewSeoTitle: null,
reviewSeoUrl: null,
reviewDescription: "",
reviewQuality: "average",
reviewSource: "utm_source=OysterConnect&utm_medium=Oysterconnect&utm_campaign=PreetiGautamJul18Group2=Akshita Rathod",
reviewTitle: "Delighted to be here because of the faculty and curriculum.",
status: "published",
userId: 0,
visitorSessionId: "41d272761e3ab9924261379a987e047a47e9437f20180726151551",
courseId: 1688,
instituteId: 318,
locationId: 115642,
yearOfGraduation: 2020,
reviewerId: 295853,
reviewerDetails: {
id: 295853,
userName: "Pavan",
email: "pavanchill29@gmail.com",
},
},
{
reviewId: 314449,
anonymousFlag: "NO",
averageRating: 4.8,
avgSalaryPlacementRating: 0,
campusFacilitiesRating: 0,
creationDate: "2018-09-11 19:56:32",
crowdCampusRating: 0,
facultyDescription: "The faculty in our college is another reason why students seek to study in the premier institutes. Such premier institutes are expected to host the best possible group of faculty for teaching. IIMB does a decent job at that. Although all the faculty members possess varied academic distinctions (having a range of academic publications, prior academic experience in other reputed institutes) or rich industry knowledge (having worked in an organisation or sector for good part of their lives) or both, only some are able to translate that to rich learning engagements for students in the class. At least, that has been my experience so far. One could assume a normal distribution in quality of professors where the small portion (~20%) are excellent, most of them (~60%) are average, and the remaining are not much good at their lectureship.",
facultyRating: 0,
helpfulFlagCount: 6,
incentiveFlag: "0",
infraDescription: "One of the perks of studying in such a premier institute of the nation is having access to the best institutional infrastructure. Be it in the academic space like labs, classrooms, library, etc., personal space like sports and fitness facilities, recreational facilities, etc., or related space like Wi-Fi, canteen and cafeteria food, medical facilities, etc., one gets access to the top-notch quality of systemic infrastructure. The high fees charged per student could be attributed as one of the primary factors contributing to such availing.",
isShikshaInstitute: "YES",
postedDate: "2018-09-11 19:56:32",
moneyRating: 0,
notHelpfulFlagCount: 0,
placementDescription: "The placement rate of IIMB has been pegging at 100% for many years now. The lateral and final placements for PGP class of 2016-18 saw 420 students receiving offers from 140+ companies, in India and abroad, across sectors. Similar was the case for summer placements of PGP 2017-19 batch, which I was a part of. Though I don't have ascertained information on absolute highest and lowest placement figures, the average has been consistently pegging at 20 LPA-22 LPA for the last couple of years. The offers were provided by domains such as consulting, marketing, banks and finance sector, general management, product management, supply chain management, human resource management etc. Top-tier firms from all of the aforementioned sectors participate in the placement process. The efficient placement cell of the institute makes sure of that.",
reason: 0,
recommendCollegeFlag: "YES",
reviewSeoTitle: null,
reviewSeoUrl: null,
reviewDescription: "IIM-B has a beautiful, lush green and eco-diverse campus. Being situated at Bangalore is another pro, climate and lifestyle-wise. The fests, though decent, are not as big as some of the engineering fests that one might have experienced earlier. The campus life is good, both academic and non-academic wise. Since the duration of the programme is short, the overall schedule is much more condensed and compact compared to an undergraduate programme.",
reviewQuality: "average",
reviewSource: "utm_source=OysterConnect&utm_medium=Oysterconnect&utm_campaign=PreetiGautamSep18Group2=Vijaya Bhanu Ayyapureddy",
reviewTitle: "Review of IIM, Bangalore.",
status: "published",
userId: 0,
visitorSessionId: "5c86f203f135798c247b11886d642d0b214f3c8e20180911195418",
courseId: 1688,
instituteId: 318,
locationId: 115642,
yearOfGraduation: 2019,
reviewerId: 310835,
reviewerDetails: {
id: 310835,
userName: "Akshaya",
email: "ssvmnk@yahoo.com",
},
},
{
reviewId: 127134,
anonymousFlag: "NO",
averageRating: 4.6,
avgSalaryPlacementRating: 0,
campusFacilitiesRating: 0,
creationDate: "2017-12-17 23:48:51",
crowdCampusRating: 0,
facultyDescription: "The faculty members are extremely down to earth and help the students in any way they can. They are well-qualified and are excellent in their respective research as well as in teaching. The batch is divided into six sections comprising of 70 students each. Each section is taught by six professors on average in a term(total six terms).",
facultyRating: 0,
helpfulFlagCount: 18,
incentiveFlag: "0",
infraDescription: "IIM, Bangalore boasts of excellent facilities and is perhaps the best campus in India currently to study in. The lush green campus coupled with the stone walls, make it one of the most beautiful campus to be found. There is a sports centre with the games including squash and a well-maintained gym. The classrooms are modern with the adequate technology.",
isShikshaInstitute: "YES",
postedDate: "2017-12-17 23:48:51",
moneyRating: 0,
notHelpfulFlagCount: 1,
placementDescription: "The placements (summer placements for PGP 2017-19) at IIM, Bangalore were good in general. All the students were placed within 2.5 days. The companies came from a variety of sectors. IIMB saw some first-time recruiters as well as the companies who took a gap last year. The list of companies can be found here on the website www dot iimb.ac. dot in/recruiters/whyrecruit (hyphen) iimb/our-recruiters. For a more detailed report on summer placements, please refer to the following report by IIM Bangalore on the website www.iimb.ac dot in/summer-placements -2017.                                        ",
reason: 0,
recommendCollegeFlag: "YES",
reviewSeoTitle: null,
reviewSeoUrl: null,
reviewDescription: "",
reviewQuality: "average",
reviewSource: "utm_source=cconnect&utm_medium=crnov2710&utm_campaign=7533091",
reviewTitle: "IIM, Bangalore is the place to be.",
status: "published",
userId: 0,
visitorSessionId: "003829c1813c68c4a159b85c2d93509add81f7ea20171217232227",
courseId: 1688,
instituteId: 318,
locationId: 115642,
yearOfGraduation: 2019,
reviewerId: 124425,
reviewerDetails: {
id: 124425,
userName: "Anirudh",
email: "anirudhagrawalykp@gmail.com",
},
},
{
reviewId: 120740,
anonymousFlag: "NO",
averageRating: 5,
avgSalaryPlacementRating: 0,
campusFacilitiesRating: 0,
creationDate: "2017-12-05 16:50:54",
crowdCampusRating: 0,
facultyDescription: "The faculty is world-class. We have teachers here who have studied in IIMs, MIT, Inseas, etc. We have some who have even taught in such high-class schools. There is also a process of regular feedback to make sure that the course and faculty are up-to-date.",
facultyRating: 0,
helpfulFlagCount: 14,
incentiveFlag: "0",
infraDescription: "One of the best infrastructures I have ever seen. The classes, mess, hostels everything is maintained very well. Every class has the necessary equipment like a projector, speaker, computer, etc. There are four separate places to eat including the mess, so you will never go hungry. The hostels are single accommodation and very tidy. The campus is simply beautiful. It's a pleasure to study in a place like this.",
isShikshaInstitute: "YES",
postedDate: "2017-12-05 16:50:54",
moneyRating: 0,
notHelpfulFlagCount: 0,
placementDescription: "The summer placements give the students a wide range of companies to choose and experiment type, so that they know in which field they would like to choose by the time of their final year placements come. For the process itself, a lot of help and guidance is given by the seniors and faculty, to ensure that you are ready to face the interviews and also the job.                                        ",
reason: 0,
recommendCollegeFlag: "YES",
reviewSeoTitle: null,
reviewSeoUrl: null,
reviewDescription: "A great diversity of the batch. You would meet people here from all walks of life. So, a lot to learn from everyone. There are more than 30 clubs about various activities to keep you engaged and give you a holistic development apart from the academics.",
reviewQuality: "average",
reviewSource: "utm_source=cconnect&utm_medium=crnov2710&utm_campaign=7527918",
reviewTitle: "IIM Bangalore - place to business.",
status: "published",
userId: 0,
visitorSessionId: "8f9fe4b07f4454e887f616cc53a7656de833e62d20171205163909",
courseId: 1688,
instituteId: 318,
locationId: 115642,
yearOfGraduation: 2019,
reviewerId: 118040,
reviewerDetails: {
id: 118040,
userName: "Varshika",
email: "arshi_crazycool@yahoo.co.in",
},
},
],
reviewRating: {
120740: {
reviewId: 120740,
ratingsMap: {
"Worth the Money": 5,
"Crowd & Campus Life": 5,
Placements: 5,
Infrastructure: 5,
"Faculty & Course Curriculum": 5,
},
},
127134: {
reviewId: 127134,
ratingsMap: {
"Worth the Money": 4,
"Crowd & Campus Life": 4,
Placements: 5,
Infrastructure: 5,
"Faculty & Course Curriculum": 5,
},
},
299353: {
reviewId: 299353,
ratingsMap: {
"Worth the Money": 4,
"Crowd & Campus Life": 5,
Placements: 5,
Infrastructure: 4,
"Faculty & Course Curriculum": 5,
},
},
314449: {
reviewId: 314449,
ratingsMap: {
"Worth the Money": 5,
"Crowd & Campus Life": 5,
Placements: 5,
Infrastructure: 5,
"Faculty & Course Curriculum": 4,
},
},
},
allReviewUrl: "/college/iim-bangalore-indian-institute-of-management-iimb-bannerghatta-road-318/reviews",
},
ratingDisplayOrder: [
"Placements",
"Infrastructure",
"Faculty & Course Curriculum",
"Crowd & Campus Life",
"Worth the Money",
],
courseInfo: {
1688: {
courseName: "Post Graduate Program in Management",
courseNameSuffix: "",
}
},
},
}