<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
*/
//$config['base_url']	= "http://127.0.0.1/CodeIgniter/";
//$port = ($_SERVER['SERVER_PORT'] =='') ? '' : ':'. $_SERVER['SERVER_PORT'] ;
$port='';
$config['base_url']    = "https://". $_SERVER['SERVER_NAME'] . $port .'/';


/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = "";

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of "AUTO" works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']	= "AUTO";

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = "";

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= "english";

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = "UTF-8";

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the "hooks" feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = TRUE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
//$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';
$config['permitted_uri_chars']= '';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string "words" that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['directory_trigger'] = 'd';	 // experimental not currently in use
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/logs/ folder.  Use a full server path with trailing slash.
|
*/
$config['log_path'] = 'system/logs/';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = 'system/cache/';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Sessions class with encryption
| enabled you MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = "shiksha";

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'session_cookie_name' = the name you want for the cookie
| 'encrypt_sess_cookie' = TRUE/FALSE (boolean).  Whether to encrypt the cookie
| 'session_expiration'  = the number of SECONDS you want the session to last.
|  by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']		= 'cisession';
$config['sess_expiration']		= 1800;
$config['sess_encrypt_cookie']	= TRUE;

$config['sess_table_name']		= 'ci_sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update'] 	= 300;
$config['encryption_key'] = "RT^&GT*&GTYTTtuad9uadsvf";

//For Database
$config['sess_use_database']	= TRUE;
$config['session_storage'] = "database";

//For Cookie
//$config['sess_use_database']	= FALSE;
//$config['session_storage'] = "cookie";

//For Memcache
//$config['sess_use_database']	= FALSE;
//$config['session_storage'] = "memcached";
//$config['sess_memcached_port'] = 0;
//$config['sess_memcached_nodes'] = array('unix:///tmp/memcached.sock');

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
|
*/
$config['cookie_prefix']	= "";
$config['cookie_domain']	= COOKIEDOMAIN;
$config['cookie_path']		= "/";

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = TRUE;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not "echo" any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are "local" or "gmt".  This pref tells the system whether to use
| your server's local time as the master "now" reference, or convert it to
| GMT.  See the "date helper" page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/

$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'shiksha_auth_token';
$config['csrf_cookie_name'] = 'shiksha_auth_token_name';
$config['csrf_expire'] = 3600;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';





/*
|--------------------------------------------------------------------------
| Date Limit for genereating SEO URL
|--------------------------------------------------------------------------
| getSEOURL function (url_helper.php) check into db and found that if object
| is created earlier date limit then it url will generate as per new schema
| otherwise it will render with default schema
*/

$config['seo_url_date_limit'] = '2011-02-11 21:00:00';

/* config var. to log db query taken time */
$config['db_query_execution_time_log'] = FALSE;
/* config var. to log db query taken time */
$config['db_query_execution_time_log_value'] = 5;

$config['modules_locations'] = array(
        APPPATH.'modules/AnA/'                         => '../modules/AnA/',
        APPPATH.'modules/AnA/Widgets/'                 => '../modules/AnA/Widgets/',
        APPPATH.'modules/Articles/'                    => '../modules/Articles/',
        APPPATH.'modules/Articles/Widgets/'            => '../modules/Articles/Widgets/',
        APPPATH.'modules/Common/'                      => '../modules/Common/',
        APPPATH.'modules/InternalApps/'                      => '../modules/InternalApps/',
        APPPATH.'modules/Common/Widgets/'              => '../modules/Common/Widgets/',
        APPPATH.'modules/Enterprise/'                  => '../modules/Enterprise/',
        APPPATH.'modules/Events/'                      => '../modules/Events/',
        APPPATH.'modules/Listing/'                     => '../modules/Listing/',
        APPPATH.'modules/Recommendations/'             => '../modules/Recommendations/',
        APPPATH.'modules/Mail/'                        => '../modules/Mail/',
        APPPATH.'modules/MMM/'                         => '../modules/MMM/',
        APPPATH.'modules/NotUsed/'                     => '../modules/NotUsed/',
        APPPATH.'modules/Search/'                      => '../modules/Search/',
        APPPATH.'modules/ShikshaHelp/'                 => '../modules/ShikshaHelp/',
        APPPATH.'modules/Sums/'                        => '../modules/Sums/',
        APPPATH.'modules/User/'                        => '../modules/User/',
        APPPATH.'modules/Events/Widgets/'              => '../modules/Events/Widgets/',
        APPPATH.'modules/OnlineForms/'                 => '../modules/OnlineForms/',
        APPPATH.'modules/mobileSite/'                  => '../modules/mobileSite/',
        APPPATH.'modules/mobileSite/mlisting/'         => '../modules/mobileSite/mlisting/',
        APPPATH.'modules/Ranking/'                     => '../modules/Ranking/',
        APPPATH.'modules/CareerProduct/'               => '../modules/CareerProduct/',
        APPPATH.'modules/mobileSite/messageBoard/'     => '../modules/mobileSite/messageBoard/',
        APPPATH.'modules/mobileSite5/'                 => '../modules/mobileSite5/',
        APPPATH.'modules/mobileSite5/mlisting5/'       => '../modules/mobileSite5/mlisting5/',
        APPPATH.'modules/mobileSite5/messageBoard5/'   => '../modules/mobileSite5/messageBoard5/',
        APPPATH.'modules/CoursePages/'                 => '../modules/CoursePages/',
        APPPATH.'modules/CampusAmbassador/'            => '../modules/CampusAmbassador/',
        APPPATH.'modules/CollegePredictor/'            => '../modules/CollegePredictor/',
        APPPATH.'modules/RankPredictor/'               => '../modules/RankPredictor/',
        APPPATH.'modules/CountryPages/'                 => '../modules/CountryPages/',
        APPPATH.'modules/mobileSite5/mcommon5/'        => '../modules/mobileSite5/mcommon5/',
        APPPATH.'modules/NaukriTool/'                  => '../modules/NaukriTool/',
        APPPATH.'modules/mobileSiteSA/'                => '../modules/mobileSiteSA/',
        APPPATH.'modules/mobileSite5/mNaukriTool5/'    => '../modules/mobileSite5/mNaukriTool5/',
        APPPATH.'modules/Consultant/'                  => '../modules/Consultant/',
        APPPATH.'modules/eventCalender/'               => '../modules/eventCalender/',
        APPPATH.'modules/mobileSite5/mEventCalendar5/' => '../modules/mobileSite5/mEventCalendar5/',
        APPPATH.'modules/API/user_api/'               => '../modules/API/user_api/',
        APPPATH.'modules/API/ana_api/'                => '../modules/API/ana_api/',
	APPPATH.'modules/API/universal_api/'          => '../modules/API/universal_api/',
        APPPATH.'modules/API/search_api/'             => '../modules/API/search_api/',
	APPPATH.'modules/API/tags_api/'              => '../modules/API/tags_api/',
        APPPATH.'modules/API/'                        => '../modules/API/',
	APPPATH.'modules/ShikshaApply/' 	      => '../modules/ShikshaApply/',
        APPPATH.'modules/SAEnterprise/'               => '../modules/SAEnterprise/',
        APPPATH.'modules/mobileSite5/mTag5'           => '../modules/mobileSite5/mTag5/',
        APPPATH.'modules/Scholarship/'                 => '../modules/Scholarship/',
    APPPATH.'modules/StudyAbroad/'                 => '../modules/StudyAbroad/'
    );

    $config['mobile_site_open'] = TRUE;

	/* GA Code Config */
	//$config['ga_code'] = "old"; // Old GA Code
	$config['ga_code'] = "new_minified"; // New GA Code
	//$config['ga_code'] = "new_src"; // New GA code non minified

/* End of file config.php */
/* Location: ./system/application/config/config.php */
