<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['palette_color'] = array(
                            array("R" => 0, "G" => 0, "B" =>255, "Alpha" => 100),
                            array("R" => 250, "G" => 0, "B" => 0, "Alpha" => 100),
                            array("R" => 250, "G" => 98, "B" =>237, "Alpha" => 100),
                            array("R" => 16,"G" => 16, "B" =>16, "Alpha" => 100),
                            array("R" => 128,"G" => 0, "B" =>128, "Alpha" => 100)
                            );

$config['page_name_title'] = array(
    'BLANK'                               		=>'BLANK',
    'SA_HOMEPAGE'                               =>'Study Abroad Home Page',
    'SA_UNIVERSITYPAGE'                         =>'Study Abroad University Listing Page',
    'SA_LISTINGPAGE'                            =>'Study Abroad Course Listing Page',
    'SA_CATEGORYPAGE'                           =>'Study Abroad Category Page',
    'SA_SHORTLISTPAGE'                          =>'Study Abroad Shortlist Page',
    'SA_COUNTRYPAGE'                            =>'Study Abroad Country Page',
    'SA_APPLYCONTENT'				=>'Study Abroad Apply Content Page',
    'SA_ARTICLEPAGE'                            =>'Study Abroad Article Page',
    'SA_GUIDEPAGE'                              =>'Study Abroad Guide Page',
    'SA_EXAMPAGE'				=>'Study Abroad Exam Page',
    'SA_SEARCHPAGE'                             =>'Study Abroad Search Page',
    'SA_SUCCESS_PAGE'				=>'Study Abroad RMC Success Page',
    'SA_LOGINPAGE'				=>'Study Abroad Login Page',
    'SA_PAGE_UNDEFINED'                         =>'Study Abroad Page Undefined',
    'SA_COUNTRYHOMEPAGE'                        =>'Study Abroad Country Home Page',
    'SA_APPLYHOMEPAGE'                          =>'Study Abroad Apply Home Page',
    'SA_COUNSELORPAGE'                          =>'Study Abroad Apply Counselor Page',
    'SA_SHIPMENTWELCOMEPAGE'                    =>'Study Abroad Shipment Welcome Page',
    'SA_SCHOLARSHIPDETAILPAGE'                  =>'Study Abroad Scholarship Detail Page',
    'SA_SCHOLARSHIPHOMEPAGE'                  =>'Study Abroad Scholarship Home Page',
    'home'                                      =>'Shiksha Home Page',
    'listing_detail_institute'                  =>'Institute Listing Page',
    'listing_detail_course'                     =>'Course Listing Page',
    'listing_detail'                            =>'Listing Detail',
    'category_listing'                          =>'Category Page',
    'ShortlistPage'                             =>'Shortlist Page',
    'MobileMyShortlistHomepage'                 =>'MyShortlist Homepage',
    'MobileMyShortlistCourseSnapshot'           =>'MyShortlist Course Snapshot',
    'MobileMyShortlistInstituteDetailsTabs'     =>'MyShortlist Institute Detail Tab',
    'MobileMyShortlistQuestionDetailPage'       =>'MyShortlist Question Detail Page',
    'MobileMyShortlistSearchByExam'             =>'MyShortlist Search By Exam Page',
    'article_detail_page'                       =>'Article Detail Page',
    'article_list_page'                         =>'Article List Page',
    'Mobile5ExamPage'                           =>'Exam Page',
    'SEARCH_HOME_PAGE'                          =>'Search Home Page',
    'SEARCH_RESULT_PAGE'                        =>'Search Result Page',
    'SEARCH_SIMILAR_COURSES_PAGE'               =>'Search Similar Course Page',
    'SEARCH_TOP_SEARCHES_PAGE'                  =>'Search Top Searches Page',
    'REFINE_LOCATION_SEARCH_PAGE'               =>'Refine Location Search Page',
    'REFINE_SEARCH_PAGE'                        =>'Refine Search Page',
    'college_predictor_branch'                  =>'College Predictor Branch',
    'college_predictor_cutoff'                  =>'College Predictor Cutoff',
    'college_predictor_rank'                    =>'College Predictor Rank',
    'College_review_homepage'                   =>'College Review Homepage',
    'College_review_intermediate'               =>'College Review Intermediate',
    'CampusConnectHomepage'                     =>'Campus Connect Home page',
    'CampusConnectIntermediatePage'             =>'Campus Connect Intermediate Page',
    'CAREER_COMPASS'                            =>'CAREER COMPASS',
    'ComparePage'                               =>'Compare Page',
    'Online_form_homepage'                      =>'Online Form Homepage',
    'ranking_page'                              =>'Ranking Page',
    'RANK_PREDICTOR'                            =>'Rank Predictor',
    'EVENT_CALENDAR'                            =>'Event Calendar',
    'login_page'                                =>'Login Page',
    'aboutUs'                                   =>'About Us',
);   

?>
