<?php 
$config['FIELD_ALIAS'] = array(
	//url
	"stream"         		=> "s",
	"substream"      		=> "sb",
	"specialization"     	=> "sp",
	"base_course"        	=> "bc",
	"education_type"     	=> "et",
	"delivery_method"       => "dm",
	"credential"        	=> "cr",
	"exam"               	=> "ex",
	"city"               	=> "ct",
	"affiliation"			=> "af",
	"state"              	=> "st",
	"locality"           	=> "lo",
	"fees"               	=> "fe",
	"popular_group"		 	=> "pg",
	"certificate_provider"	=> "cp",
	"course_level" 			=> "cl",
	"level_credential"		=> "lc",
	"approvals"				=> "ap",
	"grants"	 			=> "gr",
	"facilities"         	=> "fa",
	"college_ownership"		=> "co",
	"accreditation" 	 	=> "ac",
	"pageNumber"         	=> "pn",
	"sort_by"				=> "sby",
	"keyword"				=> "q",
	"trackingSearchId"	 	=> "ts",
	"trackingFilterId"	 	=> "tf",
	"requestFrom"		 	=> "rf",
	"oldKeyword"		 	=> "okw",
	"relevantResults"	 	=> "rr", 
	"searchedAttributes" 	=> "sa",
	"qerResults"         	=> "qer",
	"offered_by_college"	=> "ob",
	"twoStepClosedSearch"   => "tscs",
	"typedKeyword"		 	=> "tk",
	"isTrending"		 	=> "ist",
	"isInstituteMultiple"	=> "ism",
	"isInterim"				=> "ii",
	"filterBy"				=> "fb",
	"review" 				=> "rw",

	//facets
	"sub_spec"         				=> "ss",
	"sub_spec_parent"         		=> "ssp",
	"substream_parent"				=> "sbp",
	"et_dm"     					=> "ed",
	"et_dm_parent"					=> "edp",
	"credential_parent"    			=> "crp",
	"exam_parent"					=> "exp",
	"instt_course"					=> "ic",
	"city_parent"          			=> "ctp",
	"state_parent"         			=> "stp",
	"locality_parent"				=> "lop",
	"popular_group_parent" 			=> "pgp",
	"certificate_provider_parent"	=> "cpp",
	"base_course_parent"			=> "bcp",
	"specialization_parent"			=> "spp",
	"course_level_parent"			=> "clp",
	"level_credential_parent"		=> "lcp",
	"facilities_parent"    			=> "fap",
	"course_status"					=> "cs",
	"offered_by_college_parent"		=> "obp",
	"course_type_parent"			=> "ctyp",
	"course_type"					=> "cty",
	"course_status_parent"			=> "csp",
	"college_ownership_parent"		=> "cop",
	"accreditation_parent"			=> "acp",
	"approvals_parent" 				=> "app",
	"singleStreamClosedSearch" 		=> "sscs",
	"additionalFacetsToFetch"		=> "adff",
	"nl_course_review_rating_agg"   => "crra",
	
	//fl list
	"nl_institute_name"					=> "in",
	"nl_institute_id"					=> "id",
	"nl_course_id" 						=> "cd",
	"nl_course_name"					=> "cn",
	"nl_institute_type"					=> "it",
	"nl_entity_count_name_id_type_map"	=> "en",
	"nl_entity_quality_name_id_type_map"=> "eq",
	"nl_entity_tag_qna_count"			=> "ec",
	"nl_entity_url"						=> "url",
	"nl_stream_id"						=> "si",
	"nl_stream_name"					=> "sn",
	"nl_course_offered_by"				=> "cob",
	"nl_entity_creation_date"			=> "ncd",
	"nl_course_status_name_id_map"		=> "csi",
   );

$config['FILTERS_POSSIBLE'] = array('stream','substream','specialization','base_course','popular_group','certificate_provider','education_type','delivery_method','course_status','city','state','locality','facilities','course_level','exam','credential','offered_by_college','college_ownership','accreditation','approvals','grants','fees','sub_spec','et_dm','level_credential','review');

$config['FEES_RANGE'] = array(
							'f1'  => array('min'=>'1', 'max'=>'99999','placeholder'=> ' < 1 Lakh'),
							'f2'  => array('min'=>'100000', 'max'=>'199999','placeholder'=> '1 - 2 Lakh'),
							'f3'  => array('min'=>'200000', 'max'=>'299999','placeholder'=> '2 - 3 Lakh'),
							'f4'  => array('min'=>'300000', 'max'=>'499999','placeholder'=> '3 - 5 Lakh'),
							'f5'  => array('min'=>'500000', 'max'=> '*','placeholder'=> ' > 5 Lakh'),
						);

$config['RATING_RANGE'] = array(
							'r1'  => array('min'=>'1', 'max'=>'2','placeholder'=> '1-2 Stars'),
							'r2'  => array('min'=>'2.1', 'max'=>'3','placeholder'=> '> 2-3 Stars'),
							'r3'  => array('min'=>'3.1', 'max'=>'4','placeholder'=> '> 3-4 Stars'),
							'r4'  => array('min'=>'4.1', 'max'=>'5','placeholder'=> '> 4-5 Stars'),
						);


$config['FACETS_FILTER_MAPPING'] = array(
		'stream' => array(
				'default' => array(
						'location',
						'base_course',
						'review',
						'sub_spec',
						'credential',
						'course_level',
						'et_dm',
						'approvals',
						'course_status',
						'accreditation',
						'college_ownership',
						'fees',
						'exam',
						'facilities'
					)
			),

		'substream' => array(
				'default' => array(
						'location',
						'base_course',
						'review',
						'specialization',
						'course_level',
						'credential',
						'et_dm',
						'approvals',
						'course_status',
						'accreditation',
						'college_ownership',
						'fees',
						'exam',
						'facilities'
					)
			),

		'base_course' => array(
				'10' => array(
						'location',
						'specialization',
						'review',
						'exam',
						'course_status',
						'college_ownership',
						'fees',
						'approvals',
						'accreditation',
						'et_dm',
						'facilities'
					),

				'86' => array(
						'location',
						'specialization',
						'review',
						'course_status',
						'college_ownership',
						'fees',
						'approvals',
						'accreditation',
						'et_dm',
						'exam',
						'facilities'
					),

				'101' => array(
						'location',
						'specialization',
						'review',
						'exam',
						'course_status',
						'college_ownership',
						'fees',
						'approvals',
						'accreditation',
						'et_dm',
						'facilities'
					),

				'default' => array(
						'location',
						'specialization',
						'review',
						'course_status',
						'approvals',
						'accreditation',
						'college_ownership',
						'et_dm',
						'fees',
						'exam',
						'facilities',
					)
			),

		'all_courses' => array(
				'with_stream' => array(
						'offered_by_college',
						'sub_spec',
						'base_course',
						'course_level',
						'et_dm',
						'location'
					),

				'default' => array(
						'offered_by_college',
						'stream',
						'sub_spec',
						'base_course',
						'course_level',
						'et_dm',
						'location'
					),
			),

		'default' => array(
						'stream',
						'location'
					)
	);

$config['FACETS_ADVANCED_FILTER_MAPPING'] = array(
		'stream' => array(
				'1' => array(
						'base_course',
						'sub_spec',
						'et_dm',
					),
				'2' => array(
						'base_course',
						'sub_spec',
						'et_dm',
					),
				'3' => array(
						'base_course',
						'sub_spec',
					),
				'4' => array(
						'sub_spec',
						'base_course',
					),
				'5' => array(
						'base_course',
						'sub_spec',
					),
				'6' => array(
						'base_course',
						'sub_spec',
					),
				'7' => array(
						'base_course',
						'sub_spec',
					),
				'8' => array(
						'base_course',
						'sub_spec',
					),
				'9' => array(
						'base_course',
						'sub_spec',
					),
				'10' => array(
						'sub_spec',
						'base_course',
					),
				'11' => array(
						'base_course',
						'sub_spec',
					),
				'12' => array(
						'base_course',
						'sub_spec',
					),
				'13' => array(
						'base_course',
						'sub_spec',
					),
				'14' => array(
						'sub_spec',
						'et_dm',
					),
				'16' => array(
						'base_course',
						'sub_spec',
					),
			),

		'base_course' => array(
				'10' => array(
						'exam',
						'fees',
						'specialization',
					),
				'75' => array(
						'et_dm',
						'specialization',
						'exam',
					),
				'86' => array(
						'specialization',
						'exam',
					),
				'101' => array(
						'specialization',
						'exam',
						'fees',
					),
			),

		'default' => array()
);

$config['FACETS_GNB_FILTER_MAPPING'] = array(
		'stream' => array(
				'default' => array(
						'base_course',
						'sub_spec'
					)
			),
);

$config['COMBINED_FILTERS'] = array(
			'et_dm' => array(
							'education_type',
							'delivery_method'
						),
			'sub_spec' => array(
							'substream',
							'specialization'
						),
);

$config['FILTER_NAME_MAPPING'] = array(
		'stream'               => 'Streams',
		'offered_by_college'   => 'Colleges',
		'review'			   => 'Rating',
		'exam'                 => 'Exams Accepted',
		'location'             => 'Location',
		'course_level'         => 'Course Level',
		'credential'           => 'Credential',
		'et_dm'                => 'Mode of Study',
		'facilities'           => 'Facilities',
		'fees'                 => 'Total Fees',
		'base_course'          => 'Course',
		'sub_spec'             => 'Specialization',
		'specialization'       => 'Specialization',
		'substream'            => 'Substreams',
		'popular_group'        => 'Popular Groups',
		'certificate_provider' => 'Certificate Providers',
		'level_credential'     => 'Course Level',
		'course_status'        => 'Course Status',
		'accreditation'        => 'Accreditation',
		'college_ownership'    => 'Ownership',
	);
if(isMobileRequest()){
	$config['FILTER_NAME_MAPPING']['approvals'] = 'Approvals';
}
else{
	$config['FILTER_NAME_MAPPING']['approvals'] = 'Approvals / Recognition';
}

$config['virtual_city_mapping'] = array(10223 => array(74,84,87,95,146,161,166,181,1113,1616,2631,10632,10644,10645,10646,10647,10648,10649,10650,10653), //Delhi NCR
										10224 => array(151, 158, 838), //Mumbai
										12292 => array(63,12285,12286)
								);

$config['TRACKING_KEYS_IDS'] = "(67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,356,357,358,359,360,406,445,446,447,448,449,450,451,452,453,454,455,457,458,459,460,462,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,528,529,530,531,532,533,534,535,536,537,538,539,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,593,594,595,597,598,599,612,613,616,617,618,619,621,622,623,624,625,627,628,629,630,631,632,633,634,635,636,637,640,641,642,643,644,650,651,652,665,666,672,673,675,676,681,682,683,695,696,697,699,706,707,708,709,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,793,794,795,796,797,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,904,905,915,918,919,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1131,1132,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1208,1209,1210,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1233,1234,1235,1236,1237,1238,1239,1240,1241,1243,1244,1250,1251,1252,1253,1254,1255,1258,1259,1261,1262,1263,1265,1266,1267,1268,1269,1270,1271,1272,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1294,1295,1296,1297,1298,1299,1300,1301,1302,1303,1304,1305,1306,1307,1308,1312,1313,1314,1329,1330,1331,1332,1333,1334,1335,1336,1340,1341,1342,1343,1344,1345,1346,1347,1348,1349,1350,1351,1352,1353,1357,1358,1363,1364,1365,1366,1367,1368,1369,1370,1371,1372,1373,1374,1375,1376,1377,1378,1379,1381,1383,1385,1387,1389,1391,1393,1395,1397,1399,1409,1415,1417,1423,1425,1427,1429,1431)";

$config['EXAM_CHILD_PAGES'] = array("Dates", "Syllabus", "Results", "Pattern", "Question Papers", "Cut Off", "Admit Card", "Application Form", "Counselling", "Answer Key", "Slot Booking");

$config['SRP_TO_CTP_MAPPING'] = array(
    'stream' => array(
		'1' => '/business-management-studies/colleges/colleges-india',
		'2' => '/engineering/colleges/colleges-india',
		'3' => '/design/colleges/colleges-india',
		'4' => '/hospitality-travel/colleges/colleges-india',
		'5' => '/law/colleges/colleges-india',
		'6' => '/animation/colleges/colleges-india',
		'7' => '/mass-communication-media/colleges/colleges-india',
		'8' => '/it-software/colleges/colleges-india',
		'9' => '/humanities-social-sciences/colleges/colleges-india',
		'10' => '/arts-fine-visual-performing/colleges/colleges-india',
		'11' => '/science/colleges/colleges-india',
		'12' => '/architecture-planning/colleges/colleges-india',
		'13' => '/accounting-commerce/colleges/colleges-india',
		'14' => '/banking-finance-insurance/colleges/colleges-india',
		'15' => '/aviation/colleges/colleges-india',
		'16' => '/teaching-education/colleges/colleges-india',
		'17' => '/nursing/colleges/colleges-india',
		'18' => '/medicine-health-sciences/colleges/colleges-india',
		'19' => '/beauty-fitness/colleges/colleges-india',
    ),
    'substream' => array(
        '1' => '/animation/2d-3d-animation/colleges/colleges-india',
		'2' => '/accounting-commerce/accounting/colleges/colleges-india',
		'3' => '/mass-communication-media/advertising/colleges/colleges-india',
		'4' => '/it-software/ai-robotics/colleges/colleges-india',
		'5' => '/aviation/air-navigation-services/colleges/colleges-india',
		'6' => '/medicine-health-sciences/alternative-medicine/colleges/colleges-india',
		'7' => '/animation/animation-film-making/colleges/colleges-india',
		'8' => '/humanities-social-sciences/anthropology/colleges/colleges-india',
		'9' => '/arts-fine-visual-performing/applied-arts/colleges/colleges-india',
		'10' => '/humanities-social-sciences/archaeology/colleges/colleges-india',
		'11' => '/arts-fine-visual-performing/art-education/colleges/colleges-india',
		'12' => '/arts-fine-visual-performing/art-history-aesthetics/colleges/colleges-india',
		'13' => '/it-software/augmented-virtual-reality/colleges/colleges-india',
		'14' => '/beauty-fitness/beauty-culture-cosmetology/colleges/colleges-india',
		'15' => '/it-software/big-data-analytics/colleges/colleges-india',
		'16' => '/aviation/cabin-crew-air-hostess/colleges/colleges-india',
		'17' => '/it-software/cad-cam-cae/colleges/colleges-india',
		'18' => '/aviation/cargo-management/colleges/colleges-india',
		'19' => '/hospitality-travel/catering/colleges/colleges-india',
		'20' => '/arts-fine-visual-performing/ceramics/colleges/colleges-india',
		'22' => '/it-software/cloud-computing/colleges/colleges-india',
		'23' => '/it-software/cms-e-commerce-platforms/colleges/colleges-india',
		'24' => '/design/communication-design/colleges/colleges-india',
		'25' => '/humanities-social-sciences/communication-studies/colleges/colleges-india',
		'26' => '/architecture-planning/construction/colleges/colleges-india',
		'27' => '/it-software/crm/colleges/colleges-india',
		'28' => '/hospitality-travel/culinary-arts/colleges/colleges-india',
		'29' => '/arts-fine-visual-performing/dance-choreography/colleges/colleges-india',
		'30' => '/it-software/databases/colleges/colleges-india',
		'31' => '/arts-fine-visual-performing/decorative-arts/colleges/colleges-india',
		'32' => '/medicine-health-sciences/dental/colleges/colleges-india',
		'33' => '/medicine-health-sciences/dietics-nutrition/colleges/colleges-india',
		'34' => '/humanities-social-sciences/economics/colleges/colleges-india',
		'35' => '/architecture-planning/environmental/colleges/colleges-india',
		'36' => '/it-software/erp/colleges/colleges-india',
		'37' => '/hospitality-travel/event-management/colleges/colleges-india',
		'38' => '/hospitality-travel/fares-ticketing/colleges/colleges-india',
		'39' => '/design/fashion-design/colleges/colleges-india',
		'40' => '/mass-communication-media/film-tv/colleges/colleges-india',
		'41' => '/arts-fine-visual-performing/film-making/colleges/colleges-india',
		'42' => '/aviation/flying-pilot-training/colleges/colleges-india',
		'43' => '/it-software/game-design/colleges/colleges-india',
		'44' => '/humanities-social-sciences/geography/colleges/colleges-india',
		'45' => '/animation/graphic-web-design/colleges/colleges-india',
		'46' => '/arts-fine-visual-performing/graphics-art/colleges/colleges-india',
		'47' => '/aviation/ground-services/colleges/colleges-india',
		'48' => '/humanities-social-sciences/history/colleges/colleges-india',
		'49' => '/hospitality-travel/hotel-hospitality-management/colleges/colleges-india',
		'50' => '/design/industrial-product-design/colleges/colleges-india',
		'51' => '/architecture-planning/industrial-design/colleges/colleges-india',
		'52' => '/architecture-planning/infrastruture-housing/colleges/colleges-india',
		'53' => '/design/interior-design/colleges/colleges-india',
		'54' => '/it-software/it-service-management/colleges/colleges-india',
		'55' => '/mass-communication-media/journalism/colleges/colleges-india',
		'56' => '/architecture-planning/landscape/colleges/colleges-india',
		'57' => '/humanities-social-sciences/languages/colleges/colleges-india',
		'58' => '/humanities-social-sciences/library-information-science/colleges/colleges-india',
		'59' => '/humanities-social-sciences/linguistics/colleges/colleges-india',
		'60' => '/humanities-social-sciences/literature/colleges/colleges-india',
		'61' => '/beauty-fitness/massage-spa-therapy/colleges/colleges-india',
		'62' => '/medicine-health-sciences/medicine/colleges/colleges-india',
		'63' => '/teaching-education/middle-school/colleges/colleges-india',
		'64' => '/it-software/mobile-app-development/colleges/colleges-india',
		'65' => '/arts-fine-visual-performing/murals/colleges/colleges-india',
		'66' => '/arts-fine-visual-performing/music/colleges/colleges-india',
		'67' => '/mass-communication-media/music-sound-production/colleges/colleges-india',
		'68' => '/beauty-fitness/nail-body-art/colleges/colleges-india',
		'69' => '/it-software/networking-hardware-security/colleges/colleges-india',
		'70' => '/nursing/nursing-midwifery/colleges/colleges-india',
		'71' => '/it-software/office-suite/colleges/colleges-india',
		'72' => '/it-software/operating-systems/colleges/colleges-india',
		'73' => '/arts-fine-visual-performing/painting-drawing/colleges/colleges-india',
		'74' => '/medicine-health-sciences/paramedical/colleges/colleges-india',
		'75' => '/medicine-health-sciences/pharmacy/colleges/colleges-india',
		'76' => '/humanities-social-sciences/philosophy/colleges/colleges-india',
		'77' => '/arts-fine-visual-performing/photography/colleges/colleges-india',
		'78' => '/teaching-education/physical-education/colleges/colleges-india',
		'79' => '/medicine-health-sciences/physiotherapy/colleges/colleges-india',
		'80' => '/humanities-social-sciences/political-science/colleges/colleges-india',
		'81' => '/teaching-education/pre-primary-primary-school/colleges/colleges-india',
		'82' => '/it-software/programming/colleges/colleges-india',
		'83' => '/it-software/project-management/colleges/colleges-india',
		'84' => '/humanities-social-sciences/psychology/colleges/colleges-india',
		'85' => '/medicine-health-sciences/public-health-management/colleges/colleges-india',
		'86' => '/mass-communication-media/public-relations/colleges/colleges-india',
		'87' => '/it-software/quality-assurance-testing/colleges/colleges-india',
		'88' => '/mass-communication-media/radio/colleges/colleges-india',
		'89' => '/humanities-social-sciences/religious-studies/colleges/colleges-india',
		'90' => '/architecture-planning/rural-regional/colleges/colleges-india',
		'91' => '/humanities-social-sciences/rural-studies/colleges/colleges-india',
		'92' => '/arts-fine-visual-performing/sculpture/colleges/colleges-india',
		'93' => '/teaching-education/secondary-sr-secondary-school/colleges/colleges-india',
		'94' => '/humanities-social-sciences/social-work/colleges/colleges-india',
		'95' => '/humanities-social-sciences/sociology/colleges/colleges-india',
		'96' => '/animation/sound-video-editing/colleges/colleges-india',
		'97' => '/teaching-education/special-education/colleges/colleges-india',
		'98' => '/accounting-commerce/taxation/colleges/colleges-india',
		'99' => '/arts-fine-visual-performing/drama/colleges/colleges-india',
		'100' => '/architecture-planning/transport/colleges/colleges-india',
		'101' => '/hospitality-travel/travel-tourism/colleges/colleges-india',
		'102' => '/architecture-planning/urban/colleges/colleges-india',
		'103' => '/animation/vfx/colleges/colleges-india',
		'104' => '/teaching-education/vocational-education/colleges/colleges-india',
		'105' => '/beauty-fitness/yoga/colleges/colleges-india',
    ),

    'specialization' => array(
        '1' => '/it-software/colleges/dot-net-colleges-india',
		'2' => '/animation/2d-3d-animation/colleges/3ds-max-colleges-india',
		'3' => '/hospitality-travel/fares-ticketing/colleges/abacus-colleges-india',
		'5' => '/mass-communication-media/colleges/acting-colleges-india',
		'6' => '/science/colleges/actuarial-science-colleges-india',
		'7' => '/law/colleges/administrative-law-colleges-india',
		'9' => '/mba/colleges/mba-in-advertising-colleges-india',
		'10' => '/engineering/colleges/aeronautical-engineering-colleges-india',
		'11' => '/science/colleges/aeronautical-science-colleges-india',
		'12' => '/engineering/colleges/aerospace-engineering-colleges-india',
		'13' => '/humanities-social-sciences/colleges/aesthetics-colleges-india',
		'14' => '/it-software/colleges/agile-scrum-kanban-colleges-india',
		'15' => '/science/colleges/agriculture-colleges-india',
		'16' => '/engineering/colleges/agriculture-farm-engineering-colleges-india',
		'17' => '/mba/colleges/mba-in-agri-business-colleges-india',
		'18' => '/law/colleges/air-space-law-colleges-india',
		'19' => '/aviation/flying-pilot-training/colleges/aircraft-colleges-india',
		'20' => '/engineering/colleges/aircraft-maintenance-engineering-colleges-india',
		'21' => '/it-software/colleges/ajax-colleges-india',
		'24' => '/hospitality-travel/fares-ticketing/colleges/amadeus-colleges-india',
		'25' => '/it-software/colleges/amazon-ec2-colleges-india',
		'26' => '/medicine-health-sciences/paramedical/colleges/anaesthesia-technology-colleges-india',
		'27' => '/mass-communication-media/colleges/anchoring-reporting-colleges-india',
		'29' => '/humanities-social-sciences/colleges/ancient-history-colleges-india',
		'31' => '/it-software/colleges/android-colleges-india',
		'32' => '/it-software/colleges/ansys-colleges-india',
		'34' => '/it-software/colleges/apache-hadoop-colleges-india',
		'35' => '/design/fashion-design/colleges/apparel-design-colleges-india',
		'36' => '/humanities-social-sciences/colleges/applied-econometrics-colleges-india',
		'38' => '/humanities-social-sciences/colleges/applied-psychology-colleges-india',
		'39' => '/law/colleges/arbitration-law-colleges-india',
		'40' => '/it-software/colleges/assembly-language-colleges-india',
		'41' => '/science/colleges/astronomy-colleges-india',
		'42' => '/medicine-health-sciences/paramedical/colleges/audiology-speech-therapy-colleges-india',
		'43' => '/accounting-commerce/accounting/colleges/auditing-control-colleges-india',
		'44' => '/it-software/colleges/autocad-colleges-india',
		'45' => '/engineering/colleges/automobile-engineering-colleges-india',
		'46' => '/design/industrial-product-design/colleges/automotive-design-colleges-india',
		'48' => '/b-tech/colleges/b-tech-in-avionics-colleges-india',
		'49' => '/medicine-health-sciences/alternative-medicine/colleges/ayurved-colleges-india',
		'50' => '/hospitality-travel/culinary-arts/colleges/bakery-confectionery-colleges-india',
		'53' => '/law/colleges/banking-law-colleges-india',
		'54' => '/hospitality-travel/culinary-arts/colleges/bartending-colleges-india',
		'55' => '/arts-fine-visual-performing/dance-choreography/colleges/bhartnatayam-colleges-india',
		'56' => '/engineering/colleges/biochemical-engineering-colleges-india',
		'57' => '/science/colleges/biochemistry-colleges-india',
		'58' => '/science/colleges/bioinformatics-colleges-india',
		'59' => '/humanities-social-sciences/colleges/biological-anthropology-colleges-india',
		'61' => '/science/colleges/biology-colleges-india',
		'62' => '/engineering/colleges/biomedical-engineering-colleges-india',
		'63' => '/science/colleges/biotechnology-colleges-india',
		'64' => '/engineering/colleges/biotechnology-engineering-colleges-india',
		'65' => '/medicine-health-sciences/paramedical/colleges/blood-bank-technology-colleges-india',
		'66' => '/science/colleges/botany-colleges-india',
		'67' => '/mba/colleges/mba-in-business-economics-colleges-india',
		'68' => '/law/colleges/business-law-colleges-india',
		'69' => '/it-software/colleges/c-c-plus-plus-colleges-india',
		'70' => '/it-software/colleges/c-sharp-colleges-india',
		'71' => '/it-software/colleges/cadworx-colleges-india',
		'72' => '/arts-fine-visual-performing/graphics-art/colleges/calligraphy-colleges-india',
		'73' => '/mass-communication-media/colleges/camera-handling-lighting-colleges-india',
		'74' => '/mba/colleges/mba-in-capital-markets-colleges-india',
		'76' => '/medicine-health-sciences/paramedical/colleges/cardiovascular-technology-colleges-india',
		'77' => '/medicine-health-sciences/paramedical/colleges/cath-lab-technology-colleges-india',
		'79' => '/it-software/colleges/catia-colleges-india',
		'81' => '/design/industrial-product-design/colleges/ceramic-glass-design-colleges-india',
		'82' => '/engineering/colleges/ceramic-engineering-colleges-india',
		'83' => '/accounting-commerce/accounting/colleges/chartered-accountancy-colleges-india',
		'84' => '/engineering/colleges/chemical-engineering-colleges-india',
		'85' => '/science/colleges/chemistry-colleges-india',
		'86' => '/humanities-social-sciences/colleges/chinese-mandarin-colleges-india',
		'88' => '/humanities-social-sciences/colleges/christianity-colleges-india',
		'89' => '/mass-communication-media/colleges/cinematography-colleges-india',
		'90' => '/engineering/colleges/civil-engineering-colleges-india',
		'91' => '/law/colleges/civil-law-colleges-india',
		'92' => '/humanities-social-sciences/colleges/clinical-psychology-colleges-india',
		'93' => '/medicine-health-sciences/paramedical/colleges/clinical-research-colleges-india',
		'94' => '/medicine-health-sciences/paramedical/colleges/clinical-trials-colleges-india',
		'95' => '/it-software/colleges/cloud-databases-colleges-india',
		'96' => '/humanities-social-sciences/colleges/cognitive-psychology-colleges-india',
		'98' => '/law/colleges/commercial-law-colleges-india',
		'99' => '/mba/colleges/mba-in-commodity-currency-markets-colleges-india',
		'100' => '/engineering/colleges/communications-engineering-colleges-india',
		'102' => '/law/colleges/company-law-colleges-india',
		'103' => '/accounting-commerce/accounting/colleges/company-secretary-colleges-india',
		'104' => '/law/colleges/competition-law-colleges-india',
		'106' => '/arts-fine-visual-performing/graphics-art/colleges/computer-graphics-colleges-india',
		'107' => '/science/colleges/computer-science-colleges-india',
		'108' => '/engineering/colleges/computer-science-engineering-colleges-india',
		'110' => '/law/colleges/constitutional-law-colleges-india',
		'111' => '/engineering/colleges/construction-engineering-colleges-india',
		'112' => '/law/colleges/consumer-law-colleges-india',
		'114' => '/engineering/colleges/control-systems-colleges-india',
		'115' => '/it-software/colleges/coreldraw-colleges-india',
		'116' => '/mba/colleges/mba-in-corporate-banking-colleges-india',
		'117' => '/law/colleges/corporate-law-colleges-india',
		'118' => '/accounting-commerce/accounting/colleges/cost-management-accounting-colleges-india',
		'119' => '/law/colleges/criminal-law-colleges-india',
		'120' => '/humanities-social-sciences/colleges/criminology-colleges-india',
		'123' => '/hospitality-travel/culinary-arts/colleges/culinary-management-colleges-india',
		'124' => '/humanities-social-sciences/colleges/cultural-anthropology-colleges-india',
		'125' => '/law/colleges/cyber-law-colleges-india',
		'126' => '/mass-communication-media/colleges/cyber-media-colleges-india',
		'127' => '/it-software/colleges/cyber-security-colleges-india',
		'128' => '/science/colleges/dairy-science-colleges-india',
		'129' => '/engineering/colleges/dairy-technology-colleges-india',
		'130' => '/it-software/colleges/data-analytics-colleges-india',
		'131' => '/it-software/colleges/data-mining-colleges-india',
		'132' => '/it-software/colleges/data-visualization-colleges-india',
		'134' => '/mba/colleges/mba-in-debt-markets-colleges-india',
		'136' => '/mba/colleges/mba-in-derivatives-futures-options-colleges-india',
		'137' => '/humanities-social-sciences/colleges/development-psychology-colleges-india',
		'138' => '/medicine-health-sciences/paramedical/colleges/diabetology-colleges-india',
		'139' => '/medicine-health-sciences/paramedical/colleges/dialysis-technology-colleges-india',
		'140' => '/hospitality-travel/culinary-arts/colleges/dietetics-colleges-india',
		'141' => '/mba/colleges/mba-in-digital-marketing-colleges-india',
		'143' => '/mass-communication-media/colleges/direction-colleges-india',
		'144' => '/mba/colleges/mba-in-disaster-management-colleges-india',
		'145' => '/mass-communication-media/colleges/dj-colleges-india',
		'146' => '/it-software/colleges/distributed-algorithms-colleges-india',
		'147' => '/it-software/colleges/drupal-colleges-india',
		'148' => '/teaching-education/pre-primary-primary-school/colleges/early-childhood-care-education-ecce-colleges-india',
		'149' => '/science/colleges/earth-science-colleges-india',
		'150' => '/medicine-health-sciences/paramedical/colleges/echo-cardiology-cardiac-technology-colleges-india',
		'151' => '/humanities-social-sciences/colleges/econometrics-colleges-india',
		'153' => '/arts-fine-visual-performing/film-making/colleges/editing-colleges-india',
		'154' => '/law/colleges/education-law-colleges-india',
		'155' => '/humanities-social-sciences/colleges/educational-psychology-colleges-india',
		'156' => '/engineering/colleges/electrical-engineering-colleges-india',
		'157' => '/arts-fine-visual-performing/film-making/colleges/electronic-cinematography-colleges-india',
		'158' => '/mass-communication-media/colleges/electronic-media-tv-radio-online-colleges-india',
		'159' => '/science/colleges/electronics-colleges-india',
		'160' => '/engineering/colleges/electronics-communication-engineering-colleges-india',
		'161' => '/engineering/colleges/electronics-engineering-colleges-india',
		'162' => '/it-software/colleges/embedded-systems-vlsi-colleges-india',
		'164' => '/medicine-health-sciences/paramedical/colleges/emergency-medical-technology-colleges-india',
		'165' => '/mba/colleges/mba-in-energy-environment-colleges-india',
		'166' => '/law/colleges/energy-law-colleges-india',
		'167' => '/humanities-social-sciences/colleges/english-colleges-india',
		'168' => '/it-software/colleges/enterprise-java-beans-ejb-colleges-india',
		'169' => '/law/colleges/entertainment-media-law-colleges-india',
		'170' => '/mba/colleges/mba-in-entrepreneurship-colleges-india',
		'171' => '/engineering/colleges/environmental-engineering-colleges-india',
		'172' => '/humanities-social-sciences/colleges/environmental-geography-colleges-india',
		'173' => '/law/colleges/environmental-law-colleges-india',
		'174' => '/science/colleges/environmental-sciences-colleges-india',
		'178' => '/it-software/colleges/ethical-hacking-colleges-india',
		'179' => '/humanities-social-sciences/colleges/ethics-colleges-india',
		'180' => '/design/communication-design/colleges/exhibition-design-colleges-india',
		'181' => '/mba/colleges/mba-in-family-business-colleges-india',
		'182' => '/law/colleges/family-law-colleges-india',
		'183' => '/design/fashion-design/colleges/fashion-design-colleges-india',
		'184' => '/design/communication-design/colleges/film-video-design-colleges-india',
		'185' => '/mass-communication-media/colleges/film-making-colleges-india',
		'186' => '/mass-communication-media/colleges/film-studies-colleges-india',
		'187' => '/animation/animation-film-making/colleges/final-cut-pro-colleges-india',
		'188' => '/mba/colleges/mba-in-finance-colleges-india',
		'189' => '/mba/colleges/mba-in-financial-modelling-colleges-india',
		'190' => '/mba/colleges/mba-in-financial-planning-analysis-colleges-india',
		'192' => '/science/colleges/fisheries-science-colleges-india',
		'193' => '/aviation/ground-services/colleges/flight-operations-colleges-india',
		'194' => '/arts-fine-visual-performing/music/colleges/flute-colleges-india',
		'195' => '/arts-fine-visual-performing/music/colleges/folk-dance-colleges-india',
		'196' => '/hospitality-travel/hotel-hospitality-management/colleges/food-beverage-service-colleges-india',
		'197' => '/science/colleges/food-nutrition-colleges-india',
		'198' => '/hospitality-travel/culinary-arts/colleges/food-wine-harmony-colleges-india',
		'199' => '/hospitality-travel/culinary-arts/colleges/food-photography-food-writing-colleges-india',
		'200' => '/hospitality-travel/culinary-arts/colleges/food-production-colleges-india',
		'201' => '/hospitality-travel/culinary-arts/colleges/food-styling-presentation-colleges-india',
		'202' => '/engineering/colleges/food-technology-colleges-india',
		'203' => '/design/fashion-design/colleges/footwear-design-colleges-india',
		'205' => '/medicine-health-sciences/paramedical/colleges/forensic-medical-science-colleges-india',
		'206' => '/science/colleges/forensic-science-colleges-india',
		'207' => '/science/colleges/forestry-colleges-india',
		'208' => '/mba/colleges/part-time-mba-in-forex-management-colleges-india',
		'209' => '/humanities-social-sciences/colleges/french-colleges-india',
		'210' => '/hospitality-travel/hotel-hospitality-management/colleges/front-office-management-colleges-india',
		'211' => '/design/industrial-product-design/colleges/furniture-design-colleges-india',
		'212' => '/hospitality-travel/fares-ticketing/colleges/galileo-colleges-india',
		'213' => '/design/communication-design/colleges/game-design-colleges-india',
		'214' => '/mba/colleges/mba-in-general-insurance-colleges-india',
		'216' => '/engineering/colleges/genetic-engineering-colleges-india',
		'217' => '/science/colleges/genetics-colleges-india',
		'218' => '/science/colleges/geoinformatics-colleges-india',
		'219' => '/science/colleges/geology-colleges-india',
		'220' => '/humanities-social-sciences/colleges/geomatics-colleges-india',
		'221' => '/science/colleges/geophysics-colleges-india',
		'222' => '/humanities-social-sciences/colleges/german-colleges-india',
		'223' => '/law/colleges/gis-remote-sensing-law-colleges-india',
		'225' => '/hospitality-travel/culinary-arts/colleges/global-cuisine-gastronomy-colleges-india',
		'227' => '/design/communication-design/colleges/graphic-design-colleges-india',
		'228' => '/humanities-social-sciences/colleges/greek-colleges-india',
		'229' => '/aviation/ground-services/colleges/ground-staff-colleges-india',
		'230' => '/arts-fine-visual-performing/music/colleges/guitar-colleges-india',
		'231' => '/beauty-fitness/beauty-culture-cosmetology/colleges/hair-styling-grooming-colleges-india',
		'232' => '/beauty-fitness/beauty-culture-cosmetology/colleges/hand-feet-care-colleges-india',
		'233' => '/arts-fine-visual-performing/music/colleges/harmonium-colleges-india',
		'234' => '/medicine-health-sciences/public-health-management/colleges/health-information-administration-colleges-india',
		'235' => '/mba/colleges/mba-in-health-insurance-colleges-india',
		'236' => '/mba/colleges/mba-in-healthcare-hospital-colleges-india',
		'237' => '/law/colleges/healthcare-law-colleges-india',
		'239' => '/aviation/flying-pilot-training/colleges/helicopter-colleges-india',
		'240' => '/humanities-social-sciences/colleges/hinduism-colleges-india',
		'241' => '/arts-fine-visual-performing/music/colleges/hindustani-classical-vocals-colleges-india',
		'242' => '/arts-fine-visual-performing/dance-choreography/colleges/hip-hop-colleges-india',
		'244' => '/science/colleges/home-science-colleges-india',
		'245' => '/medicine-health-sciences/alternative-medicine/colleges/homeopathy-colleges-india',
		'246' => '/science/colleges/horticulture-colleges-india',
		'247' => '/medicine-health-sciences/public-health-management/colleges/hospital-healthcare-management-colleges-india',
		'248' => '/hospitality-travel/hotel-hospitality-management/colleges/house-keeping-colleges-india',
		'249' => '/it-software/colleges/html-css-colleges-india',
		'251' => '/mba/colleges/mba-in-human-resources-colleges-india',
		'252' => '/law/colleges/human-rights-international-humanitarian-law-colleges-india',
		'253' => '/arts-fine-visual-performing/graphics-art/colleges/illustration-colleges-india',
		'254' => '/animation/graphic-web-design/colleges/illustrator-colleges-india',
		'255' => '/law/colleges/immigration-law-colleges-india',
		'256' => '/medicine-health-sciences/paramedical/colleges/immunology-colleges-india',
		'257' => '/mba/colleges/mba-in-import-export-colleges-india',
		'258' => '/accounting-commerce/taxation/colleges/income-tax-colleges-india',
		'259' => '/hospitality-travel/culinary-arts/colleges/indian-cuisine-culture-colleges-india',
		'260' => '/accounting-commerce/taxation/colleges/indirect-taxation-colleges-india',
		'261' => '/engineering/colleges/industrial-engineering-colleges-india',
		'263' => '/design/communication-design/colleges/information-design-colleges-india',
		'264' => '/engineering/colleges/information-technology-colleges-india',
		'265' => '/law/colleges/information-technology-law-colleges-india',
		'266' => '/mba/colleges/mba-in-infrastructure-colleges-india',
		'267' => '/engineering/colleges/instrumentation-technology-colleges-india',
		'268' => '/law/colleges/insurance-law-colleges-india',
		'269' => '/law/colleges/intellectual-property-law-colleges-india',
		'270' => '/accounting-commerce/accounting/colleges/internal-audit-colleges-india',
		'271' => '/law/colleges/international-international-trade-law-colleges-india',
		'272' => '/accounting-commerce/accounting/colleges/international-accounting-colleges-india',
		'273' => '/mba/colleges/mba-in-international-banking-colleges-india',
		'274' => '/mba/colleges/mba-in-international-business-colleges-india',
		'275' => '/humanities-social-sciences/colleges/international-economics-colleges-india',
		'276' => '/humanities-social-sciences/colleges/international-relations-colleges-india',
		'278' => '/mba/colleges/mba-in-investment-banking-colleges-india',
		'279' => '/mba/colleges/mba-in-investment-operations-colleges-india',
		'280' => '/it-software/colleges/ios-colleges-india',
		'281' => '/humanities-social-sciences/colleges/islam-colleges-india',
		'282' => '/mba/colleges/mba-in-islamic-banking-finance-colleges-india',
		'283' => '/mba/colleges/mba-in-it-systems-colleges-india',
		'284' => '/hospitality-travel/travel-tourism/colleges/itinerary-planning-colleges-india',
		'285' => '/it-software/colleges/j2ee-colleges-india',
		'286' => '/it-software/colleges/j2se-colleges-india',
		'287' => '/humanities-social-sciences/colleges/japanese-colleges-india',
		'288' => '/it-software/colleges/java-colleges-india',
		'289' => '/it-software/colleges/java-struts-colleges-india',
		'290' => '/it-software/colleges/javascript-colleges-india',
		'292' => '/design/fashion-design/colleges/jewellery-design-colleges-india',
		'294' => '/it-software/colleges/joomla-colleges-india',
		'295' => '/engineering/colleges/jute-fiber-technology-colleges-india',
		'296' => '/arts-fine-visual-performing/dance-choreography/colleges/kathak-colleges-india',
		'298' => '/design/fashion-design/colleges/knitwear-design-colleges-india',
		'299' => '/arts-fine-visual-performing/dance-choreography/colleges/kuchipudi-colleges-india',
		'300' => '/law/colleges/labor-employment-law-colleges-india',
		'302' => '/humanities-social-sciences/colleges/latin-colleges-india',
		'303' => '/it-software/colleges/lean-colleges-india',
		'304' => '/design/fashion-design/colleges/leather-design-colleges-india',
		'305' => '/mba/colleges/mba-in-life-insurance-colleges-india',
		'306' => '/design/fashion-design/colleges/lifestyle-accesory-design-colleges-india',
		'307' => '/it-software/colleges/linux-colleges-india',
		'310' => '/humanities-social-sciences/colleges/logic-colleges-india',
		'312' => '/humanities-social-sciences/colleges/macroeconomics-colleges-india',
		'313' => '/it-software/colleges/magento-colleges-india',
		'315' => '/beauty-fitness/beauty-culture-cosmetology/colleges/makeup-beautician-colleges-india',
		'316' => '/engineering/colleges/marine-engineering-colleges-india',
		'318' => '/mba/colleges/mba-in-materials-management-colleges-india',
		'319' => '/engineering/colleges/materials-science-colleges-india',
		'321' => '/science/colleges/mathematics-colleges-india',
		'322' => '/it-software/colleges/matlab-colleges-india',
		'323' => '/animation/2d-3d-animation/colleges/maya-colleges-india',
		'324' => '/engineering/colleges/mechanical-engineering-colleges-india',
		'325' => '/engineering/colleges/mechatronics-engineering-colleges-india',
		'326' => '/mass-communication-media/colleges/media-planning-colleges-india',
		'328' => '/medicine-health-sciences/paramedical/colleges/medical-laboratory-technology-colleges-india',
		'329' => '/medicine-health-sciences/paramedical/colleges/medical-record-technology-colleges-india',
		'331' => '/medicine-health-sciences/paramedical/colleges/medical-transcription-colleges-india',
		'332' => '/humanities-social-sciences/colleges/medieval-colleges-india',
		'334' => '/engineering/colleges/metallurgical-engineering-colleges-india',
		'335' => '/humanities-social-sciences/colleges/metaphysics-colleges-india',
		'336' => '/science/colleges/microbiology-colleges-india',
		'337' => '/humanities-social-sciences/colleges/microeconomics-colleges-india',
		'338' => '/engineering/colleges/microelectronics-colleges-india',
		'339' => '/it-software/colleges/microsoft-azure-colleges-india',
		'342' => '/engineering/colleges/mining-engineering-colleges-india',
		'343' => '/mass-communication-media/colleges/modelling-colleges-india',
		'345' => '/humanities-social-sciences/colleges/modern-history-colleges-india',
		'346' => '/humanities-social-sciences/colleges/modern-philosophy-colleges-india',
		'348' => '/arts-fine-visual-performing/music/colleges/mridangam-colleges-india',
		'349' => '/it-software/colleges/ms-bi-ssas-colleges-india',
		'350' => '/it-software/colleges/ms-bi-ssis-colleges-india',
		'351' => '/it-software/colleges/ms-bi-ssrs-colleges-india',
		'352' => '/it-software/colleges/ms-excel-colleges-india',
		'354' => '/it-software/colleges/ms-word-colleges-india',
		'355' => '/mba/colleges/mba-in-mutual-funds-colleges-india',
		'356' => '/engineering/colleges/nanotechnology-colleges-india',
		'358' => '/arts-fine-visual-performing/dance-choreography/colleges/nattuvangam-colleges-india',
		'359' => '/medicine-health-sciences/alternative-medicine/colleges/naturopathy-colleges-india',
		'360' => '/engineering/colleges/naval-architecture-colleges-india',
		'363' => '/it-software/colleges/network-administration-colleges-india',
		'364' => '/medicine-health-sciences/paramedical/colleges/neuro-physiology-colleges-india',
		'365' => '/humanities-social-sciences/colleges/neuro-psychology-colleges-india',
		'367' => '/it-software/colleges/newsql-databases-colleges-india',
		'368' => '/mba/colleges/mba-in-ngo-management-colleges-india',
		'369' => '/it-software/colleges/nosql-databases-colleges-india',
		'370' => '/engineering/colleges/nuclear-engineering-colleges-india',
		'371' => '/law/colleges/nuclear-law-colleges-india',
		'372' => '/medicine-health-sciences/paramedical/colleges/nuclear-medicine-technology-colleges-india',
		'374' => '/teaching-education/pre-primary-primary-school/colleges/nursery-teacher-training-ntt-colleges-india',
		'378' => '/medicine-health-sciences/paramedical/colleges/occupational-therapy-colleges-india',
		'379' => '/engineering/colleges/ocean-engineering-colleges-india',
		'380' => '/science/colleges/oceanography-colleges-india',
		'381' => '/arts-fine-visual-performing/dance-choreography/colleges/odissi-colleges-india',
		'382' => '/mba/colleges/mba-in-oil-gas-colleges-india',
		'384' => '/medicine-health-sciences/paramedical/colleges/operation-theatre-technology-colleges-india',
		'385' => '/mba/colleges/mba-in-operations-colleges-india',
		'386' => '/medicine-health-sciences/paramedical/colleges/opthalmic-technology-colleges-india',
		'387' => '/medicine-health-sciences/paramedical/colleges/optometry-colleges-india',
		'388' => '/it-software/colleges/oracle-crm-colleges-india',
		'389' => '/it-software/colleges/oracle-erp-colleges-india',
		'392' => '/hospitality-travel/culinary-arts/colleges/patisserie-colleges-india',
		'393' => '/accounting-commerce/accounting/colleges/payroll-colleges-india',
		'395' => '/medicine-health-sciences/paramedical/colleges/perfusion-technology-colleges-india',
		'396' => '/it-software/colleges/perl-colleges-india',
		'397' => '/humanities-social-sciences/colleges/personnel-management-colleges-india',
		'398' => '/engineering/colleges/petroleum-engineering-colleges-india',
		'399' => '/mba/colleges/mba-in-pharma-colleges-india',
		'400' => '/engineering/colleges/pharmaceutical-engineering-colleges-india',
		'401' => '/animation/graphic-web-design/colleges/photoshop-colleges-india',
		'402' => '/it-software/colleges/php-colleges-india',
		'403' => '/humanities-social-sciences/colleges/physical-geography-colleges-india',
		'404' => '/medicine-health-sciences/paramedical/colleges/physician-assistant-colleges-india',
		'405' => '/science/colleges/physics-colleges-india',
		'406' => '/arts-fine-visual-performing/music/colleges/piano-colleges-india',
		'407' => '/it-software/colleges/pl-sql-colleges-india',
		'410' => '/humanities-social-sciences/colleges/politics-colleges-india',
		'412' => '/engineering/colleges/polymer-technology-colleges-india',
		'413' => '/engineering/colleges/power-engineering-colleges-india',
		'415' => '/teaching-education/pre-primary-primary-school/colleges/pre-primary-teacher-training-pptt-colleges-india',
		'416' => '/teaching-education/pre-primary-primary-school/colleges/primary-teacher-training-ptt-colleges-india',
		'417' => '/mass-communication-media/colleges/print-media-colleges-india',
		'418' => '/arts-fine-visual-performing/graphics-art/colleges/printmaking-colleges-india',
		'419' => '/it-software/colleges/pro-e-colleges-india',
		'420' => '/mass-communication-media/colleges/production-design-colleges-india',
		'421' => '/engineering/colleges/production-engineering-colleges-india',
		'422' => '/mba/colleges/mba-in-project-management-colleges-india',
		'424' => '/humanities-social-sciences/colleges/public-administration-colleges-india',
		'425' => '/medicine-health-sciences/public-health-management/colleges/public-health-colleges-india',
		'426' => '/humanities-social-sciences/political-science/colleges/public-policy-colleges-india',
		'427' => '/engineering/colleges/pulp-paper-technology-colleges-india',
		'428' => '/it-software/colleges/python-colleges-india',
		'429' => '/it-software/colleges/qtp-colleges-india',
		'430' => '/it-software/colleges/r-programming-colleges-india',
		'431' => '/mass-communication-media/colleges/radio-jockeying-colleges-india',
		'432' => '/mass-communication-media/colleges/radio-production-colleges-india',
		'433' => '/medicine-health-sciences/paramedical/colleges/radiology-imaging-science-colleges-india',
		'434' => '/medicine-health-sciences/paramedical/colleges/radiotherapy-technology-colleges-india',
		'435' => '/arts-fine-visual-performing/music/colleges/ravindra-sangeet-shastra-colleges-india',
		'436' => '/law/colleges/real-estate-infrastructure-law-colleges-india',
		'437' => '/medicine-health-sciences/paramedical/colleges/rehabilitation-colleges-india',
		'438' => '/it-software/colleges/relational-dbms-colleges-india',
		'439' => '/medicine-health-sciences/paramedical/colleges/respiratory-care-technology-colleges-india',
		'440' => '/mba/colleges/mba-in-retail-colleges-india',
		'441' => '/mba/colleges/mba-in-retail-banking-colleges-india',
		'442' => '/it-software/colleges/revit-lt-suite-colleges-india',
		'443' => '/engineering/colleges/rf-microwave-engineering-colleges-india',
		'444' => '/mba/colleges/mba-in-risk-management-colleges-india',
		'445' => '/engineering/colleges/robotics-engineering-colleges-india',
		'446' => '/engineering/colleges/rubber-technology-colleges-india',
		'447' => '/it-software/colleges/ruby-colleges-india',
		'448' => '/mba/colleges/mba-in-rural-management-colleges-india',
		'449' => '/hospitality-travel/fares-ticketing/colleges/sabre-colleges-india',
		'451' => '/mba/colleges/mba-in-sales-marketing-colleges-india',
		'452' => '/arts-fine-visual-performing/dance-choreography/colleges/salsa-colleges-india',
		'453' => '/it-software/colleges/sap-crm-colleges-india',
		'454' => '/it-software/colleges/sap-erp-colleges-india',
		'455' => '/arts-fine-visual-performing/music/colleges/sarod-colleges-india',
		'457' => '/mass-communication-media/colleges/screenplay-writing-colleges-india',
		'458' => '/mass-communication-media/colleges/script-writing-colleges-india',
		'459' => '/law/colleges/security-investment-law-colleges-india',
		'460' => '/it-software/colleges/selenium-colleges-india',
		'461' => '/science/colleges/sericulture-colleges-india',
		'462' => '/it-software/colleges/server-administration-colleges-india',
		'464' => '/it-software/colleges/signal-processing-colleges-india',
		'467' => '/arts-fine-visual-performing/music/colleges/sitar-colleges-india',
		'468' => '/it-software/colleges/six-sigma-colleges-india',
		'471' => '/humanities-social-sciences/colleges/social-psychology-colleges-india',
		'473' => '/engineering/colleges/soil-water-conservation-engineering-colleges-india',
		'474' => '/it-software/colleges/solidworks-colleges-india',
		'475' => '/mass-communication-media/colleges/sound-design-colleges-india',
		'476' => '/mass-communication-media/colleges/sound-editing-colleges-india',
		'477' => '/mass-communication-media/colleges/sound-engineering-colleges-india',
		'478' => '/mass-communication-media/colleges/sound-recording-colleges-india',
		'479' => '/humanities-social-sciences/colleges/spanish-colleges-india',
		'480' => '/mba/colleges/mba-in-sports-colleges-india',
		'482' => '/it-software/colleges/staad-colleges-india',
		'483' => '/science/colleges/statistics-colleges-india',
		'484' => '/mba/colleges/mba-in-stock-analysis-trading-colleges-india',
		'485' => '/engineering/colleges/structural-engineering-colleges-india',
		'487' => '/mba/colleges/mba-in-supply-chain-colleges-india',
		'488' => '/medicine-health-sciences/paramedical/colleges/surgical-technology-colleges-india',
		'490' => '/it-software/colleges/switching-routing-colleges-india',
		'492' => '/arts-fine-visual-performing/music/colleges/tabla-colleges-india',
		'493' => '/it-software/colleges/tally-colleges-india',
		'494' => '/law/colleges/tax-law-colleges-india',
		'495' => '/it-software/colleges/tcp-internet-protocols-colleges-india',
		'496' => '/mba/colleges/mba-in-telecom-colleges-india',
		'497' => '/engineering/colleges/telecommunication-engineering-colleges-india',
		'499' => '/aviation/ground-services/colleges/terminal-operations-management-colleges-india',
		'500' => '/design/fashion-design/colleges/textile-design-colleges-india',
		'501' => '/engineering/colleges/textile-engineering-colleges-india',
		'502' => '/mba/colleges/mba-in-textile-management-colleges-india',
		'503' => '/arts-fine-visual-performing/drama/colleges/theatre-techniques-design-colleges-india',
		'504' => '/humanities-social-sciences/colleges/theology-colleges-india',
		'506' => '/engineering/colleges/tool-engineering-colleges-india',
		'507' => '/hospitality-travel/travel-tourism/colleges/tour-management-colleges-india',
		'508' => '/hospitality-travel/travel-tourism/colleges/tour-operations-colleges-india',
		'509' => '/hospitality-travel/travel-tourism/colleges/tourism-studies-colleges-india',
		'510' => '/design/industrial-product-design/colleges/toy-design-colleges-india',
		'511' => '/mba/colleges/mba-in-transport-logistics-colleges-india',
		'512' => '/engineering/colleges/transportation-engineering-colleges-india',
		'513' => '/hospitality-travel/travel-tourism/colleges/travel-tourism-management-colleges-india',
		'514' => '/arts-fine-visual-performing/graphics-art/colleges/typography-colleges-india',
		'515' => '/design/communication-design/colleges/ui-ux-colleges-india',
		'516' => '/medicine-health-sciences/alternative-medicine/colleges/unani-colleges-india',
		'517' => '/it-software/colleges/unix-colleges-india',
		'518' => '/it-software/colleges/unix-shell-scripting-colleges-india',
		'519' => '/it-software/colleges/vc-plus-plus-colleges-india',
		'520' => '/arts-fine-visual-performing/music/colleges/veena-colleges-india',
		'521' => '/mass-communication-media/colleges/video-editing-post-production-colleges-india',
		'522' => '/arts-fine-visual-performing/music/colleges/violin-colleges-india',
		'523' => '/it-software/colleges/virtualization-colleges-india',
		'524' => '/it-software/colleges/visual-basic-colleges-india',
		'525' => '/mass-communication-media/colleges/visual-communication-colleges-india',
		'526' => '/design/fashion-design/colleges/visual-merchandising-colleges-india',
		'527' => '/engineering/colleges/vlsi-design-colleges-india',
		'529' => '/mba/colleges/mba-in-wealth-management-colleges-india',
		'530' => '/design/communication-design/colleges/web-design-colleges-india',
		'531' => '/arts-fine-visual-performing/music/colleges/western-contemporary-colleges-india',
		'532' => '/it-software/colleges/windows-colleges-india',
		'533' => '/it-software/colleges/wireless-colleges-india',
		'534' => '/humanities-social-sciences/colleges/women-studies-colleges-india',
		'535' => '/it-software/colleges/wordpress-colleges-india',
		'537' => '/science/colleges/zoology-colleges-india',
		'538' => '/it-software/big-data-analytics/colleges/business-analytics-colleges-india',
		'540' => '/medicine-health-sciences/colleges/md-pharmacovigilance-colleges-india',
		'545' => '/engineering/colleges/fire-safety-engineering-colleges-india',
    ),

    'base_course' => array(
		'1' => '/humanities-social-sciences/colleges/b-a-colleges-india',
		'2' => '/humanities-social-sciences/colleges/b-a-colleges-india',
		'3' => '/law/colleges/b-a-ll-b-colleges-india',
		'4' => '/law/colleges/b-a-ll-b-colleges-india',
		'5' => '/architecture-planning/colleges/b-arch-colleges-india',
		'6' => '/accounting-commerce/colleges/b-com-colleges-india',
		'7' => '/accounting-commerce/colleges/b-com-hons-colleges-india',
		'8' => '/law/colleges/colleges-india',
		'9' => '/design/fashion-design/colleges/b-des-colleges-india',
		'10' => '/b-tech/colleges/b-tech-colleges-india',
		'11' => '/teaching-education/colleges/b-ed-colleges-india',
		'12' => '/teaching-education/colleges/b-ed-colleges-india',
		'13' => '/science/colleges/b-f-sc-fisheries-science-colleges-india',
		'15' => '/mass-communication-media/journalism/colleges/b-j-colleges-india',
		'16' => '/mass-communication-media/colleges/b-j-m-c-colleges-india',
		'17' => '/humanities-social-sciences/library-information-science/colleges/b-lib-sc-colleges-india',
		'18' => '/humanities-social-sciences/library-information-science/colleges/b-lib-sc-colleges-india',
		'20' => '/mass-communication-media/colleges/b-m-m-colleges-india',
		'23' => '/teaching-education/colleges/b-p-ed-colleges-india',
		'24' => '/medicine-health-sciences/colleges/b-pharma-courses-india',
		'25' => '/architecture-planning/colleges/b-plan-colleges-india',
		'26' => '/science/colleges/b-sc-colleges-india',
		'27' => '/nursing/colleges/pb-b-sc-colleges-india',
		'28' => '/law/colleges/colleges-india',
		'29' => '/teaching-education/colleges/b-voc-colleges-india',
		'30' => '/bba/colleges/bba-colleges-india',
		'31' => '/law/colleges/bba-ll-b-colleges-india',
		'32' => '/law/colleges/colleges-india',
		'33' => '/it-software/colleges/bca-colleges-india',
		'34' => '/hospitality-travel/colleges/bct-ca-college-india',
		'35' => '/medicine-health-sciences/dental/colleges/bds-colleges-india',
		'36' => '/arts-fine-visual-performing/colleges/bfa-colleges-india',
		'37' => '/hospitality-travel/colleges/bhm-college-india',
		'39' => '/hospitality-travel/colleges/bhmtt-college-india',
		'40' => '/medicine-health-sciences/colleges/bmlt-colleges-india',
		'46' => '/medicine-health-sciences/physiotherapy/colleges/b-p-th-colleges-india',
		'48' => '/humanities-social-sciences/colleges/bsw-colleges-india',
		'50' => '/accounting-commerce/colleges/ca-colleges-india',
		'53' => '/it-software/networking-hardware-security/colleges/ccda-courses-india',
		'55' => '/it-software/networking-hardware-security/colleges/ccent-courses-india',
		'56' => '/it-software/networking-hardware-security/colleges/ccie-courses-india',
		'57' => '/it-software/networking-hardware-security/colleges/ccna-colleges-india',
		'58' => '/it-software/networking-hardware-security/colleges/ccnp-courses-india',
		'61' => '/banking-finance-insurance/colleges/cfa-colleges-india',
		'62' => '/banking-finance-insurance/colleges/cfp-colleges-india',
		'65' => '/accounting-commerce/colleges/cs-colleges-india',
		'67' => '/teaching-education/colleges/d-ed-colleges-india',
		'71' => '/it-software/colleges/doeacc-a-level-colleges-india',
		'72' => '/it-software/colleges/doeacc-b-level-colleges-india',
		'73' => '/it-software/colleges/doeacc-c-level-colleges-india',
		'74' => '/it-software/colleges/doeacc-o-level-colleges-india',
		'75' => '/business-management-studies/colleges/executive-mba-colleges-india',
		'77' => '/it-software/it-service-management/colleges/itil-institutes-india',
		'78' => '/law/colleges/ll-b-colleges-india',
		'81' => '/law/colleges/ll-m-colleges-india',
		'82' => '/humanities-social-sciences/colleges/m-a-colleges-india',
		'83' => '/architecture-planning/colleges/m-arch-colleges-india',
		'84' => '/accounting-commerce/colleges/m-com-colleges-india',
		'85' => '/animation/colleges/m-des-colleges-india',
		'86' => '/engineering/colleges/m-tech-colleges-india',
		'87' => '/teaching-education/colleges/m-ed-colleges-india',
		'89' => '/science/colleges/m-f-sc-fisheries-science-colleges-india',
		'94' => '/humanities-social-sciences/library-information-science/colleges/m-lib-sc-colleges-india',
		'96' => '/teaching-education/colleges/m-p-ed-colleges-india',
		'97' => '/medicine-health-sciences/pharmacy/colleges/m-pharma-colleges-india',
		'98' => '/humanities-social-sciences/colleges/m-phil-colleges-india',
		'99' => '/architecture-planning/colleges/m-plan-colleges-india',
		'100' => '/science/colleges/m-sc-colleges-india',
		'101' => '/mba/colleges/mba-colleges-india',
		'102' => '/medicine-health-sciences/colleges/mbbs-colleges-india',
		'103' => '/it-software/colleges/mca-colleges-india',
		'104' => '/it-software/databases/colleges/mcdba-courses-india',
		'105' => '/it-software/colleges/mcdst-courses-india',
		'106' => '/it-software/colleges/mcitp-colleges-india',
		'107' => '/it-software/colleges/mcp-colleges-india',
		'108' => '/it-software/colleges/mcpd-courses-india',
		'109' => '/it-software/colleges/mcsa-colleges-india',
		'110' => '/it-software/colleges/mcse-colleges-india',
		'111' => '/it-software/colleges/mcts-colleges-india',
		'112' => '/medicine-health-sciences/colleges/md-colleges-india',
		'114' => '/medicine-health-sciences/dental/colleges/mds-colleges-india',
		'115' => '/arts-fine-visual-performing/colleges/mfa-colleges-india',
		'117' => '/it-software/office-suite/colleges/mos-courses-india',
		'119' => '/medicine-health-sciences/colleges/mph-colleges-india',
		'120' => '/medicine-health-sciences/colleges/mpt-colleges-india',
		'122' => '/humanities-social-sciences/colleges/msw-colleges-india',
		'124' => '/humanities-social-sciences/colleges/ph-d-colleges-india',
		'126' => '/it-software/programming/colleges/scja-courses-india',
		'127' => '/it-software/programming/colleges/scjd-courses-india',
		'128' => '/it-software/programming/colleges/scjp-courses-india',
		'129' => '/it-software/programming/colleges/scwcd-courses-india',
		'146' => '/hospitality-travel/colleges/bhmct-college-india',
		'148' => '/it-software/networking-hardware-security/colleges/cise-courses-india',
	),
);

$config['MPT_EXCLUSION_LIST'] = array(49060,49061,49062,49063,49064,49085,49086,49087,49088,49089,49090,49091,49075,49076,49077,49078,49079,49080,49081,49082,49083,49084,49067,49066,49068,49069,49070,49071,49072,49145);
