export const courseWidget = {
flagshipCourseId: 1653,
allCoursesUrl: "/college/iim-ahmedabad-indian-institute-of-management-iima-vastrapur-307/courses",
allCourses: {
1645: {
name: "Post Graduate Program in Food and Agribusiness Management",
lateral: null,
twinning: null,
integrated: null,
dual: null,
username: 9884653,
recognition: null,
fees: [
{
category: "general",
period: "overall",
fees_value: 1892000,
fees_unit: 1,
fees_type: "total",
total_includes: {
value_0: "Hostel",
value_1: "Tuition",
value_2: "Admission",
value_3: "Library",
},
fees_disclaimer: 0,
fees_unit_name: "INR",
}
],
nbaAccreditation: null,
eligibility: [ ],
locations: { },
media: [ ],
partner: [ ],
course_id: 1645,
primary_id: 307,
primary_type: "institute",
primary_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
parent_id: 307,
parent_type: "institute",
parent_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
offered_by_id: 307,
offered_by_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
offered_by_short_name: "IIM Ahmedabad",
primary_short_name: "IIM Ahmedabad",
parent_short_name: "IIM Ahmedabad",
course_variant: 3,
course_order: 4,
brochure_url: "https://images.shiksha.com/mediadata/listingsBrochures/course_1645_2019-06-19-20-00.pdf",
brochure_year: 2019,
brochure_size: "126393",
is_brochure_auto_generated: 1,
listing_seo_url: "/mba/course/post-graduate-program-in-food-and-agribusiness-management-iim-ahmedabad-indian-institute-of-management-iima-vastrapur-1645",
seo_title: "Post Graduate Program in Food and Agribusiness Management by IIM Ahmedabad - Indian Institute of Management (IIMA), Vastrapur - Placements, Fees, Admission & Eligibility",
seo_description: "Read more about Post Graduate Program in Food and Agribusiness Management at IIM Ahmedabad - Indian Institute of Management (IIMA), Vastrapur. Find out about fees, admissions, reviews and more only at Shiksha.com",
affiliated_university_id: null,
affiliated_university_name: null,
affiliated_university_scope: null,
pack_type: 0,
total_seats: 0,
disabled_url: null,
duration_unit: "years",
duration_value: 2,
duration_disclaimer: null,
review_count: 1,
questions_count: 44,
expiry_date: null,
last_modify_date: "2019-06-19 19:00:44",
education_type: {
id: 20,
name: "Full Time",
},
difficulty_level: {
id: 0,
name: "",
},
delivery_method: {
id: 33,
name: "Classroom",
},
time_of_learning: {
id: null,
name: "",
},
main_location: {
fees: null,
course_id: 1645,
listing_location_id: 87021,
state_id: 109,
city_id: 30,
locality_id: 81,
state_name: "Gujarat",
city_name: "Ahmedabad",
locality_name: "Vastrapur",
is_main: 1,
contact_details: {
listing_id: null,
listing_location_id: 87021,
website_url: null,
address: null,
latitude: null,
longitude: null,
admission_contact_number: null,
admission_email: null,
generic_contact_number: "7966324599",
generic_email: "director@iimahd.ernet.in",
google_url: null,
actual_listing_location_id: null,
},
},
object_creation_date: "2019-06-19 20:00:39",
course_type_information: {
entry_course: {
type: "entry",
credential: {
id: 10,
name: "Diploma",
},
hierarchy: [
{
stream_id: 1,
substream_id: 0,
specialization_id: 17,
primary_hierarchy: 1,
}
],
course_id: 1645,
base_course: 101,
course_level: {
id: 15,
name: "PG",
},
}
},
placements_interships: { },
usp_list: [ ],
medium_of_instruction: [ ],
},
1653: {
name: "Post Graduate Program in Management",
lateral: null,
twinning: null,
integrated: null,
dual: null,
username: 9884653,
recognition: null,
fees: [
{
category: "general",
period: "overall",
fees_value: 2300000,
fees_unit: 1,
fees_type: "total",
total_includes: null,
fees_disclaimer: 0,
fees_unit_name: "INR",
}
],
nbaAccreditation: null,
eligibility: [ ],
locations: { },
media: [ ],
partner: [ ],
course_id: 1653,
primary_id: 307,
primary_type: "institute",
primary_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
parent_id: 307,
parent_type: "institute",
parent_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
offered_by_id: 307,
offered_by_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
offered_by_short_name: "IIM Ahmedabad",
primary_short_name: "IIM Ahmedabad",
parent_short_name: "IIM Ahmedabad",
course_variant: 3,
course_order: 1,
brochure_url: "https://images.shiksha.com/mediadata/listingsBrochures/course_1653_2019-06-19-20-00.pdf",
brochure_year: 2019,
brochure_size: "133209",
is_brochure_auto_generated: 1,
listing_seo_url: "/mba/course/post-graduate-program-in-management-iim-ahmedabad-indian-institute-of-management-iima-vastrapur-1653",
seo_title: "Post Graduate Program in Management by IIM Ahmedabad - Indian Institute of Management (IIMA), Vastrapur - Placements, Fees, Admission & Eligibility",
seo_description: "Read more about Post Graduate Program in Management at IIM Ahmedabad - Indian Institute of Management (IIMA), Vastrapur. Find out about fees, admissions, reviews and more only at Shiksha.com",
affiliated_university_id: null,
affiliated_university_name: null,
affiliated_university_scope: null,
pack_type: 0,
total_seats: 0,
disabled_url: null,
duration_unit: "years",
duration_value: 2,
duration_disclaimer: null,
review_count: 17,
questions_count: 1275,
expiry_date: null,
last_modify_date: "2019-06-19 18:27:01",
education_type: {
id: 20,
name: "Full Time",
},
difficulty_level: {
id: 0,
name: "",
},
delivery_method: {
id: 33,
name: "Classroom",
},
time_of_learning: {
id: null,
name: "",
},
main_location: {
fees: null,
course_id: 1653,
listing_location_id: 87021,
state_id: 109,
city_id: 30,
locality_id: 81,
state_name: "Gujarat",
city_name: "Ahmedabad",
locality_name: "Vastrapur",
is_main: 1,
contact_details: {
listing_id: null,
listing_location_id: 87021,
website_url: "https://www.iima.ac.in",
address: "",
latitude: "23.0329",
longitude: "72.5328",
admission_contact_number: "07966323456",
admission_email: "admission@iima.ac.in",
generic_contact_number: "07926308357",
generic_email: "director@iima.ac.in",
google_url: "https://images.shiksha.com/mediadata/images/listingGoogle/listingLocationlive87021.jpg",
actual_listing_location_id: 87021,
},
},
object_creation_date: "2019-06-19 20:00:27",
course_type_information: {
entry_course: {
type: "entry",
credential: {
id: 10,
name: "Diploma",
},
hierarchy: [
{
stream_id: 1,
substream_id: 0,
specialization_id: 0,
primary_hierarchy: 1,
}
],
course_id: 1653,
base_course: 101,
course_level: {
id: 15,
name: "PG",
},
}
},
placements_interships: { },
usp_list: [ ],
medium_of_instruction: [ ],
},
1656: {
name: "Faculty Development Programme (FDP)",
lateral: null,
twinning: null,
integrated: null,
dual: null,
username: 9884653,
recognition: [
{
id: 45,
name: "AICTE",
}
],
fees: [
{
category: "general",
period: "overall",
fees_value: 157500,
fees_unit: 1,
fees_type: "total",
total_includes: null,
fees_disclaimer: 0,
fees_unit_name: "INR",
}
],
nbaAccreditation: null,
eligibility: [ ],
locations: { },
media: [ ],
partner: [ ],
course_id: 1656,
primary_id: 307,
primary_type: "institute",
primary_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
parent_id: 307,
parent_type: "institute",
parent_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
offered_by_id: 307,
offered_by_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
offered_by_short_name: "IIM Ahmedabad",
primary_short_name: "IIM Ahmedabad",
parent_short_name: "IIM Ahmedabad",
course_variant: 3,
course_order: 5,
brochure_url: "https://images.shiksha.com/mediadata/listingsBrochures/course_1656_2019-06-19-20-00.pdf",
brochure_year: 2019,
brochure_size: "115976",
is_brochure_auto_generated: 1,
listing_seo_url: "/business-management-studies/course/faculty-development-programme-fdp-iim-ahmedabad-indian-institute-of-management-iima-vastrapur-1656",
seo_title: "Faculty Development Programme (FDP) by IIM Ahmedabad - Indian Institute of Management (IIMA), Vastrapur - Placements, Fees, Admission & Eligibility",
seo_description: "Read more about Faculty Development Programme (FDP) at IIM Ahmedabad - Indian Institute of Management (IIMA), Vastrapur. Find out about fees, admissions, reviews and more only at Shiksha.com",
affiliated_university_id: null,
affiliated_university_name: null,
affiliated_university_scope: null,
pack_type: 0,
total_seats: 60,
disabled_url: null,
duration_unit: "months",
duration_value: 4,
duration_disclaimer: null,
review_count: 0,
questions_count: 19,
expiry_date: null,
last_modify_date: "2019-06-19 18:36:04",
education_type: {
id: 20,
name: "Full Time",
},
difficulty_level: {
id: 0,
name: "",
},
delivery_method: {
id: 33,
name: "Classroom",
},
time_of_learning: {
id: null,
name: "",
},
main_location: {
fees: null,
course_id: 1656,
listing_location_id: 87021,
state_id: 109,
city_id: 30,
locality_id: 81,
state_name: "Gujarat",
city_name: "Ahmedabad",
locality_name: "Vastrapur",
is_main: 1,
contact_details: {
listing_id: null,
listing_location_id: 87021,
website_url: null,
address: null,
latitude: null,
longitude: null,
admission_contact_number: null,
admission_email: null,
generic_contact_number: "7965224886",
generic_email: "pgppmp@iimahd.ernet.in",
google_url: null,
actual_listing_location_id: null,
},
},
object_creation_date: "2019-06-19 20:00:30",
course_type_information: {
entry_course: {
type: "entry",
credential: {
id: 11,
name: "Certificate",
},
hierarchy: [
{
stream_id: 1,
substream_id: 0,
specialization_id: 0,
primary_hierarchy: 1,
}
],
course_id: 1656,
base_course: 0,
course_level: {
id: 19,
name: "None",
},
}
},
placements_interships: { },
usp_list: [ ],
medium_of_instruction: [ ],
},
1662: {
name: "Post Graduate Programme for Executives",
lateral: null,
twinning: null,
integrated: null,
dual: null,
username: 9884653,
recognition: null,
fees: [
{
category: "general",
period: "overall",
fees_value: 2500000,
fees_unit: 1,
fees_type: "total",
total_includes: null,
fees_disclaimer: 0,
fees_unit_name: "INR",
}
],
nbaAccreditation: null,
eligibility: [ ],
locations: { },
media: [ ],
partner: [ ],
course_id: 1662,
primary_id: 307,
primary_type: "institute",
primary_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
parent_id: 307,
parent_type: "institute",
parent_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
offered_by_id: 307,
offered_by_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
offered_by_short_name: "IIM Ahmedabad",
primary_short_name: "IIM Ahmedabad",
parent_short_name: "IIM Ahmedabad",
course_variant: 3,
course_order: 3,
brochure_url: "https://images.shiksha.com/mediadata/pdf/1556020271phphILOxz.pdf",
brochure_year: 2019,
brochure_size: "5994698",
is_brochure_auto_generated: null,
listing_seo_url: "/business-management-studies/course/post-graduate-programme-for-executives-iim-ahmedabad-indian-institute-of-management-iima-vastrapur-1662",
seo_title: "Post Graduate Programme for Executives by IIM Ahmedabad - Indian Institute of Management (IIMA), Vastrapur - Placements, Fees, Admission & Eligibility",
seo_description: "Read more about Post Graduate Programme for Executives at IIM Ahmedabad - Indian Institute of Management (IIMA), Vastrapur. Find out about fees, admissions, reviews and more only at Shiksha.com",
affiliated_university_id: null,
affiliated_university_name: null,
affiliated_university_scope: null,
pack_type: 7,
total_seats: 140,
disabled_url: null,
duration_unit: "years",
duration_value: 1,
duration_disclaimer: null,
review_count: 1,
questions_count: 46,
expiry_date: "2021-03-23 11:02:16",
last_modify_date: "2019-06-19 18:58:56",
education_type: {
id: 20,
name: "Full Time",
},
difficulty_level: {
id: 0,
name: "",
},
delivery_method: {
id: 33,
name: "Classroom",
},
time_of_learning: {
id: null,
name: "",
},
main_location: {
fees: null,
course_id: 1662,
listing_location_id: 87021,
state_id: 109,
city_id: 30,
locality_id: 81,
state_name: "Gujarat",
city_name: "Ahmedabad",
locality_name: "Vastrapur",
is_main: 1,
contact_details: {
listing_id: null,
listing_location_id: 87021,
website_url: "https://www.iima.ac.in/web/pgpx/programme",
address: "PGPX Office, New Campus, IMDC Block, Indian Institute of Management Vastrapur, Ahmedabad, Gujarat 380015 INDIA",
latitude: "23.0329",
longitude: "72.5328",
admission_contact_number: "07966324449",
admission_email: "pgpxquery@iima.ac.in",
generic_contact_number: "07966324450",
generic_email: "pgpxmngr@iima.ac.in",
google_url: null,
actual_listing_location_id: null,
},
},
object_creation_date: "2019-06-19 19:00:05",
course_type_information: {
entry_course: {
type: "entry",
credential: {
id: 10,
name: "Diploma",
},
hierarchy: [
{
stream_id: 1,
substream_id: 0,
specialization_id: 0,
primary_hierarchy: 1,
}
],
course_id: 1662,
base_course: 75,
course_level: {
id: 15,
name: "PG",
},
}
},
placements_interships: { },
usp_list: [ ],
medium_of_instruction: [ ],
},
1666: {
name: "Fellow Programe in Management",
lateral: null,
twinning: null,
integrated: null,
dual: null,
username: 9884653,
recognition: null,
fees: null,
nbaAccreditation: null,
eligibility: [ ],
locations: { },
media: [ ],
partner: [ ],
course_id: 1666,
primary_id: 307,
primary_type: "institute",
primary_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
parent_id: 307,
parent_type: "institute",
parent_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
offered_by_id: 307,
offered_by_name: "IIM Ahmedabad - Indian Institute of Management (IIMA)",
offered_by_short_name: "IIM Ahmedabad",
primary_short_name: "IIM Ahmedabad",
parent_short_name: "IIM Ahmedabad",
course_variant: 3,
course_order: 2,
brochure_url: "https://images.shiksha.com/mediadata/listingsBrochures/course_1666_2019-06-19-20-00.pdf",
brochure_year: 2019,
brochure_size: "119748",
is_brochure_auto_generated: 1,
listing_seo_url: "/business-management-studies/course/fellow-programe-in-management-iim-ahmedabad-indian-institute-of-management-iima-vastrapur-1666",
seo_title: "Fellow Programe in Management by IIM Ahmedabad - Indian Institute of Management (IIMA), Vastrapur - Placements, Fees, Admission & Eligibility",
seo_description: "Read more about Fellow Programe in Management at IIM Ahmedabad - Indian Institute of Management (IIMA), Vastrapur. Find out about fees, admissions, reviews and more only at Shiksha.com",
affiliated_university_id: null,
affiliated_university_name: null,
affiliated_university_scope: null,
pack_type: 0,
total_seats: 30,
disabled_url: null,
duration_unit: "months",
duration_value: 54,
duration_disclaimer: null,
review_count: 0,
questions_count: 44,
expiry_date: null,
last_modify_date: "2019-06-19 18:35:30",
education_type: {
id: 20,
name: "Full Time",
},
difficulty_level: {
id: 0,
name: "",
},
delivery_method: {
id: 33,
name: "Classroom",
},
time_of_learning: {
id: null,
name: "",
},
main_location: {
fees: null,
course_id: 1666,
listing_location_id: 87021,
state_id: 109,
city_id: 30,
locality_id: 81,
state_name: "Gujarat",
city_name: "Ahmedabad",
locality_name: "Vastrapur",
is_main: 1,
contact_details: {
listing_id: null,
listing_location_id: 87021,
website_url: "https://www.iima.ac.in",
address: "",
latitude: "23.0329",
longitude: "72.5328",
admission_contact_number: "07966323456",
admission_email: "admission@iima.ac.in",
generic_contact_number: "07926308357",
generic_email: "director@iima.ac.in",
google_url: "https://images.shiksha.com/mediadata/images/listingGoogle/listingLocationlive87021.jpg",
actual_listing_location_id: 87021,
},
},
object_creation_date: "2019-06-19 20:00:29",
course_type_information: {
entry_course: {
type: "entry",
credential: {
id: 9,
name: "Degree",
},
hierarchy: [
{
stream_id: 1,
substream_id: 0,
specialization_id: 0,
primary_hierarchy: 1,
}
],
course_id: 1666,
base_course: 124,
course_level: {
id: 17,
name: "Doctorate",
},
}
},
placements_interships: { },
usp_list: [ ],
medium_of_instruction: [ ],
},
},
isPaidCourse: {
1645: false,
1653: false,
1656: false,
1662: false,
1666: false,
},
popularCourseList: null,
featuredCourseList: [
1653,
1662,
1645,
1666,
1656,
],
baseCourseObjects: [
{
baseCourseId: 101,
name: "MBA/PGDM",
alias: "MBA",
url: "mba-pgdm-bc",
synonym: [
"MBA",
"PGDM",
"PGP",
"PGPM",
"PGPDM",
"PGPGM",
"Master in Business Administration",
],
level: 15,
credential: [
9,
10,
],
isDummy: 0,
isPopular: 1,
isHyperlocal: 0,
isExecutive: 0,
},
{
baseCourseId: 75,
name: "Executive MBA/PGDM",
alias: "Executive MBA",
url: "executive-mba-pgdm-bc",
synonym: [
"Executive MBA",
"Executive PGDM",
"EPGP",
"EPGDM",
],
level: 15,
credential: [
9,
10,
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 1,
},
{
baseCourseId: 124,
name: "Ph.D.",
alias: null,
url: "phd-bc",
synonym: [
"Doctor of Philosophy"
],
level: 17,
credential: [
9
],
isDummy: 0,
isPopular: 0,
isHyperlocal: 0,
isExecutive: 0,
},
],
streamObjects: [
{
streamId: 1,
name: "Business & Management Studies",
alias: null,
displayOrder: 1,
url: "business-and-management-studies-s",
synonyms: [
"Business Management",
"Business",
"Management",
"Business Studies",
"Management Studies",
],
}
],
specializationIds: [
17
],
totalCourseCount: 5,
instituteHasPaidCourse: false,
agrregateReviewsData: {
aggregateRatingDisplayOrder: {
avgSalaryPlacementRating: "Placements",
campusFacilitiesRating: "Infrastructure",
facultyRating: "Faculty & Course Curriculum",
crowdCampusRating: "Crowd & Campus Life",
moneyRating: "Value for Money",
},
intervalsDisplayOrder: {
'4-5': ">4-5",
'3-4': ">3-4",
'2-3': ">2-3",
'1-2': "1-2",
},
ratingIdToDisplayNameMapping: {
1: "Value for Money",
2: "Crowd & Campus Life",
3: "Placements",
4: "Infrastructure",
5: "Faculty & Course Curriculum",
6: "Infrastructure",
7: "Placements",
8: "Infrastructure",
9: "Infrastructure",
10: "Placements",
},
aggregateReviewData: {
1645: {
totalCount: 1,
aggregateRating: {
averageRating: {
count: 1,
sum: 5,
mean: 5,
},
facultyRating: {
count: 1,
sum: 5,
mean: 5,
},
campusFacilitiesRating: {
count: 1,
sum: 5,
mean: 5,
},
avgSalaryPlacementRating: {
count: 1,
sum: 5,
mean: 5,
},
crowdCampusRating: {
count: 1,
sum: 5,
mean: 5,
},
moneyRating: {
count: 1,
sum: 5,
mean: 5,
},
},
intervalRatingCount: {
"1-2": 0,
"2-3": 0,
"3-4": 0,
"4-5": 1,
},
intervalRatingCountForPlacement: {
"1-2": 0,
"2-3": 0,
"3-4": 0,
"4-5": 1,
},
},
1653: {
totalCount: 17,
aggregateRating: {
averageRating: {
count: 17,
sum: 76.6,
mean: 4.5,
},
facultyRating: {
count: 17,
sum: 79,
mean: 4.6,
},
campusFacilitiesRating: {
count: 17,
sum: 79,
mean: 4.6,
},
avgSalaryPlacementRating: {
count: 17,
sum: 74,
mean: 4.4,
},
crowdCampusRating: {
count: 17,
sum: 75,
mean: 4.4,
},
moneyRating: {
count: 17,
sum: 76,
mean: 4.5,
},
},
intervalRatingCount: {
"1-2": 0,
"2-3": 2,
"3-4": 1,
"4-5": 14,
},
intervalRatingCountForPlacement: {
"1-2": 2,
"2-3": 2,
"3-4": 1,
"4-5": 12,
},
},
1656: null,
1662: {
totalCount: 1,
aggregateRating: {
averageRating: {
count: 1,
sum: 3.6,
mean: 3.6,
},
facultyRating: {
count: 1,
sum: 1,
mean: 1,
},
campusFacilitiesRating: {
count: 1,
sum: 5,
mean: 5,
},
avgSalaryPlacementRating: {
count: 1,
sum: 3,
mean: 3,
},
crowdCampusRating: {
count: 1,
sum: 4,
mean: 4,
},
moneyRating: {
count: 1,
sum: 5,
mean: 5,
},
},
intervalRatingCount: {
"1-2": 0,
"2-3": 0,
"3-4": 1,
"4-5": 0,
},
intervalRatingCountForPlacement: {
"1-2": 0,
"2-3": 1,
"3-4": 0,
"4-5": 0,
},
},
1666: null,
},
},
streamIds: [
1
],
baseCourseIds: [
101,
75,
124,
],
popularCourse: {
	courseId: 1653,
	name: "Post Graduate Program in Management",
	url: "/mba/course/post-graduate-program-in-management-iim-ahmedabad-indian-institute-of-management-iima-vastrapur-1653",
},
pdfUrl: "https://images.shiksha.com/mediadata/instituteCtaPdf/courses/307.pdf"
}