<?php

 $Board = array(		
				'CBSE'=>'CBSE Board',
				'CISCE'=>'CISCE (ICSE/ISC)',
				'andhraPradesh'=>'Andhra Pradesh Board',
				'assam'=>'Assam Board',
				'bihar'=>'Bihar Board',
				'chattisgarh'=>'Chattisgarh Board',
				'goa'=>'Goa Board',
				'gujarat'=>'Gujarat Board',
				'haryana'=>'Haryana Board',
				'himachalPradesh'=>'Himachal Pradesh Board',
				'JK'=>'J&K Board',
				'jharkhand'=>'Jharkhand Board',
				'karnataka'=>'Karnataka Board',
				'kerala'=>'Kerala Board',
				'madhyaPradesh'=>'Madhya Pradesh Board',
				'maharashtra'=>'Maharashtra Board',
				'manipur'=>'Manipur Board',
				'meghalaya'=>'Meghalaya Board',
				'mizoram'=>'Mizoram Board',
				'nagaland'=>'Nagaland Board',
				'nationalOpenSchool'=>'National Institute of Open Schooling',
				'orissa'=>'Orissa Board',
				'others'=>'Other Boards',
				'punjab'=>'Punjab Board',
				'rajasthan'=>'Rajasthan Board',
				'tamilNadu'=>'Tamil Nadu Board',
				'tripura'=>'Tripura Board',
				'uttarPradesh'=>'Uttar Pradesh Board',
				'uttrakhand'=>'Uttarakhand Board',
				'westBengal'=>'West Bengal Board'
			);


 $graduationStream = array(
 		'ActuarialScience'=>'Actuarial Science',
		'AgriculturalEngineering'=>'Agricultural Engineering',
		'Agriculture'=>'Agriculture',
		'AnimalHusbandry'=>'Animal Husbandry',
		'Architecture'=>'Architecture',
		'ArtsHumanities'=>'Arts/Humanities (including vocational degrees)',
		'BioscienceBiotechnology'=>'Bioscience & Biotechnology',
		'CharteredAccountancy'=>'Chartered Accountancy (CA)',
		'CommerceEconomics'=>'Commerce/Economics (including vocational degrees)',
		'CompanySecretaryship'=>'Company Secretaryship (CS)',		
		'ComputerApplications'=>'Computer Applications',
		'ICWA'=>'Cost and Works Accountancy (ICWA)',
		'DairyScienceTechnology'=>'Dairy Science/Technology',
		'Dentistry'=>'Dentistry' ,
		'PhysicalEducation'=>'Education, Physical Education and Sports',
		'EngineeringTechnology'=>'Engineering/Technology',
		'FashionDesign'=>'Fashion & Design',
		'Fisheries'=>'Fisheries',
		'FoodTechnology'=>'Food Technology',
		'GeographyGeologicalSciences'=>'Geography & Geological Sciences',
		'Forestry'=>'Forestry',
		'Horticulture'=>'Horticulture',
		'HotelManagement'=>'Hotel & Tourism Management',
		'Law'=>'Law',
		'Management'=>'Management',
		'MathematicalSciences'=>'Mathematical Sciences',
		'MedicineSurgery'=>'Medicine and Surgery',
		'NaturalSciences'=>'Natural Sciences',
		'ParamedicalPhysiotherapy'=>'Paramedical/Physiotherapy',
		'PharmacologyPharmacy'=>'Pharmacology/Pharmacy',
		'Planning'=>'Planning',
		'Rural'=>'Rural - Studies/Sociology/Cooperatives/Banking',
		'Science'=>'Science (Others)',
		'VetrinaryScience'=>'Vetrinary Science',
		'TextileTechnology'=>'Textile Technology/Engineering',
		'Others'=>'Any other Discipline'
	);

$IIM_rank = array(
		'IIM_Ahmedabad',
		'IIM_Bangalore',
		'IIM_Calcutta',
		'IIM_Lucknow',
		'IIM_Indore',
		'IIM_Kozhikode',
		'IIM_Shillong',
		'IIM_Kashipur',
		'IIM_Raipur',
		'IIM_Udaipur',
		'IIM_Rohtak',
		'IIM_Trichy',
		'IIM_Ranchi',
		'IIM_Bodhgaya',
		'IIM_Sambalpur',
		'IIM_Nagpur',
		'IIM_Amritsar',
		'IIM_Sirmaur',
		'IIM_Visakhapatnam'
	);


$IIM_Article_Page_link = array(
		'IIM_Ahmedabad' => '',
		'IIM_Bangalore'=> '',
		'IIM_Calcutta'=> '',
		'IIM_Lucknow'=> '',
		'IIM_Indore'=> '',
		'IIM_Kozhikode'=> '',
		'IIM_Shillong'=> '',
		'IIM_Kashipur'=> '',
		'IIM_Raipur'=> '',
		'IIM_Udaipur'=> '',
		'IIM_Rohtak'=> '',
		'IIM_Trichy'=> '',
		'IIM_Ranchi'=> '',
		'IIM_Bodhgaya'=> '',
		'IIM_Sambalpur'=> '',
		'IIM_Nagpur'=> '',
		'IIM_Amritsar'=> '',
		'IIM_Sirmaur'=> '',
		'IIM_Visakhapatnam'=> ''
	);

$article_page_links = array(
			    'IIM_Ahmedabad'=>SHIKSHA_HOME.'/cat-iim-ahmedabad-announces-admission-policy-for-pgp-2017-2019-batch-article-13101-1',
                'IIM_Calcutta'=>SHIKSHA_HOME.'/cat-2016-iim-calcutta-announces-admission-policy-minimum-cut-off-90-percentile-article-13054-1',
				'IIM_Kozhikode'=>SHIKSHA_HOME.'/admission-policy-2017-2019-iim-kozhikode-to-give-more-weightage-to-pi-than-cat-2016-article-13138-1',
				'IIM_Shillong'=>SHIKSHA_HOME.'/iim-shillong-admission-policy-2017-2019-sectional-cat-2016-cut-off-fixed-at-70-percentile-article-13413-1',
				'IIM_Trichy'=>SHIKSHA_HOME.'/admission-policy-2017-2019-iim-kozhikode-to-give-more-weightage-to-pi-than-cat-2016-article-13138-1',
				'IIM_Kashipur'=>SHIKSHA_HOME.'/iim-kashipur-releases-shortlisting-criteria-for-pgp-batch-2016-18-article-11578-1',
				'IIM_Raipur'=>SHIKSHA_HOME.'/iim-raipur-admission-policy-2017-2019-32-weightage-allotted-to-cat-2016-article-13410-1',
				'IIM_Udaipur'=>SHIKSHA_HOME.'/iim-udaipur-admission-policy-2017-2019-maximum-weightage-allotted-to-cat-2016-score-article-13277-1',
				'IIM_Rohtak'=>SHIKSHA_HOME.'/iim-rohtak-announces-admission-criteria-2017-19-40-weightage-to-cat-article-13408-1',
				'IIM_Ranchi'=>SHIKSHA_HOME.'/iim-ranchi-announces-admission-criteria-for-pgdm-and-pgdhrm-2016-2018-article-11740-1',
				'IIM_Bodhgaya'=>SHIKSHA_HOME.'/iim-bodh-gaya-admission-criteria-2017-2019-equal-weightage-allotted-to-cat-2016-and-pi-article-13407-1',
				'IIM_Sambalpur'=>SHIKSHA_HOME.'/how-much-cat-score-do-you-need-to-make-it-to-these-iims-article-13415-1',
				'IIM_Amritsar'=>SHIKSHA_HOME.'/how-much-cat-score-do-you-need-to-make-it-to-these-iims-article-13415-1',
				'IIM_Nagpur'=>SHIKSHA_HOME.'/how-much-cat-score-do-you-need-to-make-it-to-these-iims-article-13415-1',
				'IIM_Sirmaur'=>SHIKSHA_HOME.'/how-much-cat-score-do-you-need-to-make-it-to-these-iims-article-13415-1',
				'IIM_Bangalore'=>SHIKSHA_HOME.'/iim-bangalore-pgp-2017-2019-admission-policy-cat-2016-to-carry-40-weightage-article-13159-1',
				'IIM_Lucknow'=>SHIKSHA_HOME.'/iim-lucknow-announces-admission-policy-changes-in-component-score-weightage-article-13074-1',
				'IIM_Indore'=>SHIKSHA_HOME.'/iim-indore-admission-criteria-2017-2019-cat-2016-allotted-only-20-weigtage-article-13359-1',
				'IIM_Visakhapatnam'=>SHIKSHA_HOME.'/how-much-cat-score-do-you-need-to-make-it-to-these-iims-article-13415-1'
		);

$ILP_Page_Links = array('IIM_Ahmedabad' => array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-ahmedabad-vastrapur-307','courseId'=>1653),
	    'IIM_Bangalore'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-bangalore-bannerghatta-road-318','courseId'=>1688),
		'IIM_Calcutta'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-calcutta-joka-kolkata-20190','courseId'=>22931),
		'IIM_Lucknow'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-lucknow-333','courseId'=>111876),
		'IIM_Indore'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-indore-29623','courseId'=>119554),
		'IIM_Kozhikode'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-kozhikode-20188','courseId'=>22929),
		'IIM_Shillong'=> array('url'=>SHIKSHA_HOME.'/college/rajiv-gandhi-indian-institute-of-management-shillong-23700','courseId'=>27159),
		'IIM_Kashipur'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-kashipur-uttarakhand-other-36080','courseId'=>164638),
		'IIM_Raipur'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-raipur-32740','courseId'=>130065),
		'IIM_Udaipur'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-udaipur-36085','courseId'=>164788),
		'IIM_Rohtak'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-rohtak-32736','courseId'=>130055),
		'IIM_Trichy'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-tiruchirappalli-36076','courseId'=>164564),
		'IIM_Ranchi'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-ranchi-32728','courseId'=>130026),
		'IIM_Bodhgaya'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-ahmedabad-vastrapur-307','courseId'=>265230),
		'IIM_Sambalpur'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-sambalpur-48265','courseId'=>246565),
		'IIM_Nagpur'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-nagpur-47711','courseId'=>241824),
		'IIM_Amritsar'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-amritsar-47709','courseId'=>241811),
		'IIM_Sirmaur'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-sirmaur-sirmour-47703','courseId'=>241783),
		'IIM_Visakhapatnam'=> array('url'=>SHIKSHA_HOME.'/college/indian-institute-of-management-visakhapatnam-47712','courseId'=>241826)
	);

$ICP_fields_Mapping = array(
		'graduationPercentage' => 'Graduation',
		'xthPercentage' => 'Class X',
		'xiithPercentage' => 'Class XII',
		'VRC_Percentile' => 'VRC',
		'DILR_Percentile' => 'DI-LR',
		'QA_Percentile' => 'QA',
		'cat_percentile' => 'CAT',
		'X_XII_Science_avg' => 'Average of<br/>X & XII',
		'X_XII_Commerce_avg' => 'Average of<br/>X & XII',
		'X_XII_Arts_avg' => 'Average of<br/>X & XII'
	);