<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config = array();

define("M_ASK_QUES_HEADER", 714);

define("MQnA_PAGEVIEW", "qnaPage");
define("MQnA_ASK_QUE_STICKY", 715);
define("MQnA_ANSWER_POST_WIDGET",716);
define("MQnA_DCOMMENT_POST_WIDGET",717);
define("MQnA_TUP_ANSWER_TUPLE",718);
define("MQnA_TDOWN_ANSWER_TUPLE", 719);
define("MQnA_TUP_DCOMMENT_TUPLE", 720);
define("MQnA_TDOWN_DCOMMENT_TUPLE",721);
define("MQnA_FOLLOW_QUES", 753);
define("MQnA_FOLLOW_DISC", 754);
define("MQnA_FOLLOW_TAGS_RECOMMENDATION", 755);
define("MQnA_FOLLOW_USER_RECOMMENDATION", 756);

define("MDISC_PAGEVIEW", 'discussionPage');
define("MDISC_POST_DISC_STICKY", 722);
define("MDISC_DCOMMENT_POST_WIDGET", 723);
define("MDISC_TUP_DCOMMENT_TUPLE", 724);
define("MDISC_TDOWN_DCOMMENT_TUPLE",725);
define("MDISC_FOLLOW_DISC", 757);


define('MUANS_PAGEVIEW',"unAnsweredPage");
define("MUANS_ANSWER_POST_WIDGET", 726);
define("MUANS_FOLLOW_QUES", 758);

define('MQDP_PAGEVIEW',"questionDetailPage");
define("MQDP_ANSWER_POST_WIDGET", 727);
define("MQDP_ABUSE_QUES_TUPLE", 728);
define("MQDP_TUP_ANSWER_TUPLE",729);
define("MQDP_TDOWN_ANSWER_TUPLE", 730);
define("MQDP_COMMENT_POST_WIDGET", 731);
define("MQDP_ABUSE_ANSWER_TUPLE", 732);
define("MQDP_ASK_QUES_ASKNOW_BOTTOM_WIDGET", 733);
define("MQDP_ABUSE_COMMNET_TUPLE", 734);
define("MQDP_FOLLOW_QUES", 759);
define("MQDP_ANSWER_LATER",784);
define("MQDP_FOLLOW_USER_FOLLOWER_LIST",786);
define("MQDP_FOLLOW_USER_UPVOTERS_LIST",787);

define("MDDP_PAGEVIEW", "discussionDetailPage");
define("MDDP_DCOMMENT_POST_WIDGET", 735);
define("MDDP_ABUSE_DISC_TUPLE", 736);
define("MDDP_TUP_DCOMMENT_TUPLE", 737);
define("MDDP_TDOWN_DCOMMENT_TUPLE", 738);
define("MDDP_ABUSE_DCOMMENT_TUPLE", 739);
define("MDDP_ASK_QUES_ASKNOW_BOTTOM_WIDGET", 740);
define("MDDP_REPLY_POST_WIDGET",741);
define("MDDP_ABUSE_REPLY_TUPLE", 742);
define("MDDP_FOLLOW_DISC", 760);
define("MDDP_COMMENT_LATER",785);
define("MDDP_FOLLOW_USER_FOLLOWER_LIST",788);
define("MDDP_FOLLOW_USER_UPVOTERS_LIST", 789);

define("MTDP_PAGEVIEW","tagDetailPage");
define("MTDP_ALL_TAB_PAGEVIEW","home");
define("MTDP_DISC_TAB_PAGEVIEW", "discssuions");
define("MTDP_UANS_TAB_PAGEVIEW", "unanswered");
define("MTDP_TOP_ASK_WIDGET", 1439);
define("MTDP_ALL_ANSWER_POST_WIDGET", 743);
define("MTDP_ALL_DCOMMENET_POST_WIDGET", 744);
define("MTDP_ALL_TUP_ANSWER_TUPLE", 745);
define("MTDP_ALL_TDOWN_ANSWER_TUPLE", 746);
define("MTDP_ALL_TUP_DCOMMENT_TUPE", 747);
define("MTDP_ALL_TDOWN_DCOMMENT_TUPLE", 748);
define("MTDP_ALL_FOLLOW_TAG_STATS_WIDGET", 761);
define("MTDP_ALL_FOLLOW_QUES", 762);
define("MTDP_ALL_FOLLOW_DISC", 763);
define("MTDP_ALL_FOLLOW_USER_ACTIVE_WIDGET", 764);
define("MTDP_ALL_FOLLOW_TAG_RELATED_WIDGET", 765);

define("MTDP_DISC_TAB_DCOMMENT_POST_WIDGET", 749);
define("MTDP_DISC_TAB_TUP_DCOMMENT_TUPLE", 750);
define("MTDP_DISC_TAB_TDOWN_DCOMMENT_TUPLE", 751);
define("MTDP_DISC_FOLLOW_DISC", 766);
define("MTDP_DISC_FOLLOW_USER_ACTIVE_WIDGET", 767);
define("MTDP_DISC_FOLLOW_TAG_RELATED_WIDGET", 768);
define("MTDP_UANS_TAB_ANSWER_POST_WIDGET", 752);
define("MTDP_UANS_FOLLOW_QUES", 769);
define("MTDP_UANS_FOLLOW_USER_ACTIVE_WIDGET", 770);
define("MTDP_UANS_FOLLOW_TAG_RELATED_WIDGET", 771);
define("MVIEW_TAGS_PAGEVIEW", 'viewAllTagsPage');


?>