<?php 
$config['groupIdToStreamMap'] = array(
	90 => array('name' => 'JEECE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    400 => array('name' => 'HP LEET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    212 => array('name' => 'AUEET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    373 => array('name' => 'MUEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    866 => array('name' => 'NIMSEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    872 => array('name' => 'NIMSEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    887 => array('name' => 'OUAT Entrance Exam', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    959 => array('name' => 'Shobhit University National Entrance Test (SUNET)', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    232 => array('name' => 'AMUEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    76 => array('name' => 'RPET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1241 => array('name' => 'SSU Entrance Test', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1337 => array('name' => 'IUET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1339 => array('name' => 'IUET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1341 => array('name' => 'IUET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    520 => array('name' => 'AISECT University Entrance Exam', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    164 => array('name' => 'PESSAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    133 => array('name' => 'BITSAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    961 => array('name' => 'NPAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    966 => array('name' => 'NPAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    174 => array('name' => 'AEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    140 => array('name' => 'AISEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    112 => array('name' => 'WBJEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    104 => array('name' => 'AMIE Exam', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    101 => array('name' => 'Assam CEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    146 => array('name' => 'ATIT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    149 => array('name' => 'CUSAT CAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    94 => array('name' => 'GCET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    12 => array('name' => 'KCET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    107 => array('name' => 'HPCET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    156 => array('name' => 'IEMJEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    163 => array('name' => 'NERIST Entrance Exam', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    102 => array('name' => 'TJEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    184 => array('name' => 'VSAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    223 => array('name' => 'GUJCET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    208 => array('name' => 'SEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    166 => array('name' => 'SAEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    147 => array('name' => 'BVP CET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    173 => array('name' => 'Alliance AUEET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    143 => array('name' => 'Amity JEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    109 => array('name' => 'AP EAMCET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    148 => array('name' => 'CIEAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    795 => array('name' => 'PESSAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    551 => array('name' => 'SNUSAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1119 => array('name' => 'AP ECET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    955 => array('name' => 'DCET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    812 => array('name' => 'SLIET SET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    369 => array('name' => 'Jharkhand DTODECE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    366 => array('name' => 'Haryana LEET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    347 => array('name' => 'JLEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    365 => array('name' => 'Jaypee LEET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    348 => array('name' => 'PULEET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    370 => array('name' => 'DTU LEET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1459 => array('name' => 'CMRUAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    155 => array('name' => 'HITSEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1047 => array('name' => 'VEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    167 => array('name' => 'SRMJEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    170 => array('name' => 'VITEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1331 => array('name' => 'NSAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    251 => array('name' => 'MZUEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    114 => array('name' => 'COMEDK UGET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    154 => array('name' => 'GEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    157 => array('name' => 'IMUCET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    16 => array('name' => 'KEAM', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    158 => array('name' => 'KEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    60 => array('name' => 'MHT CET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    98 => array('name' => 'REAP', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    165 => array('name' => 'REVA EET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    110 => array('name' => 'TNEA', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    95 => array('name' => 'TS EAMCET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    169 => array('name' => 'UPESEAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    171 => array('name' => 'VTUEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    205 => array('name' => 'SRMHJEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    209 => array('name' => 'BEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1505 => array('name' => 'TS ECET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    13 => array('name' => 'UPSEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1509 => array('name' => 'MRNAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    919 => array('name' => 'KIITEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    162 => array('name' => 'NAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    99 => array('name' => 'SITEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    111 => array('name' => 'JEE Advanced', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    113 => array('name' => 'JEE Main', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    137 => array('name' => 'AJEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    153 => array('name' => 'GAT - UGTP', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    159 => array('name' => 'KIITEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    160 => array('name' => 'MET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    161 => array('name' => 'LPU NEST', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    168 => array('name' => 'SUAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    189 => array('name' => 'SPSAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    196 => array('name' => 'CEE AMPAI', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    211 => array('name' => 'TMISAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    219 => array('name' => 'IPU CET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    233 => array('name' => 'Chandigarh University CUSAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    246 => array('name' => 'SVUEET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    350 => array('name' => 'CUEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    351 => array('name' => 'SMIT Offline Test', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    352 => array('name' => 'SAAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    353 => array('name' => 'JAC Chandigarh Admission', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    357 => array('name' => 'UKSEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    358 => array('name' => 'KLEEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    359 => array('name' => 'Punjab BTech Admissions', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    360 => array('name' => 'CG PET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    361 => array('name' => 'CENTAC Counselling', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    363 => array('name' => 'GLAET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    364 => array('name' => 'Uttarakhand BTech Admission', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    367 => array('name' => 'WBJEE JELET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    368 => array('name' => 'DTE Kerala LET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    371 => array('name' => 'KRLMPCA CET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    372 => array('name' => 'J&K BOPEE CET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    375 => array('name' => 'Banasthali University Aptitude Test', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    383 => array('name' => 'SRMS EET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    387 => array('name' => 'DAVUET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    389 => array('name' => 'MP BE Counselling', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    390 => array('name' => 'DASA UG', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    391 => array('name' => 'BCECE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    423 => array('name' => 'CUCET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    461 => array('name' => 'UPCATET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    603 => array('name' => 'Goenkan Aptitude Test for Admission (GATA)', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    632 => array('name' => 'SHIATS Entrance Exam', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    646 => array('name' => 'Goenkan Aptitude Test for Admission (GATA)', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    653 => array('name' => 'CEPT Entrance Exam', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    675 => array('name' => 'JAC Delhi Admissions', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    697 => array('name' => 'DUET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    734 => array('name' => 'SU JEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    867 => array('name' => 'MCAER CET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    967 => array('name' => 'MUSAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    968 => array('name' => 'MUSAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    972 => array('name' => 'Jaipur National University Combined Entrance Test', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1010 => array('name' => 'SUAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1029 => array('name' => 'OJEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1046 => array('name' => 'Uni-GAUGE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1053 => array('name' => 'ITM NEST', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1069 => array('name' => 'HSTES BTech Admission', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1163 => array('name' => 'Jamia Millia Islamia Entrance Exam', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1263 => array('name' => 'ACET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1421 => array('name' => 'SNUET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1435 => array('name' => 'DSAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1545 => array('name' => 'NTA', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1547 => array('name' => 'JoSAA', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1557 => array('name' => 'JET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1559 => array('name' => 'MUJEE', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1591 => array('name' => 'CUET', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1593 => array('name' => 'Shoolini Engineering Scholarship Test (SEST)', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),
    1639 => array('name' => 'SRMHCAT', 'label' => 'Engineering', 'st' => 2, 'bc' => 10, 'et' => 20),

    192 => array('name' => 'GMAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    245 => array('name' => 'DAVUMET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    757 => array('name' => 'KUPGCET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    762 => array('name' => 'KUPGCET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    893 => array('name' => 'NIMSEE', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1355 => array('name' => 'IUET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1367 => array('name' => 'IUET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    134 => array('name' => 'IRMASAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    119 => array('name' => 'PESSAT MBA', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    964 => array('name' => 'NPAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    584 => array('name' => 'HPCET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    602 => array('name' => 'IEMJEE', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    604 => array('name' => 'IEMJEE', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    93 => array('name' => 'ICET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    92 => array('name' => 'MAH CET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    91 => array('name' => 'OJEE', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    191 => array('name' => 'PU-CET (PG)', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    138 => array('name' => 'PU MET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    139 => array('name' => 'SPJAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    122 => array('name' => 'SRMJEEM', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    141 => array('name' => 'TISSNET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    142 => array('name' => 'X-GMT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    231 => array('name' => 'JKLU-MET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    249 => array('name' => 'DHSGSU PGET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    97 => array('name' => 'TSICET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    125 => array('name' => 'B-MAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    49 => array('name' => 'JEMAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    128 => array('name' => 'HBSAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    108 => array('name' => 'KMAT KERALA', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    121 => array('name' => 'SMAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    230 => array('name' => 'REVA MAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    117 => array('name' => 'GNDU GMET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    136 => array('name' => 'PIM-MAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    63 => array('name' => 'MPMET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    96 => array('name' => 'TANCET MBA', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    127 => array('name' => 'GSIB Entrance Test', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    120 => array('name' => 'KIITEE MANAGEMENT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    794 => array('name' => 'PESSAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    115 => array('name' => 'ALLIANCE-AMAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    100 => array('name' => 'CUSAT MBA', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    206 => array('name' => 'SRMHCAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    234 => array('name' => 'DAVV CET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    248 => array('name' => 'SU MAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    946 => array('name' => 'DYPCET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    987 => array('name' => 'MMET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1141 => array('name' => 'PAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    814 => array('name' => 'SLIET SET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    258 => array('name' => 'ANUCDE', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    75 => array('name' => 'RMAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1004 => array('name' => 'TUET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1417 => array('name' => 'GET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1461 => array('name' => 'CMRUAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    381 => array('name' => 'LUMET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    124 => array('name' => 'UPESMET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1049 => array('name' => 'VEE', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1335 => array('name' => 'DPU Entrance Test', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    493 => array('name' => 'JUET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    679 => array('name' => 'MAH HM CET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    116 => array('name' => 'BET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1257 => array('name' => 'UPSEE', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    931 => array('name' => 'KIITEE', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1543 => array('name' => 'SBPPSE', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1545 => array('name' => 'NTA', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1071 => array('name' => 'LPU NEST', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1010 => array('name' => 'SUAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1014 => array('name' => 'SUAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    840 => array('name' => 'SPSAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    939 => array('name' => 'GLAET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    857 => array('name' => 'UKSEE', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1054 => array('name' => 'ITM NEST', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1060 => array('name' => 'ITM NEST', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1053 => array('name' => 'ITM NEST', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    737 => array('name' => 'SU JEE', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    968 => array('name' => 'MUSAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1383 => array('name' => 'MUSAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1275 => array('name' => 'ACET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1207 => array('name' => 'AMU Entrance Exam', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    439 => array('name' => 'CUCET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    912 => array('name' => 'FDDI AIST', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    477 => array('name' => 'NICC Entrance Exam', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    871 => array('name' => 'MCAER CET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    3 => array('name' => 'MAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    29 => array('name' => 'ATMA', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    637 => array('name' => 'SHIATS Entrance Exam', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    443 => array('name' => 'TERI University Entrance Exam', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    129 => array('name' => 'HPU MAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    53 => array('name' => 'KMAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    132 => array('name' => 'IGNOU OPENMAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    464 => array('name' => 'UPCATET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    103 => array('name' => 'Karnataka PGCET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    236 => array('name' => 'Goenkan Aptitude Test for Admission (GATA)', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    243 => array('name' => 'KLUBSAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    106 => array('name' => 'UPMCAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    118 => array('name' => 'PGRRCDE Entrance Test', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    376 => array('name' => 'Utkal University Entrance Test', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    378 => array('name' => 'MGU CAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    489 => array('name' => 'BHU PET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    505 => array('name' => 'BHU PET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    503 => array('name' => 'BHU PET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    782 => array('name' => 'KUK Entrance Exam', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    135 => array('name' => 'MICAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    454 => array('name' => 'AUCET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    80 => array('name' => 'TANCET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    130 => array('name' => 'IBSAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1173 => array('name' => 'Jamia Millia Islamia Entrance Exam', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    479 => array('name' => 'Sports Management Admission Test (SMAT)', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    478 => array('name' => 'Sports Management Admission Test (SMAT)', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1 => array('name' => 'NMAT by GMAC', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    1321 => array('name' => 'AJEE', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    654 => array('name' => 'CEPT Entrance Exam', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    4 => array('name' => 'SNAP', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    9 => array('name' => 'CAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    972 => array('name' => 'Jaipur National University Combined Entrance Test', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    980 => array('name' => 'Jaipur National University Combined Entrance Test', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    691 => array('name' => 'DAVUET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    131 => array('name' => 'IIFT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    123 => array('name' => 'VMOU MET', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    5 => array('name' => 'XAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    20 => array('name' => 'CMAT', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20),
    750 => array('name' => 'URATPG', 'label' => 'MBA', 'st' => 1, 'bc' => 101, 'et' => 20)
);
//stateId to Exam mapping
$config['otherExamList'] = array(
	113 => array(
        105 => array('groupId' => 1069, 'name' => 'Haryana BTech Counselling'),
        113 => array('groupId' => 389, 'name' => 'MP BE Admissions'),
        120 => array('groupId' => 359, 'name' => 'Punjab BTech Admissions'),
        121 => array('groupId' => 98, 'name' => 'REAP'),
        128 => array('groupId' => 675, 'name' => 'JAC Delhi Admissions'),
        131 => array('groupId' => 361, 'name' => 'CENTAC Counselling'),
        133 => array('groupId' => 364, 'name' => 'Uttarakhand BTech Admissions'),
        134 => array('groupId' => 353, 'name' => 'JAC Chandigarh Admissions'),
        126 => array('groupId' => 0, 'name' => '')
    )
);
$config['examGroupInfo'] = array(
    113 => array('st' => 2, 'bc' => 10, 'et' => 20)
);
